import { NextResponse } from 'next/server';
import { createServerSupabaseClient } from '@/lib/supabase/server';
import {notifyAdmins,notifyUser,serviceDb} from '@/lib/project-flow';

const messageTypes=new Set(['update','question','blocker','decision']);
const resourceTypes=new Set(['github','google_drive','onedrive','figma','canva','power_bi','tableau','looker','dataset','documentation','other']);
const meetingPlatforms=new Set(['google_meet','microsoft_teams','zoom','other']);
function clean(value:unknown,max=2000){return String(value??'').trim().slice(0,max);}
function validUrl(value:string){try{return new URL(value).protocol==='https:';}catch{return false;}}
async function context(projectId:string){const supabase=await createServerSupabaseClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return{supabase,user:null,membership:null};const {data:membership}=await supabase.from('project_members').select('team_role,membership_status').eq('project_id',projectId).eq('user_id',user.id).maybeSingle();return{supabase,user,membership};}
async function emailFor(db:NonNullable<ReturnType<typeof serviceDb>>,userId:string){const {data}=await db.auth.admin.getUserById(userId);return data.user?.email||null;}

export async function POST(request:Request){
 try{
  const body=await request.json();const projectId=clean(body.project_id,80);const action=clean(body.action,60);if(!projectId)return NextResponse.json({error:'Project is required.'},{status:400});
  const ctx=await context(projectId);if(!ctx.user)return NextResponse.json({error:'Authentication required.'},{status:401});const isAdmin=ctx.user.app_metadata?.role==='admin';if(!ctx.membership&&!isAdmin)return NextResponse.json({error:'Project membership is required.'},{status:403});const activeMember=ctx.membership?.membership_status==='active'||ctx.membership?.membership_status==='completed';const canLead=Boolean(activeMember&&ctx.membership?.team_role==='project_lead');const canReview=isAdmin||Boolean(activeMember&&ctx.membership?.team_role==='reviewer');
  if(action==='discussion'){
   if(isAdmin&&!ctx.membership)return NextResponse.json({error:'Admin project discussion access is read-only.'},{status:403});if(!activeMember)return NextResponse.json({error:'Project discussion opens when the project kicks off.'},{status:403});
   const messageType=clean(body.message_type,30)||'update';const text=clean(body.body,5000);const mentions:string[]=Array.isArray(body.mentioned_user_ids)?body.mentioned_user_ids.map((v:unknown)=>clean(v,80)).filter(Boolean).slice(0,20):[];const parentId=clean(body.parent_id,80)||null;if(!messageTypes.has(messageType)||!text)return NextResponse.json({error:'Add a valid discussion type and message.'},{status:400});if(mentions.length){const {data}=await ctx.supabase.from('project_members').select('user_id').eq('project_id',projectId).in('membership_status',['active','completed']).in('user_id',mentions);if((data||[]).length!==mentions.length)return NextResponse.json({error:'Mentions must be active project members.'},{status:400});}if(parentId){const {data:parent}=await ctx.supabase.from('project_discussions').select('id').eq('id',parentId).eq('project_id',projectId).maybeSingle();if(!parent)return NextResponse.json({error:'Reply target is not part of this project.'},{status:400});}const {data,error}=await ctx.supabase.from('project_discussions').insert({project_id:projectId,author_user_id:ctx.user.id,parent_id:parentId,message_type:messageType,body:text,mentioned_user_ids:mentions}).select('id').single();if(error)throw error;if(mentions.length){const db=serviceDb();if(db){const {data:project}=await db.from('projects').select('title').eq('id',projectId).maybeSingle();for(const mentioned of mentions.filter((id:string)=>id!==ctx.user?.id))await notifyUser(db,{userId:mentioned,projectId,type:'project_mention',eventKey:'task_assigned',title:'You were mentioned in a project discussion',body:`You were mentioned in ${project?.title||'a Mettelo Labs project'} discussion.`,actionUrl:`/member/projects/${projectId}`,dedupeKey:`discussion:${data.id}:mention:${mentioned}`});}}return NextResponse.json({ok:true,item:data});
  }
  if(action==='resource'){
   if(isAdmin&&!ctx.membership)return NextResponse.json({error:'Admin project access is read-only for team resources.'},{status:403});if(!activeMember)return NextResponse.json({error:'Project resources open when the project kicks off.'},{status:403});
   const title=clean(body.title,180);const type=clean(body.resource_type,40);const url=clean(body.url,600);const description=clean(body.description,1200);if(!title||!resourceTypes.has(type)||!validUrl(url))return NextResponse.json({error:'Add a title, valid resource type and HTTPS URL.'},{status:400});const {data,error}=await ctx.supabase.from('project_resources').insert({project_id:projectId,title,resource_type:type,url,description:description||null,added_by:ctx.user.id}).select('id').single();if(error)throw error;return NextResponse.json({ok:true,item:data});
  }
  if(action==='meeting'){
   if(!canLead)return NextResponse.json({error:'Only the active Project Lead can share or update team meetings.'},{status:403});const title=clean(body.title,180);const purpose=clean(body.purpose,1200);const platform=clean(body.platform,40);const joinUrl=clean(body.join_url,600);const startsAt=clean(body.starts_at,80);if(!title||!meetingPlatforms.has(platform)||!startsAt||!validUrl(joinUrl))return NextResponse.json({error:'Add a title, platform, date/time and valid HTTPS joining URL.'},{status:400});const {data,error}=await ctx.supabase.from('project_meetings').insert({project_id:projectId,title,purpose:purpose||null,platform,starts_at:startsAt,ends_at:body.ends_at||null,join_url:joinUrl,organiser_user_id:ctx.user.id}).select('id').single();if(error)throw error;const db=serviceDb();if(db){const [{data:project},{data:members}]=await Promise.all([db.from('projects').select('title').eq('id',projectId).maybeSingle(),db.from('project_members').select('user_id').eq('project_id',projectId).eq('membership_status','active')]);for(const member of members||[]){if(member.user_id===ctx.user.id)continue;await notifyUser(db,{userId:member.user_id,email:await emailFor(db,member.user_id),projectId,type:'event_changed',eventKey:'event_changed',title:'Project meeting scheduled',body:`${title} for ${project?.title||'your Mettelo Labs project'} is scheduled for ${new Date(startsAt).toLocaleString('en-GB')}.`,actionUrl:`/member/projects/${projectId}`,subject:`Project meeting — ${project?.title||'Mettelo Labs'}`,dedupeKey:`project-meeting:${data.id}:${member.user_id}`});}}return NextResponse.json({ok:true,item:data});
  }
  if(action==='book_presentation'){
   if(!canLead)return NextResponse.json({error:'Only the Project Lead can book the project presentation.'},{status:403});const slotId=clean(body.slot_id,80);const deckUrl=clean(body.deck_url,600);const presenters=Array.isArray(body.presenter_ids)?body.presenter_ids.map((v:unknown)=>clean(v,80)).filter(Boolean).slice(0,12):[];if(!slotId)return NextResponse.json({error:'Choose an available presentation slot.'},{status:400});if(deckUrl&&!validUrl(deckUrl))return NextResponse.json({error:'Provide a valid HTTPS presentation/deck URL.'},{status:400});const db=serviceDb();if(!db)return NextResponse.json({error:'Presentation booking service is not configured.'},{status:503});const {data,error}=await db.rpc('book_project_presentation_service',{target_project:projectId,target_slot:slotId,target_deck_url:deckUrl||null,target_presenters:presenters,actor_user:ctx.user.id,actor_is_admin:false});if(error)return NextResponse.json({error:error.message||'Unable to book presentation.'},{status:409});await notifyAdmins(db,{projectId,type:'project_presentation_booked',eventKey:'project_kickoff',title:'Project presentation booked',body:'A project team has booked a Mettelo presentation slot and may require review support.',actionUrl:'/admin/project-operations',subject:'Mettelo project presentation booked',dedupeKey:`presentation-booked:${data}`});return NextResponse.json({ok:true,presentation_id:data});
  }
  if(action==='presentation_status'){
   const status=clean(body.status,40);const notes=clean(body.reviewer_notes,1800);if(!canReview)return NextResponse.json({error:'Reviewer or Admin access is required.'},{status:403});if(status==='changes_required'&&!notes)return NextResponse.json({error:'Explain the required presentation changes.'},{status:400});const db=serviceDb();if(!db)return NextResponse.json({error:'Presentation review service is not configured.'},{status:503});const {error}=await db.rpc('update_project_presentation_status_service',{target_project:projectId,target_status:status,target_notes:notes||null,actor_user:ctx.user.id,actor_is_admin:isAdmin});if(error)return NextResponse.json({error:error.message||'Unable to update presentation.'},{status:400});const [{data:project},{data:leads}]=await Promise.all([db.from('projects').select('title').eq('id',projectId).maybeSingle(),db.from('project_members').select('user_id').eq('project_id',projectId).eq('team_role','project_lead').eq('membership_status','active')]);for(const lead of leads||[])await notifyUser(db,{userId:lead.user_id,email:await emailFor(db,lead.user_id),projectId,type:'contribution_review',eventKey:'contribution_review',title:'Presentation review updated',body:`The presentation for ${project?.title||'your project'} is now ${status.replaceAll('_',' ')}.${notes?` ${notes}`:''}`,actionUrl:`/member/projects/${projectId}`,subject:`Presentation review — ${project?.title||'Mettelo Labs'}`,dedupeKey:`presentation:${projectId}:${status}`});return NextResponse.json({ok:true});
  }
  if(action==='submit_completion'){
   if(!canLead&&!isAdmin)return NextResponse.json({error:'Project Lead or Admin access is required.'},{status:403});const {data:readiness,error:readinessError}=await ctx.supabase.rpc('project_completion_readiness',{target_project:projectId});if(readinessError)throw readinessError;if(!readiness?.ready)return NextResponse.json({error:'This project is not ready for completion yet.',readiness},{status:409});const db=serviceDb();if(!db)return NextResponse.json({error:'Completion service is not configured.'},{status:503});const nextStatus=isAdmin?'completed':'review';const {error}=await db.from('projects').update({status:nextStatus,updated_at:new Date().toISOString()}).eq('id',projectId);if(error)return NextResponse.json({error:error.message||'Unable to update project completion.'},{status:409});const {data:project}=await db.from('projects').select('title').eq('id',projectId).maybeSingle();if(isAdmin){const {data:members}=await db.from('project_members').select('user_id').eq('project_id',projectId).in('membership_status',['active','completed']);for(const member of members||[])await notifyUser(db,{userId:member.user_id,email:await emailFor(db,member.user_id),projectId,type:'project_completed',eventKey:'project_kickoff',title:'Project completed',body:`${project?.title||'Your Mettelo Labs project'} has been marked complete. Verified contribution and Proof can now be reviewed from My Mettelo.`,actionUrl:'/member/proof',subject:`Project completed — ${project?.title||'Mettelo Labs'}`,dedupeKey:`project:${projectId}:completed`});}else{await notifyAdmins(db,{projectId,type:'project_completion_review',eventKey:'contribution_review',title:`Project ready for completion review — ${project?.title||'Mettelo Labs'}`,body:'The Project Lead has submitted this project for completion review.',actionUrl:'/admin/project-operations',subject:`Completion review — ${project?.title||'Mettelo Labs'}`,dedupeKey:`project:${projectId}:completion-review`});}return NextResponse.json({ok:true,message:isAdmin?'Project completed. Verified contribution has been unlocked for the team.':'Project submitted for completion review.'});
  }
  return NextResponse.json({error:'Unknown collaboration action.'},{status:400});
 }catch(error){console.error('project collaboration error',error);return NextResponse.json({error:'Unable to update this project workspace.'},{status:500});}
}
