import type {Metadata} from 'next';
import Link from 'next/link';
import {createPublicSupabaseClient} from '@/lib/supabase/public';

export const metadata:Metadata={title:'Search',description:'Search across public Mettelo projects, opportunities, people, events and insights.'};
export const dynamic='force-dynamic';

type SearchType='all'|'projects'|'opportunities'|'people'|'events'|'insights';
type Result={id:string;type:Exclude<SearchType,'all'>;title:string;summary:string;meta:string;href:string;score:number};
type Params={q?:string;type?:string};
function cleanQuery(value:string){return value.trim().slice(0,80).replace(/[%,()]/g,' ').replace(/\s+/g,' ')}
function score(title:string,fields:string[],q:string){const needle=q.toLowerCase();const t=title.toLowerCase();if(t===needle)return 100;if(t.startsWith(needle))return 85;if(t.includes(needle))return 70;return fields.join(' ').toLowerCase().includes(needle)?45:20}
function typeLabel(type:Result['type']){return ({projects:'Project',opportunities:'Opportunity',people:'Person',events:'Event',insights:'Insight'})[type]}

export default async function SearchPage({searchParams}:{searchParams:Promise<Params>}){
  const params=await searchParams;const q=cleanQuery(params.q||'');const requested=(params.type||'all') as SearchType;const active:SearchType=['all','projects','opportunities','people','events','insights'].includes(requested)?requested:'all';
  const db=createPublicSupabaseClient();let results:Result[]=[];let loadError=false;
  if(q&&db){const pattern=`%${q}%`;const jobs:Promise<Result[]>[]=[];
    if(active==='all'||active==='projects')jobs.push(db.from('projects').select('id,title,summary,problem_statement,status,location,difficulty_level').or(`title.ilike.${pattern},summary.ilike.${pattern},problem_statement.ilike.${pattern},location.ilike.${pattern}`).limit(20).then(({data,error})=>{if(error)throw error;return (data||[]).map(r=>({id:r.id,type:'projects' as const,title:r.title,summary:r.summary||r.problem_statement||'Mettelo project',meta:[r.status?.replaceAll('_',' '),r.difficulty_level,r.location].filter(Boolean).join(' · '),href:'/projects#open-projects',score:score(r.title,[r.summary||'',r.problem_statement||'',r.location||''],q)}))}));
    if(active==='all'||active==='opportunities')jobs.push(db.from('opportunities').select('id,title,organisation,opportunity_type,summary,location,role_family').or(`title.ilike.${pattern},organisation.ilike.${pattern},summary.ilike.${pattern},location.ilike.${pattern},role_family.ilike.${pattern}`).limit(30).then(({data,error})=>{if(error)throw error;return (data||[]).map(r=>({id:r.id,type:'opportunities' as const,title:r.title,summary:r.summary||`${r.organisation||'Organisation'} opportunity`,meta:[r.organisation,r.opportunity_type?.replaceAll('_',' '),r.location].filter(Boolean).join(' · '),href:`/opportunities/${r.id}`,score:score(r.title,[r.organisation||'',r.summary||'',r.location||'',r.role_family||''],q)}))}));
    if(active==='all'||active==='people')jobs.push(db.from('profiles').select('id,full_name,headline,bio,location,professional_area,current_job_title,organisation').or(`full_name.ilike.${pattern},headline.ilike.${pattern},bio.ilike.${pattern},location.ilike.${pattern},professional_area.ilike.${pattern},current_job_title.ilike.${pattern},organisation.ilike.${pattern}`).limit(20).then(({data,error})=>{if(error)throw error;return (data||[]).map(r=>({id:r.id,type:'people' as const,title:r.full_name||'Mettelo member',summary:r.headline||r.bio||r.professional_area||'Public Mettelo profile',meta:[r.current_job_title,r.organisation,r.location].filter(Boolean).join(' · '),href:`/people/${r.id}`,score:score(r.full_name||'', [r.headline||'',r.bio||'',r.location||'',r.professional_area||'',r.current_job_title||'',r.organisation||''],q)}))}));
    if(active==='all'||active==='events')jobs.push(db.from('events').select('id,slug,title,event_type,summary,description,starts_at,location_label,status,host_name').or(`title.ilike.${pattern},summary.ilike.${pattern},description.ilike.${pattern},location_label.ilike.${pattern},host_name.ilike.${pattern}`).limit(20).then(({data,error})=>{if(error)throw error;return (data||[]).map(r=>({id:r.id,type:'events' as const,title:r.title,summary:r.summary||r.description||'Mettelo event',meta:[r.event_type?.replaceAll('_',' '),new Date(r.starts_at).toLocaleDateString('en-GB',{dateStyle:'medium'}),r.location_label,r.status?.replaceAll('_',' ')].filter(Boolean).join(' · '),href:`/events/${r.slug}`,score:score(r.title,[r.summary||'',r.description||'',r.location_label||'',r.host_name||''],q)}))}));
    if(active==='all'||active==='insights')jobs.push(db.from('content_posts').select('id,slug,title,summary,body,author_name,content_type').or(`title.ilike.${pattern},summary.ilike.${pattern},body.ilike.${pattern},author_name.ilike.${pattern},content_type.ilike.${pattern}`).limit(20).then(({data,error})=>{if(error)throw error;return (data||[]).map(r=>({id:r.id,type:'insights' as const,title:r.title,summary:r.summary||'Mettelo insight',meta:[r.content_type?.replaceAll('_',' '),r.author_name].filter(Boolean).join(' · '),href:`/blog/${r.slug}`,score:score(r.title,[r.summary||'',r.body||'',r.author_name||'',r.content_type||''],q)}))}));
    try{results=(await Promise.all(jobs)).flat().sort((a,b)=>b.score-a.score||a.title.localeCompare(b.title)).slice(0,60)}catch(error){console.error('search error',error);loadError=true;}
  }else if(q&&!db)loadError=true;
  const grouped=(['projects','opportunities','people','events','insights'] as Result['type'][]).map(type=>({type,items:results.filter(r=>r.type===type)})).filter(g=>g.items.length);
  const filters:[SearchType,string][]=[['all','Everything'],['projects','Projects'],['opportunities','Opportunities'],['people','People'],['events','Events'],['insights','Insights']];
  return <>
    <section className="hero searchHero"><div className="shell"><div className="eyebrow">Search Mettelo</div><h1>Find capability, work and opportunity across Mettelo.</h1><p className="heroLead">Search public projects, opportunities, people, events and insights from one place.</p><form className="unifiedSearchForm" action="/search" method="get"><label className="srOnly" htmlFor="search-q">Search Mettelo</label><input id="search-q" className="searchInput" name="q" defaultValue={q} placeholder="Try: data analyst, Python, project, career…" autoComplete="off"/><input type="hidden" name="type" value={active}/><button className="button dark" type="submit">Search →</button></form><nav className="searchFilters" aria-label="Search categories">{filters.map(([value,label])=><Link key={value} className={`filter${active===value?' active':''}`} href={`/search?q=${encodeURIComponent(q)}&type=${value}`}>{label}</Link>)}</nav></div></section>
    <section className="section"><div className="shell searchResultsShell">{!q?<div className="emptyState"><h3>Start with what you are looking for.</h3><p>Search by role, skill, organisation, topic, location or project problem. Results only include content already visible publicly on Mettelo.</p></div>:loadError?<div className="emptyState"><h3>Search is temporarily unavailable.</h3><p>Please try again shortly or use the main Explore navigation.</p></div>:!results.length?<div className="emptyState"><h3>No results for “{q}”.</h3><p>Try a broader term or switch back to Everything.</p><div className="actions"><Link className="button ghost" href="/search">Clear search</Link></div></div>:<><div className="searchSummary"><strong>{results.length}</strong><span>{results.length===1?'result':'results'} for “{q}”</span></div>{grouped.map(group=><section className="searchGroup" key={group.type}><div className="searchGroupHead"><div><span className="eyebrow">{typeLabel(group.type)}</span><h2>{typeLabel(group.type)}{group.items.length===1?'':'s'}</h2></div><span className="chip">{group.items.length}</span></div><div className="searchResultList">{group.items.map(item=><Link href={item.href} className="searchResultCard" key={`${item.type}-${item.id}`}><div><span className="chip">{typeLabel(item.type).toUpperCase()}</span><h3>{item.title}</h3><p>{item.summary}</p>{item.meta&&<small>{item.meta}</small>}</div><span className="searchArrow" aria-hidden="true">→</span></Link>)}</div></section>)}</>}</div></section>
    <style>{`.searchHero{padding-bottom:46px}.searchHero h1{max-width:900px}.unifiedSearchForm{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;max-width:840px;margin-top:28px}.unifiedSearchForm .searchInput{width:100%;min-height:52px;padding:0 16px;border:1px solid var(--ui-line-strong,#d7dce4);border-radius:13px;background:#fff;color:inherit;font-size:1rem}.searchFilters{display:flex;gap:7px;overflow-x:auto;max-width:920px;margin-top:14px;padding-bottom:3px;scrollbar-width:none}.searchFilters::-webkit-scrollbar{display:none}.searchFilters .filter{flex:none;display:inline-flex;align-items:center;min-height:40px;padding:0 13px;border:1px solid var(--ui-line,#e5e8ed);border-radius:999px;background:#fff;color:#596271;font-size:.75rem;font-weight:750}.searchFilters .filter.active{background:#141824;color:#fff;border-color:#141824}.searchResultsShell{max-width:980px}.searchSummary{display:flex;align-items:baseline;gap:8px;margin-bottom:30px;color:#667080}.searchSummary strong{font-family:var(--font-space);font-size:2rem;color:#141824}.searchGroup{margin-bottom:42px}.searchGroupHead{display:flex;align-items:end;justify-content:space-between;gap:18px;margin-bottom:14px}.searchGroupHead h2{margin:5px 0 0;font-size:clamp(1.55rem,3vw,2.25rem)}.searchResultList{display:grid;gap:9px}.searchResultCard{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:18px;align-items:center;padding:18px 20px;border:1px solid var(--ui-line,#e5e8ed);border-radius:15px;background:#fff;color:inherit;transition:border-color .15s ease,box-shadow .15s ease}.searchResultCard:hover{border-color:#d7b77a;box-shadow:0 10px 30px rgba(20,24,36,.06)}.searchResultCard h3{margin:10px 0 5px;font-size:1.05rem}.searchResultCard p{max-width:760px;margin:0 0 7px;color:#596271;font-size:.84rem;line-height:1.5}.searchResultCard small{color:#7a8390}.searchArrow{font-size:1.35rem}@media(max-width:680px){.unifiedSearchForm{grid-template-columns:1fr}.unifiedSearchForm .button{width:100%}.searchResultCard{padding:16px;align-items:start}.searchResultCard p{font-size:.8rem}.searchArrow{padding-top:7px}.searchGroup{margin-bottom:34px}}`}</style>
  </>;
}
