import type { Metadata } from 'next';
export const metadata: Metadata = { title:'Search', description:'Search across Mettelo projects, opportunities, people, events and insights.' };

export default function SearchPage(){
 return <>
 <section className="hero"><div className="shell"><div className="eyebrow">Search Mettelo</div><h1 style={{maxWidth:860}}>Find the right project, person, event or opportunity.</h1><p className="heroLead">One search layer should eventually span the full ecosystem rather than forcing members to search each product separately.</p><div className="searchPanel" style={{marginTop:28}}><div><input className="searchInput" placeholder="Search skills, roles, projects, events, topics..."/></div><div className="filterBar" style={{margin:0}}><button className="filter active">Everything</button><button className="filter">Projects</button><button className="filter">People</button><button className="filter">Opportunities</button></div></div></div></section>
 <section className="section"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">Example results</div><h2>Search by intent, not just keywords.</h2></div></div><div className="grid3"><article className="card"><span className="chip">PROJECT</span><h3 style={{marginTop:18}}>Open Data Quality Monitor</h3><p>Recruiting Data Analysts, Analytics Engineers and QA contributors.</p><div className="actions"><a className="linkArrow" href="/projects">Open project →</a></div></article><article className="card"><span className="chip">PEOPLE</span><h3 style={{marginTop:18}}>Analytics Engineers</h3><p>Discover members by skills, location, project credits and collaboration interests.</p><div className="actions"><a className="linkArrow" href="/people">Browse people →</a></div></article><article className="card"><span className="chip">EVENT</span><h3 style={{marginTop:18}}>Technical Review Office Hours</h3><p>Upcoming support around projects, portfolios and technical evidence.</p><div className="actions"><a className="linkArrow" href="/mentors">See office hours →</a></div></article></div></div></section>
 </>;
}
