import Link from 'next/link';
import {redirect} from 'next/navigation';
import {createServerSupabaseClient} from '@/lib/supabase/server';
import {serviceDb} from '@/lib/project-flow';
import AdminSectionTabs from '@/components/AdminSectionTabs';
import AdminStatusBadge from '@/components/AdminStatusBadge';

export const dynamic='force-dynamic';
type Row={id:string;full_name:string;email:string;status:string;submitted_at:string;career_roles:{title:string}|null};const stages=['submitted','in_review','shortlisted','interview','offer','hired','rejected'];
export default async function AdminCareerPipelinePage(){const auth=await createServerSupabaseClient();const {data:{user}}=await auth.auth.getUser();if(!user)redirect('/signin');if(user.app_metadata?.role!=='admin')redirect('/member');const db=serviceDb();const {data}=db?await db.from('career_applications').select('id,full_name,email,status,submitted_at,career_roles(title)').order('submitted_at',{ascending:false}).limit(500):{data:[]};const rows=(data||[]) as unknown as Row[];return <section className="section softSection"><div className="shell"><AdminSectionTabs label="Career sections" tabs={[{label:'Roles',href:'/admin/careers/roles'},{label:'Candidates',href:'/admin/careers/applications'},{label:'Pipeline overview',href:'/admin/careers/pipeline'}]}/><div className="adminPageHeader"><div><div className="eyebrow">Admin / Recruiting / Careers / Pipeline</div><h1>Pipeline overview</h1><p>A compact visual read of candidate distribution. The Candidates table remains the primary management surface.</p></div></div><div className="careerKanban" aria-label="Career candidate pipeline">{stages.map(stage=>{const items=rows.filter(row=>row.status===stage);return <section key={stage}><header><AdminStatusBadge status={stage} label={stage==='submitted'?'New':undefined}/><strong>{items.length}</strong></header><div>{items.slice(0,20).map(item=><Link href={`/admin/careers/applications?candidate=${item.id}`} key={item.id}><strong>{item.full_name}</strong><span>{item.career_roles?.title||'Mettelo role'}</span><small>{new Date(item.submitted_at).toLocaleDateString('en-GB')}</small></Link>)}{items.length>20&&<Link href={`/admin/careers/applications?status=${stage}`}>+ {items.length-20} more →</Link>}</div></section>})}</div><style jsx>{`.careerKanban{display:grid;grid-template-columns:repeat(7,minmax(190px,1fr));gap:10px;overflow-x:auto;padding-bottom:8px}.careerKanban>section{min-height:280px;border:1px solid #dce1e6;border-radius:13px;background:#f7f8fa}.careerKanban header{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:11px;border-bottom:1px solid #e2e5e8}.careerKanban header>strong{font-size:.72rem}.careerKanban section>div{display:grid;gap:7px;padding:8px}.careerKanban a{display:grid;gap:3px;padding:10px;border:1px solid #e0e4e8;border-radius:9px;background:#fff;color:#10131d;text-decoration:none}.careerKanban a:hover{border-color:#aeb7c2}.careerKanban a strong{font-size:.72rem}.careerKanban a span{color:#48515e;font-size:.65rem}.careerKanban a small{color:#7b8490;font-size:.6rem}@media(max-width:760px){.careerKanban{grid-template-columns:repeat(7,82vw)}}`}</style></div></section>}
