import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {createPublicSupabaseClient} from '@/lib/supabase/public';
import SocialShare from '@/components/SocialShare';

export const dynamic='force-dynamic';
type Proof={id:string;user_id:string;title:string;contribution_type:string;description:string|null;evidence_url:string|null;verified_at:string|null;visibility:string;projects:{id:string;title:string;summary:string;github_url:string|null;status:string}|null;profiles:{full_name:string|null;headline:string|null;avatar_url:string|null}|null};
async function getProof(id:string){const db=createPublicSupabaseClient();if(!db)return null;const {data}=await db.from('contributions').select('id,user_id,title,contribution_type,description,evidence_url,verified_at,visibility,projects(id,title,summary,github_url,status),profiles(full_name,headline,avatar_url)').eq('id',id).eq('verification_status','verified').eq('visibility','public').maybeSingle();return data as unknown as Proof|null;}
export async function generateMetadata({params}:{params:Promise<{id:string}>}):Promise<Metadata>{const {id}=await params;const item=await getProof(id);if(!item)return {title:'Verified Proof'};const name=item.profiles?.full_name||'Mettelo contributor';const title=`${name} — Verified Mettelo Proof: ${item.title}`;const description=item.description||`${name} has verified contribution evidence on Mettelo.`;return {title,description,openGraph:{title,description,type:'article',url:`/proof/${item.id}`},twitter:{card:'summary_large_image',title,description}};}
export default async function ProofDetailPage({params}:{params:Promise<{id:string}>}){const {id}=await params;const item=await getProof(id);if(!item)notFound();const name=item.profiles?.full_name?.trim()||'Mettelo contributor';const url=`https://mettelo.com/proof/${item.id}`;const text=`I have verified contribution proof on Mettelo: ${item.title}${item.projects?.title?` · ${item.projects.title}`:''}.`;return <section className="section softSection"><div className="shell"><main className="panel" style={{maxWidth:820,margin:'0 auto'}} aria-labelledby="public-proof-title"><div className="eyebrow">Mettelo Verified Proof</div><div className="personAvatar" style={item.profiles?.avatar_url?{backgroundImage:`url(${item.profiles.avatar_url})`,backgroundSize:'cover',backgroundPosition:'center',margin:'20px 0'}:{margin:'20px 0'}}>{item.profiles?.avatar_url?'':name.charAt(0).toUpperCase()}</div><span className="chip green">✓ VERIFIED BY METTELO</span><h1 id="public-proof-title" style={{marginTop:14}}>{item.title}</h1><h2>{name}</h2>{item.profiles?.headline&&<p><strong>{item.profiles.headline}</strong></p>}
<div className="grid2" style={{margin:'22px 0'}}><div className="publicProfileFact"><small>PROJECT</small><strong>{item.projects?.title||'Mettelo contribution'}</strong></div><div className="publicProfileFact"><small>CONTRIBUTION TYPE</small><strong>{item.contribution_type.replaceAll('_',' ')}</strong></div><div className="publicProfileFact"><small>VERIFIED</small><strong>{item.verified_at?new Date(item.verified_at).toLocaleDateString('en-GB',{dateStyle:'long'}):'Verification recorded by Mettelo'}</strong></div><div className="publicProfileFact"><small>VISIBILITY</small><strong>Public by member choice</strong></div></div>
{item.description&&<div><h3>What this person contributed</h3><p>{item.description}</p></div>}<div className="panelNote" style={{marginTop:20}}><strong>What verification means</strong><p>Mettelo has reviewed this contribution as part of the project evidence workflow. Verification confirms the recorded contribution; it is not a claim of employment, certification, or endorsement beyond the evidence shown.</p></div><div className="actions" style={{alignItems:'center',marginTop:20}}><SocialShare url={url} text={text} label="Share this Proof"/>{item.evidence_url&&<a className="button ghost" href={item.evidence_url} target="_blank" rel="noopener noreferrer">Open supporting evidence →</a>}<Link className="button ghost" href={`/people/${item.user_id}`}>View profile →</Link></div></main></div></section>;}
