import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {createPublicSupabaseClient} from '@/lib/supabase/public';
import SocialShare from '@/components/SocialShare';

export const dynamic='force-dynamic';
type Proof={id:string;user_id:string;title:string;contribution_type:string;description:string|null;evidence_url:string|null;projects:{id:string;title:string;summary:string;github_url:string|null;status:string}|null;profiles:{full_name:string|null;headline:string|null;avatar_url:string|null}|null};
async function getProof(id:string){const db=createPublicSupabaseClient();if(!db)return null;const {data}=await db.from('contributions').select('id,user_id,title,contribution_type,description,evidence_url,projects(id,title,summary,github_url,status),profiles(full_name,headline,avatar_url)').eq('id',id).eq('verification_status','verified').eq('is_public',true).maybeSingle();return data as unknown as Proof|null;}
export async function generateMetadata({params}:{params:Promise<{id:string}>}):Promise<Metadata>{const {id}=await params;const item=await getProof(id);if(!item)return {title:'Verified Proof'};const name=item.profiles?.full_name||'Mettelo contributor';const title=`${name} — Verified Mettelo Proof: ${item.title}`;const description=item.description||`${name} has verified contribution evidence on Mettelo.`;return {title,description,openGraph:{title,description,type:'article',url:`/proof/${item.id}`},twitter:{card:'summary_large_image',title,description}};}
export default async function ProofDetailPage({params}:{params:Promise<{id:string}>}){const {id}=await params;const item=await getProof(id);if(!item)notFound();const name=item.profiles?.full_name?.trim()||'Mettelo contributor';const url=`https://mettelo.com/proof/${item.id}`;const text=`I have verified contribution proof on Mettelo: ${item.title}${item.projects?.title?` · ${item.projects.title}`:''}.`;return <section className="section softSection"><div className="shell"><div className="panel" style={{maxWidth:780,margin:'0 auto'}}><div className="eyebrow">Mettelo Verified Proof</div><div className="personAvatar" style={item.profiles?.avatar_url?{backgroundImage:`url(${item.profiles.avatar_url})`,backgroundSize:'cover',backgroundPosition:'center',margin:'20px 0'}:{margin:'20px 0'}}>{item.profiles?.avatar_url?'':name.charAt(0).toUpperCase()}</div><span className="chip green">VERIFIED</span><h1 style={{marginTop:14}}>{item.title}</h1><h2>{name}</h2>{item.profiles?.headline&&<p><strong>{item.profiles.headline}</strong></p>}<p>{item.projects?.title||'Mettelo contribution'} · {item.contribution_type.replaceAll('_',' ')}</p>{item.description&&<p>{item.description}</p>}<div className="actions" style={{alignItems:'center'}}><SocialShare url={url} text={text} label="Share this proof"/>{item.evidence_url&&<a className="button ghost" href={item.evidence_url} target="_blank" rel="noopener noreferrer">Open evidence →</a>}<Link className="button ghost" href={`/people/${item.user_id}`}>View profile →</Link></div></div></div></section>;}
