import styles from '../public-wave1.module.css';

const participation=[
  ['01','Meet peers','Join the open community, introduce yourself and find people working on similar problems.','https://discord.gg/Nx6qCbEY','Join Discord'],
  ['02','Find opportunity','Use community context to discover current Data & AI roles, referrals and routes forward.','/opportunities','Explore opportunities'],
  ['03','Build together','Move from conversation into structured Labs work with clear roles, ownership and outcomes.','/projects','See projects'],
  ['04','Learn with people','Use events, mentoring and practitioner conversation to get context you cannot get from content alone.','/events','See events']
];

export default function CommunityPage(){return <div className={styles.wavePage}>
  <section className={`${styles.hero} ${styles.heroDark} ${styles.communityHero}`} aria-labelledby="community-title"><div className="shell"><div className={styles.heroGrid}><div className={styles.heroCopy}><div className="eyebrow">METTELO COMMUNITY</div><h1 id="community-title">Belong somewhere that leads to real work.</h1><p>Meet serious Data & AI peers, get useful professional context, find collaborators and move into projects, events and opportunities when you are ready.</p><div className={styles.communityActions}><a href="https://discord.gg/Nx6qCbEY"><span>Join the main community</span><span aria-hidden="true">→</span></a><a href="https://chat.whatsapp.com/LrxCOfDBCDUJhRqXFRD2cY"><span>WhatsApp</span><span aria-hidden="true">↗</span></a><a href="https://x.com/i/communities/2015608740804718665"><span>X Community</span><span aria-hidden="true">↗</span></a></div></div><aside className={styles.signalPanel}><span className={styles.signalKicker}>HOW PARTICIPATION GROWS</span><div className={styles.participationPath}><div><span>01</span><div><strong>Join</strong><p>Find the community and introduce yourself.</p></div></div><div><span>02</span><div><strong>Participate</strong><p>Ask, answer, share and build relationships.</p></div></div><div><span>03</span><div><strong>Contribute</strong><p>Move into projects, events or mentoring.</p></div></div><div><span>04</span><div><strong>Build Proof</strong><p>Turn meaningful contribution into stronger professional evidence.</p></div></div></div></aside></div></div></section>

  <section className={styles.section} aria-labelledby="community-paths-title"><div className="shell"><div className={styles.sectionHead}><div><div className={styles.sectionEyebrow}>WAYS TO PARTICIPATE</div><h2 id="community-paths-title">Start with what you need now.</h2></div><p>Community should not pressure everyone into the same behaviour. It should make useful routes visible and let deeper contribution emerge naturally.</p></div><div className={styles.participationGrid}>{participation.map(([index,title,copy,href,cta])=><article className={styles.participationCard} key={title}><span className={styles.participationIndex}>{index}</span><div><h3>{title}</h3><p>{copy}</p></div><a href={href}>{cta} →</a></article>)}</div></div></section>

  <section className={`${styles.section} ${styles.soft}`} aria-labelledby="community-discovery-title"><div className="shell"><div className={styles.sectionHead}><div><div className={styles.sectionEyebrow}>PEOPLE BEFORE CHANNELS</div><h2 id="community-discovery-title">The right relationship can be more useful than another feed.</h2></div><p>Use Mettelo to discover professionals, mentors and contributors through context that can lead to collaboration rather than passive networking.</p></div><div className={styles.discoveryPrinciples}><article><span>PEOPLE</span><h3>Capability directory</h3><p>Discover professionals through role, skills, location and public verified contribution.</p><div className={styles.heroActions}><a className="button ghost" href="/people">Browse people →</a></div></article><article><span>MENTORS</span><h3>Office Hours</h3><p>Find career, technical, leadership and project support without creating unlimited one-to-one commitments.</p><div className={styles.heroActions}><a className="button ghost" href="/mentors">Find support →</a></div></article><article><span>CONTRIBUTE</span><h3>Build Mettelo</h3><p>Take responsibility for useful work across Labs, product, community, research, content and operations.</p><div className={styles.heroActions}><a className="button ghost" href="/contribute">See pathways →</a></div></article></div></div></section>

  <section className={`${styles.section} ${styles.darkSection}`} aria-labelledby="community-networks-title"><div className="shell"><div className={styles.networkBand}><div className={styles.networkIntro}><div className={styles.sectionEyebrow}>FOCUSED NETWORKS</div><h2 id="community-networks-title">Global community. Local professional context.</h2><p>Different markets create different career, hiring and professional problems. Focused networks can reduce noise while the wider Mettelo ecosystem stays connected.</p></div><div className={styles.networkList}><article><span>UK</span><div><h3>UK Data Professionals</h3><p>Job search, Civil Service, NHS and private-sector context, interviews and local peer support.</p></div></article><article><span>NIGERIA</span><div><h3>Nigeria Data & AI</h3><p>Local opportunities, projects, professional development and ecosystem connection.</p></div></article><article><span>GLOBAL</span><div><h3>Open Community</h3><p>Cross-border collaboration, Labs, open source, events, research and shared professional knowledge.</p></div></article></div></div></div></section>

  <section className={styles.section}><div className="shell"><div className={styles.communityCta}><div><div className={styles.sectionEyebrow}>YOUR NEXT STEP</div><h2>Join first. Contribute when ready.</h2><p>Start with the community, then move into the part of Mettelo that helps you build, prove or discover what comes next.</p></div><a className="button dark" href="https://discord.gg/Nx6qCbEY">Join Mettelo Community →</a></div></div></section>
</div>}
