import type { Metadata } from 'next';

export const metadata:Metadata={title:'My Mettelo',description:'Your private Mettelo member workspace for profile, projects, applications and contribution.'};

export default function MemberDashboard(){return <section className="section softSection"><div className="shell dashboard">
<aside className="sidebar"><div className="sidebarTop"><h3>My Mettelo</h3><small>Member workspace</small></div><a className="active" href="#overview">Overview <span>⌂</span></a><a href="#profile">Profile <span>→</span></a><a href="#projects">Projects <span>→</span></a><a href="#proof">Proof <span>→</span></a><a href="/opportunities">Opportunities <span>→</span></a><a href="/events">Events <span>→</span></a><a href="/community">Community <span>→</span></a></aside>
<main className="dashboardMain" id="overview"><div className="eyebrow">Member workspace</div><h1>Your Mettelo activity starts here.</h1><p className="lead">This workspace is protected by your account. Production activity appears here as profile, Labs and Proof records are connected to the database.</p>
<div className="dashboardGrid" id="profile"><section className="panel"><div className="panelHead"><h3>Start with your profile</h3><span className="chip">FIRST STEP</span></div><p>Your member profile will hold the professional context needed for project matching and future proof records. Profile editing is the next account feature to connect to Supabase.</p><div className="actions"><a className="button ghost" href="/community">Enter the community</a></div></section><aside className="panel"><div className="panelHead"><h3>What is live now?</h3></div><div className="listRow"><span>Account authentication</span><strong>Live when Supabase is configured</strong></div><div className="listRow"><span>Protected member route</span><strong>Ready</strong></div><div className="listRow"><span>Project interest form</span><strong>Ready</strong></div><div className="listRow"><span>Profile/activity data</span><strong>Connecting</strong></div></aside></div>
<div className="dashboardGrid" style={{marginTop:18}} id="projects"><section className="panel"><div className="panelHead"><h3>Projects</h3><a className="linkArrow" href="/projects">Explore Labs →</a></div><div className="emptyState"><h3>No project activity to show yet.</h3><p>When you register interest or join a live Labs project, its status can appear here once the production database migration is active.</p></div></section><aside className="panel" id="proof"><div className="panelHead"><h3>Proof</h3><a className="linkArrow" href="/showcase">See the model →</a></div><div className="emptyState"><h3>No verified contribution yet.</h3><p>Proof is earned through reviewed work, leadership, mentoring or other meaningful contribution — never by passive attendance.</p></div></aside></div>
<section className="panel" style={{marginTop:18}}><div className="panelHead"><h3>Where to go next</h3></div><div className="grid3"><div><span className="cardNumber">CONNECT</span><h3 style={{fontSize:'1.1rem',marginTop:10}}>Community</h3><p>Meet peers and find the spaces relevant to your goals.</p><a className="linkArrow" href="/community">Open community →</a></div><div><span className="cardNumber">BUILD</span><h3 style={{fontSize:'1.1rem',marginTop:10}}>Labs</h3><p>Review pilot project briefs and register useful interest.</p><a className="linkArrow" href="/projects">Explore Labs →</a></div><div><span className="cardNumber">STAY CLOSE</span><h3 style={{fontSize:'1.1rem',marginTop:10}}>Updates</h3><p>Get new projects, events and opportunities without checking manually.</p><a className="linkArrow" href="/newsletter">Get updates →</a></div></div></section>
</main></div></section>}
