import type {Metadata} from 'next';
import {redirect} from 'next/navigation';
import {createClient} from '@supabase/supabase-js';
import {createServerSupabaseClient} from '@/lib/supabase/server';
import MemberApplicationTracker from '@/components/MemberApplicationTracker';
import styles from './member.module.css';

export const metadata:Metadata={title:'Dashboard · Mettelo',description:'Your Mettelo member dashboard.'};export const dynamic='force-dynamic';
type Formation={filled:number;threshold:number;status:string;is_full:boolean;kickoff_at:string|null};
type Application={id:string;status:string;submitted_at:string;project_id:string;application_kind?:string;requested_role?:string|null;projects:{title:string;status:string;project_type?:string}|null;project_roles:{title:string}|null;formation?:Formation|null};
type Membership={id:string;team_role:string;membership_status:string;project_id:string;project_run_id:string|null;projects:{title:string;status:string;project_type:string}|null;project_runs:{status:string;run_number:number}|null};
type Task={id:string;title:string;status:string;due_at:string|null;project_id:string;projects:{title:string}|null};
type CareerApp={id:string;status:string;submitted_at:string;career_roles:{title:string}|null};

export default async function MemberDashboard(){
  const supabase=await createServerSupabaseClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/signin');
  const [profileResult,appsResult,membersResult,proofResult,savedResult,tasksResult,careerResult]=await Promise.all([
    supabase.from('profiles').select('*').eq('id',user.id).single(),
    supabase.from('project_applications').select('id,status,submitted_at,project_id,application_kind,requested_role,projects(title,status,project_type),project_roles(title)',{count:'exact'}).eq('user_id',user.id).order('submitted_at',{ascending:false}).limit(3),
    supabase.from('project_members').select('id,team_role,membership_status,project_id,project_run_id,projects(title,status,project_type),project_runs(status,run_number)').eq('user_id',user.id).in('membership_status',['waiting','active','completed']).order('joined_at',{ascending:false}),
    supabase.from('contributions').select('id',{count:'exact',head:true}).eq('user_id',user.id).eq('verification_status','verified'),
    supabase.from('saved_opportunities').select('opportunity_id',{count:'exact',head:true}).eq('user_id',user.id),
    supabase.from('project_tasks').select('id,title,status,due_at,project_id,projects(title)').eq('assignee_user_id',user.id).neq('status','done').order('due_at',{ascending:true,nullsFirst:false}).limit(5),
    supabase.from('career_applications').select('id,status,submitted_at,career_roles(title)',{count:'exact'}).eq('user_id',user.id).order('submitted_at',{ascending:false}).limit(3)
  ]);
  const profile=profileResult.data||{};const memberships=(membersResult.data||[]) as unknown as Membership[];const tasks=(tasksResult.data||[]) as unknown as Task[];const rawApps=(appsResult.data||[]) as unknown as Application[];const careerApps=(careerResult.data||[]) as unknown as CareerApp[];
  const ids=[...new Set(rawApps.map(a=>a.project_id))];const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;const service=url&&key?createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}):null;const formations=new Map<string,Formation>();
  if(service&&ids.length){const [{data:projects},{data:members}]=await Promise.all([service.from('projects').select('id,team_size_threshold').in('id',ids),service.from('project_members').select('project_id,project_run_id,membership_status').in('project_id',ids).in('membership_status',['waiting','active'])]);for(const p of projects||[]){const relevant=(members||[]).filter(m=>m.project_id===p.id);const filled=relevant.length;const threshold=p.team_size_threshold||1;formations.set(p.id,{filled,threshold,status:'forming',is_full:filled>=threshold,kickoff_at:null})}}
  const apps=rawApps.map(a=>({...a,formation:formations.get(a.project_id)||null}));const active=memberships.filter(m=>m.membership_status==='active'&&m.project_runs?.status==='active');const waiting=memberships.filter(m=>m.membership_status==='waiting');
  const name=profile.full_name||user.user_metadata?.full_name||user.email?.split('@')[0]||'Member';const profileReady=Boolean(profile.full_name&&(profile.headline||profile.current_job_title||profile.professional_area)&&profile.skills?.length&&profile.project_availability);
  const attention=[!profileReady?{title:'Finish your profile',text:'Add your skills and availability so people can understand what you do.',href:'/member/profile',cta:'Update profile'}:null,tasks.length?{title:`${tasks.length} project task${tasks.length===1?'':'s'} to check`,text:'Open your workspace and update your progress.',href:`/member/projects/${tasks[0].project_id}`,cta:'Open project'}:null,waiting.length?{title:`${waiting.length} project team${waiting.length===1?' is':'s are'} forming`,text:'Your place is confirmed. We will show the start date when the team is ready.',href:'/member/applications',cta:'View status'}:null].filter(Boolean) as {title:string;text:string;href:string;cta:string}[];
  return <section className={`${styles.memberScope} section softSection memberWorkspace`}><div className="shell memberDashboardMain"><header className="memberHero"><div className="eyebrow">My Mettelo</div><h1>Welcome back, {name}.</h1><p className="lead">Pick up your work, check your applications and handle anything that needs you.</p></header>
    <div className="metricGrid memberMetricGrid"><a className="metric" href="/member/projects"><strong>{active.length}</strong><span>Active projects</span></a><a className="metric" href="/member/applications"><strong>{appsResult.count||0}</strong><span>Project applications</span></a><a className="metric" href="/member/applications#careers"><strong>{careerResult.count||0}</strong><span>Career applications</span></a><a className="metric" href="/member/proof"><strong>{proofResult.count||0}</strong><span>Verified Proof</span></a></div>
    <section className="panel memberSection" style={{marginTop:18}}><div className="panelHead"><div><span className="cardNumber">YOUR PROJECTS</span><h3 style={{marginTop:7}}>Continue your work</h3></div><a className="linkArrow" href="/member/projects">View projects →</a></div>{active.length?<div className="memberProjectList">{active.slice(0,4).map(item=><div className="listRow" key={item.id}><div><strong>{item.projects?.title||'Mettelo project'}</strong><br/><small>{item.projects?.project_type==='partner'?'Partner Project':'Open Project'} · Team {item.project_runs?.run_number||1} · {item.team_role.replaceAll('_',' ')}</small></div><a className="button dark" href={`/member/projects/${item.project_id}`}>Open workspace →</a></div>)}</div>:<div className="emptyState"><h3>No active project yet.</h3><p>When your team starts, the shared workspace will appear here.</p><a className="linkArrow" href="/projects">Find a project →</a></div>}</section>
    <section className="panel memberSection" style={{marginTop:18}}><div className="panelHead"><div><span className="cardNumber">APPLICATIONS</span><h3 style={{marginTop:7}}>Latest project requests</h3></div><a className="linkArrow" href="/member/applications">View all →</a></div><MemberApplicationTracker applications={apps}/></section>
    {careerApps.length>0&&<section className="panel memberSection" style={{marginTop:18}}><div className="panelHead"><div><span className="cardNumber">CAREERS</span><h3 style={{marginTop:7}}>Your Mettelo role applications</h3></div><a className="linkArrow" href="/member/applications#careers">View details →</a></div>{careerApps.map(item=><div className="listRow" key={item.id}><div><strong>{item.career_roles?.title||'Mettelo role'}</strong><br/><small>Applied {new Date(item.submitted_at).toLocaleDateString('en-GB')}</small></div><span className="chip">{item.status.replaceAll('_',' ').toUpperCase()}</span></div>)}</section>}
    <div className="dashboardGrid" style={{marginTop:18}}><section className="panel"><div className="panelHead"><div><span className="cardNumber">NEXT</span><h3 style={{marginTop:7}}>Needs your attention</h3></div></div>{attention.length?attention.map((item,index)=><div className="listRow" key={index}><div><strong>{item.title}</strong><br/><small>{item.text}</small></div><a className="button ghost" href={item.href}>{item.cta} →</a></div>):<div className="emptyState"><h3>You are up to date.</h3><p>Nothing needs your attention right now.</p><a className="linkArrow" href="/member/recommended">See recommendations →</a></div>}</section><aside className="panel"><div className="panelHead"><div><span className="cardNumber">TASKS</span><h3 style={{marginTop:7}}>Assigned to you</h3></div></div>{tasks.length?tasks.slice(0,4).map(task=><div className="listRow" key={task.id}><div><strong>{task.title}</strong><br/><small>{task.projects?.title||'Mettelo project'}{task.due_at?` · due ${new Date(task.due_at).toLocaleDateString('en-GB')}`:''}</small></div><span className="chip">{task.status.replaceAll('_',' ').toUpperCase()}</span></div>):<div className="emptyState"><h3>No open tasks.</h3><p>New project tasks will appear here.</p></div>}</aside></div>
    <p style={{marginTop:18,fontSize:12,color:'#7a838f'}}>You have {savedResult.count||0} saved opportunit{savedResult.count===1?'y':'ies'}.</p>
  </div></section>;
}
