import type { Metadata } from 'next';
import SubmissionForm from '@/components/SubmissionForm';

export const metadata: Metadata = {title:'Contact us',description:'Contact Mettelo about membership, projects, events, media, support or general enquiries.'};

export default function ContactPage(){return <>
<section className="hero"><div className="shell heroGrid"><div><div className="eyebrow">Contact Mettelo</div><h1>Start with the right route.</h1><p className="heroLead">Whether you are a member, contributor, organisation, speaker, employer or simply trying to understand Mettelo, give us enough context to route your enquiry well.</p></div><aside className="heroPanel"><span className="chip">ORGANISATIONS</span><h3 style={{marginTop:18}}>Partnership enquiry?</h3><p>Use the dedicated partnership form for projects, hiring, research, events, sponsorship or collaboration.</p><div className="actions"><a className="button dark" href="/partnership">Partnership form →</a></div></aside></div></section>
<section className="section"><div className="shell contactGrid"><div className="contactOptions"><div><div className="eyebrow">Choose your route</div><h2 style={{fontSize:'clamp(2.4rem,5vw,4.2rem)',margin:'0 0 22px'}}>What do you need help with?</h2></div><div className="contactOption"><small>MEMBERSHIP</small><strong>Joining or accessing Mettelo</strong><p>Questions about membership, onboarding, community access or your account.</p></div><div className="contactOption"><small>PROJECTS</small><strong>Labs and project applications</strong><p>Questions about a project brief, application, contributor role or active project.</p></div><div className="contactOption"><small>EVENTS & MEDIA</small><strong>Speaking, events and content</strong><p>Event questions, speaker enquiries, recorded sessions or media collaboration.</p></div><div className="contactOption"><small>OTHER</small><strong>General Mettelo enquiry</strong><p>Anything that does not fit the routes above.</p></div></div>
<SubmissionForm formType="contact" submitLabel="Send message →"><h3 style={{fontSize:'1.7rem',marginTop:0}}>Send us a message</h3><p style={{color:'var(--slate)'}}>Choose the closest route and tell us what you need. We removed the separate subject field because the topic and message already provide the routing context.</p><div className="fieldRow"><div><label htmlFor="contact-name">Full name *</label><input id="contact-name" required name="name" autoComplete="name"/></div><div><label htmlFor="contact-email">Email *</label><input id="contact-email" required name="email" type="email" autoComplete="email"/></div></div><label htmlFor="contact-topic">What is this about? *</label><select id="contact-topic" required name="topic" defaultValue=""><option value="" disabled>Select a topic</option><option value="membership_account">Membership / account</option><option value="project_application">Project application</option><option value="active_project">Active Mettelo project</option><option value="events_speaking">Events / speaker enquiry</option><option value="media">Media</option><option value="jobs_opportunities">Jobs / opportunities</option><option value="spotlight_awards">Spotlight / awards</option><option value="technical_issue">Technical issue</option><option value="community_moderation">Community / moderation</option><option value="general">General enquiry</option></select><label htmlFor="contact-message">How can we help? *</label><textarea id="contact-message" required minLength={10} name="message" placeholder="Include the project, page or account context when relevant so we can route this without unnecessary back-and-forth."/><label className="consent"><input required type="checkbox" name="consent" value="yes"/><span>I agree that Mettelo can use the information provided to respond to this enquiry.</span></label></SubmissionForm>
</div></section>
<section className="section softSection"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">Faster routes</div><h2>You may not need a general enquiry.</h2></div></div><div className="grid3"><article className="card"><span className="chip">PROJECTS</span><h3 style={{marginTop:18}}>Want to join a project?</h3><p>Browse Labs briefs and use the project application flow.</p><div className="actions"><a className="linkArrow" href="/projects">Browse projects →</a></div></article><article className="card"><span className="chip">MEMBERSHIP</span><h3 style={{marginTop:18}}>Want to join Mettelo?</h3><p>Create your account through the secure sign-up flow.</p><div className="actions"><a className="linkArrow" href="/signin">Create account →</a></div></article><article className="card"><span className="chip">PARTNERS</span><h3 style={{marginTop:18}}>Representing an organisation?</h3><p>Use the partnership form so we can assess the opportunity properly.</p><div className="actions"><a className="linkArrow" href="/partnership">Partnership form →</a></div></article></div></div></section>
</>}
