import type { Metadata } from 'next';
import { redirect } from 'next/navigation';
import { createClient } from '@supabase/supabase-js';
import { createServerSupabaseClient } from '@/lib/supabase/server';
import AdminOpportunityReviewQueue from '@/components/AdminOpportunityReviewQueue';
import AdminPublishedOpportunities from '@/components/AdminPublishedOpportunities';

export const metadata:Metadata={title:'Opportunity Management · Mettelo Admin'};
export const dynamic='force-dynamic';

type ReviewItem={id:string;title:string;organisation:string|null;location:string|null;role_family:string|null;data_ai_relevance_score:number|null;data_ai_relevance_status:string;verification_score:number|null;verification_status:string;verification_reasons:string[];source_type:string|null;source_url:string|null;official_application_url:string|null;eligibility_status:string;sponsorship_status:string;suspicion_score:number;updated_at:string};
type PublishedItem={id:string;title:string;organisation:string|null;location:string|null;data_ai_relevance_score:number|null;published_at:string|null;source_url:string|null;source_organisation:string|null;last_verified_at:string|null;next_verification_at:string|null;sponsorship_status:string;country_code:string|null};

export default async function OpportunityReviewPage(){
  const auth=await createServerSupabaseClient();const {data:{user}}=await auth.auth.getUser();if(!user)redirect('/signin');if(user.app_metadata?.role!=='admin')redirect('/member');
  const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;let items:ReviewItem[]=[];let publishedItems:PublishedItem[]=[];let total=0;let published=0;
  if(url&&key){const db=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});const [queue,publishedRows,countAll,countPublished]=await Promise.all([db.from('opportunities').select('id,title,organisation,location,role_family,data_ai_relevance_score,data_ai_relevance_status,verification_score,verification_status,verification_reasons,source_type,source_url,official_application_url,eligibility_status,sponsorship_status,suspicion_score,updated_at').eq('review_required',true).neq('verification_status','rejected').order('updated_at',{ascending:false}).limit(100),db.from('opportunities').select('id,title,organisation,location,data_ai_relevance_score,published_at,source_url,source_organisation,last_verified_at,next_verification_at,sponsorship_status,country_code').eq('status','published').order('published_at',{ascending:false}).limit(100),db.from('opportunities').select('id',{count:'exact',head:true}),db.from('opportunities').select('id',{count:'exact',head:true}).eq('status','published')]);items=(queue.data||[]) as ReviewItem[];publishedItems=(publishedRows.data||[]) as PublishedItem[];total=countAll.count||0;published=countPublished.count||0;}
  return <section className="section softSection"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">Mettelo Admin · Opportunities</div><h1>Keep the public Data & AI feed focused.</h1></div><p>Strong Data & AI matches can publish automatically. Admin retains final control and can remove any listing that does not meet the Mettelo standard.</p></div><div className="metricGrid"><div className="metric"><strong>{published}</strong><span>Published</span></div><div className="metric"><strong>{items.length}</strong><span>Needs review</span></div><div className="metric"><strong>{Math.max(total-published-items.length,0)}</strong><span>Draft / rejected / archived</span></div></div><div className="actions"><a className="button ghost" href="/admin">← Admin overview</a><a className="button ghost" href="/admin/opportunity-sources">Run job discovery →</a><a className="button ghost" href="/opportunities">Public opportunities →</a></div><section className="panel" style={{marginTop:18}}><div className="panelHead"><div><span className="cardNumber">LIVE OPPORTUNITIES</span><h3 style={{marginTop:8}}>Published Data & AI opportunities</h3></div><span className="chip green">{publishedItems.length} LIVE</span></div><p>See source and verification health here, and remove any listing immediately if it is off-topic, stale or does not meet the quality bar.</p><AdminPublishedOpportunities initialItems={publishedItems}/></section>{items.length>0&&<section className="panel" style={{marginTop:18}}><div className="panelHead"><div><span className="cardNumber">EXCEPTION REVIEW</span><h3 style={{marginTop:8}}>Only listings automation could not safely decide</h3></div><span className="chip">{items.length} WAITING</span></div><AdminOpportunityReviewQueue initialItems={items}/></section>}</div></section>;
}
