import AdminApplicationQueue from '@/components/AdminApplicationQueue';

const base={avatar_url:null,email:'member@example.test',project_id:'00000000-0000-4000-8000-00000000b701',project:'Community Data Quality Project',project_type:'open',partner_name:null,participation_mode:'team',difficulty:'Intermediate',weekly_commitment:'4–6 hours/week',recruitment_state:'Open',role:'No formal role at interest stage',application_kind:'interest',submitted_at:'2026-09-05T12:00:00.000Z',statement:'I want to contribute data-quality analysis, document findings and communicate recommendations clearly.',portfolio_url:'https://example.test/proof',availability:'Weekday evenings',participation_preference:'team',flexible_preference:null,effective_participation_mode:'team' as const,start_threshold:2,team_configuration:{minimum:2,target:4,maximum:5},leadership_interest:true,reviewer_notes:null,profile_completeness:92,admission_lane:'review_required' as const,profile:{headline:'Data analyst focused on quality and insight',skills:['SQL','Power BI','Data Quality'],experience_level:'Intermediate',project_availability:'Available now',weekly_capacity:'4–6 hours/week'},proof:[{title:'Verified data-quality contribution',description:'Validated a project dataset and documented the remediation approach.',evidence_url:'https://example.test/evidence',project_id:null,verification_status:'verified'}],capacity:{confirmed:2,reservedOffers:0,minimum:2,target:4,maximum:5},communications:[]};

const items=[
 {...base,id:'phase7-submitted',name:'Amina Okafor',username:'amina_data',member_id:'MTL-100101',status:'submitted',project:'Partner Customer Insight Project',project_type:'partner',partner_name:'Northstar Analytics'},
 {...base,id:'phase7-review',name:'Jordan Lee',username:'jordan_lee',member_id:'MTL-100102',status:'in_review',leadership_interest:false},
 {...base,id:'phase7-clarification',name:'Lena Martin',username:'lena_m',member_id:'MTL-100105',status:'clarification_requested',reviewer_notes:'Please clarify which data-quality checks you would use before analysis.'},
 {...base,id:'phase7-shortlist',name:'Priya Shah',username:'priya_shah',member_id:'MTL-100103',status:'shortlisted',participation_preference:'flexible',flexible_preference:'no_preference',effective_participation_mode:'flexible' as const,start_threshold:1},
 {...base,id:'phase7-offered',name:'Daniel Mensah',username:'daniel_m',member_id:'MTL-100104',status:'offered',participation_mode:'flexible',participation_preference:'solo',effective_participation_mode:'solo' as const,start_threshold:1,capacity:{confirmed:2,reservedOffers:1,minimum:2,target:4,maximum:5}},
 {...base,id:'phase7-auto',name:'Maya Chen',username:'maya_auto',member_id:'MTL-100106',status:'waiting_for_team',project:'Open AUTO Formation Project',admission_lane:'auto' as const,leadership_interest:false}
];

export default function Phase7AdminReviewFixture(){return <main id="main-content" style={{padding:'24px',maxWidth:'1280px',margin:'0 auto'}}><div className="eyebrow">PHASE 7 ACCEPTANCE FIXTURE</div><h1>Admin project-request review</h1><p>Rendered fixture for Partner and Open REVIEW_REQUIRED review plus AUTO oversight. AUTO submissions are visible but remain outside the human-review transition controls.</p><AdminApplicationQueue initialItems={items}/></main>}
