'use client';

import {FormEvent,useEffect,useState} from 'react';
import {createClient} from '@/lib/supabase/client';

export default function UpdatePasswordPage(){
  const [status,setStatus]=useState<'checking'|'idle'|'working'|'error'>('checking');const [message,setMessage]=useState('Checking your reset link…');const [showPassword,setShowPassword]=useState(false);const [showConfirm,setShowConfirm]=useState(false);
  useEffect(()=>{let active=true;const supabase=createClient();void supabase.auth.getSession().then(({data,error})=>{if(!active)return;if(error||!data.session){setStatus('error');setMessage('This reset link is invalid, expired or already used. Request a new password reset email and try again.')}else{setStatus('idle');setMessage('')}});return()=>{active=false}},[]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setStatus('working');setMessage('');try{const form=new FormData(event.currentTarget);const password=String(form.get('password')||'');const confirm=String(form.get('confirmPassword')||'');if(password.length<8)throw new Error('Use at least eight characters. A longer, unique password is recommended.');if(password!==confirm)throw new Error('The passwords do not match.');const supabase=createClient();const {error}=await supabase.auth.updateUser({password});if(error)throw error;window.location.assign('/auth/password-changed')}catch(error){setStatus('error');setMessage(error instanceof Error?error.message:'Unable to update password.')}}
  const unavailable=status==='checking'||(status==='error'&&(message.includes('expired')||message.includes('already used')));
  return <section className="section softSection"><div className="shell formShell"><div><div className="eyebrow">Account security</div><h1 style={{fontSize:'clamp(2.55rem,5.5vw,4.8rem)',margin:0}}>Choose a new password.</h1><p className="lead">Use at least 8 characters and choose a password you do not use on another account. Once saved, this recovery link cannot be reused.</p></div><form className="formCard" onSubmit={submit}><label htmlFor="password">New password *</label><div style={{display:'grid',gridTemplateColumns:'1fr auto',gap:8}}><input id="password" name="password" type={showPassword?'text':'password'} minLength={8} required autoComplete="new-password" disabled={unavailable}/><button className="button ghost" type="button" onClick={()=>setShowPassword(value=>!value)} aria-pressed={showPassword}>{showPassword?'Hide':'Show'}</button></div><label htmlFor="confirmPassword">Confirm new password *</label><div style={{display:'grid',gridTemplateColumns:'1fr auto',gap:8}}><input id="confirmPassword" name="confirmPassword" type={showConfirm?'text':'password'} minLength={8} required autoComplete="new-password" disabled={unavailable}/><button className="button ghost" type="button" onClick={()=>setShowConfirm(value=>!value)} aria-pressed={showConfirm}>{showConfirm?'Hide':'Show'}</button></div><button className="button dark" type="submit" disabled={unavailable||status==='working'} style={{width:'100%',marginTop:20}}>{status==='working'?'Updating…':'Update password →'}</button><div className={`formStatus ${status==='checking'?'idle':status}`} role="status" aria-live="polite">{message}</div>{unavailable&&<a className="button ghost" href="/signin?mode=reset" style={{width:'100%',marginTop:8}}>Request a new reset link →</a>}</form></div></section>;
}
