import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Partner with Mettelo',
  description: 'Partner with Mettelo on projects, talent, events, research, community and ecosystem initiatives.',
};

export default function PartnershipPage(){
  const routes=[
    ['Bring a real problem','Submit a problem brief that a multidisciplinary Mettelo Labs team can explore, analyse or build around.'],
    ['Access emerging talent','Work with Mettelo on contribution-led talent discovery, project exposure and future employer pathways.'],
    ['Partner on events','Co-create workshops, webinars, showcases, hackathons, networking sessions or specialist conversations.'],
    ['Research & insight','Collaborate on practical reports, surveys, datasets, benchmarks and sector intelligence.'],
    ['Support the ecosystem','Sponsor or resource projects, programmes, community infrastructure, events and recognition initiatives.'],
    ['Community collaboration','Create useful cross-community initiatives where the benefit to members and contributors is clear.']
  ];
  return <>
    <section className="hero"><div className="shell heroGrid"><div><div className="eyebrow">Partner with Mettelo</div><h1>Bring a problem, opportunity or idea worth building around.</h1><p className="heroLead">We want partnerships to create practical value for both organisations and professionals — through real project briefs, talent discovery, events, research, open source and meaningful ecosystem collaboration.</p><div className="actions"><a className="button dark" href="#partnership-form">Start partnership form →</a><a className="button ghost" href="/about">Understand Mettelo first</a></div></div><aside className="heroPanel"><span className="chip">GOOD PARTNERSHIP FIT</span><h3 style={{marginTop:18}}>Useful work. Clear ownership. Visible outcomes.</h3><p>A strong Mettelo partnership should create a real problem to solve, a real audience to serve, a real learning opportunity or a stronger route into professional opportunity.</p><div className="listRow"><strong>Problem briefs</strong><span>Labs →</span></div><div className="listRow"><strong>Talent & opportunity</strong><span>Access →</span></div><div className="listRow"><strong>Events & community</strong><span>Engage →</span></div><div className="listRow"><strong>Research & open source</strong><span>Build →</span></div></aside></div></section>

    <section className="section"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">Ways to collaborate</div><h2>Partnership should lead to something useful.</h2></div><p>We are deliberately broad about who can partner with Mettelo, but specific about the value a partnership should create.</p></div><div className="grid3">{routes.map(([t,c],i)=><article className="card featureCard" key={t}><div><div className="cardNumber">0{i+1}</div><h3 style={{marginTop:24}}>{t}</h3><p>{c}</p></div></article>)}</div></div></section>

    <section className="section softSection" id="partnership-form"><div className="shell formShell"><div className="formIntro"><div className="eyebrow">Partnership enquiry</div><h2 style={{fontSize:'clamp(2.5rem,5vw,4.4rem)',margin:0}}>Tell us enough to understand the opportunity.</h2><p className="lead">The form is structured to reduce unnecessary meetings. Give us the context, the outcome you want and what you can bring to the partnership.</p><div className="miniList"><div><strong>1. We review the fit</strong><span>Is this useful, realistic and aligned with Mettelo?</span></div><div><strong>2. We identify an owner</strong><span>The right Mettelo lead responds rather than routing everything through the founder.</span></div><div><strong>3. We define the next step</strong><span>Discovery call, project brief, event plan, research scope or partnership proposal.</span></div></div></div>
      <form className="formCard"><h3 style={{fontSize:'1.7rem',marginTop:0}}>Partnership application</h3><p style={{color:'var(--slate)'}}>Fields marked * should be completed before submission.</p>
        <div className="fieldRow"><div><label>Organisation name *</label><input required name="organisation" placeholder="Organisation or company"/></div><div><label>Organisation website</label><input name="website" type="url" placeholder="https://"/></div></div>
        <div className="fieldRow"><div><label>Your full name *</label><input required name="name" placeholder="Full name"/></div><div><label>Work email *</label><input required name="email" type="email" placeholder="name@organisation.com"/></div></div>
        <div className="fieldRow"><div><label>Your role *</label><input required name="role" placeholder="Job title / responsibility"/></div><div><label>Organisation type *</label><select required name="organisationType" defaultValue=""><option value="" disabled>Select one</option><option>Employer / Company</option><option>Startup / Technology company</option><option>Nonprofit / Charity</option><option>Government / Public sector</option><option>University / Research organisation</option><option>Professional community</option><option>Recruitment / Talent organisation</option><option>Other</option></select></div></div>
        <label>What type of partnership are you interested in? *</label><select required name="partnershipType" defaultValue=""><option value="" disabled>Select the closest fit</option><option>Submit a real problem / Mettelo Labs project</option><option>Talent discovery / jobs / referrals</option><option>Event / webinar / workshop partnership</option><option>Research / survey / data collaboration</option><option>Open-source collaboration</option><option>Sponsorship / ecosystem support</option><option>Community collaboration</option><option>Other partnership</option></select>
        <label>What are you trying to achieve? *</label><textarea required name="objective" placeholder="Describe the problem, opportunity or outcome you want to create."/>
        <label>What would your organisation contribute? *</label><textarea required name="contribution" placeholder="For example: problem brief, subject-matter experts, data, speakers, funding, mentorship, employer access, technology or other resources."/>
        <div className="fieldRow"><div><label>Preferred timeframe</label><select name="timeframe"><option>As soon as possible</option><option>Within 1 month</option><option>1–3 months</option><option>3–6 months</option><option>6+ months / exploratory</option></select></div><div><label>Approximate scale</label><select name="scale"><option>Small pilot</option><option>Single event / activity</option><option>Multi-week project</option><option>Ongoing partnership</option><option>Not sure yet</option></select></div></div>
        <label>Anything else we should know?</label><textarea name="notes" placeholder="Useful links, constraints, audience, geography, budget context or other details."/>
        <label className="consent"><input required type="checkbox"/><span>I confirm that the information provided can be used by Mettelo to assess and respond to this partnership enquiry.</span></label>
        <button className="button dark" type="submit" style={{width:'100%',marginTop:20}}>Submit partnership enquiry →</button><p style={{fontSize:'.74rem',color:'var(--slate)',marginTop:10}}>Submission storage and automated routing will be connected to the Mettelo database in the functional backend phase.</p>
      </form></div></section>
  </>;
}
