import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {createPublicSupabaseClient} from '@/lib/supabase/public';
import SocialShare from '@/components/SocialShare';

export const dynamic='force-dynamic';
type Spotlight={id:string;user_id:string;title:string;category:string;summary:string|null;award_month:string|null;profiles:{full_name:string|null;headline:string|null;avatar_url:string|null}|null};
async function getSpotlight(id:string){const db=createPublicSupabaseClient();if(!db)return null;const {data}=await db.from('spotlights').select('id,user_id,title,category,summary,award_month,profiles(full_name,headline,avatar_url)').eq('id',id).eq('status','published').eq('is_excluded',false).maybeSingle();return data as unknown as Spotlight|null;}
function monthLabel(value:string|null){if(!value)return 'Monthly Spotlight';return new Intl.DateTimeFormat('en-GB',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(`${value}T00:00:00Z`));}
export async function generateMetadata({params}:{params:Promise<{id:string}>}):Promise<Metadata>{const {id}=await params;const item=await getSpotlight(id);if(!item)return {title:'Spotlight & Awards'};const name=item.profiles?.full_name||'Mettelo member';const title=`${name} — ${item.title} · ${monthLabel(item.award_month)}`;const description=item.summary||`${name} has been recognised in Mettelo Spotlight & Awards.`;return {title,description,openGraph:{title,description,type:'article',url:`/spotlight/${item.id}`},twitter:{card:'summary_large_image',title,description}};}
export default async function SpotlightDetailPage({params}:{params:Promise<{id:string}>}){const {id}=await params;const item=await getSpotlight(id);if(!item)notFound();const name=item.profiles?.full_name?.trim()||'Mettelo member';const url=`https://mettelo.com/spotlight/${item.id}`;const text=`I’m recognised as ${item.title} in Mettelo’s ${monthLabel(item.award_month)} Spotlight & Awards.`;return <section className="section softSection"><div className="shell"><div className="panel" style={{maxWidth:760,margin:'0 auto'}}><div className="eyebrow">{monthLabel(item.award_month)} · Mettelo Spotlight</div><div className="personAvatar" style={item.profiles?.avatar_url?{backgroundImage:`url(${item.profiles.avatar_url})`,backgroundSize:'cover',backgroundPosition:'center',margin:'20px 0'}:{margin:'20px 0'}}>{item.profiles?.avatar_url?'':name.charAt(0).toUpperCase()}</div><span className="chip green">AWARD</span><h1 style={{marginTop:14}}>{item.title}</h1><h2>{name}</h2>{item.profiles?.headline&&<p><strong>{item.profiles.headline}</strong></p>}<p>{item.summary||'Recognised for meaningful contribution across Mettelo.'}</p><div className="actions" style={{alignItems:'center'}}><SocialShare url={url} text={text} label="Share this award"/><Link className="button ghost" href={`/people/${item.user_id}`}>View profile →</Link></div></div></div></section>;}
