import {redirect} from 'next/navigation';
import {createServerSupabaseClient} from '@/lib/supabase/server';
import {serviceDb} from '@/lib/project-flow';
export const dynamic='force-dynamic';
export default async function AdminDashboard(){
  const auth=await createServerSupabaseClient();const {data:{user}}=await auth.auth.getUser();if(!user)redirect('/signin');if(user.app_metadata?.role!=='admin')redirect('/member');
  const db=serviceDb();let counts={applications:0,formingTeams:0,activeTeams:0,reviewTeams:0,proof:0,intake:0,members:0};
  if(db){const [applications,formingTeams,activeTeams,reviewTeams,proof,intake,members]=await Promise.all([db.from('project_applications').select('id',{count:'exact',head:true}).in('status',['submitted','in_review','shortlisted']),db.from('project_runs').select('id',{count:'exact',head:true}).eq('status','forming'),db.from('project_runs').select('id',{count:'exact',head:true}).eq('status','active'),db.from('project_runs').select('id',{count:'exact',head:true}).eq('status','review'),db.from('contributions').select('id',{count:'exact',head:true}).in('verification_status',['pending','needs_changes']),db.from('form_submissions').select('id',{count:'exact',head:true}).eq('status','new'),db.from('profiles').select('id',{count:'exact',head:true})]);counts={applications:applications.count||0,formingTeams:formingTeams.count||0,activeTeams:activeTeams.count||0,reviewTeams:reviewTeams.count||0,proof:proof.count||0,intake:intake.count||0,members:members.count||0};}
  const cards=[['Applications',counts.applications,'Review project applications and decide what happens next.','/admin/applications'],['Project teams',counts.formingTeams,'See forming teams, assign leads and start delivery.','/admin/project-operations'],['Active teams',counts.activeTeams,'Check teams currently working on projects.','/admin/project-operations'],['Completion review',counts.reviewTeams,'Review teams that are ready to finish.','/admin/project-operations'],['Proof review',counts.proof,'Review evidence submitted by members.','/admin/proof'],['Publishing','', 'Create and manage Mettelo content.','/admin/content'],['General intake',counts.intake,'Review other requests sent to Mettelo.','/admin/intake'],['Admin access','', 'Choose who can use the Admin console.','/admin/access']];
  return <section className="section softSection"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">Mettelo Admin</div><h1>What needs attention?</h1></div><p>Start with applications and project teams, then move to reviews and publishing.</p></div><div className="metricGrid"><div className="metric"><strong>{counts.members}</strong><span>Members</span></div><div className="metric"><strong>{counts.applications}</strong><span>Applications to review</span></div><div className="metric"><strong>{counts.formingTeams}</strong><span>Teams forming</span></div><div className="metric"><strong>{counts.activeTeams}</strong><span>Active teams</span></div></div><div className="grid3" style={{marginTop:22}}>{cards.map(([title,count,text,href])=><article className="card" key={String(title)}><span className="cardNumber">{count!==''?`${count} OPEN`:'ADMIN'}</span><h3>{title}</h3><p>{text}</p><a className="linkArrow" href={String(href)}>Open →</a></article>)}</div></div></section>;
}
