import {redirect} from 'next/navigation';
import {createClient} from '@supabase/supabase-js';
import {createServerSupabaseClient} from '@/lib/supabase/server';

export const dynamic='force-dynamic';
type Membership={id:string;team_role:string;membership_status:string;joined_at:string;project_id:string;projects:{id:string;title:string;status:string;team_size_threshold:number|null}|null};
export default async function MyProjectsPage(){
  const auth=await createServerSupabaseClient();const {data:{user}}=await auth.auth.getUser();if(!user)redirect('/signin');
  const {data}=await auth.from('project_members').select('id,team_role,membership_status,joined_at,project_id,projects(id,title,status,team_size_threshold)').eq('user_id',user.id).order('joined_at',{ascending:false});
  const memberships=((data||[]) as unknown as Membership[]).filter(x=>!['removed','left'].includes(x.membership_status));const ids=memberships.map(x=>x.project_id);
  const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;const service=url&&key?createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}):null;const filled=new Map<string,number>();
  if(service&&ids.length){const {data:members}=await service.from('project_members').select('project_id,membership_status').in('project_id',ids).in('membership_status',['waiting','active']);for(const id of ids)filled.set(id,(members||[]).filter(m=>m.project_id===id).length);}
  const active=memberships.filter(x=>x.membership_status==='active');const waiting=memberships.filter(x=>x.membership_status==='waiting');const completed=memberships.filter(x=>x.membership_status==='completed'||x.projects?.status==='completed');
  const render=(items:Membership[],empty:string)=>items.length?<div className="memberProjectList">{items.map(item=>{const threshold=item.projects?.team_size_threshold||1;const count=filled.get(item.project_id)||0;const canOpen=item.membership_status==='active'||item.membership_status==='completed'||['active','review','completed'].includes(item.projects?.status||'');return <article className="memberProjectRow" key={item.id}><div className="memberProjectInfo"><strong>{item.projects?.title||'Mettelo Labs project'}</strong><small>{item.team_role.replaceAll('_',' ')} · {item.membership_status.replaceAll('_',' ')}</small>{item.membership_status==='waiting'&&<small>{count} of {threshold} team spots filled</small>}</div><div className="memberRowActions"><span className={`chip ${item.membership_status==='active'?'green':''}`}>{item.projects?.status?.toUpperCase()||item.membership_status.toUpperCase()}</span>{canOpen?<a className="button dark" href={`/member/projects/${item.project_id}`}>{item.membership_status==='completed'?'View workspace →':'Open workspace →'}</a>:<a className="button ghost" href="/member/applications">Track formation →</a>}</div></article>})}</div>:<div className="emptyState"><h3>{empty}</h3><p>Explore projects that match your capability and availability.</p><a className="linkArrow" href="/projects">Discover projects →</a></div>;
  return <section className="section softSection memberWorkspace"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">My work · Projects</div><h1>Your project workspace.</h1></div><p>See what is forming, what is active and what you have completed.</p></div><div className="metricGrid"><div className="metric"><strong>{waiting.length}</strong><span>Waiting for team</span></div><div className="metric"><strong>{active.length}</strong><span>Active</span></div><div className="metric"><strong>{completed.length}</strong><span>Completed</span></div></div><section className="panel" style={{marginTop:18}}><div className="panelHead"><h3>Active projects</h3><span className="chip green">WORK NOW</span></div>{render(active,'No active projects yet.')}</section><section className="panel" style={{marginTop:18}}><div className="panelHead"><h3>Waiting for team</h3><span className="chip">FORMING</span></div>{render(waiting,'No projects are currently forming around you.')}</section><section className="panel" style={{marginTop:18}}><div className="panelHead"><h3>Completed</h3></div>{render(completed,'No completed projects yet.')}</section></div><style>{`.memberProjectList{display:grid;gap:0}.memberProjectRow{display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:center;gap:24px;padding:20px 0;border-bottom:1px solid var(--line)}.memberProjectRow:last-child{border-bottom:0}.memberProjectInfo{min-width:0;display:grid;gap:6px}.memberProjectInfo strong{font-size:1rem;overflow-wrap:anywhere}.memberProjectInfo small{color:var(--slate)}.memberRowActions{display:grid;grid-template-columns:auto minmax(156px,auto);align-items:center;justify-content:end;gap:12px}.memberRowActions .chip{justify-self:end}.memberRowActions .button{min-height:44px;justify-content:center;white-space:nowrap}@media(max-width:760px){.memberProjectRow{grid-template-columns:1fr;gap:14px;padding:18px 0}.memberRowActions{grid-template-columns:1fr;justify-content:stretch}.memberRowActions .chip{justify-self:start}.memberRowActions .button{width:100%;min-height:46px}.memberWorkspace .panel{padding:18px}.memberWorkspace .panelHead{align-items:flex-start;gap:10px}.memberWorkspace .metricGrid{grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.memberWorkspace .metric{padding:14px 10px}.memberWorkspace .metric strong{font-size:1.35rem}.memberWorkspace .metric span{font-size:.68rem}}@media(max-width:420px){.memberWorkspace .metricGrid{grid-template-columns:1fr}.memberWorkspace .metric{display:flex;align-items:center;justify-content:space-between}}`}</style></section>;
}
