import {createClient} from '@supabase/supabase-js';
import {expect,test,type Page} from '@playwright/test';
import {PROJECT_PARTICIPATION_TERMS_VERSION} from '../lib/project-participation-terms';
import {GET as runFormationCron} from '../app/api/cron/project-formation/route';
import {makeGovernedProjectPublicationReady} from './helpers/governed-project-fixture';

const reviewProject='00000000-0000-4000-8000-00000000da01';
const soloProject='00000000-0000-4000-8000-00000000da02';
const teamProject='00000000-0000-4000-8000-00000000da03';
const flexSoloProject='00000000-0000-4000-8000-00000000da04';
const flexTeamProject='00000000-0000-4000-8000-00000000da05';
const raceProject='00000000-0000-4000-8000-00000000da06';

function required(name:string){const value=process.env[name]?.trim();if(!value)throw new Error(`${name} is required`);return value}
function db(){const url=required('E2E_SUPABASE_URL');if(!['127.0.0.1','localhost'].includes(new URL(url).hostname))throw new Error('Admin Project Applications E2E refuses non-local Supabase hosts.');return createClient(url,required('E2E_SUPABASE_SERVICE_ROLE_KEY'),{auth:{persistSession:false,autoRefreshToken:false}})}
async function identities(){const client=db();const {data,error}=await client.auth.admin.listUsers({page:1,perPage:1000});if(error)throw error;const member=data.users.find(user=>user.email===required('E2E_MEMBER_EMAIL'));const architect=data.users.find(user=>user.email===required('E2E_ARCHITECT_EMAIL'));const admin=data.users.find(user=>user.email===required('E2E_ADMIN_EMAIL'));if(!member||!architect||!admin)throw new Error('Admin Project Applications E2E requires member, architect and admin fixtures.');return{member,architect,admin}}
async function signIn(page:Page,email:string,password:string){await page.goto('/signin',{waitUntil:'domcontentloaded'});const main=page.locator('#main-content');await main.locator('input[type="email"]').fill(email);await main.locator('input[type="password"]').fill(password);await main.getByRole('button',{name:'Sign in →'}).click();await page.waitForURL(url=>!url.pathname.startsWith('/signin'),{timeout:20_000})}
async function cleanup(client:ReturnType<typeof db>,projectId:string){const {data:apps}=await client.from('project_applications').select('id').eq('project_id',projectId);const appIds=(apps||[]).map(row=>row.id);if(appIds.length)await client.from('project_application_events').delete().in('application_id',appIds);await client.from('project_offers').delete().eq('project_id',projectId);await client.from('project_activity_log').delete().eq('project_id',projectId);await client.from('project_members').delete().eq('project_id',projectId);await client.from('project_applications').delete().eq('project_id',projectId);await client.from('project_runs').delete().eq('project_id',projectId);await client.from('projects').delete().eq('id',projectId)}
async function seedProject(client:ReturnType<typeof db>,projectId:string,{admission='auto',participation='solo',min=1,target=1,max=1,type='open'}:{admission?:'auto'|'review_required';participation?:'solo'|'team'|'flexible';min?:number;target?:number;max?:number;type?:'open'|'partner'}={}){
 await cleanup(client,projectId);
 const inserted=await client.from('projects').insert({id:projectId,slug:`admin-start-${projectId.slice(-4)}`,title:`Admin start ${projectId.slice(-4)}`,summary:'Disposable Admin Project Applications acceptance fixture.',problem_statement:'Validate human review and AUTO formation/start boundaries.',status:'draft',visibility:'private',project_type:type,partner_name:type==='partner'?'E2E Partner':null,applications_open:false,team_size_threshold:min,min_team_size:min,target_team_size:target,max_team_size:max,participation_mode:participation,admission_mode:admission,auto_start_delay_minutes:360,late_joining_enabled:true});if(inserted.error)throw inserted.error;
 const {data:role,error:roleError}=await client.from('project_roles').insert({project_id:projectId,title:'Delivery Contributor',discipline:'Data & AI',description:'Disposable team role.',skills:['Collaboration'],responsibilities:['Delivery ownership'],openings:max}).select('id').single();if(roleError||!role)throw roleError||new Error('Could not seed project role.');
 await makeGovernedProjectPublicationReady(client,projectId);
 const opened=await client.from('projects').update({status:'open',visibility:'public',applications_open:true}).eq('id',projectId);if(opened.error)throw opened.error;
 return{roleId:role.id};
}
async function seedInterest(client:ReturnType<typeof db>,projectId:string,userId:string,preference:'solo'|'team'|'flexible',review=false){const now=new Date().toISOString();const payload:Record<string,unknown>={project_id:projectId,user_id:userId,project_role_id:null,status:'submitted',application_kind:'interest',participation_preference:preference,contribution_statement:'Admin Project Applications acceptance interest with enough detail.',terms_accepted_at:now,terms_version:PROJECT_PARTICIPATION_TERMS_VERSION,submitted_at:now};if(review){payload.admission_mode_snapshot='review_required';payload.admission_decision='review_required'}const {data,error}=await client.from('project_applications').insert(payload).select('id,status,project_run_id,admission_decision').single();if(error||!data)throw error||new Error('Could not seed project interest.');return data}
async function makeTeamReady(client:ReturnType<typeof db>,projectId:string,runId:string,adminId:string){const {data:role,error:roleError}=await client.from('project_roles').select('id').eq('project_id',projectId).eq('title','Delivery Contributor').single();if(roleError||!role)throw roleError||new Error('Role fixture missing.');const {data:members,error}=await client.from('project_members').select('id').eq('project_run_id',runId).in('membership_status',['waiting','active']).order('joined_at',{ascending:true});if(error||!members?.length)throw error||new Error('Membership fixture missing.');for(const member of members){const assigned=await client.rpc('phase10_assign_delivery_responsibility',{p_membership_id:member.id,p_responsibility:'Delivery ownership',p_source_project_role_id:role.id,p_actor_user_id:adminId,p_reason:'E2E readiness'});if(assigned.error)throw assigned.error}const lead=await client.rpc('phase10_confirm_project_lead',{p_membership_id:members[0].id,p_actor_user_id:adminId,p_reason:'E2E readiness'});if(lead.error)throw lead.error}
async function forceDue(client:ReturnType<typeof db>,runId:string){const reached=new Date(Date.now()-7*60*60_000).toISOString();const due=new Date(Date.now()-60_000).toISOString();const result=await client.from('project_runs').update({threshold_reached_at:reached,start_ready_at:reached,start_scheduled_at:reached,scheduled_start_at:due,auto_start_failure:null}).eq('id',runId).eq('has_started',false);if(result.error)throw result.error}
async function cron(){const previous=process.env.CRON_SECRET;const secret='admin-app-auto-start-e2e';process.env.CRON_SECRET=secret;try{return await runFormationCron(new Request('http://127.0.0.1:3000/api/cron/project-formation',{headers:{authorization:`Bearer ${secret}`}}))}finally{if(previous===undefined)delete process.env.CRON_SECRET;else process.env.CRON_SECRET=previous}}
async function adminStart(page:Page,projectId:string,runId:string){const response=await page.context().request.patch('/api/admin/project-admission',{data:{project_id:projectId,project_run_id:runId,action:'start_run'}});const body=await response.json().catch(()=>({}));return{response,body}}

test.describe.configure({mode:'serial'});
test.describe('Admin Project Applications review and AUTO start recovery',()=>{
 test('SC-56 Start Review works from the real Admin queue, persists and records reviewer/audit history',async({page,browser})=>{const client=db();const {member,admin}=await identities();await seedProject(client,reviewProject,{admission:'review_required',participation:'team',min:2,target:3,max:4});try{const app=await seedInterest(client,reviewProject,member.id,'team',true);await signIn(page,required('E2E_ADMIN_EMAIL'),required('E2E_ADMIN_PASSWORD'));await page.goto(`/admin/project-operations/applications?project=${reviewProject}`,{waitUntil:'networkidle'});const row=page.locator('.applicationTable tbody tr').filter({hasText:'Admin start da01'}).first();await expect(row).toBeVisible();await row.locator('.rowMenu summary').click();await row.getByRole('button',{name:'Start review'}).click();await expect(page.locator('.formStatus')).toContainText('moved to In review');await expect(page.getByRole('dialog')).toBeVisible();const stored=await client.from('project_applications').select('status').eq('id',app.id).single();expect(stored.data?.status).toBe('in_review');const event=await client.from('project_application_events').select('from_status,to_status,actor_user_id').eq('application_id',app.id).eq('to_status','in_review').order('created_at',{ascending:false}).limit(1).single();expect(event.data).toMatchObject({from_status:'submitted',to_status:'in_review',actor_user_id:admin.id});const activity=await client.from('project_activity_log').select('event_type,actor_user_id').eq('project_id',reviewProject).eq('event_type','review_started').order('created_at',{ascending:false}).limit(1).single();expect(activity.data).toMatchObject({event_type:'review_started',actor_user_id:admin.id});await page.reload({waitUntil:'networkidle'});await expect(page.locator('.applicationTable tbody tr').filter({hasText:'Admin start da01'}).first()).toContainText(/In review/i);const memberContext=await browser.newContext();const memberPage=await memberContext.newPage();await signIn(memberPage,required('E2E_MEMBER_EMAIL'),required('E2E_MEMBER_PASSWORD'));const denied=await memberPage.context().request.patch('/api/admin/applications',{data:{id:app.id,status:'shortlisted'}});expect(denied.status()).toBe(403);await memberContext.close()}finally{await cleanup(client,reviewProject)}});

 test('SC-57/62 AUTO Solo: row UI hides early start, then exposes governed Start Project Now after six hours',async({page})=>{const client=db();const {member}=await identities();await seedProject(client,soloProject,{admission:'auto',participation:'solo',min:1,target:1,max:1});try{const app=await seedInterest(client,soloProject,member.id,'solo');expect(app.admission_decision).toBe('auto_qualified');const runId=app.project_run_id!;const before=await client.from('project_runs').select('threshold_reached_at,scheduled_start_at,has_started').eq('id',runId).single();expect(before.data?.threshold_reached_at).toBeTruthy();expect(Date.parse(before.data!.scheduled_start_at!)).toBeGreaterThan(Date.now());await signIn(page,required('E2E_ADMIN_EMAIL'),required('E2E_ADMIN_PASSWORD'));await page.goto(`/admin/project-operations/applications?project=${soloProject}`,{waitUntil:'networkidle'});const row=page.locator('.applicationTable tbody tr').filter({hasText:'Admin start da02'}).first();await expect(row).toBeVisible();await row.locator('.rowMenu summary').click();await expect(row.getByRole('button',{name:'Start project now'})).toHaveCount(0);await expect(row.getByRole('link',{name:'View status'})).toBeVisible();const early=await adminStart(page,soloProject,runId);expect(early.response.status()).toBe(409);expect(early.body).toMatchObject({status:'eligibility_window'});await forceDue(client,runId);await page.reload({waitUntil:'networkidle'});const readyRow=page.locator('.applicationTable tbody tr').filter({hasText:'Admin start da02'}).first();await readyRow.locator('.rowMenu summary').click();await readyRow.getByRole('button',{name:'Start project now'}).click();const confirm=page.getByRole('dialog',{name:'Start project?'});await expect(confirm).toContainText('completed the six-hour eligibility window');await confirm.getByRole('button',{name:'Start project',exact:true}).click();await expect(page.locator('.formStatus')).toContainText(/started successfully/i);const run=await client.from('project_runs').select('id,status,has_started').eq('id',runId).single();expect(run.data).toMatchObject({id:runId,status:'active',has_started:true});const runs=await client.from('project_runs').select('id').eq('project_id',soloProject);expect(runs.data).toHaveLength(1)}finally{await cleanup(client,soloProject)}});

 test('SC-58 Team starts at configured minimum 2, not target 5, and recruitment may remain open',async({page})=>{const client=db();const {member,architect,admin}=await identities();await seedProject(client,teamProject,{admission:'auto',participation:'team',min:2,target:5,max:5});try{const first=await seedInterest(client,teamProject,member.id,'team');const runId=first.project_run_id!;let run=await client.from('project_runs').select('required_team_size,scheduled_start_at').eq('id',runId).single();expect(run.data).toMatchObject({required_team_size:2,scheduled_start_at:null});const second=await seedInterest(client,teamProject,architect.id,'team');expect(second.project_run_id).toBe(runId);run=await client.from('project_runs').select('required_team_size,threshold_reached_at,scheduled_start_at').eq('id',runId).single();expect(run.data?.required_team_size).toBe(2);expect(run.data?.scheduled_start_at).toBeTruthy();await makeTeamReady(client,teamProject,runId,admin.id);await forceDue(client,runId);await signIn(page,required('E2E_ADMIN_EMAIL'),required('E2E_ADMIN_PASSWORD'));const start=await adminStart(page,teamProject,runId);expect(start.response.status(),JSON.stringify(start.body)).toBe(200);const active=await client.from('project_runs').select('status,has_started,recruitment_open').eq('id',runId).single();expect(active.data).toMatchObject({status:'active',has_started:true,recruitment_open:true});const members=await client.from('project_members').select('id',{count:'exact',head:true}).eq('project_run_id',runId).eq('membership_status','active');expect(members.count).toBe(2)}finally{await cleanup(client,teamProject)}});

 test('SC-59/60 Flexible resolves both Solo and Team effective thresholds canonically',async({page})=>{const client=db();const {member,architect,admin}=await identities();await signIn(page,required('E2E_ADMIN_EMAIL'),required('E2E_ADMIN_PASSWORD'));await seedProject(client,flexSoloProject,{admission:'auto',participation:'flexible',min:2,target:4,max:5});await seedProject(client,flexTeamProject,{admission:'auto',participation:'flexible',min:2,target:4,max:5});try{const solo=await seedInterest(client,flexSoloProject,member.id,'solo');let run=await client.from('project_runs').select('required_team_size,scheduled_start_at').eq('id',solo.project_run_id).single();expect(run.data?.required_team_size).toBe(1);expect(run.data?.scheduled_start_at).toBeTruthy();await forceDue(client,solo.project_run_id!);expect((await adminStart(page,flexSoloProject,solo.project_run_id!)).response.status()).toBe(200);const team1=await seedInterest(client,flexTeamProject,member.id,'team');run=await client.from('project_runs').select('required_team_size,scheduled_start_at').eq('id',team1.project_run_id).single();expect(run.data).toMatchObject({required_team_size:2,scheduled_start_at:null});const team2=await seedInterest(client,flexTeamProject,architect.id,'team');expect(team2.project_run_id).toBe(team1.project_run_id);await makeTeamReady(client,flexTeamProject,team1.project_run_id!,admin.id);await forceDue(client,team1.project_run_id!);expect((await adminStart(page,flexTeamProject,team1.project_run_id!)).response.status()).toBe(200)}finally{await cleanup(client,flexSoloProject);await cleanup(client,flexTeamProject)}});

 test('SC-26..28 losing minimum clears threshold; regaining creates fresh window; extra member does not reset it',async()=>{const client=db();const {member,architect}=await identities();await seedProject(client,teamProject,{admission:'auto',participation:'team',min:2,target:3,max:4});try{const a=await seedInterest(client,teamProject,member.id,'team');const b=await seedInterest(client,teamProject,architect.id,'team');const runId=a.project_run_id!;expect(b.project_run_id).toBe(runId);const reached=await client.from('project_runs').select('threshold_reached_at,scheduled_start_at').eq('id',runId).single();const oldThreshold=reached.data?.threshold_reached_at;expect(oldThreshold).toBeTruthy();const membership=await client.from('project_members').select('id').eq('project_run_id',runId).eq('user_id',architect.id).single();await client.from('project_members').update({membership_status:'left',left_at:new Date().toISOString()}).eq('id',membership.data!.id);let state=await client.from('project_runs').select('threshold_reached_at,scheduled_start_at').eq('id',runId).single();expect(state.data).toMatchObject({threshold_reached_at:null,scheduled_start_at:null});await client.from('project_members').update({membership_status:'waiting',left_at:null}).eq('id',membership.data!.id);state=await client.from('project_runs').select('threshold_reached_at,scheduled_start_at').eq('id',runId).single();expect(state.data?.threshold_reached_at).toBeTruthy();expect(state.data?.threshold_reached_at).not.toBe(oldThreshold);const freshThreshold=state.data!.threshold_reached_at!;const freshSchedule=state.data!.scheduled_start_at!;expect(Date.parse(freshSchedule)-Date.parse(freshThreshold)).toBe(6*60*60_000);const users=await client.auth.admin.listUsers({page:1,perPage:1000});const extra=users.data.users.find(user=>user.email!==required('E2E_MEMBER_EMAIL')&&user.email!==required('E2E_ARCHITECT_EMAIL')&&user.email!==required('E2E_ADMIN_EMAIL'));if(extra){await seedInterest(client,teamProject,extra.id,'team');const unchanged=await client.from('project_runs').select('threshold_reached_at,scheduled_start_at').eq('id',runId).single();expect(unchanged.data).toMatchObject({threshold_reached_at:freshThreshold,scheduled_start_at:freshSchedule})}}finally{await cleanup(client,teamProject)}});

 test('SC-61..63 cron and Admin race use one canonical start and produce one activation',async({page})=>{const client=db();const {member}=await identities();await seedProject(client,raceProject,{admission:'auto',participation:'solo',min:1,target:1,max:1});try{const app=await seedInterest(client,raceProject,member.id,'solo');const runId=app.project_run_id!;await forceDue(client,runId);await signIn(page,required('E2E_ADMIN_EMAIL'),required('E2E_ADMIN_PASSWORD'));const [adminResult,cronResult]=await Promise.all([adminStart(page,raceProject,runId),cron()]);expect([200,409]).toContain(adminResult.response.status());expect(cronResult.status).toBe(200);const run=await client.from('project_runs').select('id,status,has_started').eq('id',runId).single();expect(run.data).toMatchObject({id:runId,status:'active',has_started:true});const runs=await client.from('project_runs').select('id').eq('project_id',raceProject);expect(runs.data).toHaveLength(1);const events=await client.from('project_activity_log').select('id',{count:'exact',head:true}).eq('project_run_id',runId).in('event_type',['project_auto_started','project_auto_start_retry_started','project_manual_started']);expect(events.count).toBe(1);const activeMembers=await client.from('project_members').select('id',{count:'exact',head:true}).eq('project_run_id',runId).eq('membership_status','active');expect(activeMembers.count).toBe(1)}finally{await cleanup(client,raceProject)}});
});
