import {expect,test,type Page} from '@playwright/test';

type Credentials={email:string;password:string};
const labProjectId='00000000-0000-4000-8000-00000000e2e1';
const labTeam1RunId='00000000-0000-4000-8000-00000000e211';
const labTeam2RunId='00000000-0000-4000-8000-00000000e212';
const labUrl=(view='home',run=labTeam1RunId)=>`/member/projects/${labProjectId}?run=${run}&view=${view}`;
function credentials(prefix:'MEMBER'|'ARCHITECT'|'ADMIN'):Credentials{const email=process.env[`E2E_${prefix}_EMAIL`]?.trim();const password=process.env[`E2E_${prefix}_PASSWORD`];if(!email||!password)throw new Error(`Missing E2E_${prefix}_EMAIL or E2E_${prefix}_PASSWORD. Run npm run check:e2e-config first.`);return{email,password}}
async function signIn(page:Page,account:Credentials,next:string){await page.goto(`/signin?next=${encodeURIComponent(next)}`,{waitUntil:'networkidle'});const main=page.locator('#main-content');await main.locator('input[type="email"]').fill(account.email);await main.locator('input[type="password"]').fill(account.password);await main.getByRole('button',{name:'Sign in →'}).click();await page.waitForURL(url=>!url.pathname.startsWith('/signin'),{timeout:20_000})}
async function noOverflow(page:Page,label:string){const dimensions=await page.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth}));expect(dimensions.scrollWidth,label).toBeLessThanOrEqual(dimensions.clientWidth)}

test.describe('authenticated staging smoke tests',()=>{
 test('member Applications matches the approved responsive composition',async({page})=>{const account=credentials('MEMBER');await signIn(page,account,'/member/applications');
  for(const width of [375,390,414,768,1024,1440]){await page.setViewportSize({width,height:900});await page.goto('/member/applications',{waitUntil:'networkidle'});await expect(page.getByRole('heading',{name:'Applications',exact:true})).toBeVisible();await expect(page.getByText('MY WORK · PROJECT REQUESTS',{exact:true})).toBeVisible();await expect(page.getByText('Track project interests, automatic project entry, governed review, clarification requests, team formation and confirmed project work from one canonical request history. Project offers and explicit acceptance are shown here before membership begins.',{exact:true})).toBeVisible();await expect(page.getByLabel('Current section')).toHaveCount(1);await expect(page.locator('nav[aria-label="Breadcrumb"]')).toHaveCount(0);await expect(page.getByText('Your recruitment journey')).toHaveCount(0);await expect(page.getByRole('heading',{name:'Looking for another project?'})).toBeVisible();await noOverflow(page,`Applications overflowed at ${width}px`);
   const summary=page.getByLabel('Project request summary');if(await summary.count()){await expect(summary).toBeVisible();for(const label of ['Needs you','In review / offered','Team forming','Closed'])await expect(summary.getByText(label,{exact:true})).toBeVisible();const cards=summary.locator('article');const boxes=await cards.evaluateAll(elements=>elements.map(element=>{const box=element.getBoundingClientRect();return{y:box.y}}));if(width>=1025){for(const box of boxes.slice(1))expect(Math.abs(box.y-boxes[0].y),`Applications summary should stay four-up at ${width}px`).toBeLessThanOrEqual(1)}else if(boxes.length===4){expect(Math.abs(boxes[1].y-boxes[0].y)).toBeLessThanOrEqual(1);expect(boxes[2].y).toBeGreaterThan(boxes[0].y+20);expect(Math.abs(boxes[3].y-boxes[2].y)).toBeLessThanOrEqual(1)}
    const filters=page.getByLabel('Search and filter project requests');await expect(filters).toBeVisible();await expect(page.getByLabel('Search project requests')).toHaveAttribute('placeholder','Search project requests');await expect(page.getByLabel('Filter legacy requests by project role').locator('option').first()).toHaveText('All roles');const needs=page.getByRole('button',{name:'Needs action'});await needs.click();await expect(needs).toHaveAttribute('aria-pressed','true');await expect(page.getByRole('heading',{name:'Looking for another project?'})).toBeVisible();await page.getByRole('button',{name:'Current',exact:true}).click();}
   const currentCard=page.locator('.mmaApplicationCard').first();if(await currentCard.count()){const columns=await currentCard.evaluate(element=>getComputedStyle(element).gridTemplateColumns.trim().split(/\s+/).filter(Boolean).length);expect(columns,`Applications card composition at ${width}px`).toBe(width>=1025?2:1)}
   const desktopNav=page.getByRole('complementary',{name:'My Mettelo navigation'});const mobileNav=page.getByRole('navigation',{name:'My Mettelo mobile navigation'});const discoverAction=page.locator('a.applicationsButtonDark[href="/member/discover"]');await expect(discoverAction).toBeVisible();if(width<=480){await expect(desktopNav).toBeHidden();await expect(mobileNav).toBeVisible();await expect(mobileNav.locator(':scope > details > summary')).toHaveAttribute('aria-current','page')}else{await expect(desktopNav).toBeVisible();await expect(mobileNav).toBeHidden();await expect(desktopNav.locator('a[href="/member/applications"]')).toHaveAttribute('aria-current','page')}
   const frame=await page.locator('.applicationsPage').boundingBox();if(frame&&width>=1025)expect(frame.width).toBeLessThanOrEqual(1181);
  }
 });
 test('non-admin member sees only their own Lab team and Mettelo Lab never overflows',async({page})=>{test.slow();const account=credentials('MEMBER');await signIn(page,account,labUrl());const apiResponse=await page.context().request.get(`/api/project-team-overview?project_id=${labProjectId}&project_run_id=${labTeam1RunId}`);expect(apiResponse.status()).toBe(200);const payload=await apiResponse.json();const own=payload.teams.find((team:{run_number:number})=>team.run_number===1);const other=payload.teams.find((team:{run_number:number})=>team.run_number===2);expect(own).toMatchObject({id:labTeam1RunId,is_member:true});expect(Array.isArray(own.members)).toBe(true);expect(own.members.length).toBeGreaterThan(0);expect(other).toMatchObject({id:'cohort-2',run_number:2,status:'forming',is_member:false,required_team_size:null,has_started:null,members:[]});expect(JSON.stringify(other)).not.toContain(labTeam2RunId);
  const teamResponse=await page.goto(labUrl('team'),{waitUntil:'networkidle'});expect(teamResponse?.status()).toBe(200);const teamSection=page.locator('#team');await expect(teamSection).toBeVisible();await expect(teamSection.getByText('YOUR TEAM · METTELO LAB',{exact:true})).toBeVisible();await expect(teamSection.getByRole('heading',{name:/Team 1/})).toBeVisible();await expect(page.getByText('Open project cohorts',{exact:true})).toHaveCount(0);await expect(page.getByText('Not a member of this cohort',{exact:true})).toHaveCount(0);await expect(page.getByText(/Team 2/)).toHaveCount(0);await expect(page.locator('[data-lab-home-section]').first()).toBeHidden();
  const forbidden=await page.goto(labUrl('team',labTeam2RunId),{waitUntil:'domcontentloaded'});expect(forbidden?.status()).toBe(404);
  for(const width of [375,390,414,768,1024,1440]){await page.setViewportSize({width,height:900});await page.goto(labUrl('home'),{waitUntil:'networkidle'});const dimensions=await page.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth}));expect(dimensions.scrollWidth,`Mettelo Lab page overflowed at ${width}px`).toBeLessThanOrEqual(dimensions.clientWidth);const cta=page.locator('#mettelo-lab').getByRole('link',{name:/Continue task|View next event|View team|View team status/}).first();await expect(cta).toBeVisible();const box=await cta.boundingBox();expect(box?.height||0).toBeGreaterThanOrEqual(44);if(width<=480){await expect(page.getByRole('navigation',{name:'Mettelo Lab mobile navigation'})).toBeVisible();await expect(page.getByRole('navigation',{name:'Member mobile navigation'})).toBeHidden()}else if(width<=1024){await expect(page.locator('aside[aria-label="Mettelo Lab workspace"]')).toBeVisible();await expect(page.getByText('METTELO LAB',{exact:true}).first()).toBeVisible()}else{await expect(page.locator('aside[aria-label="Mettelo Lab workspace"]')).toBeVisible()}}
 });
 test('Project Architect can open their project workspace',async({page})=>{const account=credentials('ARCHITECT');await signIn(page,account,'/member/architect-projects');await page.goto('/member/architect-projects',{waitUntil:'networkidle'});await expect(page.locator('#main-content')).toBeVisible();await expect(page).toHaveURL(/\/member\/architect-projects/)});
 test('admin can open project applications and intake queues',async({page})=>{const account=credentials('ADMIN');await signIn(page,account,'/admin');await page.goto('/admin/project-operations/applications',{waitUntil:'networkidle'});await expect(page.getByRole('heading',{level:1,name:/^Project requests\b/i})).toBeVisible();await page.goto('/admin/intake',{waitUntil:'networkidle'});await expect(page.locator('#main-content')).toBeVisible();await expect(page).toHaveURL(/\/admin\/intake/)});
 test('admin mobile navigation is a bounded accessible application drawer',async({page})=>{test.slow();const account=credentials('ADMIN');await signIn(page,account,'/admin/project-operations/projects');
  for(const width of [320,360,375,390,412,430,768,1024]){await page.setViewportSize({width,height:900});await page.goto('/admin/project-operations/projects',{waitUntil:'networkidle'});await expect(page.getByRole('heading',{level:1,name:'Projects'})).toBeVisible();await noOverflow(page,`Admin projects overflowed at ${width}px`);const nav=page.locator('#admin-primary-navigation');const menu=page.locator('.adminMenuButton');const active=nav.locator('a[href="/admin/project-operations/projects"]');await expect(active).toHaveAttribute('aria-current','page');const memberSwitch=page.locator('a.memberSwitch[href="/member"]');await expect(memberSwitch).toHaveAttribute('href','/member');
   if(width<=760){await expect(menu).toBeVisible();const memberBox=await memberSwitch.boundingBox();expect(memberBox?.height||0).toBeGreaterThanOrEqual(42);await expect(menu).toHaveAttribute('aria-expanded','false');await menu.click();await expect(menu).toHaveAttribute('aria-expanded','true');await expect(nav).toHaveClass(/isOpen/);await expect.poll(async()=>Math.round((await nav.boundingBox())?.x??-999),{message:`Admin drawer should settle inside the viewport at ${width}px`}).toBeGreaterThanOrEqual(-1);const navBox=await nav.boundingBox();expect(navBox,`Admin drawer should have geometry at ${width}px`).not.toBeNull();expect(navBox?.width||0).toBeLessThanOrEqual(Math.min(360,width*.95)+1);expect(navBox?.height||0).toBeGreaterThanOrEqual(899);const close=nav.locator('button[data-admin-nav-close]');const closeBox=await close.boundingBox();expect(closeBox?.width||0).toBeGreaterThanOrEqual(44);expect(closeBox?.height||0).toBeGreaterThanOrEqual(44);const activeBox=await active.boundingBox();expect(activeBox?.height||0).toBeGreaterThanOrEqual(48);const overviewBox=await nav.locator('a.adminOverviewLink').boundingBox();expect((activeBox?.y||999)-(overviewBox?.y||0),`Active Projects group should be discoverable near the top at ${width}px`).toBeLessThan(330);const bodyOverflow=await page.evaluate(()=>document.body.style.overflow);expect(bodyOverflow).toBe('hidden');await noOverflow(page,`Open Admin drawer overflowed at ${width}px`);await page.keyboard.press('Escape');await expect(menu).toHaveAttribute('aria-expanded','false');await expect(menu).toBeFocused();}
   else{await expect(menu).toBeHidden();await expect(nav).toBeVisible();const position=await nav.evaluate(element=>getComputedStyle(element).position);expect(position).toBe('sticky');}
  }
 });
 test('admin audit log page and API are usable, bounded and responsive',async({page})=>{const account=credentials('ADMIN');await signIn(page,account,'/admin/system/audit');
  const api=page.context().request;const response=await api.get('/api/admin/audit?page=1&page_size=25');expect(response.status()).toBe(200);const payload=await response.json();expect(payload).toMatchObject({page:1,page_size:25});expect(Array.isArray(payload.items)).toBe(true);expect(typeof payload.total).toBe('number');expect(typeof payload.pages).toBe('number');
  const invalid=await api.get('/api/admin/audit?result=not-a-result');expect(invalid.status()).toBe(400);
  for(const width of [390,768,1440]){await page.setViewportSize({width,height:900});await page.goto('/admin/system/audit',{waitUntil:'networkidle'});await expect(page.getByRole('heading',{level:1,name:'Audit log'})).toBeVisible();const filters=page.locator('form[action="/admin/system/audit"]');await expect(filters).toBeVisible();await expect(page.getByRole('textbox',{name:'Actor email or ID'})).toBeVisible();await expect(page.getByRole('combobox',{name:'Result'})).toBeVisible();await expect(page.getByRole('combobox',{name:'Rows'})).toHaveValue('25');await expect(page.getByRole('button',{name:'Apply filters'})).toBeVisible();await noOverflow(page,`Admin audit page overflowed at ${width}px`);}
 });
});
