import {createHash} from 'node:crypto';
import {createClient} from '@supabase/supabase-js';
import {expect,test,type Page} from '@playwright/test';
import type {CapabilityPathImportManifest} from '@/lib/capability-path-import-workbook';

type ImportReviewRow={decision:string;row_kind:string};
type ImportReviewResource={id:string;governance_status:string};
type ImportDetail={rows:ImportReviewRow[];resources:ImportReviewResource[]};

function credentials(){const email=process.env.E2E_ADMIN_EMAIL?.trim(),password=process.env.E2E_ADMIN_PASSWORD;if(!email||!password)throw new Error('Missing E2E admin credentials.');return{email,password}}
async function signIn(page:Page,next:string){const account=credentials();await page.goto(`/signin?next=${encodeURIComponent(next)}`,{waitUntil:'networkidle'});const main=page.locator('#main-content');await main.locator('input[type="email"]').fill(account.email);await main.locator('input[type="password"]').fill(account.password);await main.getByRole('button',{name:'Sign in →'}).click();await page.waitForURL(url=>!url.pathname.startsWith('/signin'),{timeout:20_000})}
function serviceDb(){const url=process.env.E2E_SUPABASE_URL?.trim(),key=process.env.E2E_SUPABASE_SERVICE_ROLE_KEY?.trim();if(!url||!key)throw new Error('Missing isolated Supabase service credentials.');if(!['127.0.0.1','localhost'].includes(new URL(url).hostname))throw new Error('Phase 5 import test refuses non-local Supabase.');return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
function manifest(stamp:string,existingTitle:string):CapabilityPathImportManifest{
 const projects=Array.from({length:117},(_,i)=>({source_key:`E2E-P${String(i+1).padStart(3,'0')}`,source_sheet:'Project Library',source_row:i+5,slug:`e2e-import-${stamp}-project-${i+1}`,title:i===0?existingTitle:`E2E Import ${stamp} Project ${i+1}`,summary:`Decision-ready project ${i+1} for the Phase 5 realistic-volume import acceptance.`,problem_statement:`A realistic problem statement for project ${i+1} that is deliberately long enough to exercise governed import content without pretending that the workbook automatically publishes production copy. The Admin must still review this private Draft before release.`,use_case:`Use the project to demonstrate controlled import, canonical reuse and reviewable evidence for project ${i+1}.`,decision_to_support:'Which evidence-backed option should the stakeholder prioritise?',project_objective:'Produce a governed analytical recommendation.',deliverables:'1. Analysis. 2. Decision memo. 3. Reviewable evidence pack.',success_criteria:'- Reproducible analysis.\n- Decision linked to evidence.\n- Limitations documented.',stakeholder:'E2E Stakeholder',domain:'',dataset:`E2E Dataset ${i+1}`,source_organisation:'Mettelo E2E',source_url:`https://example.com/e2e/${stamp}/${i+1}`,licence:'Test fixture only',data_reality:'Synthetic isolated CI fixture',technical_skills:[],professional_skills:[],tools:[],methods:[],team_roles:'1 Project Lead, 2 Analysts, 1 Reviewer',evidence_proof:'Analysis, memo and reviewed contribution evidence.',duration_weeks:4,weekly_commitment:'5 hours per week',team_size:4,review_decision:'APPROVE'}));
 const paths=Array.from({length:15},(_,i)=>({source_key:`e2e-path-${stamp}-${i+1}`,source_sheet:`E2E Path ${i+1}`,source_row:i+5,slug:`e2e-path-${stamp}-${i+1}`,name:`E2E Capability Path ${stamp} ${i+1}`,target_role:`E2E Target Role ${i+1}`,short_description:'A recommended professional progression through real project work.',description:'Synthetic isolated acceptance Path used to prove realistic import volume.',progression_summary:'Foundation → Applied → Advanced',target_outcome:`Build toward governed E2E capability ${i+1}.`,sort_order:(i+1)*10}));
 const placements:CapabilityPathImportManifest['placements']=[];for(let p=0;p<15;p++){const path=paths[p];const ids:number[]=[];for(let position=1;position<=15;position++){const index=(p*7+position-1)%117;ids.push(index);placements.push({source_key:`${path.source_key}:${projects[index].source_key}`,source_sheet:path.source_sheet,source_row:position+6,path_key:path.source_key,project_source_key:projects[index].source_key,position,stage_name:position<=5?'Foundation':position<=10?'Applied':'Advanced',stage_slug:position<=5?'foundation':position<=10?'applied':'advanced',competency_focus:`Competency focus ${p+1}.${position}`,capability_built:`Capability built ${p+1}.${position}`,prerequisite_project_source_key:position>1?projects[ids[position-2]].source_key:'',path_outcome:`Path outcome ${p+1}.${position}`})}}
 const sourceSha256=createHash('sha256').update(`capability-paths-phase5-${stamp}`).digest('hex');
 return{manifest_version:'capability-paths-v1',source_filename:`E2E_Capability_Paths_${stamp}.xlsx`,source_sha256:sourceSha256,source_version:'e2e-realistic-volume',expected:{paths:15,placements:225,projects:117},paths,projects,placements,resources:[{project_source_key:projects[0].source_key,title:'Existing project reference source',source_organisation:'Mettelo E2E',source_url:`https://example.com/e2e/${stamp}/green`,licence:'CC BY 4.0',data_reality:'Synthetic test',governance_status:'green',storage_decision:'link_only',attribution_required:true,review_note:'GREEN — link-only fixture'},{project_source_key:projects[1].source_key,title:'Amber provenance fixture',source_organisation:'Mettelo E2E',source_url:`https://example.com/e2e/${stamp}/amber`,licence:'Needs upstream review',data_reality:'Synthetic test',governance_status:'amber',storage_decision:'link_only',attribution_required:false,review_note:'AMBER — provenance review'}]};
}

async function post(page:Page,data:Record<string,unknown>){const response=await page.context().request.post('/api/admin/capability-paths/import',{data});return{response,body:await response.json().catch(()=>({}))}}

test.describe('Capability Paths Phase 5 controlled import',()=>{
 test('15 Paths / 225 placements / 117 canonical candidates dry-run, commit idempotently and rollback safely',async({page})=>{
  test.setTimeout(120_000);const db=serviceDb();const {data:existing}=await db.from('projects').select('id,title').eq('id','00000000-0000-4000-8000-00000000e2e1').maybeSingle();expect(existing,'canonical E2E project fixture is required').toBeTruthy();const stamp=Date.now().toString(36),input=manifest(stamp,existing!.title);
  const [{count:projectCountBefore},{count:appBefore},{count:memberBefore},{count:proofBefore}]=await Promise.all([db.from('projects').select('id',{count:'exact',head:true}),db.from('project_applications').select('id',{count:'exact',head:true}).eq('project_id',existing!.id),db.from('project_members').select('id',{count:'exact',head:true}).eq('project_id',existing!.id),db.from('contributions').select('id',{count:'exact',head:true}).eq('project_id',existing!.id)]);
  await signIn(page,'/admin/capability-paths/import');
  const started=Date.now();const dry=await post(page,{action:'dry_run',manifest:input});expect(dry.response.status()).toBe(201);expect(dry.body.summary.actual).toEqual({paths:15,placements:225,projects:117});expect(dry.body.summary.count_issues).toEqual([]);expect(dry.body.summary.reused_existing_projects).toBe(1);expect(Date.now()-started).toBeLessThan(60_000);const batchId=String(dry.body.batch_id);
  const detail=await page.context().request.get(`/api/admin/capability-paths/import?id=${batchId}`);expect(detail.status()).toBe(200);const detailBody=await detail.json() as ImportDetail;expect(detailBody.rows.filter(row=>['pending','needs_changes','blocked'].includes(row.decision))).toHaveLength(0);expect(detailBody.rows.filter(row=>row.row_kind==='placement')).toHaveLength(225);expect(detailBody.rows.filter(row=>row.row_kind==='project')).toHaveLength(117);
  const amber=detailBody.resources.find(item=>item.governance_status==='amber');expect(amber).toBeTruthy();const unsafe=await post(page,{action:'resource_decision',batch_id:batchId,resource_id:amber!.id,storage_decision:'store_allowed'});expect(unsafe.response.status()).toBe(409);
  const approve=await post(page,{action:'approve',batch_id:batchId});expect(approve.response.status()).toBe(200);
  const commitStarted=Date.now();const committed=await post(page,{action:'commit',batch_id:batchId});expect(committed.response.status()).toBe(200);expect(committed.body.result.created_paths).toBe(15);expect(committed.body.result.created_projects).toBe(116);expect(committed.body.result.reused_projects).toBe(1);expect(committed.body.result.placements).toBe(225);expect(Date.now()-commitStarted).toBeLessThan(60_000);
  const [pathOrigins,projectOrigins,placementOrigins,{data:importedPaths},{data:newProjects}]=await Promise.all([db.from('capability_path_import_path_origins').select('path_id',{count:'exact'}).eq('batch_id',batchId),db.from('capability_path_import_project_origins').select('project_id,was_existing',{count:'exact'}).eq('batch_id',batchId),db.from('capability_path_import_placement_origins').select('source_key',{count:'exact'}).eq('batch_id',batchId),db.from('capability_paths').select('id,status').like('slug',`e2e-path-${stamp}-%`),db.from('projects').select('id,status,visibility,title').like('slug',`e2e-import-${stamp}-project-%`)]);expect(pathOrigins.count).toBe(15);expect(projectOrigins.count).toBe(117);expect(projectOrigins.data?.filter(row=>row.was_existing)).toHaveLength(1);expect(placementOrigins.count).toBe(225);expect(importedPaths).toHaveLength(15);expect(importedPaths?.every(item=>item.status==='draft')).toBe(true);expect(newProjects).toHaveLength(116);expect(newProjects?.every(item=>item.status==='draft'&&item.visibility==='private')).toBe(true);
  const secondCommit=await post(page,{action:'commit',batch_id:batchId});expect(secondCommit.response.status()).toBe(200);expect(secondCommit.body.result.already_imported).toBe(true);
  const duplicateDry=await post(page,{action:'dry_run',manifest:input});expect(duplicateDry.response.status()).toBe(200);expect(duplicateDry.body.reused).toBe(true);expect(duplicateDry.body.batch_id).toBe(batchId);
  const rollback=await post(page,{action:'rollback',batch_id:batchId});expect(rollback.response.status()).toBe(200);expect(rollback.body.result.removed_paths).toBe(15);expect(rollback.body.result.removed_projects).toBe(116);expect(rollback.body.result.retained_projects).toBe(0);
  const [{count:projectCountAfter},{count:remainingPaths},{count:remainingNewProjects},{count:appAfter},{count:memberAfter},{count:proofAfter},{data:existingAfter},{data:batchAfter}]=await Promise.all([db.from('projects').select('id',{count:'exact',head:true}),db.from('capability_paths').select('id',{count:'exact',head:true}).like('slug',`e2e-path-${stamp}-%`),db.from('projects').select('id',{count:'exact',head:true}).like('slug',`e2e-import-${stamp}-project-%`),db.from('project_applications').select('id',{count:'exact',head:true}).eq('project_id',existing!.id),db.from('project_members').select('id',{count:'exact',head:true}).eq('project_id',existing!.id),db.from('contributions').select('id',{count:'exact',head:true}).eq('project_id',existing!.id),db.from('projects').select('id,title').eq('id',existing!.id).maybeSingle(),db.from('capability_path_import_batches').select('status').eq('id',batchId).single()]);expect(projectCountAfter).toBe(projectCountBefore);expect(remainingPaths).toBe(0);expect(remainingNewProjects).toBe(0);expect(appAfter).toBe(appBefore);expect(memberAfter).toBe(memberBefore);expect(proofAfter).toBe(proofBefore);expect(existingAfter?.id).toBe(existing!.id);expect(batchAfter.status).toBe('rolled_back');
  const rerun=await post(page,{action:'dry_run',manifest:input});expect(rerun.response.status()).toBe(201);expect(rerun.body.batch_id).not.toBe(batchId);const rerunId=String(rerun.body.batch_id);await db.from('capability_path_import_batches').delete().eq('id',rerunId);
 });
});