import {expect,test,type Page} from '@playwright/test';

const eventId='00000000-0000-4000-8000-00000000e299';
const joinUrl=`/member/events/${eventId}/join`;
function required(name:string){const value=process.env[name]?.trim();if(!value)throw new Error(`Missing ${name}.`);return value;}
async function signIn(page:Page){await page.goto(`/signin?next=${encodeURIComponent(joinUrl)}`,{waitUntil:'networkidle'});const main=page.locator('#main-content');await main.locator('input[type="email"]').fill(required('E2E_MEMBER_EMAIL'));await main.locator('input[type="password"]').fill(required('E2E_MEMBER_PASSWORD'));await main.getByRole('button',{name:'Sign in →'}).click();await page.waitForURL(url=>!url.pathname.startsWith('/signin'),{timeout:20_000});}
async function openFailure(page:Page){await page.route(`**/api/project-events/${eventId}/token`,route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Live video is temporarily unavailable.',code:'SERVICE_UNAVAILABLE',eventId,stage:'token'})}));await signIn(page);await page.goto(joinUrl,{waitUntil:'domcontentloaded'});return page.locator('[data-event-room-surface="failure"]');}

test('failure state is announced, keyboard reachable and does not rely on colour alone',async({page})=>{const failure=await openFailure(page);await expect(failure).toBeVisible();const role=await failure.getAttribute('role');expect(['alert','status']).toContain(role);const retry=failure.getByRole('button',{name:/try again/i});if(await retry.count()){await retry.focus();await expect(retry).toBeFocused();const box=await retry.boundingBox();expect(box?.width??0).toBeGreaterThanOrEqual(44);expect(box?.height??0).toBeGreaterThanOrEqual(44);}await expect(failure.getByRole('link',{name:/upcoming events/i})).toBeVisible();});

test('200 and 400 percent reflow keep the failure journey operable without page-level horizontal scrolling',async({page})=>{const failure=await openFailure(page);await expect(failure).toBeVisible();for(const scale of [2,4]){await page.locator('html').evaluate((el,value)=>{(el as HTMLElement).style.fontSize=`${value*100}%`;},scale);const metrics=await page.evaluate(()=>({client:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth}));expect(metrics.scroll).toBeLessThanOrEqual(metrics.client+1);await expect(failure.getByRole('link',{name:/upcoming events/i})).toBeVisible();}});

test('reduced motion does not remove state meaning or recovery actions',async({page})=>{await page.emulateMedia({reducedMotion:'reduce'});const failure=await openFailure(page);await expect(failure).toBeVisible();await expect(failure).toContainText(/unavailable|unable|try|event/i);await expect(failure.getByRole('link',{name:/upcoming events/i})).toBeVisible();});

test('interactive room controls expose semantic names and state without leaking sensitive identifiers',async({page})=>{await page.route(`**/api/project-events/${eventId}/token`,route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({token:'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwaGFzZTEyIiwiaWF0IjoxLCJleHAiOjk5OTk5OTk5OTl9.signature',url:'ws://10.255.255.1:65535',event:{id:eventId,title:'Phase 12 room'},role:'contributor'})}));await signIn(page);await page.goto(joinUrl,{waitUntil:'domcontentloaded'});await expect(page.locator('[data-event-room-shell]')).toBeVisible();const buttons=page.locator('[data-event-room-shell] button:visible');const count=await buttons.count();for(let i=0;i<count;i++){const button=buttons.nth(i);const name=(await button.getAttribute('aria-label'))||((await button.textContent())??'').trim();expect(name.length).toBeGreaterThan(0);}const exposed=((await page.locator('body').textContent())??'').toLowerCase();expect(exposed).not.toContain('livekit_api_secret');expect(exposed).not.toContain('10.255.255.1');});