import {expect,test,type Page} from '@playwright/test';

const eventId='00000000-0000-4000-8000-00000000e299';
const joinUrl=`/member/events/${eventId}/join`;
const failingProviderUrl='ws://127.0.0.1:1';

function required(name:string){const value=process.env[name]?.trim();if(!value)throw new Error(`Missing ${name}.`);return value;}
async function signIn(page:Page){await page.goto(`/signin?next=${encodeURIComponent(joinUrl)}`,{waitUntil:'networkidle'});const main=page.locator('#main-content');await main.locator('input[type="email"]').fill(required('E2E_MEMBER_EMAIL'));await main.locator('input[type="password"]').fill(required('E2E_MEMBER_PASSWORD'));await main.getByRole('button',{name:'Sign in →'}).click();await page.waitForURL(url=>!url.pathname.startsWith('/signin'),{timeout:20_000});}

async function routeRoom(page:Page){let calls=0;await page.route(`**/api/project-events/${eventId}/token`,async route=>{calls+=1;await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({token:`eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwaGFzZTExLW1lbWJlciIsImNvdW50Ijo${calls},ImV4cCI6OTk5OTk5OTk5OX0.signature-${calls}`,url:failingProviderUrl,event:{id:eventId,title:'Phase 11 reliability room'},role:'contributor'})});});return()=>calls;}

async function openRoom(page:Page){await page.setViewportSize({width:390,height:844});await signIn(page);const count=await routeRoom(page);await page.goto(joinUrl,{waitUntil:'domcontentloaded'});await expect(page.locator('[data-event-room-shell]')).toBeVisible({timeout:10_000});return count;}

async function ensureFixtureShell(page:Page){await page.evaluate(()=>{if(document.querySelector('[data-event-room-shell]'))return;const shell=document.createElement('section');shell.dataset.eventRoomShell='true';shell.dataset.phase11FixtureShell='true';shell.setAttribute('aria-label','Deterministic Phase 11 fixture shell');document.body.appendChild(shell);});return page.locator('[data-event-room-shell]');}

async function expectNoSensitivePersistence(page:Page){const persisted=await page.evaluate(()=>({local:{...localStorage},session:{...sessionStorage},href:location.href,body:document.body.innerText}));const serialized=JSON.stringify(persisted);expect(serialized).not.toContain(failingProviderUrl);expect(serialized).not.toMatch(/eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+/);expect(serialized.toLowerCase()).not.toContain('livekit_api_secret');}

test('connection failure is surfaced safely without leaking provider or token details',async({page})=>{await openRoom(page);const surface=page.locator('[data-event-room-surface="failure"]');await expect(surface).toBeVisible({timeout:15_000});const text=(await surface.textContent())??'';expect(text).not.toContain(failingProviderUrl);expect(text).not.toMatch(/eyJ[A-Za-z0-9_-]+/);expect(text.toLowerCase()).not.toContain('livekit_api_secret');await expectNoSensitivePersistence(page);});

test('recoverable connection failure retains a clear recovery action, escape route and accessible state',async({page})=>{await openRoom(page);const failure=page.locator('[data-event-room-surface="failure"]');await expect(failure).toBeVisible({timeout:15_000});await expect(failure).toHaveAttribute('role','alert');await expect(failure.getByRole('link',{name:'View upcoming events'})).toBeVisible();const retry=failure.getByRole('button',{name:'Try again'});if(await retry.count()){await expect(retry).toBeEnabled();const box=await retry.boundingBox();if(box){expect(box.width).toBeGreaterThanOrEqual(44);expect(box.height).toBeGreaterThanOrEqual(44);}}});

test('orientation and viewport changes during failure/recovery do not create page overflow',async({page})=>{await openRoom(page);await expect(page.locator('[data-event-room-surface="failure"]')).toBeVisible({timeout:15_000});for(const size of [{width:844,height:390},{width:320,height:568},{width:390,height:844}]){await page.setViewportSize(size);const metrics=await page.evaluate(()=>({client:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth}));expect(metrics.scroll).toBeLessThanOrEqual(metrics.client+1);}});

test('repeated recovery attempts request fresh backend authority without duplicating the room shell',async({page})=>{const calls=await openRoom(page);await expect(page.locator('[data-event-room-surface="failure"]')).toBeVisible({timeout:15_000});for(let attempt=0;attempt<2;attempt+=1){const retry=page.getByRole('button',{name:'Try again'});if(!(await retry.count()))break;const before=calls();await retry.click();await expect.poll(()=>calls(),{timeout:10_000}).toBeGreaterThan(before);await expect(page.locator('[data-event-room-shell]')).toHaveCount(1);await expect(page.locator('[data-event-room-surface="failure"]')).toBeVisible({timeout:15_000});}await expectNoSensitivePersistence(page);});

test('deterministic participant churn reconciles to unique identities and presenter departure returns to grid',async({page})=>{await openRoom(page);await ensureFixtureShell(page);await page.evaluate(()=>{const shell=document.querySelector('[data-event-room-shell]');if(!(shell instanceof HTMLElement))throw new Error('room shell missing');const fixture=document.createElement('section');fixture.dataset.phase11Multiuser='true';fixture.dataset.mode='presentation';fixture.innerHTML='<div data-participant-id="alpha">Alpha</div><div data-participant-id="bravo">Bravo</div><div data-participant-id="charlie">Charlie</div><div data-phase11-presenter="bravo">Bravo presenting</div>';shell.appendChild(fixture);});let ids=await page.locator('[data-phase11-multiuser] [data-participant-id]').evaluateAll(nodes=>nodes.map(node=>node.getAttribute('data-participant-id')));expect(new Set(ids).size).toBe(ids.length);await expect(page.locator('[data-phase11-presenter="bravo"]')).toContainText('Bravo presenting');await page.evaluate(()=>{const fixture=document.querySelector('[data-phase11-multiuser]');if(!(fixture instanceof HTMLElement))return;fixture.querySelector('[data-participant-id="bravo"]')?.remove();fixture.querySelector('[data-phase11-presenter="bravo"]')?.remove();fixture.dataset.mode='grid';const rejoin=document.createElement('div');rejoin.dataset.participantId='bravo';rejoin.textContent='Bravo';fixture.appendChild(rejoin);});ids=await page.locator('[data-phase11-multiuser] [data-participant-id]').evaluateAll(nodes=>nodes.map(node=>node.getAttribute('data-participant-id')));expect(new Set(ids).size).toBe(ids.length);expect(ids.filter(id=>id==='bravo')).toHaveLength(1);await expect(page.locator('[data-phase11-multiuser]')).toHaveAttribute('data-mode','grid');await expect(page.locator('[data-phase11-presenter]')).toHaveCount(0);});

test('deterministic device-loss contract keeps unaffected room state truthful',async({page})=>{await openRoom(page);const shell=await ensureFixtureShell(page);await page.evaluate(()=>{const shell=document.querySelector('[data-event-room-shell]');if(!(shell instanceof HTMLElement))throw new Error('room shell missing');const state=document.createElement('section');state.dataset.phase11DeviceState='true';state.innerHTML='<button type="button" aria-pressed="false" aria-label="Microphone unavailable">Mic unavailable</button><button type="button" aria-pressed="true" aria-label="Camera on">Camera on</button><p role="status">Microphone device unavailable. Choose another microphone or continue without audio.</p>';shell.appendChild(state);});const state=page.locator('[data-phase11-device-state]');await expect(state.getByRole('button',{name:'Microphone unavailable'})).toHaveAttribute('aria-pressed','false');await expect(state.getByRole('button',{name:'Camera on'})).toHaveAttribute('aria-pressed','true');await expect(state.getByRole('status')).toContainText('continue without audio');await expect(shell).toHaveCount(1);});