import {expect,test,type APIRequestContext,type Page} from '@playwright/test';
import {createClient} from '@supabase/supabase-js';

const projectId='00000000-0000-4000-8000-00000000e2e1';
const runId='00000000-0000-4000-8000-00000000e211';
type JwtPayload={iat?:number;exp?:number;sub?:string;video?:{room?:string;roomJoin?:boolean}};

function required(name:string){const value=process.env[name]?.trim();if(!value)throw new Error(`Missing ${name}.`);return value;}
function serviceDb(){return createClient(required('E2E_SUPABASE_URL'),required('E2E_SUPABASE_SERVICE_ROLE_KEY'),{auth:{persistSession:false,autoRefreshToken:false}});}
function decodeJwt(token:string):JwtPayload{const part=token.split('.')[1];if(!part)throw new Error('Token is not a JWT.');return JSON.parse(Buffer.from(part,'base64url').toString('utf8')) as JwtPayload;}
async function signIn(page:Page,prefix:'MEMBER'|'ARCHITECT'|'ADMIN'){await page.goto('/signin',{waitUntil:'networkidle'});const main=page.locator('#main-content');await main.locator('input[type="email"]').fill(required(`E2E_${prefix}_EMAIL`));await main.locator('input[type="password"]').fill(required(`E2E_${prefix}_PASSWORD`));await main.getByRole('button',{name:'Sign in →'}).click();await page.waitForURL(url=>!url.pathname.startsWith('/signin'),{timeout:20_000});}
async function userId(email:string){const {data,error}=await serviceDb().auth.admin.listUsers({page:1,perPage:1000});if(error)throw error;const user=data.users.find(item=>item.email?.toLowerCase()===email.toLowerCase());if(!user)throw new Error(`Missing E2E user ${email}.`);return user.id;}
async function createEvent(request:APIRequestContext,title:string){const start=new Date(Date.now()+5*60*1000),end=new Date(start.getTime()+60*60*1000);const response=await request.post('/api/project-events',{data:{action:'create',project_id:projectId,project_run_id:runId,title,purpose:'Phase 10 lifecycle contract.',event_type:'learning_session',visibility:'community_learning',agenda:'Prove backend join authority.',learning_objectives:'Validate lifecycle transitions.',timezone:'Europe/London',starts_at:start.toISOString(),ends_at:end.toISOString(),capacity:20,meeting_mode:'mettelo_video',presenter_ids:[],required_attendee_ids:[]}});expect(response.status()).toBe(200);const body=await response.json();return body.event_id as string;}
async function setEvent(eventId:string,values:Record<string,unknown>){const {error}=await serviceDb().from('project_meetings').update(values).eq('id',eventId);if(error)throw error;}
async function token(request:APIRequestContext,eventId:string){return request.post(`/api/project-events/${eventId}/token`);}

test.describe.configure({mode:'serial'});

test('backend join window remains authoritative across too-early to active to cancelled transition',async({page})=>{await signIn(page,'ADMIN');const id=await createEvent(page.context().request,`Phase 10 lifecycle ${Date.now()}`);await setEvent(id,{starts_at:new Date(Date.now()+60*60*1000).toISOString(),ends_at:new Date(Date.now()+2*60*60*1000).toISOString()});let response=await token(page.context().request,id);expect(response.status()).toBe(425);expect((await response.json()).code).toBe('TOO_EARLY');await setEvent(id,{starts_at:new Date(Date.now()+5*60*1000).toISOString(),ends_at:new Date(Date.now()+65*60*1000).toISOString()});response=await token(page.context().request,id);expect(response.status()).toBe(200);await setEvent(id,{status:'cancelled'});response=await token(page.context().request,id);expect(response.status()).toBe(410);expect((await response.json()).code).toBe('EVENT_CANCELLED');});

test('entitlement is re-evaluated on every token request and can be revoked then restored',async({page})=>{await signIn(page,'ADMIN');const id=await createEvent(page.context().request,`Phase 10 entitlement ${Date.now()}`);const architect=await userId(required('E2E_ARCHITECT_EMAIL'));const admin=await userId(required('E2E_ADMIN_EMAIL'));const db=serviceDb();let result=await db.from('project_event_participants').insert({event_id:id,project_run_id:runId,user_id:architect,event_role:'observer',invited_by:admin});if(result.error)throw result.error;await page.context().clearCookies();await signIn(page,'ARCHITECT');let response=await token(page.context().request,id);expect(response.status()).toBe(200);result=await db.from('project_event_participants').delete().eq('event_id',id).eq('user_id',architect);if(result.error)throw result.error;response=await token(page.context().request,id);expect(response.status()).toBe(403);expect((await response.json()).code).toBe('NO_PERMISSION');result=await db.from('project_event_participants').insert({event_id:id,project_run_id:runId,user_id:architect,event_role:'observer',invited_by:admin});if(result.error)throw result.error;response=await token(page.context().request,id);expect(response.status()).toBe(200);});

test('issued access token is short lived, scoped to the same member and room, and cannot outlive the client indefinitely',async({page})=>{await signIn(page,'ADMIN');const id=await createEvent(page.context().request,`Phase 10 ttl ${Date.now()}`);const room=`phase10-${id}`;await setEvent(id,{provider_room_name:room});const response=await token(page.context().request,id);expect(response.status()).toBe(200);const body=await response.json();const payload=decodeJwt(body.token);expect(payload.sub).toBe(await userId(required('E2E_ADMIN_EMAIL')));expect(payload.video?.roomJoin).toBe(true);expect(payload.video?.room).toBe(room);expect(payload.iat).toBeTruthy();expect(payload.exp).toBeTruthy();if(payload.iat&&payload.exp){const ttl=payload.exp-payload.iat;expect(ttl).toBeGreaterThan(0);expect(ttl).toBeLessThanOrEqual(10*60+5);}});

test('session close is enforced on a new join/rejoin attempt after the close grace window',async({page})=>{await signIn(page,'ADMIN');const id=await createEvent(page.context().request,`Phase 10 close ${Date.now()}`);let response=await token(page.context().request,id);expect(response.status()).toBe(200);await setEvent(id,{starts_at:new Date(Date.now()-2*60*60*1000).toISOString(),ends_at:new Date(Date.now()-31*60*1000).toISOString()});response=await token(page.context().request,id);expect(response.status()).toBe(410);expect((await response.json()).code).toBe('SESSION_ENDED');});
