import {createClient} from '@supabase/supabase-js';
import {expect,test,type Page} from '@playwright/test';
import {mkdir} from 'node:fs/promises';

const widths=[320,375,390,414,768,1024,1440] as const;
const projectId='00000000-0000-4000-8000-00000000d151';
const roleId='00000000-0000-4000-8000-00000000d152';
const title='E2E Member Discover Project';
const artifactDir='artifacts/member-discover-v1';
let memberId='';

type Credentials={email:string;password:string};
function credentials():Credentials{const email=process.env.E2E_MEMBER_EMAIL?.trim();const password=process.env.E2E_MEMBER_PASSWORD;if(!email||!password)throw new Error('Missing E2E member credentials.');return{email,password}}
function localDb(){const url=process.env.E2E_SUPABASE_URL?.trim();const key=process.env.E2E_SUPABASE_SERVICE_ROLE_KEY?.trim();if(!url||!key)throw new Error('Missing isolated E2E Supabase credentials.');if(!['127.0.0.1','localhost'].includes(new URL(url).hostname))throw new Error('Member Discover fixture refuses non-local Supabase hosts.');return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
async function signIn(page:Page){const account=credentials();await page.goto('/signin?next=%2Fmember%2Fdiscover',{waitUntil:'networkidle'});const main=page.locator('#main-content');await main.locator('input[type="email"]').fill(account.email);await main.locator('input[type="password"]').fill(account.password);await main.getByRole('button',{name:'Sign in →'}).click();await page.waitForURL(url=>url.pathname==='/member/discover',{timeout:20_000})}
async function noOverflow(page:Page,label:string){const size=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth,body:document.body.scrollWidth}));expect(size.scroll,`${label}: document overflow`).toBeLessThanOrEqual(size.client);expect(size.body,`${label}: body overflow`).toBeLessThanOrEqual(size.client)}
async function columns(page:Page,selector:string){return page.locator(selector).first().evaluate(element=>getComputedStyle(element).gridTemplateColumns.trim().split(/\s+/).filter(Boolean).length)}
async function resetMemberState(){const db=localDb();for(const query of [db.from('project_applications').delete().eq('project_id',projectId).eq('user_id',memberId),db.from('project_members').delete().eq('project_id',projectId).eq('user_id',memberId),db.from('saved_projects').delete().eq('project_id',projectId).eq('user_id',memberId)]){const {error}=await query;if(error)throw error}}

test.beforeAll(async()=>{
 const db=localDb();const account=credentials();const {data:list,error:listError}=await db.auth.admin.listUsers({page:1,perPage:1000});if(listError)throw listError;const user=list.users.find(item=>item.email?.toLowerCase()===account.email.toLowerCase());if(!user)throw new Error('E2E member identity not found.');memberId=user.id;
 const {error:profileError}=await db.from('profiles').update({full_name:'E2E Member',headline:'Data analyst',professional_area:'Data Analysis / BI',location:'London, UK',experience_level:'mid',skills:['SQL','Data Analysis','Visualisation'],preferred_roles:['Data Analyst / BI'],project_availability:'available_now',weekly_capacity:'4–6 hours/week'}).eq('id',memberId);if(profileError)throw profileError;
 const [{data:domain,error:domainError},{data:roleFamily,error:roleFamilyError},{data:capabilities,error:capabilityError},{data:tool,error:toolError},{data:method,error:methodError}]=await Promise.all([db.from('domains').select('id').eq('slug','cross-industry-open-data').eq('is_active',true).single(),db.from('project_role_catalogue').select('id').eq('slug','data-analyst').eq('active',true).single(),db.from('capabilities').select('id,slug').in('slug',['data-analysis','data-quality','stakeholder-communication']).eq('is_active',true),db.from('tools').select('id').eq('slug','python').eq('is_active',true).single(),db.from('methods').select('id').eq('slug','data-quality').eq('is_active',true).single()]);
 if(domainError)throw domainError;if(roleFamilyError)throw roleFamilyError;if(capabilityError)throw capabilityError;if(toolError)throw toolError;if(methodError)throw methodError;if(!domain||!roleFamily||!tool||!method||(capabilities||[]).length!==3)throw new Error('E2E Member Discover requires the Phase 1 canonical catalogue taxonomy.');
 await db.from('profile_domain_preferences').delete().eq('user_id',memberId);await db.from('profile_tool_preferences').delete().eq('user_id',memberId);const domainPref=await db.from('profile_domain_preferences').insert({user_id:memberId,domain_id:domain.id});if(domainPref.error)throw domainPref.error;const toolPref=await db.from('profile_tool_preferences').insert({user_id:memberId,tool_id:tool.id});if(toolPref.error)throw toolPref.error;
 const {error:projectError}=await db.from('projects').upsert({id:projectId,slug:'e2e-member-discover-project',title,summary:'Use a deterministic member project to verify Discover, qualification and Submit Interest continuity.',problem_statement:'Validate that signed-in members can understand the same canonical project, qualification and team state before submitting interest.',status:'draft',visibility:'private',project_type:'open',applications_open:false,location:'Remote',location_type:'remote',catalogue_working_model_source:'explicit',duration_weeks:6,weekly_commitment:'5–8 hrs/week',application_deadline:null,participation_mode:'team',min_team_size:2,target_team_size:3,max_team_size:4,team_size_threshold:2},{onConflict:'id'});if(projectError)throw projectError;
 const {error:roleError}=await db.from('project_roles').upsert({id:roleId,project_id:projectId,title:'Data Analyst',description:'Analyse the project dataset and translate validated patterns into decision-ready findings.',skills:['Data Analysis','Visualisation'],openings:2},{onConflict:'id'});if(roleError)throw roleError;
 for(const operation of [db.from('project_role_families').upsert({project_id:projectId,role_catalogue_id:roleFamily.id,source:'e2e_member_discover'},{onConflict:'project_id,role_catalogue_id'}),db.from('project_capabilities').upsert((capabilities||[]).map(item=>({project_id:projectId,capability_id:item.id,importance:'core',evidence_expected:true})),{onConflict:'project_id,capability_id'}),db.from('project_domains').upsert({project_id:projectId,domain_id:domain.id,is_primary:true},{onConflict:'project_id,domain_id'}),db.from('project_tools').upsert({project_id:projectId,tool_id:tool.id},{onConflict:'project_id,tool_id'}),db.from('project_methods').upsert({project_id:projectId,method_id:method.id},{onConflict:'project_id,method_id'})]){const {error}=await operation;if(error)throw error}
 const {data:readiness,error:readinessError}=await db.from('project_catalogue_readiness').select('catalogue_ready,missing_requirements').eq('project_id',projectId).single();if(readinessError)throw readinessError;if(!readiness.catalogue_ready)throw new Error(`Member Discover fixture is catalogue-incomplete: ${(readiness.missing_requirements||[]).join(', ')}`);const {error:intakeError}=await db.from('projects').update({status:'recruiting',visibility:'public',applications_open:true}).eq('id',projectId);if(intakeError)throw intakeError;
});

test.beforeEach(async()=>{await resetMemberState()});

test('Discover and member project detail preserve responsive decision journey with one Submit Interest CTA',async({page})=>{
 test.setTimeout(300_000);await page.emulateMedia({reducedMotion:'reduce'});await mkdir(artifactDir,{recursive:true});await signIn(page);
 for(const width of widths){await page.setViewportSize({width,height:900});await page.goto('/member/discover',{waitUntil:'networkidle'});await expect(page.getByRole('heading',{level:1,name:'Discover projects'})).toBeVisible();const card=page.locator('.mdProjectCard').filter({hasText:title});await expect(card).toBeVisible();await expect(card.getByText('Data Analyst',{exact:true})).toBeVisible();await expect(card.getByRole('link',{name:'View project'})).toHaveAttribute('href',`/member/discover/${projectId}`);expect(await columns(page,'.mdProjectGrid'),`${width}px Discover grid`).toBe(width>980?2:1);await noOverflow(page,`${width}px Discover`);
  await page.goto(`/member/discover/${projectId}`,{waitUntil:'networkidle'});await expect(page.getByRole('heading',{level:1,name:title})).toBeVisible();await expect(page.getByText('MEMBER PROJECT DETAIL',{exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Understand how this project fits your direction'})).toBeVisible();await expect(page.getByRole('heading',{name:'Understand the current team situation'})).toBeVisible();await expect(page.getByText('Minimum to start',{exact:true}).first()).toBeVisible();await expect(page.getByText('Target team',{exact:true}).first()).toBeVisible();await expect(page.getByText('Maximum team',{exact:true}).first()).toBeVisible();await expect(page.getByRole('heading',{name:'Possible contribution areas'})).toBeVisible();await expect(page.getByRole('button',{name:/choose this role/i})).toHaveCount(0);const submit=page.getByRole('link',{name:'Submit Interest'}).first();await expect(submit).toHaveAttribute('href',`/member/discover/${projectId}/apply`);await noOverflow(page,`${width}px detail`);await page.screenshot({path:`${artifactDir}/${width}-detail.png`,fullPage:true,animations:'disabled'});}
});

test('Discover Filters V2 remains governed and keyboard accessible',async({page})=>{test.setTimeout(120_000);await signIn(page);await page.setViewportSize({width:390,height:844});await page.goto('/member/discover',{waitUntil:'networkidle'});const trigger=page.getByRole('button',{name:'Filters · 0'});await trigger.click();const dialog=page.getByRole('dialog',{name:'Filter projects'});await expect(dialog.getByLabel('Career / Role')).toContainText('Data Analyst');await expect(dialog.getByLabel('Industry')).toContainText('Cross-industry');await expect(dialog.getByLabel('Tools & technologies')).toContainText('Python');const capability=dialog.getByRole('combobox',{name:'Skills you want to build'});await capability.fill('data qual');await expect(dialog.getByRole('option',{name:'Data Quality'})).toBeVisible();await capability.press('Enter');await expect(capability).toHaveValue('Data Quality');await dialog.getByRole('button',{name:/Show \d+ projects?/}).click();await expect(page.getByRole('button',{name:'Filters · 1'})).toBeVisible();await page.evaluate(()=>{document.documentElement.style.fontSize='200%'});await noOverflow(page,'390px Discover Filters V2 at 200% text zoom')});

test('Discover pagination remains 9 per page and refinements reset page 1',async({page})=>{test.setTimeout(120_000);await signIn(page);await page.setViewportSize({width:1024,height:900});await page.goto('/member/discover',{waitUntil:'networkidle'});await page.evaluate(()=>{const grid=document.querySelector<HTMLElement>('.mdProjectGrid');const template=grid?.querySelector<HTMLElement>('.mdProjectCard');if(!grid||!template)throw new Error('Discover project grid missing');const required=Math.max(0,12-grid.querySelectorAll('.mdProjectCard').length);for(let index=0;index<required;index++){const clone=template.cloneNode(true) as HTMLElement;const heading=clone.querySelector('h2');if(heading)heading.textContent=`Synthetic pagination project ${index+1}`;grid.appendChild(clone)}});const pagination=page.getByRole('navigation',{name:'Discover project pages'});await expect(pagination).toContainText('Showing 1–9 of 12');await pagination.getByRole('button',{name:'Next page'}).click();await expect(pagination).toContainText('Page 2 of 2');await page.getByPlaceholder('Search projects, roles, skills, tools or industries').fill(title);await expect(page.locator('.mdProjectCard').filter({hasText:title})).toBeVisible()});

test('public Submit Interest survives authentication and enters Phase 5 same-project qualification',async({page})=>{test.setTimeout(120_000);await page.goto(`/projects/${projectId}`,{waitUntil:'networkidle'});const signInLink=page.getByRole('link',{name:'Submit interest'}).first();await signInLink.click();await page.waitForURL(url=>url.pathname==='/signin'&&url.searchParams.get('next')===`/member/discover/${projectId}`,{timeout:20_000});const account=credentials();const main=page.locator('#main-content');await main.locator('input[type="email"]').fill(account.email);await main.locator('input[type="password"]').fill(account.password);await main.getByRole('button',{name:'Sign in →'}).click();await page.waitForURL(url=>url.pathname===`/member/discover/${projectId}`,{timeout:20_000});await expect(page.getByRole('link',{name:'Submit Interest'}).first()).toBeVisible()});

test('Submit Interest enters Phase 6 without a formal role and retains form responses',async({page})=>{test.setTimeout(180_000);await signIn(page);await page.setViewportSize({width:390,height:844});await page.goto(`/member/discover/${projectId}`,{waitUntil:'networkidle'});const save=page.getByRole('button',{name:/Save project|Saved/});await save.click();await page.goto(`/member/discover/${projectId}`,{waitUntil:'networkidle'});await page.getByRole('link',{name:'Submit Interest'}).first().click();await page.waitForURL(url=>url.pathname===`/member/discover/${projectId}/apply`&&!url.searchParams.has('role'),{timeout:20_000});await expect(page.getByRole('heading',{level:1,name:`Submit Interest — ${title}`})).toBeVisible();for(const label of ['Availability','How you could contribute','Review'])await expect(page.getByText(label,{exact:true}).first()).toBeVisible();await expect(page.locator('input[type="radio"]')).toHaveCount(0);const availability=page.getByPlaceholder('Share anything the project team should know about your timing or availability.');await availability.fill('Available evenings and Saturday mornings.');await page.getByRole('button',{name:'Continue →'}).click();const response=page.getByPlaceholder('Describe the work, capability or perspective you could contribute.');await response.fill('I can own analysis tasks, validate patterns, document assumptions and communicate decision-ready findings.');await page.getByRole('button',{name:'Continue →'}).click();await expect(page.getByText('Available evenings and Saturday mornings.')).toBeVisible();await expect(page.getByText(/I can own analysis tasks/)).toBeVisible();await page.getByRole('button',{name:'← Back'}).click();await expect(response).toHaveValue(/I can own analysis tasks/);await page.evaluate(()=>{document.documentElement.style.fontSize='200%'});await noOverflow(page,'390px interest at 200% text zoom')});

test('profile readiness repair preserves exact project and recalculates qualification',async({page})=>{test.setTimeout(180_000);const db=localDb();const {error}=await db.from('profiles').update({weekly_capacity:null}).eq('id',memberId);if(error)throw error;await signIn(page);await page.setViewportSize({width:390,height:844});await page.goto(`/member/discover/${projectId}`,{waitUntil:'networkidle'});const submit=page.getByRole('link',{name:'Submit Interest'}).first();await expect(submit).toHaveAttribute('href',`/member/profile?next=${encodeURIComponent(`/member/discover/${projectId}`)}`);await submit.click();await page.waitForURL(url=>url.pathname==='/member/profile'&&url.searchParams.get('next')===`/member/discover/${projectId}`,{timeout:20_000});const edit=page.getByRole('button',{name:'Edit profile →'});if(await edit.count())await edit.click();const capacity=page.locator('#profile-capacity');await capacity.selectOption('4–6 hours/week');const saveResponse=page.waitForResponse(response=>response.url().endsWith('/api/profile')&&response.request().method()==='PATCH');await page.getByRole('button',{name:'Save profile →'}).click();expect((await saveResponse).status()).toBe(200);await page.goto(`/member/discover/${projectId}`,{waitUntil:'networkidle'});await expect(page.getByRole('link',{name:'Submit Interest'}).first()).toHaveAttribute('href',`/member/discover/${projectId}/apply`);await noOverflow(page,'390px profile-save-unlock')});
