import {expect,test,type Locator,type Page} from '@playwright/test';
import {mkdir} from 'node:fs/promises';

type Credentials={email:string;password:string};
const labProjectId='00000000-0000-4000-8000-00000000e2e1';
const labTeam1RunId='00000000-0000-4000-8000-00000000e211';
const screens=[['home','#mettelo-lab'],['plan','#problem'],['tasks','#delivery'],['chat','#discussion'],['data','#data-sources'],['proof','#proof'],['resources','#resources'],['events','#meetings'],['team','#team']] as const;
const viewports=[{name:'phone-320',width:320,height:740},{name:'phone-360',width:360,height:800},{name:'phone-375',width:375,height:812},{name:'phone-390',width:390,height:844},{name:'phone-412',width:412,height:915},{name:'phone-414',width:414,height:896},{name:'phone-430',width:430,height:932},{name:'tablet-768',width:768,height:1024},{name:'tablet-1024',width:1024,height:900},{name:'desktop-1440',width:1440,height:900}] as const;
const urlFor=(view:string)=>`/member/projects/${labProjectId}?run=${labTeam1RunId}&view=${view}`;
function credentials():Credentials{const email=process.env.E2E_MEMBER_EMAIL?.trim();const password=process.env.E2E_MEMBER_PASSWORD;if(!email||!password)throw new Error('Missing E2E member credentials.');return{email,password}}
async function signIn(page:Page,next:string){const account=credentials();await page.goto(`/signin?next=${encodeURIComponent(next)}`,{waitUntil:'networkidle'});const main=page.locator('#main-content');await main.locator('input[type="email"]').fill(account.email);await main.locator('input[type="password"]').fill(account.password);await main.getByRole('button',{name:'Sign in →'}).click();await page.waitForURL(url=>!url.pathname.startsWith('/signin'),{timeout:20_000})}
async function seedChat(page:Page){const messages=[
 'Quick project update: the source review is complete and the team can move into the comparison work.',
 'Decision: use the governed dataset as the single comparison source, document the assumptions clearly, and link the final analysis back to the delivery record.',
 'Blocker: this long reference must wrap safely without widening the conversation https://example.com/e2e/project/research/source-with-a-deliberately-long-path-for-chat-layout-validation'
];for(const [index,body] of messages.entries()){const response=await page.request.post('/api/project-collaboration',{data:{action:'discussion',project_id:labProjectId,project_run_id:labTeam1RunId,body,mentioned_user_ids:[],message_type:index===1?'decision':index===2?'blocker':'update'}});expect(response.ok(),`Chat fixture ${index+1} should be created through the collaboration API`).toBeTruthy()}}
async function assertNoHorizontalOverflow(page:Page,label:string){const dimensions=await page.evaluate(()=>({documentScrollWidth:document.documentElement.scrollWidth,documentClientWidth:document.documentElement.clientWidth,bodyScrollWidth:document.body.scrollWidth}));expect(dimensions.documentScrollWidth,`${label}: document overflow`).toBeLessThanOrEqual(dimensions.documentClientWidth);expect(dimensions.bodyScrollWidth,`${label}: body overflow`).toBeLessThanOrEqual(dimensions.documentClientWidth)}
async function labelsDoNotOverlap(labels:Locator,label:string){const boxes=await labels.evaluateAll(elements=>elements.map(element=>{const box=element.getBoundingClientRect();return{left:box.left,right:box.right}}));for(let index=1;index<boxes.length;index++)expect(boxes[index-1].right,`${label}: Lab nav labels overlap`).toBeLessThanOrEqual(boxes[index].left+1)}
async function assertShell(page:Page,width:number,label:string){const labRail=page.locator('aside[aria-label="Mettelo Lab workspace"]'),rightRail=page.locator('aside[aria-label="Mettelo Lab project context"]'),mobileNav=page.getByRole('navigation',{name:'Mettelo Lab mobile navigation'}),outerMemberNav=page.getByRole('navigation',{name:'My Mettelo mobile navigation'}),labContextHeader=page.locator('header:has(+ main#mettelo-lab-content)');await expect(outerMemberNav).toBeHidden();if(width<=480){await expect(labRail).toBeHidden();await expect(labContextHeader,`${label}: redundant mobile Lab context header stays hidden`).toBeHidden();await expect(mobileNav).toBeVisible();await labelsDoNotOverlap(mobileNav.locator('a small, button small'),label);for(const control of await mobileNav.locator(':scope > a, :scope > div > button').all()){const box=await control.boundingBox();expect(box?.height||0,`${label}: mobile Lab navigation target`).toBeGreaterThanOrEqual(44)}}else if(width<=1024){await expect(labRail).toBeVisible();await expect(labContextHeader).toBeVisible();await expect(page.getByText('METTELO LAB',{exact:true}).first()).toBeVisible();await expect(mobileNav).toBeHidden()}else{await expect(labRail).toBeVisible();await expect(labRail.getByRole('heading',{name:'Mettelo Lab'})).toBeVisible();await expect(mobileNav).toBeHidden()}if(width>=1181)await expect(rightRail).toBeVisible();else await expect(rightRail).toBeHidden()}
async function assertLegacyProjectChromeHidden(page:Page){const legacySection=page.locator('[data-lab-surface] > section.softSection').first();if(!(await legacySection.count()))return;if(await legacySection.isVisible()){await expect(legacySection.locator(':scope > .shell > .workspaceNav')).toBeHidden();await expect(legacySection.locator(':scope > .shell > .sectionHead')).toBeHidden();const statBand=legacySection.locator(':scope > .shell > .statBand');if(await statBand.count())await expect(statBand).toBeHidden()}else{expect(await legacySection.boundingBox(),'hidden legacy project wrapper must not consume Lab layout space').toBeNull()}}
async function activateLabNavLink(link:Locator){await expect(link).toBeVisible();await expect(link).toBeEnabled();const box=await link.boundingBox();expect(box?.height||0,'mobile Lab navigation target remains pointer-sized').toBeGreaterThanOrEqual(44);await link.evaluate((element:HTMLAnchorElement)=>element.click())}

async function assertChatPresentation(page:Page,width:number,label:string){const bubbles=page.locator('#discussion .messageBubble');expect(await bubbles.count(),`${label}: seeded Chat messages render`).toBeGreaterThanOrEqual(3);const bubble=bubbles.first();const feed=page.locator('#discussion .messageFeed');const[bubbleBox,feedBox]=await Promise.all([bubble.boundingBox(),feed.boundingBox()]);expect(bubbleBox,`${label}: message bubble exists`).not.toBeNull();expect(feedBox,`${label}: message feed exists`).not.toBeNull();if(bubbleBox&&feedBox){expect(bubbleBox.width,`${label}: bubble remains inside the feed`).toBeLessThanOrEqual(feedBox.width+1);if(width>=681)expect(bubbleBox.width,`${label}: desktop messages stay compact`).toBeLessThanOrEqual(680)}const body=bubble.locator(':scope > p').first();await expect(body,`${label}: message body is visible`).toBeVisible();const metrics=await body.evaluate(element=>{const style=getComputedStyle(element);return{fontSize:Number.parseFloat(style.fontSize),writingMode:style.writingMode}});expect(metrics.fontSize,`${label}: message body remains readable`).toBeGreaterThanOrEqual(14);expect(metrics.writingMode,`${label}: message body remains horizontal`).toBe('horizontal-tb');const menu=bubble.locator('.messageActions');if(await menu.count())await expect(menu,`${label}: closed message actions do not become an oversized surface`).toBeHidden();const trigger=bubble.locator('.messageMenuTrigger');if(await trigger.count()){const box=await trigger.boundingBox();expect(box?.width||0,`${label}: message action trigger remains compact`).toBeLessThanOrEqual(44);expect(box?.height||0,`${label}: message action trigger remains compact`).toBeLessThanOrEqual(44)}const longMessage=bubbles.filter({hasText:'deliberately-long-path-for-chat-layout-validation'}).first();await expect(longMessage,`${label}: long content fixture remains rendered`).toBeVisible()}

test('Mettelo Lab matches the approved responsive composition screen by screen',async({page})=>{
 test.setTimeout(420_000);await page.emulateMedia({reducedMotion:'reduce'});await signIn(page,urlFor('home'));await seedChat(page);await mkdir('artifacts/mettelo-lab-visual',{recursive:true});
 for(const viewport of viewports){
  await page.setViewportSize({width:viewport.width,height:viewport.height});
  for(const [screen,selector] of screens){
   await page.goto(urlFor(screen),{waitUntil:'networkidle'});await expect(page.locator('[data-lab-view]')).toHaveAttribute('data-lab-view',screen);await assertShell(page,viewport.width,`${viewport.name}/${screen}`);await assertNoHorizontalOverflow(page,`${viewport.name}/${screen}`);
   const target=page.locator(selector).first();await expect(target,`${viewport.name}/${screen}: destination visible`).toBeVisible();await assertLegacyProjectChromeHidden(page);
   if(screen!=='home'&&screen!=='team')await expect(page.locator('#mettelo-lab')).toBeHidden();
   if(screen==='home')await expect(page.locator('[data-lab-team-section]')).toBeHidden();
   if(screen==='team')await expect(page.locator('[data-lab-home-section]').first()).toBeHidden();
   if(viewport.width<=480&&screen!=='chat')await expect(page.locator('.messageComposer')).toHaveCount(0);
   if(screen==='chat')await assertChatPresentation(page,viewport.width,`${viewport.name}/chat`);
   if(screen==='chat'&&viewport.width<=480){const composer=page.locator('#discussion .messageComposer');await expect(composer).toBeVisible();await expect(composer).toBeInViewport();const mobileNav=page.getByRole('navigation',{name:'Mettelo Lab mobile navigation'});const[composerBox,navBox]=await Promise.all([composer.boundingBox(),mobileNav.boundingBox()]);expect(composerBox).not.toBeNull();expect(navBox).not.toBeNull();if(composerBox&&navBox)expect(composerBox.y+composerBox.height,`${viewport.name}: Chat composer must sit above nav`).toBeLessThanOrEqual(navBox.y+2);const fontSize=await composer.locator('textarea').evaluate(element=>Number.parseFloat(getComputedStyle(element).fontSize));expect(fontSize,`${viewport.name}: composer input avoids iOS focus zoom`).toBeGreaterThanOrEqual(16);const author=page.locator('#discussion .messageBubble header strong').first();const box=await author.boundingBox();expect(box?.width||0,`${viewport.name}: message author must not collapse into a one-character column`).toBeGreaterThan(80)}
   await page.screenshot({path:`artifacts/mettelo-lab-visual/${viewport.name}-${screen}.png`,fullPage:false,animations:'disabled'});
  }
  if(viewport.width<=480){await page.goto(urlFor('home'),{waitUntil:'networkidle'});const nav=page.getByRole('navigation',{name:'Mettelo Lab mobile navigation'});const more=nav.getByRole('button',{name:/^More(?:,|$)/});await more.click();const panel=page.getByRole('region',{name:'More Mettelo Lab destinations'});await expect(panel).toBeVisible();await assertLegacyProjectChromeHidden(page);await expect(page.locator('.messageComposer')).toHaveCount(0);await assertNoHorizontalOverflow(page,`${viewport.name}/more`);const[navBox,panelBox]=await Promise.all([nav.boundingBox(),panel.boundingBox()]);expect(navBox).not.toBeNull();expect(panelBox).not.toBeNull();if(navBox&&panelBox)expect(panelBox.y+panelBox.height,`${viewport.name}: More drop-up stays above nav`).toBeLessThanOrEqual(navBox.y+2);await page.screenshot({path:`artifacts/mettelo-lab-visual/${viewport.name}-more.png`,fullPage:false,animations:'disabled'});await page.keyboard.press('Escape');await expect(page.locator('#lab-more-dropup')).toHaveCount(0)}
 }
 await page.setViewportSize({width:390,height:844});await page.goto(urlFor('home'),{waitUntil:'networkidle'});await page.evaluate(()=>{document.documentElement.style.fontSize='200%'});const mobileNav=page.getByRole('navigation',{name:'Mettelo Lab mobile navigation'});await labelsDoNotOverlap(mobileNav.locator('a small, button small'),'phone-390/text-zoom-200');await assertNoHorizontalOverflow(page,'phone-390/text-zoom-200');
});

test('Mettelo Lab mobile navigation transitions as one continuous workspace',async({page})=>{
 test.setTimeout(120_000);await page.emulateMedia({reducedMotion:'reduce'});await page.setViewportSize({width:390,height:844});await signIn(page,urlFor('home'));const nav=page.getByRole('navigation',{name:'Mettelo Lab mobile navigation'});const initialNavBox=await nav.boundingBox();expect(initialNavBox).not.toBeNull();
 const journey:[string,string][]=[['Tasks','tasks'],['Chat','chat'],['Data','data'],['Home','home']];
 for(const [label,view] of journey){const link=nav.getByRole('link',{name:label,exact:true});await expect(link).toHaveAttribute('href',urlFor(view));const started=Date.now();await activateLabNavLink(link);await expect(page.locator('[data-lab-view]')).toHaveAttribute('data-lab-view',view);expect(Date.now()-started,`transition/${view}: local view switch`).toBeLessThan(750);await expect(nav.getByRole('link',{name:label,exact:true})).toHaveAttribute('aria-current','page');if(view==='chat')await expect(page.locator('#discussion .messageComposer')).toBeVisible();await assertNoHorizontalOverflow(page,`transition/${view}`);const box=await nav.boundingBox();expect(box).not.toBeNull();if(initialNavBox&&box){expect(Math.abs(box.y-initialNavBox.y),`transition/${view}: bottom nav must not jump`).toBeLessThanOrEqual(2);expect(Math.abs(box.height-initialNavBox.height),`transition/${view}: bottom nav height must remain stable`).toBeLessThanOrEqual(2)}}
 const more=nav.getByRole('button',{name:/^More(?:,|$)/});await more.click();const panel=page.getByRole('region',{name:'More Mettelo Lab destinations'});await expect(panel).toBeVisible();const started=Date.now();await panel.getByRole('link',{name:/^Events/}).click();await expect(page.locator('[data-lab-view]')).toHaveAttribute('data-lab-view','events');expect(Date.now()-started,'transition/more-events: local view switch').toBeLessThan(750);await expect(more).toHaveAttribute('aria-label','More, Events selected');await expect(more).toHaveAttribute('data-active','true');await expect(page.locator('#lab-more-dropup')).toHaveCount(0);const finalNavBox=await nav.boundingBox();if(initialNavBox&&finalNavBox){expect(Math.abs(finalNavBox.y-initialNavBox.y),'transition/more: bottom nav must not jump').toBeLessThanOrEqual(2);expect(Math.abs(finalNavBox.height-initialNavBox.height),'transition/more: bottom nav height must remain stable').toBeLessThanOrEqual(2)}
});
