import {createClient} from '@supabase/supabase-js';
import {expect,test,type APIRequestContext} from '@playwright/test';
import {PROJECT_PARTICIPATION_TERMS_VERSION} from '../lib/project-participation-terms';

const startProject='00000000-0000-4000-8000-00000000c601';
const recoveryProject='00000000-0000-4000-8000-00000000c602';
const reviewProject='00000000-0000-4000-8000-00000000c603';
const partnerProject='00000000-0000-4000-8000-00000000c604';
const blockedProject='00000000-0000-4000-8000-00000000c605';
const pausedProject='00000000-0000-4000-8000-00000000c606';
const futureProject='00000000-0000-4000-8000-00000000c607';
const readinessCapability='00000000-0000-4000-8000-00000000c6c1';

function required(name:string){const value=process.env[name]?.trim();if(!value)throw new Error(`${name} is required`);return value}
function db(){const url=required('E2E_SUPABASE_URL');if(!['127.0.0.1','localhost'].includes(new URL(url).hostname))throw new Error('Formation cron E2E refuses non-local Supabase hosts.');return createClient(url,required('E2E_SUPABASE_SERVICE_ROLE_KEY'),{auth:{persistSession:false,autoRefreshToken:false}})}
async function identities(){const client=db();const {data,error}=await client.auth.admin.listUsers({page:1,perPage:1000});if(error)throw error;const member=data.users.find(user=>user.email===required('E2E_MEMBER_EMAIL'));const architect=data.users.find(user=>user.email===required('E2E_ARCHITECT_EMAIL'));if(!member||!architect)throw new Error('Formation cron E2E requires disposable member and architect identities.');return{member,architect}}
async function cron(request:APIRequestContext){return request.get('/api/cron/project-formation',{headers:{authorization:`Bearer ${required('CRON_SECRET')}`}})}
async function cleanup(client:ReturnType<typeof db>,projectId:string){const {data:runs}=await client.from('project_runs').select('id').eq('project_id',projectId);const runIds=(runs||[]).map(run=>run.id);if(runIds.length){await client.from('project_activity_log').delete().in('project_run_id',runIds);await client.from('project_members').delete().in('project_run_id',runIds)}await client.from('project_activity_log').delete().eq('project_id',projectId);await client.from('project_applications').delete().eq('project_id',projectId);await client.from('project_milestones').delete().eq('project_id',projectId);await client.from('project_success_criteria').delete().eq('project_id',projectId);await client.from('project_deliverables').delete().eq('project_id',projectId);await client.from('project_problem_briefs').delete().eq('project_id',projectId);await client.from('project_capabilities').delete().eq('project_id',projectId);await client.from('project_runs').delete().eq('project_id',projectId);await client.from('project_roles').delete().eq('project_id',projectId);await client.from('projects').delete().eq('id',projectId)}
async function seedProject(client:ReturnType<typeof db>,projectId:string,{admission='auto',type='open',participation='solo',min=1,target=1,max=2}:{admission?:'auto'|'review_required';type?:'open'|'partner';participation?:'solo'|'team'|'flexible';min?:number;target?:number;max?:number}={}){await cleanup(client,projectId);const project=await client.from('projects').insert({id:projectId,slug:`cron-e2e-${projectId.slice(-4)}`,title:`Formation cron ${projectId.slice(-4)}`,summary:'Disposable formation cron acceptance fixture.',problem_statement:'Prove daily formation processing obeys lower-bound, policy, readiness and idempotency rules.',status:'open',visibility:'public',project_type:type,partner_name:type==='partner'?'E2E Partner':null,applications_open:true,team_size_threshold:min,min_team_size:min,target_team_size:target,max_team_size:max,participation_mode:participation,admission_mode:admission,auto_start_delay_minutes:360,late_joining_enabled:true});if(project.error)throw project.error}
async function seedInterest(client:ReturnType<typeof db>,projectId:string,userId:string,preference:'solo'|'team'|'flexible'){const now=new Date().toISOString();const {data,error}=await client.from('project_applications').insert({project_id:projectId,user_id:userId,status:'submitted',application_kind:'interest',participation_preference:preference,contribution_statement:'Formation cron acceptance interest with enough detail for canonical admission.',terms_accepted_at:now,terms_version:PROJECT_PARTICIPATION_TERMS_VERSION,submitted_at:now}).select('id,status,project_run_id,admission_decision').single();if(error||!data)throw error||new Error('Could not seed formation cron interest.');return data}
async function seedReadiness(client:ReturnType<typeof db>,projectId:string,actorUserId:string){const capability=await client.from('capabilities').upsert({id:readinessCapability,slug:'formation-cron-readiness',name:'Formation cron readiness',capability_type:'professional',description:'Disposable capability for formation cron start acceptance.',is_active:true},{onConflict:'id'});if(capability.error)throw capability.error;const link=await client.from('project_capabilities').upsert({project_id:projectId,capability_id:readinessCapability,importance:'core',evidence_expected:true},{onConflict:'project_id,capability_id'});if(link.error)throw link.error;const brief=await client.from('project_problem_briefs').insert({project_id:projectId,context:'Disposable formation cron readiness context.',stakeholder:'Release acceptance',expected_outcome:'A safely startable AUTO run.',primary_use_case:'Validate daily project formation.',primary_objective:'Prove canonical readiness before scheduled activation.',key_questions:['Is the run ready to start?'],in_scope:['AUTO formation and readiness'],out_of_scope:['Alternative lifecycle services']});if(brief.error)throw brief.error;const deliverable=await client.from('project_deliverables').insert({project_id:projectId,project_run_id:null,canonical_item_key:'formation-cron-readiness-deliverable',title:'Formation cron readiness deliverable',deliverable_type:'document',acceptance_criteria:'Accepted when the scheduled run starts exactly once.',is_required:true,created_by:actorUserId});if(deliverable.error)throw deliverable.error;const criterion=await client.from('project_success_criteria').insert({project_id:projectId,title:'Formation cron starts only after readiness',is_required:true});if(criterion.error)throw criterion.error;const milestone=await client.from('project_milestones').insert({project_id:projectId,project_run_id:null,title:'Formation cron kickoff',status:'planned'});if(milestone.error)throw milestone.error}
async function forceDue(client:ReturnType<typeof db>,runId:string){const due=new Date(Date.now()-60_000).toISOString();const ready=new Date(Date.now()-7*60*60_000).toISOString();const result=await client.from('project_runs').update({start_ready_at:ready,start_scheduled_at:ready,scheduled_start_at:due}).eq('id',runId).eq('has_started',false);if(result.error)throw result.error}
async function seedPolicyRun(client:ReturnType<typeof db>,projectId:string){const due=new Date(Date.now()-60_000).toISOString();const ready=new Date(Date.now()-7*60*60_000).toISOString();const {data,error}=await client.from('project_runs').insert({project_id:projectId,run_number:1,status:'forming',team_size_threshold:1,required_team_size:1,has_started:false,recruitment_open:true,start_ready_at:ready,start_scheduled_at:ready,scheduled_start_at:due}).select('id').single();if(error||!data)throw error||new Error('Could not seed policy run.');return data.id}

// The route mutates deterministic lifecycle fixtures, so keep the evidence serial.
test.describe.configure({mode:'serial'});
test.describe('daily project formation cron acceptance',()=>{
 test('requires the server-side cron secret and ignores a future eligibility timestamp',async({request})=>{const client=db();const {member}=await identities();await seedProject(client,futureProject,{admission:'auto',participation:'solo',min:1,target:1,max:2});try{const unauthorized=await request.get('/api/cron/project-formation');expect(unauthorized.status()).toBe(401);const app=await seedInterest(client,futureProject,member.id,'solo');expect(app.admission_decision).toBe('auto_qualified');const {data:before}=await client.from('project_runs').select('id,status,has_started,scheduled_start_at').eq('id',app.project_run_id).single();expect(before?.scheduled_start_at).toBeTruthy();expect(Date.parse(before!.scheduled_start_at!)).toBeGreaterThan(Date.now());const response=await cron(request);expect(response.status()).toBe(200);const body=await response.json();expect(body.scheduled.started).toBe(0);const {data:after}=await client.from('project_runs').select('status,has_started,scheduled_start_at').eq('id',app.project_run_id).single();expect(after).toMatchObject({status:'forming',has_started:false,scheduled_start_at:before?.scheduled_start_at})}finally{await cleanup(client,futureProject)}});

 test('due ready AUTO Solo starts once and repeated daily processing cannot duplicate activation or kickoff',async({request})=>{const client=db();const {member}=await identities();await seedProject(client,startProject,{admission:'auto',participation:'solo',min:1,target:1,max:2});try{const app=await seedInterest(client,startProject,member.id,'solo');expect(app.admission_decision).toBe('auto_qualified');await seedReadiness(client,startProject,member.id);await forceDue(client,app.project_run_id!);const first=await cron(request);expect(first.status()).toBe(200);const firstBody=await first.json();expect(firstBody.scheduled.started).toBe(1);const [{data:run},{data:membership},{count:startEvents}]=await Promise.all([client.from('project_runs').select('status,has_started,started_at,kickoff_at,scheduled_start_at').eq('id',app.project_run_id).single(),client.from('project_members').select('membership_status,activated_at').eq('project_run_id',app.project_run_id).eq('user_id',member.id).single(),client.from('project_activity_log').select('id',{count:'exact',head:true}).eq('project_run_id',app.project_run_id).in('event_type',['project_auto_started','project_auto_start_retry_started','project_manual_started'])]);expect(run?.status).toBe('active');expect(run?.has_started).toBe(true);expect(run?.started_at).toBeTruthy();expect(run?.kickoff_at).toBeTruthy();expect(run?.scheduled_start_at).toBeNull();expect(membership?.membership_status).toBe('active');expect(membership?.activated_at).toBeTruthy();expect(startEvents).toBe(1);const second=await cron(request);expect(second.status()).toBe(200);expect((await second.json()).scheduled.started).toBe(0);const {count:startEventsAfter}=await client.from('project_activity_log').select('id',{count:'exact',head:true}).eq('project_run_id',app.project_run_id).in('event_type',['project_auto_started','project_auto_start_retry_started','project_manual_started']);expect(startEventsAfter).toBe(1)}finally{await cleanup(client,startProject)}});

 test('falling below minimum invalidates old eligibility, preserves forming history, and recovering threshold creates a fresh six-hour window',async({request})=>{const client=db();const {member,architect}=await identities();await seedProject(client,recoveryProject,{admission:'auto',participation:'team',min:2,target:3,max:4});try{const first=await seedInterest(client,recoveryProject,member.id,'team');expect(first.admission_decision).toBe('auto_qualified');const runId=first.project_run_id!;const oldEligibility=new Date(Date.now()-60_000).toISOString();const armed=await client.from('project_runs').update({start_ready_at:oldEligibility,start_scheduled_at:oldEligibility,scheduled_start_at:oldEligibility}).eq('id',runId);if(armed.error)throw armed.error;const processed=await cron(request);expect(processed.status()).toBe(200);const processedBody=await processed.json();expect(processedBody.scheduled.deferred).toBeGreaterThanOrEqual(1);const [{data:runAfterDrop},{data:cancelEvent}]=await Promise.all([client.from('project_runs').select('status,has_started,start_ready_at,start_scheduled_at,scheduled_start_at').eq('id',runId).single(),client.from('project_activity_log').select('event_type,metadata').eq('project_run_id',runId).eq('event_type','project_start_schedule_cancelled').order('created_at',{ascending:false}).limit(1).single()]);expect(runAfterDrop).toMatchObject({status:'forming',has_started:false,start_ready_at:null,start_scheduled_at:null,scheduled_start_at:null});expect(cancelEvent?.metadata).toMatchObject({reason:'below_minimum_at_start_time',filled:1,required_team_size:2});const recoveredAt=Date.now();const second=await seedInterest(client,recoveryProject,architect.id,'team');expect(second.admission_decision).toBe('auto_qualified');expect(second.project_run_id).toBe(runId);const {data:fresh}=await client.from('project_runs').select('status,has_started,required_team_size,start_ready_at,start_scheduled_at,scheduled_start_at').eq('id',runId).single();expect(fresh).toMatchObject({status:'forming',has_started:false,required_team_size:2});expect(fresh?.start_ready_at).toBeTruthy();expect(fresh?.start_scheduled_at).toBeTruthy();expect(fresh?.scheduled_start_at).toBeTruthy();expect(Date.parse(fresh!.scheduled_start_at!)-recoveredAt).toBeGreaterThanOrEqual(359*60_000);expect(Date.parse(fresh!.scheduled_start_at!)-recoveredAt).toBeLessThanOrEqual(361*60_000);expect(fresh?.scheduled_start_at).not.toBe(oldEligibility);const immediate=await cron(request);expect(immediate.status()).toBe(200);expect((await immediate.json()).scheduled.started).toBe(0);const {data:stillForming}=await client.from('project_runs').select('status,has_started').eq('id',runId).single();expect(stillForming).toMatchObject({status:'forming',has_started:false})}finally{await cleanup(client,recoveryProject)}});

 test('Review Required and Partner runs are excluded from AUTO processing and their stale schedules are cleared',async({request})=>{const client=db();await seedProject(client,reviewProject,{admission:'review_required',type:'open',participation:'solo'});await seedProject(client,partnerProject,{admission:'review_required',type:'partner',participation:'solo'});try{const reviewRun=await seedPolicyRun(client,reviewProject);const partnerRun=await seedPolicyRun(client,partnerProject);const response=await cron(request);expect(response.status()).toBe(200);const body=await response.json();expect(body.scheduled.policySkipped).toBeGreaterThanOrEqual(2);for(const [projectId,runId] of [[reviewProject,reviewRun],[partnerProject,partnerRun]] as const){const [{data:run},{data:event}]=await Promise.all([client.from('project_runs').select('status,has_started,start_ready_at,start_scheduled_at,scheduled_start_at,auto_start_failure').eq('id',runId).single(),client.from('project_activity_log').select('event_type,metadata').eq('project_id',projectId).eq('project_run_id',runId).eq('event_type','project_auto_start_policy_blocked').single()]);expect(run).toMatchObject({status:'forming',has_started:false,start_ready_at:null,start_scheduled_at:null,scheduled_start_at:null,auto_start_failure:'admission_mode'});expect(event?.metadata).toMatchObject({reason:'effective_admission_mode_not_auto'})}}finally{await cleanup(client,reviewProject);await cleanup(client,partnerProject)}});

 test('explicit AUTO block and automation pause both prevent a due run from starting',async({request})=>{const client=db();const {member,architect}=await identities();await seedProject(client,blockedProject,{admission:'auto',participation:'solo'});await seedProject(client,pausedProject,{admission:'auto',participation:'solo'});try{const blockedApp=await seedInterest(client,blockedProject,member.id,'solo');const pausedApp=await seedInterest(client,pausedProject,architect.id,'solo');await forceDue(client,blockedApp.project_run_id!);await forceDue(client,pausedApp.project_run_id!);const blockedAt=new Date().toISOString();const block=await client.from('project_runs').update({auto_start_blocked_at:blockedAt,auto_start_block_reason:'Release acceptance governance block'}).eq('id',blockedApp.project_run_id);if(block.error)throw block.error;const pause=await client.from('projects').update({auto_start_paused_at:new Date().toISOString()}).eq('id',pausedProject);if(pause.error)throw pause.error;const response=await cron(request);expect(response.status()).toBe(200);const body=await response.json();expect(body.scheduled.blocked).toBeGreaterThanOrEqual(1);expect(body.scheduled.paused).toBeGreaterThanOrEqual(1);const [{data:blockedRun},{data:pausedRun}]=await Promise.all([client.from('project_runs').select('status,has_started,scheduled_start_at,auto_start_blocked_at').eq('id',blockedApp.project_run_id).single(),client.from('project_runs').select('status,has_started,scheduled_start_at').eq('id',pausedApp.project_run_id).single()]);expect(blockedRun?.status).toBe('forming');expect(blockedRun?.has_started).toBe(false);expect(blockedRun?.scheduled_start_at).toBeTruthy();expect(blockedRun?.auto_start_blocked_at).toBeTruthy();expect(pausedRun?.status).toBe('forming');expect(pausedRun?.has_started).toBe(false);expect(pausedRun?.scheduled_start_at).toBeTruthy()}finally{await cleanup(client,blockedProject);await cleanup(client,pausedProject)}});
});
