import {createClient} from '@supabase/supabase-js';
import {expect,test} from '@playwright/test';

const projectId='00000000-0000-4000-8000-00000000b704';
const deliverableId='00000000-0000-4000-8000-00000000b705';
const criterionId='00000000-0000-4000-8000-00000000b706';
const milestoneId='00000000-0000-4000-8000-00000000b707';

function required(name:string){const value=process.env[name]?.trim();if(!value)throw new Error(`${name} is required`);return value}
function localUrl(){const url=required('E2E_SUPABASE_URL');if(!['127.0.0.1','localhost'].includes(new URL(url).hostname))throw new Error('Phase 7 run privacy tests refuse non-local Supabase hosts.');return url}
function service(){return createClient(localUrl(),required('E2E_SUPABASE_SERVICE_ROLE_KEY'),{auth:{persistSession:false,autoRefreshToken:false}})}
function browserClient(){return createClient(localUrl(),required('E2E_SUPABASE_ANON_KEY'),{auth:{persistSession:false,autoRefreshToken:false}})}

async function adminId(){const db=service();const {data,error}=await db.auth.admin.listUsers({page:1,perPage:1000});if(error)throw error;const admin=data.users.find(user=>user.email===required('E2E_ADMIN_EMAIL'));if(!admin)throw new Error('Phase 7 admin fixture identity is missing.');return admin.id}
async function cleanup(){const db=service();await db.from('project_runs').delete().eq('project_id',projectId);await db.from('project_role_families').delete().eq('project_id',projectId);await db.from('project_domains').delete().eq('project_id',projectId);await db.from('project_capabilities').delete().eq('project_id',projectId);await db.from('project_deliverables').delete().eq('project_id',projectId);await db.from('project_success_criteria').delete().eq('project_id',projectId);await db.from('project_milestones').delete().eq('project_id',projectId);await db.from('project_problem_briefs').delete().eq('project_id',projectId);await db.from('project_roles').delete().eq('project_id',projectId);await db.from('projects').delete().eq('id',projectId)}

async function seed(){
 const db=service();await cleanup();const actor=await adminId();
 let result=await db.from('projects').insert({id:projectId,slug:'phase7-run-privacy',title:'Phase 7 run privacy fixture',summary:'Disposable Phase 7 run privacy fixture for governed operational visibility.',problem_statement:'Validate safe public run status without exposing Admin operational metadata.',status:'draft',visibility:'private',project_type:'open',applications_open:false,team_size_threshold:1,min_team_size:1,target_team_size:1,max_team_size:2,participation_mode:'flexible',admission_mode:'auto',location:'Remote',location_type:'remote',catalogue_working_model_source:'explicit',difficulty_level:'intermediate',duration_weeks:4,weekly_commitment:'4 hours/week'});if(result.error)throw result.error;
 result=await db.from('project_problem_briefs').insert({project_id:projectId,context:'A public-safe run projection is required to validate that operational scheduling details remain private.',stakeholder:'Mettelo project members and anonymous project visitors',primary_question:'Can public run status remain useful without exposing private operational metadata?',expected_outcome:'Anonymous and member callers receive safe run state while privileged operational fields remain protected.',success_metrics:'All Phase 7 run privacy assertions pass across anonymous, authenticated and service-role clients.',constraints:'Synthetic local CI project only.',ethics_considerations:'No production identities or sensitive project data.',primary_use_case:'Release validation for run operational privacy.',primary_objective:'Prove public-safe run visibility and private operational metadata boundaries.',supporting_objectives:['Preserve canonical run visibility','Protect administrative diagnostics'],key_questions:['Which run fields may be public?','Which operational fields must remain private?'],in_scope:['Public run state','Authenticated run state','Service-role operational state'],out_of_scope:['Production scheduling','External integrations'],updated_by:actor,updated_at:new Date().toISOString()});if(result.error)throw result.error;
 result=await db.from('project_roles').insert({project_id:projectId,title:'Data Analyst',discipline:'Data & AI',description:'Release-validation contribution area.',skills:['Data analysis','Testing and QA','Collaboration'],responsibilities:['Validate privacy boundaries'],recommended_skills:['Data analysis'],openings:2});if(result.error)throw result.error;
 const [{data:roleFamily,error:roleError},{data:domain,error:domainError},{data:capabilities,error:capabilityError}]=await Promise.all([db.from('project_role_catalogue').select('id').eq('slug','data-analyst').eq('active',true).maybeSingle(),db.from('domains').select('id').eq('slug','cross-industry-open-data').eq('is_active',true).maybeSingle(),db.from('capabilities').select('id').in('slug',['data-analysis','testing-qa','collaboration']).eq('is_active',true)]);if(roleError)throw roleError;if(domainError)throw domainError;if(capabilityError)throw capabilityError;if(!roleFamily||!domain||(capabilities||[]).length!==3)throw new Error('Phase 7 publication taxonomy fixtures are missing.');
 result=await db.from('project_role_families').insert({project_id:projectId,role_catalogue_id:roleFamily.id,source:'phase7_release_fixture'});if(result.error)throw result.error;
 result=await db.from('project_domains').insert({project_id:projectId,domain_id:domain.id,is_primary:true});if(result.error)throw result.error;
 result=await db.from('project_capabilities').insert((capabilities||[]).map(capability=>({project_id:projectId,capability_id:capability.id,importance:'core',evidence_expected:true})));if(result.error)throw result.error;
 result=await db.from('project_deliverables').insert({id:deliverableId,project_id:projectId,project_run_id:null,canonical_item_key:'phase7-run-privacy:deliverable:001',title:'Run privacy validation evidence',deliverable_type:'canonical',acceptance_criteria:'Demonstrate safe run visibility and denied access to private operational fields.',public_summary:'Validated run privacy boundary.',expected_format:'Release evidence',is_required:true,sort_order:1,created_by:actor});if(result.error)throw result.error;
 result=await db.from('project_success_criteria').insert({id:criterionId,project_id:projectId,title:'Operational run metadata stays private',description:'Public and ordinary member reads cannot expose Admin-only scheduling diagnostics.',measurement:'All Phase 7 run privacy checks pass.',is_required:true,visibility:'public',sort_order:1,created_by_user_id:actor});if(result.error)throw result.error;
 result=await db.from('project_milestones').insert({id:milestoneId,project_id:projectId,project_run_id:null,title:'Run privacy release validation',description:'Complete anonymous, member and service-role privacy checks.',status:'planned',sort_order:1,week_start:1,week_end:4,expected_output:'Exact-head privacy evidence'});if(result.error)throw result.error;
 result=await db.from('projects').update({status:'active',visibility:'public',applications_open:false}).eq('id',projectId);if(result.error)throw result.error;
 const {data,error}=await db.from('project_runs').insert({project_id:projectId,run_number:1,status:'forming',team_size_threshold:1,required_team_size:1,has_started:false,recruitment_open:true,auto_start_pause_reason:'Private governance note',auto_start_block_reason:'Private security note',auto_start_failure:'private-diagnostic'}).select('id').single();if(error||!data)throw error||new Error('Could not seed Phase 7 run privacy fixture.');return data.id;
}

test.describe('Project Experience Phase 7 run operational privacy',()=>{
 test('anon sees safe run state but cannot select private operational columns',async()=>{const runId=await seed();try{const anon=browserClient();const safe=await anon.from('project_runs').select('id,status,has_started,recruitment_open,auto_start_paused_at,auto_start_blocked_at').eq('id',runId).single();expect(safe.error).toBeNull();expect(safe.data).toMatchObject({id:runId,status:'forming',has_started:false,recruitment_open:true});for(const column of ['auto_start_pause_reason','auto_start_paused_by_user_id','auto_start_block_reason','auto_start_blocked_by_user_id','auto_start_failure']){const result=await anon.from('project_runs').select(`id,${column}`).eq('id',runId);expect(result.error,`anon unexpectedly selected ${column}`).toBeTruthy()}}finally{await cleanup()}});

 test('ordinary authenticated member cannot read private operational columns',async()=>{const runId=await seed();try{const member=browserClient();const {error:authError}=await member.auth.signInWithPassword({email:required('E2E_MEMBER_EMAIL'),password:required('E2E_MEMBER_PASSWORD')});if(authError)throw authError;const safe=await member.from('project_runs').select('id,status,scheduled_start_at').eq('id',runId).single();expect(safe.error).toBeNull();const denied=await member.from('project_runs').select('id,auto_start_block_reason').eq('id',runId);expect(denied.error).toBeTruthy()}finally{await cleanup()}});

 test('service role retains full operational visibility',async()=>{const runId=await seed();try{const result=await service().from('project_runs').select('id,auto_start_pause_reason,auto_start_block_reason,auto_start_failure').eq('id',runId).single();expect(result.error).toBeNull();expect(result.data).toMatchObject({id:runId,auto_start_pause_reason:'Private governance note',auto_start_block_reason:'Private security note',auto_start_failure:'private-diagnostic'})}finally{await cleanup()}});
});