import {createClient} from '@supabase/supabase-js';
import {expect,test} from '@playwright/test';

const PROJECT='00000000-0000-4000-8000-00000000d22a';
const env=(name:string)=>{const value=process.env[name]?.trim();if(!value)throw new Error(`${name} is required`);return value};
const service=()=>{const url=env('E2E_SUPABASE_URL');if(!['127.0.0.1','localhost'].includes(new URL(url).hostname))throw new Error('Phase 22 anonymous-return tests refuse non-local Supabase hosts.');return createClient(url,env('E2E_SUPABASE_SERVICE_ROLE_KEY'),{auth:{persistSession:false,autoRefreshToken:false}})};
async function cleanup(db:ReturnType<typeof service>){const {data:needs}=await db.from('project_collaboration_needs').select('id').eq('project_id',PROJECT);const ids=(needs||[]).map(row=>row.id);if(ids.length){await db.from('project_collaboration_analytics_events').delete().in('collaboration_need_id',ids);await db.from('project_collaboration_need_capabilities').delete().in('collaboration_need_id',ids)}await db.from('project_collaboration_needs').delete().eq('project_id',PROJECT);for(const table of ['project_activity_log','project_members','project_applications','project_runs','project_roles'])await db.from(table).delete().eq('project_id',PROJECT);await db.from('projects').delete().eq('id',PROJECT)}
async function seed(){const db=service();await cleanup(db);const {data:users,error:userError}=await db.auth.admin.listUsers({page:1,perPage:1000});if(userError)throw userError;const architect=users.users.find(user=>user.email===env('E2E_ARCHITECT_EMAIL'));if(!architect)throw new Error('Disposable architect identity is required.');let result=await db.from('projects').insert({id:PROJECT,slug:'phase22-anonymous-return',title:'Phase 22 Anonymous Return',summary:'Disposable public collaboration project used only to verify anonymous account return routing.',problem_statement:'Prove the exact collaboration need survives the account and onboarding return path.',status:'draft',visibility:'private',project_type:'open',applications_open:false,participation_mode:'team',team_size_threshold:2,min_team_size:2,target_team_size:2,max_team_size:3,admission_mode:'auto',late_joining_enabled:true,collaboration_marketplace_enabled:true}).select('id').single();if(result.error)throw result.error;const role=await db.from('project_roles').insert({project_id:PROJECT,title:'Data collaborator',discipline:'Data & AI',description:'Disposable role.',skills:['SQL'],responsibilities:['Validate exact opportunity return'],openings:3}).select('id').single();if(role.error||!role.data)throw role.error||new Error('Role missing.');result=await db.from('projects').update({status:'active',visibility:'public',applications_open:true}).eq('id',PROJECT).select('id').single();if(result.error)throw result.error;const run=await db.from('project_runs').insert({project_id:PROJECT,run_number:1,status:'forming',team_size_threshold:2,required_team_size:2,has_started:false,recruitment_open:true}).select('id').single();if(run.error||!run.data)throw run.error||new Error('Run missing.');const need=await db.from('project_collaboration_needs').insert({project_id:PROJECT,project_run_id:run.data.id,created_by:architect.id,source_project_role_id:role.data.id,responsibility:'Validate exact opportunity return',status:'active',source:'member',member_message:'Return to this exact collaboration need.'}).select('id').single();if(need.error||!need.data)throw need.error||new Error('Need missing.');return{db,needId:need.data.id}}

test('anonymous opportunity retains its exact need through account and onboarding return links',async({page})=>{const fixture=await seed();const target=`/member/discover/${PROJECT}?collaboration_need=${encodeURIComponent(fixture.needId)}`;const onboarding=`/onboarding?next=${encodeURIComponent(target)}`;try{await page.goto(`/collaborate/${fixture.needId}`,{waitUntil:'domcontentloaded'});await expect(page.getByRole('heading',{name:'Phase 22 Anonymous Return'})).toBeVisible();const interest=page.getByRole('link',{name:'I’m interested'});const href=await interest.getAttribute('href');expect(href).toBeTruthy();expect(new URL(href!,'http://127.0.0.1:3000').searchParams.get('next')).toBe(target);await interest.click();await page.waitForURL(url=>url.pathname==='/signin'&&url.searchParams.get('next')===target);await page.getByRole('button',{name:'Create account',exact:true}).click();expect(new URL(page.url()).searchParams.get('next')).toBe(target);expect(new URL(page.url()).searchParams.get('mode')).toBe('signup');await page.goto(`/auth/verified?next=${encodeURIComponent(onboarding)}`,{waitUntil:'domcontentloaded'});const verifiedContinue=page.locator('a.button.dark');expect(await verifiedContinue.getAttribute('href')).toBe(onboarding);await page.goto(`/onboarding/complete?next=${encodeURIComponent(target)}`,{waitUntil:'domcontentloaded'});const returnLink=page.getByRole('link',{name:'Return to selected project →'});const returnHref=await returnLink.getAttribute('href');expect(returnHref).toBeTruthy();expect(new URL(returnHref!,'http://127.0.0.1:3000').pathname).toBe('/auth/continue-after-onboarding');expect(new URL(returnHref!,'http://127.0.0.1:3000').searchParams.get('fallback')).toBe(target)}finally{await cleanup(fixture.db)}});
