import {createClient} from '@supabase/supabase-js';
import {expect,test} from '@playwright/test';

const PROJECT='00000000-0000-4000-8000-00000000d174';
const env=(name:string)=>{const value=process.env[name]?.trim();if(!value)throw new Error(`${name} is required`);return value};
function db(){const url=env('E2E_SUPABASE_URL');if(!['127.0.0.1','localhost'].includes(new URL(url).hostname))throw new Error('Phase 17 recovery concurrency tests refuse non-local Supabase hosts.');return createClient(url,env('E2E_SUPABASE_SERVICE_ROLE_KEY'),{auth:{persistSession:false,autoRefreshToken:false}})}
async function identities(){const client=db();const {data,error}=await client.auth.admin.listUsers({page:1,perPage:1000});if(error)throw error;const member=data.users.find(user=>user.email===env('E2E_MEMBER_EMAIL'));const architect=data.users.find(user=>user.email===env('E2E_ARCHITECT_EMAIL'));const admin=data.users.find(user=>user.email===env('E2E_ADMIN_EMAIL'));if(!member||!architect||!admin)throw new Error('Phase 17 recovery concurrency identities missing.');return{member,architect,admin}}
async function cleanup(client:ReturnType<typeof db>){const cases=(await client.from('project_support_cases').select('id').eq('project_id',PROJECT)).data?.map(row=>row.id)||[];if(cases.length)await client.from('project_support_case_updates').delete().in('case_id',cases);await client.from('project_support_cases').delete().eq('project_id',PROJECT);for(const table of ['project_member_handovers','project_member_responsibilities','project_activity_log','project_members','project_runs'])await client.from(table).delete().eq('project_id',PROJECT);await client.from('projects').delete().eq('id',PROJECT)}
async function seed(){const client=db(),ids=await identities();await cleanup(client);const started=new Date(Date.now()-60_000).toISOString();const project=await client.from('projects').insert({id:PROJECT,slug:'phase17-recovery-race',title:'Phase 17 Recovery Race',summary:'Disposable concurrency fixture.',problem_statement:'Prove consequential support recovery serializes competing actions and respects replacement joining cutoff.',status:'active',visibility:'private',project_type:'open',applications_open:false,participation_mode:'team',team_size_threshold:3,min_team_size:3,target_team_size:3,max_team_size:4,admission_mode:'review_required',late_joining_enabled:true});if(project.error)throw project.error;const run=await client.from('project_runs').insert({project_id:PROJECT,run_number:1,status:'active',team_size_threshold:3,required_team_size:3,has_started:true,recruitment_open:false,started_at:started,kickoff_at:started}).select('id').single();if(run.error||!run.data)throw run.error||new Error('run missing');
 const memberships:Record<'member'|'architect'|'admin',string>={} as Record<'member'|'architect'|'admin',string>;
 for(const [key,user,role] of [['member',ids.member,'contributor'],['architect',ids.architect,'project_lead'],['admin',ids.admin,'contributor']] as const){const inserted=await client.from('project_members').insert({project_id:PROJECT,project_run_id:run.data.id,user_id:user.id,team_role:role,membership_status:'active',activated_at:started}).select('id').single();if(inserted.error||!inserted.data)throw inserted.error||new Error(`${key} membership missing`);memberships[key]=inserted.data.id}
 return{client,ids,runId:run.data.id,memberships}}
async function createCase(fixture:Awaited<ReturnType<typeof seed>>){const created=await fixture.client.from('project_support_cases').insert({project_id:PROJECT,project_run_id:fixture.runId,reporter_user_id:fixture.ids.member.id,category:'team_collaboration',description:'Governed recovery concurrency fixture without private details in project-visible history.'}).select('id,updated_at').single();if(created.error||!created.data)throw created.error||new Error('support case missing');return created.data}

test.describe('Project Experience Phase 17 recovery concurrency and cutoff',()=>{
 test('simultaneous consequential actions serialize on exact case version',async()=>{const fixture=await seed();try{const support=await createCase(fixture);const first=fixture.client.rpc('phase17_execute_support_recovery',{p_case_id:support.id,p_action:'change_lead',p_actor_user_id:fixture.ids.admin.id,p_expected_updated_at:support.updated_at,p_replacement_membership_id:fixture.memberships.member});const second=fixture.client.rpc('phase17_execute_support_recovery',{p_case_id:support.id,p_action:'change_lead',p_actor_user_id:fixture.ids.admin.id,p_expected_updated_at:support.updated_at,p_replacement_membership_id:fixture.memberships.admin});const results=await Promise.all([first,second]);const successes=results.filter(item=>!item.error),failures=results.filter(item=>item.error);expect(successes).toHaveLength(1);expect(failures).toHaveLength(1);expect(String(failures[0].error?.message||'')).toContain('SUPPORT_CASE_STALE');const roster=await fixture.client.from('project_members').select('id,team_role').eq('project_run_id',fixture.runId).eq('membership_status','active');expect(roster.error).toBeNull();expect(roster.data?.filter(item=>item.team_role==='project_lead')).toHaveLength(1)}finally{await cleanup(fixture.client)}});
 test('member removal after joining cutoff preserves vacancy without reopening recruitment',async()=>{const fixture=await seed();try{const support=await createCase(fixture);const cutoff=new Date(Date.now()-60_000).toISOString();const configured=await fixture.client.from('projects').update({late_joining_cutoff_at:cutoff}).eq('id',PROJECT);if(configured.error)throw configured.error;const removed=await fixture.client.rpc('phase17_execute_support_recovery',{p_case_id:support.id,p_action:'remove_member',p_actor_user_id:fixture.ids.admin.id,p_expected_updated_at:support.updated_at,p_target_membership_id:fixture.memberships.architect});expect(removed.error).toBeNull();expect(removed.data?.result?.replacement?.joining_not_allowed).toBe(true);const member=await fixture.client.from('project_members').select('membership_status,departure_state,departure_source').eq('id',fixture.memberships.architect).single();expect(member.data).toMatchObject({membership_status:'left',departure_state:'left',departure_source:'support_resolution'});const run=await fixture.client.from('project_runs').select('replacement_needed,recruitment_open,replacement_requested_at').eq('id',fixture.runId).single();expect(run.data?.replacement_needed).toBe(true);expect(run.data?.recruitment_open).toBe(false);expect(run.data?.replacement_requested_at).toBeNull();const events=await fixture.client.from('project_activity_log').select('event_type,metadata').eq('project_id',PROJECT);expect(events.data?.some(item=>item.event_type==='replacement_requested')).toBe(false);expect(JSON.stringify(events.data)).not.toContain('Governed recovery concurrency fixture')}finally{await cleanup(fixture.client)}});
});
