import {expect,test} from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';

const root=process.cwd();const read=(file:string)=>fs.readFileSync(path.join(root,file),'utf8');

test.describe('Project Experience Phase 18C integration, governance, accessibility and analytics contract',()=>{
 test('recommendations are explainable, dismissible and opt-out without changing eligibility',()=>{const server=read('components/MemberHomeCollaborationOpportunities.tsx');const client=read('components/MemberHomeCollaborationRecommendationCards.tsx');const migration=read('supabase/migrations/20260908105000_project_experience_phase_18c_experience_analytics.sql');for(const text of ['Why this recommendation','allow_collaboration_recommendations','project_collaboration_recommendation_dismissals'])expect(server+client+migration).toContain(text);for(const text of ['does not affect your eligibility','never admission','never admission, eligibility'])expect(client+migration).toContain(text)});
 test('recommendation controls meet keyboard, touch and phone reflow contracts',()=>{const css=read('components/MemberHomeCollaborationOpportunities.module.css');const client=read('components/MemberHomeCollaborationRecommendationCards.tsx');expect(css).toContain('min-height:44px');expect(css).toContain(':focus-visible');expect(css).toContain('@media(max-width:480px)');expect(client).toContain('role="status"');expect(client).toContain('aria-live="polite"');expect(client).toContain('aria-label={`Dismiss ${item.title} recommendation`}')});
 test('collaboration analytics are structured, server authoritative and never popularity ranking',()=>{const migration=read('supabase/migrations/20260908105000_project_experience_phase_18c_experience_analytics.sql');const triggers=read('supabase/migrations/20260908106000_project_experience_phase_18c_funnel_triggers.sql');for(const text of ['project_collaboration_analytics_events','revoke all on table public.project_collaboration_analytics_events from public,anon,authenticated','phase18_record_collaboration_analytics','interest_submitted','invite_sent','invite_accepted'])expect(migration+triggers).toContain(text);for(const forbidden of ['invitee_email text','profile_free_text','popularity_score','support_case_id'])expect(migration).not.toContain(forbidden)});
 test('public sharing analytics can only target a public canonical collaboration need',()=>{const route=read('app/api/collaboration-analytics/route.ts');const share=read('components/CollaborationShareActions.tsx');for(const text of ["project?.visibility!=='public'",'phase18_record_collaboration_analytics','share_linkedin','share_x','share_whatsapp','share_copy'])expect(route+share).toContain(text)});
 test('Admin governance revalidates run, joining and Phase 9 capacity and writes canonical audit history',()=>{const route=read('app/api/admin/collaboration-governance/route.ts');for(const text of ['Admin access required.','project_collaboration_needs','phase9_project_run_capacity','late_joining_enabled','late_joining_cutoff_at','recruitment_open','project_activity_log','collaboration_need_closed','collaboration_need_reopened'])expect(route).toContain(text);for(const duplicate of ["from('project_members').insert","from('project_runs').insert","from('project_applications').insert"])expect(route).not.toContain(duplicate)});
 test('Partner projects are database-enforced review and Offer only',()=>{const migration=read('supabase/migrations/20260908105500_project_experience_phase_18c_partner_governance.sql');for(const text of ["project_type='partner'","admission_mode='review_required'",'PARTNER_PROJECT_REQUIRES_REVIEW_OFFER','before insert or update of project_type,admission_mode'])expect(migration).toContain(text)});
 test('Project Lead authority remains exact-run scoped and existing collaboration API is reused',()=>{const route=read('app/api/collaboration-needs/route.ts');for(const text of ["membership.team_role==='project_lead'",'.eq(\'project_run_id\',runId)',"membership_status==='active'",'Only the Project Lead, Admin, or the sole active member'])expect(route).toContain(text)});
 test('Phase 18C preserves canonical interest, run, notification and Phase 15-17 systems',()=>{const application=read('app/api/project-applications/route.ts');const bridge=read('supabase/migrations/20260908104000_project_experience_phase_18_phase16_marketplace_bridge.sql');const governance=read('app/api/admin/collaboration-governance/route.ts');for(const text of ['project_applications','phase6_auto_admit_interest','notifyUser','notifyAdmins'])expect(application).toContain(text);expect(bridge).toContain('replacement_needed');for(const duplicate of ["create table public.project_members","create table public.project_runs","create table public.project_applications","create table public.project_offers"])expect(governance).not.toContain(duplicate)});
});
