import {createClient} from '@supabase/supabase-js';
import {expect,test} from '@playwright/test';
import {PROJECT_PARTICIPATION_TERMS_VERSION} from '../lib/project-participation-terms';

const reviewProject='00000000-0000-4000-8000-00000000e601';
const autoProject='00000000-0000-4000-8000-00000000e602';
function required(name:string){const value=process.env[name]?.trim();if(!value)throw new Error(`${name} is required`);return value}
function db(){const url=required('E2E_SUPABASE_URL');if(!['127.0.0.1','localhost'].includes(new URL(url).hostname))throw new Error('Phase 6 analytics tests refuse non-local Supabase hosts.');return createClient(url,required('E2E_SUPABASE_SERVICE_ROLE_KEY'),{auth:{persistSession:false,autoRefreshToken:false}})}
async function memberId(){const client=db();const {data,error}=await client.auth.admin.listUsers({page:1,perPage:1000});if(error)throw error;const member=data.users.find(user=>user.email===required('E2E_MEMBER_EMAIL'));if(!member)throw new Error('Phase 6 analytics requires the disposable member identity.');return member.id}
async function cleanup(client:ReturnType<typeof db>,projectId:string){await client.from('project_activity_log').delete().eq('project_id',projectId);await client.from('project_members').delete().eq('project_id',projectId);await client.from('project_applications').delete().eq('project_id',projectId);await client.from('project_runs').delete().eq('project_id',projectId);await client.from('project_roles').delete().eq('project_id',projectId);await client.from('projects').delete().eq('id',projectId)}
async function seedProject(client:ReturnType<typeof db>,projectId:string,admissionMode:'auto'|'review_required'){await cleanup(client,projectId);const project=await client.from('projects').insert({id:projectId,slug:`phase6-analytics-${projectId.slice(-4)}`,title:`Phase 6 ${admissionMode} analytics`,summary:'Disposable Phase 6 analytics fixture.',problem_statement:'Prove admission funnel evidence stays on the canonical lifecycle log.',status:'open',visibility:'public',project_type:'open',applications_open:true,team_size_threshold:1,min_team_size:1,target_team_size:1,max_team_size:2,participation_mode:'solo',admission_mode:admissionMode,auto_start_delay_minutes:120});if(project.error)throw project.error}
async function interest(client:ReturnType<typeof db>,projectId:string,userId:string){const now=new Date().toISOString();const {data,error}=await client.from('project_applications').insert({project_id:projectId,user_id:userId,project_role_id:null,status:'submitted',application_kind:'interest',contribution_statement:'Disposable Phase 6 analytics interest with enough detail for the canonical request contract.',terms_accepted_at:now,terms_version:PROJECT_PARTICIPATION_TERMS_VERSION,submitted_at:now}).select('id').single();if(error||!data)throw error||new Error('Could not seed Phase 6 analytics interest.');return data.id}

test.describe('Project Experience Phase 6 admission analytics',()=>{
 test('REVIEW_REQUIRED records submission and review decision without a second lifecycle model',async()=>{const client=db();const userId=await memberId();await seedProject(client,reviewProject,'review_required');try{const applicationId=await interest(client,reviewProject,userId);const now=new Date().toISOString();const decision=await client.from('project_applications').update({admission_mode_snapshot:'review_required',admission_decision:'review_required',admission_decided_at:now,updated_at:now}).eq('id',applicationId);if(decision.error)throw decision.error;const {data:events,error}=await client.from('project_activity_log').select('event_type,actor_type,actor_user_id,metadata').eq('project_id',reviewProject).in('event_type',['interest_submitted','review_required']).order('created_at');if(error)throw error;expect(events?.map(event=>event.event_type)).toEqual(['interest_submitted','review_required']);const submitted=events?.find(event=>event.event_type==='interest_submitted');expect(submitted).toMatchObject({actor_type:'user',actor_user_id:userId,metadata:{application_id:applicationId}});const review=events?.find(event=>event.event_type==='review_required');expect(review).toMatchObject({actor_type:'system',actor_user_id:null,metadata:{application_id:applicationId,user_id:userId}})}finally{await cleanup(client,reviewProject)}});

 test('AUTO records submission qualification and durable scheduling on the same project log',async()=>{const client=db();const userId=await memberId();await seedProject(client,autoProject,'auto');try{const applicationId=await interest(client,autoProject,userId);const admission=await client.rpc('phase6_auto_admit_interest',{p_application_id:applicationId,p_participation_preference:'solo'});expect(admission.error).toBeNull();expect(admission.data).toMatchObject({decision:'auto_qualified',team_ready:true});const {data:events,error}=await client.from('project_activity_log').select('event_type,metadata').eq('project_id',autoProject).in('event_type',['interest_submitted','interest_auto_qualified','project_start_scheduled']).order('created_at');if(error)throw error;expect(events?.map(event=>event.event_type)).toEqual(['interest_submitted','project_start_scheduled','interest_auto_qualified']);expect(events?.find(event=>event.event_type==='interest_auto_qualified')?.metadata).toMatchObject({application_id:applicationId,user_id:userId,required_team_size:1});expect(events?.find(event=>event.event_type==='project_start_scheduled')?.metadata).toMatchObject({required_team_size:1})}finally{await cleanup(client,autoProject)}});
});
