import {createClient} from '@supabase/supabase-js';
import {expect,test,type Page} from '@playwright/test';
import './project-experience-phase16-member-exit-e2e.spec';

const PROJECT='00000000-0000-4000-8000-00000000d150';
const OTHER_RUN='00000000-0000-4000-8000-00000000d152';
const env=(name:string)=>{const value=process.env[name]?.trim();if(!value)throw new Error(`${name} is required`);return value};
const service=()=>{const url=env('E2E_SUPABASE_URL');if(!['127.0.0.1','localhost'].includes(new URL(url).hostname))throw new Error('Phase 15 tests refuse non-local Supabase hosts.');return createClient(url,env('E2E_SUPABASE_SERVICE_ROLE_KEY'),{auth:{persistSession:false,autoRefreshToken:false}})};
const anon=()=>createClient(env('E2E_SUPABASE_URL'),env('E2E_SUPABASE_ANON_KEY'),{auth:{persistSession:false,autoRefreshToken:false}});

async function identities(){const db=service();const {data,error}=await db.auth.admin.listUsers({page:1,perPage:1000});if(error)throw error;const member=data.users.find(u=>u.email===env('E2E_MEMBER_EMAIL'));const architect=data.users.find(u=>u.email===env('E2E_ARCHITECT_EMAIL'));if(!member||!architect)throw new Error('Phase 15 disposable identities missing.');return{member,architect}}
async function login(page:Page,prefix:'MEMBER'|'ARCHITECT'|'ADMIN',next='/member'){await page.goto(`/signin?next=${encodeURIComponent(next)}`,{waitUntil:'networkidle'});const main=page.locator('#main-content');await main.locator('input[type="email"]').fill(env(`E2E_${prefix}_EMAIL`));await main.locator('input[type="password"]').fill(env(`E2E_${prefix}_PASSWORD`));await main.getByRole('button',{name:'Sign in →'}).click();await page.waitForURL(url=>!url.pathname.startsWith('/signin'),{timeout:20_000})}
async function cleanup(db:ReturnType<typeof service>){for(const table of ['contributions','project_resources','project_tasks','project_milestones','project_success_criteria','project_deliverables','project_problem_briefs','project_member_responsibilities','project_activity_log','project_members','project_runs','project_roles'])await db.from(table).delete().eq('project_id',PROJECT);await db.from('projects').delete().eq('id',PROJECT)}
async function seed(){const db=service();const{member,architect}=await identities();await cleanup(db);let result=await db.from('projects').insert({id:PROJECT,slug:'phase15-solo-conversion',title:'Phase 15 Solo Conversion',summary:'Disposable flexible solo fixture.',problem_statement:'Prove independent delivery can add a collaborator without replacing the run or prior work.',status:'active',visibility:'private',project_type:'open',applications_open:false,participation_mode:'flexible',team_size_threshold:2,min_team_size:2,target_team_size:3,max_team_size:3,admission_mode:'review_required',late_joining_enabled:true});if(result.error)throw result.error;result=await db.from('project_roles').insert({project_id:PROJECT,title:'Contributor',discipline:'Data & AI',description:'Disposable contributor role.',skills:['Collaboration'],openings:3});if(result.error)throw result.error;const run=await db.from('project_runs').insert({project_id:PROJECT,run_number:1,status:'active',team_size_threshold:1,required_team_size:1,has_started:true,recruitment_open:false,started_at:new Date().toISOString(),kickoff_at:new Date().toISOString()}).select('id').single();if(run.error||!run.data)throw run.error||new Error('Phase 15 run missing.');result=await db.from('project_members').insert({project_id:PROJECT,project_run_id:run.data.id,user_id:member.id,team_role:'project_lead',membership_status:'active',activated_at:new Date().toISOString()});if(result.error)throw result.error;const fixtures=[db.from('project_problem_briefs').insert({project_id:PROJECT,context:'Independent history.',stakeholder:'Phase 15 test',expected_outcome:'Same-run work survives.'}),db.from('project_deliverables').insert({project_id:PROJECT,project_run_id:run.data.id,title:'Independent analysis',deliverable_type:'document',acceptance_criteria:'Prior work remains attached.',is_required:true,owner_user_id:member.id}),db.from('project_success_criteria').insert({project_id:PROJECT,title:'Same-run history is preserved',is_required:true}),db.from('project_milestones').insert({project_id:PROJECT,project_run_id:run.data.id,title:'Independent milestone',status:'planned',is_required:true}),db.from('project_tasks').insert({project_id:PROJECT,project_run_id:run.data.id,title:'Independent task',description:'Existing work survives conversion.',assignee_user_id:member.id,status:'todo',is_required:true}),db.from('project_resources').insert({project_id:PROJECT,project_run_id:run.data.id,title:'Independent runbook',resource_type:'documentation',url:'https://example.invalid/phase15',description:'Existing resource.',added_by:member.id})];for(const promise of fixtures){const seeded=await promise;if(seeded.error)throw seeded.error}return{db,runId:run.data.id,architect}}
async function snapshot(db:ReturnType<typeof service>,runId:string){const tables=['project_runs','project_members','project_tasks','project_milestones','project_resources','contributions'] as const;const counts:number[]=[];for(const table of tables){let query=db.from(table).select('id',{count:'exact',head:true});query=table==='project_runs'?query.eq('project_id',PROJECT):query.eq('project_run_id',runId);const result=await query;if(result.error)throw result.error;counts.push(result.count||0)}return counts}
async function command(page:Page,runId:string,open:boolean){return page.evaluate(async({projectId,runId,recruitmentOpen})=>{const response=await fetch('/api/project-joining-availability',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({project_id:projectId,project_run_id:runId,recruitment_open:recruitmentOpen})});return{status:response.status,body:await response.json()}},{projectId:PROJECT,runId,recruitmentOpen:open})}

test.describe('Project Experience Phase 15 solo-to-team E2E',()=>{
 test('Lab opens collaboration and preserves the same run, work and Proof boundary when a collaborator joins',async({page})=>{test.slow();const f=await seed();const url=`/member/projects/${PROJECT}?run=${f.runId}&view=home`;try{expect(await snapshot(f.db,f.runId)).toEqual([1,1,1,1,1,0]);await page.setViewportSize({width:390,height:900});await login(page,'MEMBER',url);await page.goto(url,{waitUntil:'networkidle'});await expect(page.getByText('WORKING INDEPENDENTLY',{exact:true})).toBeVisible();const open=page.getByRole('button',{name:'Open collaboration place'});expect((await open.boundingBox())?.height||0).toBeGreaterThanOrEqual(44);await open.focus();await expect(open).toBeFocused();await open.click();await expect(page.getByRole('status')).toContainText('A collaboration place is now open.');const stored=await f.db.from('project_runs').select('id,recruitment_open').eq('id',f.runId).single();expect(stored.data).toMatchObject({id:f.runId,recruitment_open:true});expect(await snapshot(f.db,f.runId)).toEqual([1,1,1,1,1,0]);await page.evaluate(()=>{document.documentElement.style.fontSize='200%'});const size=await page.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth}));expect(size.scrollWidth).toBeLessThanOrEqual(size.clientWidth);const joined=await f.db.from('project_members').insert({project_id:PROJECT,project_run_id:f.runId,user_id:f.architect.id,team_role:'contributor',membership_status:'active',activated_at:new Date().toISOString()});expect(joined.error).toBeNull();expect(await snapshot(f.db,f.runId)).toEqual([1,2,1,1,1,0]);const sameRun=await f.db.from('project_runs').select('id,required_team_size,status,has_started').eq('id',f.runId).single();expect(sameRun.data).toMatchObject({id:f.runId,required_team_size:1,status:'active',has_started:true});await page.evaluate(()=>{document.documentElement.style.fontSize=''});await page.getByRole('button',{name:'Close collaboration place'}).click();await expect(page.getByRole('alert')).toContainText('working independently')}finally{await cleanup(f.db)}});

 test('command rejects non-members and same-project cross-run IDOR',async({page})=>{const f=await seed();try{await login(page,'ADMIN');expect((await command(page,f.runId,true)).status).toBe(403);await page.context().clearCookies();let result=await f.db.from('project_runs').insert({id:OTHER_RUN,project_id:PROJECT,run_number:2,status:'active',team_size_threshold:1,required_team_size:1,has_started:true,recruitment_open:false,started_at:new Date().toISOString()});if(result.error)throw result.error;result=await f.db.from('project_members').insert({project_id:PROJECT,project_run_id:OTHER_RUN,user_id:f.architect.id,team_role:'contributor',membership_status:'active',activated_at:new Date().toISOString()});if(result.error)throw result.error;await login(page,'ARCHITECT');const denied=await command(page,f.runId,true);expect(denied.status).toBe(403);expect(denied.body.error).toContain('active member of this project run')}finally{await cleanup(f.db)}});

 test('RLS blocks direct member mutation of project_runs',async()=>{const f=await seed();try{const member=anon();const signed=await member.auth.signInWithPassword({email:env('E2E_MEMBER_EMAIL'),password:env('E2E_MEMBER_PASSWORD')});if(signed.error)throw signed.error;const direct=await member.from('project_runs').update({recruitment_open:true}).eq('id',f.runId).select('id');expect(Boolean(direct.error)||direct.data?.length===0).toBe(true);const stored=await f.db.from('project_runs').select('recruitment_open').eq('id',f.runId).single();expect(stored.data?.recruitment_open).toBe(false)}finally{await cleanup(f.db)}});
});