import {expect,test} from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';

const root=process.cwd();function read(file:string){return fs.readFileSync(path.join(root,file),'utf8')}

test.describe('Phase 20 Proof operational verification',()=>{
 test('member project workspace submits contribution evidence through the canonical contribution API',()=>{const page=read('app/member/projects/[id]/page.tsx'),form=read('components/ContributionForm.tsx');expect(page).toContain('ContributionForm');for(const text of ['/api/contributions','Submit contribution for review','task','data_source','deliverable','review'])expect(form).toContain(text);});
 test('reviewer queue supports changes required, rejection and verification without self review',()=>{const panel=read('components/ProjectContributionReview.tsx'),route=read('app/api/project-contributions/route.ts');for(const text of ['Request changes','Verify contribution','Do not verify','needs_changes','verified','rejected'])expect(panel+route).toContain(text);expect(route).toContain('You cannot review your own contribution');expect(route).toContain("from('contribution_review_events')");});
 test('member can see changes required, reviewer notes and resubmit into pending review',()=>{const proof=read('components/MemberProofPortfolio.tsx'),route=read('app/api/contributions/route.ts');for(const text of ['Changes requested','review_notes','Resubmit','needs_changes'])expect(proof).toContain(text);for(const text of ["verification_status!=='needs_changes'","verification_status:'pending'",'resubmitted'])expect(route).toContain(text);});
 test('member Proof area exposes pending, verified, changes and rejected history',()=>{const proof=read('components/MemberProofPortfolio.tsx');for(const text of ['Mettelo Proof','Pending review','Verified','Changes requested','not verified','verification_status'])expect(proof).toContain(text);});
 test('verified Proof preserves member, project, run and review attribution',()=>{const submit=read('app/api/contributions/route.ts'),review=read('app/api/project-contributions/route.ts');for(const text of ['project_id','project_run_id','user_id'])expect(submit).toContain(text);for(const text of ['verified_by:','verified_at','review_notes','contribution_review_events','actor_user_id'])expect(review).toContain(text);});
 test('member profile distinguishes self-described identity from earned Verified Proof',()=>{const profile=read('components/MemberProfileSection.tsx');expect(profile).toContain('VERIFIED PROOF');expect(profile).toContain('/member/proof');expect(profile).toContain('completed, reviewed contributions');});
 test('public profile exposes only member-consented verified Proof with historical attribution',()=>{const page=read('app/people/[id]/page.tsx');expect(page).toContain("eq('verification_status','verified')");expect(page).toContain("eq('visibility','public')");for(const text of ['Mettelo Proof','CONTRIBUTION VERIFIED','projects(title)','verified_at','/proof/'])expect(page).toContain(text);});
 test('Proof surfaces retain evidence links and explicit privacy controls',()=>{const proof=read('components/MemberProofPortfolio.tsx'),submit=read('app/api/contributions/route.ts'),visibility=read('components/ProofVisibilityControl.tsx');for(const text of ['evidence_url','visibility','public'])expect(proof+submit).toContain(text);for(const text of ["value:'public'","value:'mettelo_only'","value:'private'",'/api/proof-visibility','Who can see this verified Proof?'])expect(visibility).toContain(text);});
});
