import {createClient} from '@supabase/supabase-js';
import {expect,test,type Page} from '@playwright/test';

type Credentials={email:string;password:string};
const architect=():Credentials=>({email:process.env.E2E_ARCHITECT_EMAIL||'',password:process.env.E2E_ARCHITECT_PASSWORD||''});
const member=():Credentials=>({email:process.env.E2E_MEMBER_EMAIL||'',password:process.env.E2E_MEMBER_PASSWORD||''});
function env(){const url=process.env.E2E_SUPABASE_URL||'';const anon=process.env.E2E_SUPABASE_ANON_KEY||'';const service=process.env.E2E_SUPABASE_SERVICE_ROLE_KEY||'';if(!url||!anon||!service)throw new Error('Missing isolated Supabase E2E credentials.');if(!['127.0.0.1','localhost'].includes(new URL(url).hostname))throw new Error('Phase 3 tests refuse non-local Supabase.');return{url,anon,service};}
async function signIn(page:Page,target:string){const c=architect();await page.goto(`/signin?next=${encodeURIComponent(target)}`,{waitUntil:'networkidle'});await page.locator('#main-content input[type="email"]').fill(c.email);await page.locator('#main-content input[type="password"]').fill(c.password);await page.getByRole('button',{name:'Sign in →'}).click();await page.waitForURL(url=>url.pathname===target,{timeout:20_000});}
async function noOverflow(page:Page,label:string){const size=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth}));expect(size.scroll,label).toBeLessThanOrEqual(size.client);}

test('Project Architect creator exposes canonical participation controls across viewports',async({page})=>{test.setTimeout(180_000);const target='/member/architect-projects/new';await signIn(page,target);for(const viewport of [{width:320,height:740},{width:768,height:1024},{width:1440,height:900}]){await page.setViewportSize(viewport);await page.goto(target,{waitUntil:'networkidle'});await expect(page.getByRole('heading',{name:'Create one canonical Mettelo project.'})).toBeVisible();await expect(page.getByLabel('Participation mode')).toBeVisible();await expect(page.getByLabel('Minimum participants')).toBeVisible();await expect(page.getByLabel('Target participants')).toBeVisible();await expect(page.getByLabel('Maximum participants')).toBeVisible();await noOverflow(page,`Phase 3 creator ${viewport.width}px overflow`);}});

test('Phase 3 creator remains usable at 200 percent text sizing and by keyboard',async({page})=>{const target='/member/architect-projects/new';await signIn(page,target);await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{document.documentElement.style.fontSize='200%'});await expect(page.getByLabel('Participation mode')).toBeVisible();await page.getByLabel('Participation mode').focus();await expect(page.getByLabel('Participation mode')).toBeFocused();await page.keyboard.press('ArrowDown');await page.keyboard.press('Tab');await noOverflow(page,'Phase 3 creator 200% reflow');});

test('project participation constraints and direct member ownership remain database enforced',async()=>{const {url,anon,service}=env();const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});const {data:project,error:projectError}=await admin.from('projects').select('id,participation_mode,min_team_size,target_team_size,max_team_size,team_size_threshold').limit(1).maybeSingle();if(projectError)throw projectError;if(!project)throw new Error('Expected at least one seeded project.');
  expect(project.team_size_threshold).toBe(project.min_team_size);
  expect(project.min_team_size).toBeLessThanOrEqual(project.target_team_size);
  expect(project.target_team_size).toBeLessThanOrEqual(project.max_team_size);
  const invalid=await admin.from('projects').update({participation_mode:'team',min_team_size:5,target_team_size:3,max_team_size:2,team_size_threshold:5}).eq('id',project.id).select('id');expect(invalid.error).not.toBeNull();
  const db=createClient(url,anon,{auth:{persistSession:false,autoRefreshToken:false}});const login=await db.auth.signInWithPassword(member());if(login.error)throw login.error;const forbidden=await db.from('projects').update({target_team_size:Math.min(50,Number(project.target_team_size||1)+1)}).eq('id',project.id).select('id');expect(forbidden.data||[]).toHaveLength(0);
});

test('atomic Architect revision preserves structured acceptance and dependency identity',async({},testInfo)=>{const {url,service}=env();const db=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});const projectId=testInfo.retry===0?'00000000-0000-4000-8000-00000000f3a1':'00000000-0000-4000-8000-00000000f3a2';const {data:users,error:userError}=await db.auth.admin.listUsers({page:1,perPage:1000});if(userError)throw userError;const actor=users.users.find(user=>user.email===process.env.E2E_ARCHITECT_EMAIL)||users.users[0];if(!actor)throw new Error('Phase 3 structured revision requires a disposable architect identity.');
 const basePayload={title:'Phase 3 Structured Definition Draft',summary:'Disposable canonical draft proving structured acceptance and dependencies remain in the single Architect revision transaction.',project_archetype:'analytics',difficulty_level:'intermediate',duration_weeks:4,weekly_commitment:'4 hours/week',team_size_threshold:1,participation_mode:'solo',min_team_size:1,target_team_size:1,max_team_size:1,location:'Remote',partner_project:false,partner_name:null,presentation_required:false,brief:{context:'Validate atomic structured delivery editing.',stakeholder:'Mettelo release governance',primary_question:'Can the Architect edit structured acceptance and dependencies without creating parallel project state?',expected_outcome:'Both structured collections update in one audited transaction.',success_metrics:'IDs remain stable across revision updates.',constraints:'Disposable local CI only.',ethics_considerations:'No production data.',primary_use_case:'Workstream 2 release validation.',primary_objective:'Prove canonical edit ownership.',supporting_objectives:[],key_questions:['Are IDs preserved?'],in_scope:['Structured definition edit'],out_of_scope:['Production data']},resources:[],deliverables:[],success_criteria:[],milestones:[],roles:[],capabilities:[]};
 const created=await db.from('projects').insert({id:projectId,slug:`phase3-structured-definition-draft-${testInfo.retry}`,title:basePayload.title,summary:basePayload.summary,problem_statement:basePayload.brief.primary_question,status:'draft',visibility:'private',project_type:'open',applications_open:false,governance_status:'draft',participation_mode:'solo',team_size_threshold:1,min_team_size:1,target_team_size:1,max_team_size:1});if(created.error)throw created.error;
 const first=await db.rpc('apply_project_experience_draft_revision',{target_project_id:projectId,actor_user_id:actor.id,actor_scope_value:'project_architect',payload:{...basePayload,acceptance_criteria:[{id:null,criterion:'Decision-ready output matches the agreed project question.',is_required:true,visibility:'public',sort_order:0}],dependencies:[{id:null,title:'Source access',description:'The agreed source must remain available to the project team.',dependency_type:'access',is_required:true,visibility:'members',sort_order:0}]},target_risk_level:'standard',target_risk_reasons:[],target_admin_review_required:false});if(first.error)throw first.error;
 const [{data:acceptance,error:acceptanceError},{data:dependency,error:dependencyError}]=await Promise.all([db.from('project_acceptance_criteria').select('id,criterion,visibility').eq('project_id',projectId).single(),db.from('project_dependencies').select('id,title,description,dependency_type,visibility').eq('project_id',projectId).single()]);if(acceptanceError)throw acceptanceError;if(dependencyError)throw dependencyError;
 const second=await db.rpc('apply_project_experience_draft_revision',{target_project_id:projectId,actor_user_id:actor.id,actor_scope_value:'project_architect',payload:{...basePayload,acceptance_criteria:[{id:acceptance.id,criterion:'Decision-ready output matches the agreed question and documented acceptance threshold.',is_required:true,visibility:'members',sort_order:0}],dependencies:[{id:dependency.id,title:'Governed source access',description:'The approved source and required subset must remain available.',dependency_type:'data',is_required:true,visibility:'internal',sort_order:0}]},target_risk_level:'standard',target_risk_reasons:[],target_admin_review_required:false});if(second.error)throw second.error;
 const [{data:updatedAcceptance,error:updatedAcceptanceError},{data:updatedDependency,error:updatedDependencyError},{data:event,error:eventError}]=await Promise.all([db.from('project_acceptance_criteria').select('id,criterion,visibility').eq('project_id',projectId).single(),db.from('project_dependencies').select('id,title,description,dependency_type,visibility').eq('project_id',projectId).single(),db.from('project_governance_events').select('metadata').eq('project_id',projectId).eq('event_type','project_definition_updated').order('created_at',{ascending:false}).limit(1).single()]);if(updatedAcceptanceError)throw updatedAcceptanceError;if(updatedDependencyError)throw updatedDependencyError;if(eventError)throw eventError;
 expect(updatedAcceptance).toMatchObject({id:acceptance.id,visibility:'members'});expect(updatedAcceptance?.criterion).toContain('documented acceptance threshold');expect(updatedDependency).toMatchObject({id:dependency.id,title:'Governed source access',dependency_type:'data',visibility:'internal'});expect(event?.metadata).toMatchObject({acceptance_criteria:1,dependencies:1,atomic_revision:true});
});