import {expect,test} from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const read=(file:string)=>fs.readFileSync(path.join(root,file),'utf8');

test.describe('Project Experience Phase 16 member exit contract',()=>{
 test('extends canonical membership and run architecture without duplicate systems',()=>{const base=read('supabase/migrations/20260907193000_project_experience_phase_16_member_exit.sql'),structured=read('supabase/migrations/20260907193200_project_experience_phase_16_structured_handover_recovery.sql');for(const text of ['alter table public.project_members','departure_state','leaving_at',"membership_status='left'",'phase9_lock_project_capacity'])expect(base).toContain(text);for(const text of ['replacement_needed','lead_replacement_needed','project_member_handovers'])expect(structured).toContain(text);for(const text of ['create table public.project_members','create table public.project_runs','project_invitations','project_teams_v2'])expect(`${base}\n${structured}`).not.toContain(text)});
 test('structured handover captures safe operational continuity fields and source',()=>{const migration=read('supabase/migrations/20260907193200_project_experience_phase_16_structured_handover_recovery.sql');for(const text of ['reason_category','completed_work','open_work','file_references','decisions','risks','recommendations','open_responsibilities','handover_availability','departure_source'])expect(migration).toContain(text);for(const value of ['availability_changed','workload','personal_circumstances','role_fit','technical_access','member_initiated','admin_removal','support_resolution'])expect(migration).toContain(value)});
 test('Leaving keeps capacity; Left releases authority and creates operational recovery state',()=>{const base=read('supabase/migrations/20260907193000_project_experience_phase_16_member_exit.sql'),structured=read('supabase/migrations/20260907193200_project_experience_phase_16_structured_handover_recovery.sql');expect(base).toContain("set departure_state='leaving'");expect(base).toContain("set membership_status='left',departure_state='left'");expect(structured).toContain('replacement_needed=active_members<target_members');expect(structured).toContain('lead_replacement_needed=case when is_departing_lead then true');expect(structured).not.toContain("set status='forming'")});
 test('departure preserves work and Proof history while releasing mutable authority',()=>{const migration=read('supabase/migrations/20260907193200_project_experience_phase_16_structured_handover_recovery.sql');expect(migration).toContain('update public.project_member_responsibilities');expect(migration).toContain("assignment_status='released'");expect(migration).toContain('update public.project_submission_permissions');for(const text of ['delete from public.project_tasks','delete from public.project_milestones','delete from public.project_resources','delete from public.contributions','delete from public.project_discussions'])expect(migration.toLowerCase()).not.toContain(text)});
 test('handover browser table access is closed and operational rendering is server-authorized',()=>{const privacy=read('supabase/migrations/20260907193210_project_experience_phase_16_handover_privacy.sql'),section=read('components/project-experience/ProjectTeamRecoverySection.tsx');expect(privacy).toContain('revoke select,insert,update,delete on public.project_member_handovers from anon,authenticated');expect(section).toContain("membership?.membership_status==='active'");expect(section).toContain("db.from('project_member_handovers')");expect(section).not.toContain('optional_context')});
 test('database hardening keeps one departure contract, validates handover tuple and deduplicates replacement commands',()=>{const hardening=read('supabase/migrations/20260907193400_project_experience_phase_16_integrity_hardening.sql');expect(hardening).toContain('drop function if exists public.phase16_transition_member_departure(uuid,uuid,uuid,text,text)');expect(hardening).toContain('phase16_validate_handover_context');for(const text of ['member.project_id=new.project_id','member.project_run_id=new.project_run_id','member.user_id=new.departing_user_id','HANDOVER_CONTEXT_MISMATCH'])expect(hardening).toContain(text);expect(hardening).toContain('if run_row.replacement_requested_at is not null then');expect(hardening).toContain("'already_requested',true");const duplicateLog=hardening.slice(hardening.indexOf('if run_row.replacement_requested_at is not null then'),hardening.indexOf('capacity:=public.phase9_project_run_capacity'));expect(duplicateLog).not.toContain('insert into public.project_activity_log')});
 test('replacement recovery obeys joining policy and never invents another recruitment system',()=>{const recovery=read('supabase/migrations/20260907193400_project_experience_phase_16_integrity_hardening.sql'),route=read('app/api/project-replacement-recovery/route.ts');for(const text of ['phase9_project_run_capacity','late_joining_enabled','late_joining_cutoff_at',"project_row.participation_mode<>'solo'",'replacement_requested_at','recruitment_open=true'])expect(recovery).toContain(text);expect(route).toContain("membership.team_role==='project_lead'");expect(route).toContain("hasAdminCapability(user,'projects.manage')");for(const source of [recovery,route]){expect(source).not.toContain('project_invitations');expect(source).not.toContain("from('project_runs').insert")}});
 test('recovery reconciles after valid replacement or governed Lead confirmation without project restart',()=>{const recovery=read('supabase/migrations/20260907193300_project_experience_phase_16_recovery_governance.sql');expect(recovery).toContain('after insert or update of project_run_id,membership_status,team_role or delete');expect(recovery).toContain('replacement_needed=active_members<target_members');expect(recovery).toContain('active_leads>0');for(const text of ['started_at=','has_started=false',"status='forming'"])expect(recovery).not.toContain(text)});
 test('canonical Phase 10 same-run formation discounts only replacement Offer reservation',()=>{const hardening=read('supabase/migrations/20260907193100_project_experience_phase_16_replacement_capacity_handoff.sql');for(const text of ['create or replace function public.phase10_form_accepted_offer','reserved:=greatest(reserved-1,0)','occupied+reserved>=maximum_members',"'reused_active_run',late_join",'grant execute on function public.phase10_form_accepted_offer(uuid) to service_role'])expect(hardening).toContain(text);expect(hardening).not.toContain('create table')});
 test('API authenticates exact-run member, makes completion idempotent, and keeps notification copy private',()=>{const route=read('app/api/project-member-departure/route.ts');for(const text of ['createServerSupabaseClient','auth.auth.getUser()',".eq('project_run_id',runId).eq('user_id',user.id)","membership.membership_status==='left'&&membership.departure_state==='left'","already_completed:true","db.rpc('phase16_transition_member_departure'",'notifyUser','notifyAdmins','project_member_exit_confirmation'])expect(route).toContain(text);expect(route.indexOf("membership.membership_status==='left'&&membership.departure_state==='left'")).toBeLessThan(route.indexOf("membership.membership_status!=='active'"));expect(route.indexOf('auth.auth.getUser()')).toBeLessThan(route.indexOf('serviceDb()'));expect(route).not.toContain('project_invitations');expect(route).not.toContain('body:fields.');expect(route).not.toContain('body:reasonCategory')});
 test('Lab provides structured safe handover and textual recovery states',()=>{const lab=read('components/MetteloLabPanel.tsx'),controls=read('components/project-experience/ProjectMemberDepartureControls.tsx'),recovery=read('components/project-experience/ProjectTeamRecoverySection.tsx'),css=read('components/project-experience/ProjectMemberDepartureControls.module.css');expect(lab).toContain('ProjectTeamRecoverySection');expect(lab).toContain('ProjectMemberDepartureSection');for(const text of ['High-level reason','Completed work','Open work','Files and resource references','Important decisions','Known delivery risks','Recommended next steps','Open responsibilities','Do not include passwords, credentials, health information','Complete departure'])expect(controls).toContain(text);for(const text of ['REPLACEMENT NEEDED','PROJECT LEAD NEEDED','REPLACEMENT REQUESTED'])expect(recovery).toContain(text);expect(css).toContain('min-height:44px');expect(css).toContain(':focus-visible')});
 test('real Phase 16 E2E remains local-only and protects access/same-run replacement',()=>{const e2e=read('tests/project-experience-phase16-member-exit-e2e.spec.ts');for(const text of ['Phase 16 tests refuse non-local Supabase hosts.','phase10_form_accepted_offer','privateTasks','forbiddenRpc'])expect(e2e).toContain(text)});
});