import {createClient} from '@supabase/supabase-js';
import {expect,test,type Page} from '@playwright/test';
import {PROJECT_PARTICIPATION_TERMS_VERSION} from '../lib/project-participation-terms';

const projectId='00000000-0000-4000-8000-00000000a901';
const roleId='00000000-0000-4000-8000-00000000a902';
const unavailableRoleId='00000000-0000-4000-8000-00000000a999';
function required(name:string){const value=process.env[name]?.trim();if(!value)throw new Error(`${name} is required`);return value}
async function signIn(page:Page,email:string,password:string){await page.goto('/signin',{waitUntil:'domcontentloaded'});const main=page.locator('#main-content');await main.locator('input[type="email"]').fill(email);await main.locator('input[type="password"]').fill(password);await main.getByRole('button',{name:'Sign in →'}).click();await expect.poll(()=>new URL(page.url()).pathname,{timeout:30_000}).not.toMatch(/^\/signin(?:\/|$)/)}
function serviceDb(){const url=required('E2E_SUPABASE_URL');if(!['127.0.0.1','localhost'].includes(new URL(url).hostname))throw new Error('Project application E2E refuses non-local Supabase hosts.');return createClient(url,required('E2E_SUPABASE_SERVICE_ROLE_KEY'),{auth:{persistSession:false,autoRefreshToken:false}})}
async function canonicalRow(db:ReturnType<typeof serviceDb>,table:string,slug:string,extra:Record<string,string|boolean>={}){let query=db.from(table).select('id,slug').eq('slug',slug);for(const [key,value] of Object.entries(extra))query=query.eq(key,value);const {data,error}=await query.single();if(error)throw error;return data as {id:string;slug:string}}
async function classifyProject(db:ReturnType<typeof serviceDb>){const role=await canonicalRow(db,'project_role_catalogue','data-analyst',{active:true});const domain=await canonicalRow(db,'domains','cross-industry-open-data',{is_active:true});const {data:capabilities,error:capabilityError}=await db.from('capabilities').select('id,slug').in('slug',['data-analysis','data-quality','stakeholder-communication']).eq('is_active',true);if(capabilityError)throw capabilityError;if((capabilities||[]).length!==3)throw new Error('Expected three canonical catalogue capabilities for project application fixture.');const projectUpdate=await db.from('projects').update({location_type:'remote',catalogue_working_model_source:'explicit',duration_weeks:4}).eq('id',projectId);if(projectUpdate.error)throw projectUpdate.error;const family=await db.from('project_role_families').upsert({project_id:projectId,role_catalogue_id:role.id,source:'e2e_fixture'},{onConflict:'project_id,role_catalogue_id'});if(family.error)throw family.error;const capabilityLinks=await db.from('project_capabilities').upsert((capabilities||[]).map(item=>({project_id:projectId,capability_id:item.id,importance:'core',evidence_expected:true})),{onConflict:'project_id,capability_id'});if(capabilityLinks.error)throw capabilityLinks.error;const domainLink=await db.from('project_domains').upsert({project_id:projectId,domain_id:domain.id,is_primary:true},{onConflict:'project_id,domain_id'});if(domainLink.error)throw domainLink.error;return domain}
async function seed(){const db=serviceDb();const {data:users,error:userError}=await db.auth.admin.listUsers({page:1,perPage:1000});if(userError)throw userError;const member=users.users.find(user=>user.email===required('E2E_MEMBER_EMAIL'));if(!member)throw new Error('E2E member missing');await db.from('project_activity_log').delete().eq('project_id',projectId);await db.from('project_members').delete().eq('project_id',projectId);await db.from('project_applications').delete().eq('project_id',projectId);await db.from('project_runs').delete().eq('project_id',projectId);const profile=await db.from('profiles').update({full_name:'E2E Project Member',headline:'Data analyst',professional_area:'Data Analysis / BI',location:'London',experience_level:'Intermediate',skills:['SQL','Power BI','Data Quality'],preferred_roles:['Data Analyst / BI'],project_availability:'available_now',weekly_capacity:'4–6 hours/week'}).eq('id',member.id);if(profile.error)throw profile.error;const preferenceTool=await canonicalRow(db,'tools','power-bi',{is_active:true});const preference=await db.from('profile_tool_preferences').upsert({user_id:member.id,tool_id:preferenceTool.id},{onConflict:'user_id,tool_id'});if(preference.error)throw preference.error;const draft=await db.from('projects').upsert({id:projectId,slug:'e2e-project-application-submit',title:'E2E Project Interest Submission',summary:'Deterministic isolated project interest submission fixture.',problem_statement:'Exercise authenticated member interest storage and Admin review.',status:'draft',visibility:'private',project_type:'open',applications_open:false,team_size_threshold:3,min_team_size:2,target_team_size:3,max_team_size:4,project_type_review_required:false,weekly_commitment:'3-5 hours/week',admission_mode:'review_required',participation_mode:'team',auto_start_delay_minutes:360},{onConflict:'id'});if(draft.error)throw draft.error;const role=await db.from('project_roles').upsert({id:roleId,project_id:projectId,title:'Data Analyst',discipline:'Data & AI',description:'Informational E2E contribution area',skills:['SQL'],openings:3,role_status:'open'},{onConflict:'id'});if(role.error)throw role.error;const domain=await classifyProject(db);const domainPreference=await db.from('profile_domain_preferences').upsert({user_id:member.id,domain_id:domain.id},{onConflict:'user_id,domain_id'});if(domainPreference.error)throw domainPreference.error;const opened=await db.from('projects').update({status:'open',visibility:'public',applications_open:true}).eq('id',projectId);if(opened.error)throw opened.error;const {data:readiness,error:readinessError}=await db.from('project_catalogue_readiness').select('catalogue_ready,missing_requirements').eq('project_id',projectId).single();if(readinessError)throw readinessError;if(!readiness.catalogue_ready)throw new Error(`Project interest E2E fixture is catalogue-incomplete: ${(readiness.missing_requirements||[]).join(', ')}`);return{db,member}}
const interestBody={project_id:projectId,application_kind:'interest',participation_preference:'team',project_role_id:roleId,role_fit_statement:'I have practical analysis experience and can own decision-ready insight delivery.',commitment_response:'yes',availability:'Weekday evenings',availability_note:'I can reliably protect the published weekly commitment.',collaboration_availability:'Weekday evenings and Saturday mornings',leadership_interest:true,motivation_statement:'This project is a strong fit for the evidence I want to build through practical delivery.',relevant_skills:['SQL','Power BI','Data Quality'],contribution_areas:['Analysis & insight','Testing & quality'],contribution_statement:'I can support the analysis, validate data quality and communicate findings to the project team.',portfolio_url:'example.com/member-proof',terms_accepted:true,terms_version:PROJECT_PARTICIPATION_TERMS_VERSION};
const legacyApplicationBody={...interestBody,application_kind:'application',project_role_id:roleId};
async function submitThroughUi(page:Page,preference:'solo'|'team'){await page.goto(`/member/discover/${projectId}/apply`,{waitUntil:'domcontentloaded'});await expect(page.getByRole('heading',{level:1,name:'Submit Interest — E2E Project Interest Submission'})).toBeVisible();const choice=page.locator('.mpaChoice').filter({hasText:preference==='solo'?'Solo':'Team'}).locator('input[type="radio"]');if(await choice.count())await choice.check();await page.getByRole('button',{name:'Continue →'}).click();if(preference==='team')await page.locator('.mpaField select').first().selectOption(roleId);await page.getByRole('button',{name:'Continue →'}).click();await page.getByRole('radio',{name:'Yes',exact:true}).check();await page.getByRole('button',{name:'Continue →'}).click();await page.getByLabel(/Why do you want to work on this project/i).fill('I want to build credible project evidence while contributing practical analysis that supports a real decision.');await page.getByLabel(/What would you contribute/i).fill('I will validate the source data, produce decision-ready analysis, document assumptions and communicate the findings clearly to the team.');await page.getByRole('button',{name:'Continue →'}).click();await page.getByRole('checkbox',{name:/I have read, understood and agree/i}).check();const responsePromise=page.waitForResponse(response=>response.url().includes('/api/project-applications')&&response.request().method()==='POST');await page.getByRole('button',{name:'Submit Interest',exact:true}).click();const response=await responsePromise;const body=await response.json();expect(response.status(),JSON.stringify(body)).toBe(200);await expect(page.getByRole('heading',{level:1,name:'Your interest has been submitted'})).toBeVisible();return body}
async function configureAuto(db:ReturnType<typeof serviceDb>,participationMode:'solo'|'team'|'flexible',minimum:number,target:number,maximum:number){const policy=await db.from('projects').update({admission_mode:'auto',participation_mode:participationMode,team_size_threshold:minimum,min_team_size:minimum,target_team_size:target,max_team_size:maximum,auto_start_delay_minutes:360}).eq('id',projectId);if(policy.error)throw policy.error}

// These tests intentionally share a deterministic project fixture and therefore run serially.
test.describe.configure({mode:'serial'});
test.describe('canonical project interest submission',()=>{
 test('real UI Review Required journey persists once and is immediately visible to Admin',async({page,browser})=>{test.setTimeout(90_000);const {db,member}=await seed();await signIn(page,required('E2E_MEMBER_EMAIL'),required('E2E_MEMBER_PASSWORD'));const payload=await submitThroughUi(page,'team');expect(payload).toMatchObject({ok:true,message:'Interest submitted.',admission:{decision:'review_required',participation_preference:'team'}});const {data:stored,error}=await db.from('project_applications').select('id,project_id,project_role_id,user_id,status,application_kind,participation_preference,terms_accepted_at,terms_version').eq('id',payload.application.id).single();expect(error).toBeNull();expect(stored).toMatchObject({project_id:projectId,project_role_id:roleId,user_id:member.id,status:'submitted',application_kind:'interest',participation_preference:'team',terms_version:PROJECT_PARTICIPATION_TERMS_VERSION});expect(stored?.terms_accepted_at).toBeTruthy();const {count:membershipCount}=await db.from('project_members').select('*',{count:'exact',head:true}).eq('project_id',projectId).eq('user_id',member.id);expect(membershipCount).toBe(0);const duplicate=await page.context().request.post('/api/project-applications',{data:interestBody});expect(duplicate.status()).toBe(409);expect(await duplicate.json()).toMatchObject({code:'DUPLICATE_APPLICATION'});const adminContext=await browser.newContext();const adminPage=await adminContext.newPage();await signIn(adminPage,required('E2E_ADMIN_EMAIL'),required('E2E_ADMIN_PASSWORD'));await adminPage.goto(`/admin/project-operations/applications?project=${projectId}`,{waitUntil:'domcontentloaded'});await expect(adminPage.getByRole('heading',{level:1,name:/^Project requests\b/i})).toBeVisible();await expect(adminPage.locator('.applicationTable').getByRole('link',{name:'E2E Project Interest Submission',exact:true})).toBeVisible();await adminContext.close()});

 test('real UI AUTO Solo journey creates one run, one membership and six-hour eligibility',async({page})=>{const {db,member}=await seed();await configureAuto(db,'solo',1,1,2);await signIn(page,required('E2E_MEMBER_EMAIL'),required('E2E_MEMBER_PASSWORD'));const before=Date.now();const payload=await submitThroughUi(page,'solo');expect(payload).toMatchObject({ok:true,message:'Interest submitted and participation confirmed.',admission:{decision:'auto_qualified',participation_preference:'solo'}});const [{data:application},{data:runs},{data:members}]=await Promise.all([db.from('project_applications').select('id,status,project_run_id,admission_decision,participation_preference').eq('id',payload.application.id).single(),db.from('project_runs').select('id,required_team_size,start_ready_at,start_scheduled_at,scheduled_start_at,has_started').eq('project_id',projectId),db.from('project_members').select('id,project_run_id,membership_status').eq('project_id',projectId).eq('user_id',member.id)]);expect(application).toMatchObject({status:'waiting_for_team',admission_decision:'auto_qualified',participation_preference:'solo'});expect(runs).toHaveLength(1);expect(members).toHaveLength(1);expect(members?.[0].project_run_id).toBe(application?.project_run_id);expect(runs?.[0].required_team_size).toBe(1);expect(runs?.[0].has_started).toBe(false);expect(runs?.[0].scheduled_start_at).toBeTruthy();const scheduled=Date.parse(runs?.[0].scheduled_start_at||'');expect(scheduled-before).toBeGreaterThanOrEqual(359*60_000);expect(scheduled-before).toBeLessThanOrEqual(361*60_000)});

 test('real UI Flexible to Solo preserves project Flexible and uses required members = 1',async({page})=>{const {db}=await seed();await configureAuto(db,'flexible',2,3,4);await signIn(page,required('E2E_MEMBER_EMAIL'),required('E2E_MEMBER_PASSWORD'));const payload=await submitThroughUi(page,'solo');expect(payload.admission).toMatchObject({decision:'auto_qualified',participation_preference:'solo'});const [{data:project},{data:application},{data:run}]=await Promise.all([db.from('projects').select('participation_mode').eq('id',projectId).single(),db.from('project_applications').select('project_run_id,participation_preference,admission_decision').eq('id',payload.application.id).single(),db.from('project_runs').select('required_team_size,scheduled_start_at').eq('project_id',projectId).single()]);expect(project?.participation_mode).toBe('flexible');expect(application?.participation_preference).toBe('solo');expect(run?.required_team_size).toBe(1);expect(run?.scheduled_start_at).toBeTruthy()});

 test('real UI Flexible to Team preserves Team minimum and does not start eligibility with one member',async({page})=>{const {db}=await seed();await configureAuto(db,'flexible',2,3,4);await signIn(page,required('E2E_MEMBER_EMAIL'),required('E2E_MEMBER_PASSWORD'));const payload=await submitThroughUi(page,'team');expect(payload.admission).toMatchObject({decision:'auto_qualified',participation_preference:'team'});const [{data:project},{data:application},{data:run},{count:members}]=await Promise.all([db.from('projects').select('participation_mode,min_team_size').eq('id',projectId).single(),db.from('project_applications').select('project_run_id,participation_preference,admission_decision').eq('id',payload.application.id).single(),db.from('project_runs').select('required_team_size,scheduled_start_at,start_ready_at').eq('project_id',projectId).single(),db.from('project_members').select('id',{count:'exact',head:true}).eq('project_id',projectId)]);expect(project).toMatchObject({participation_mode:'flexible',min_team_size:2});expect(application?.participation_preference).toBe('team');expect(run?.required_team_size).toBe(2);expect(members).toBe(1);expect(run?.scheduled_start_at).toBeNull();expect(run?.start_ready_at).toBeNull()});

 test('real UI Team AUTO preserves minimum and first member does not start six-hour eligibility',async({page})=>{const {db}=await seed();await configureAuto(db,'team',2,3,4);await signIn(page,required('E2E_MEMBER_EMAIL'),required('E2E_MEMBER_PASSWORD'));const payload=await submitThroughUi(page,'team');expect(payload.admission).toMatchObject({decision:'auto_qualified',participation_preference:'team'});const {data:run}=await db.from('project_runs').select('required_team_size,scheduled_start_at,start_ready_at,has_started').eq('project_id',projectId).single();expect(run).toMatchObject({required_team_size:2,scheduled_start_at:null,start_ready_at:null,has_started:false})});

 test('AUTO withdrawal below minimum releases membership and invalidates all eligibility markers',async({page})=>{const {db,member}=await seed();await configureAuto(db,'solo',1,1,2);await signIn(page,required('E2E_MEMBER_EMAIL'),required('E2E_MEMBER_PASSWORD'));const submitted=await page.context().request.post('/api/project-applications',{data:{...interestBody,participation_preference:'solo',project_role_id:null,secondary_project_role_id:null,leadership_interest:false,collaboration_availability:null}});expect(submitted.status()).toBe(200);const payload=await submitted.json();expect(payload).toMatchObject({ok:true,admission:{decision:'auto_qualified',participation_preference:'solo'}});const applicationId=payload.application.id as string;const runId=payload.application.project_run_id as string;const {count:membershipCount}=await db.from('project_members').select('*',{count:'exact',head:true}).eq('project_id',projectId).eq('user_id',member.id).eq('membership_status','waiting');expect(membershipCount).toBe(1);const withdrawn=await page.context().request.patch('/api/project-applications',{data:{id:applicationId,action:'withdraw'}});expect(withdrawn.status()).toBe(200);expect(await withdrawn.json()).toMatchObject({ok:true,application:{id:applicationId,status:'withdrawn'},team_place_released:true});const [{data:application},{data:membership},{data:run},{data:activity}]=await Promise.all([db.from('project_applications').select('status,withdrawn_at').eq('id',applicationId).single(),db.from('project_members').select('membership_status,left_at').eq('project_id',projectId).eq('user_id',member.id).single(),db.from('project_runs').select('scheduled_start_at,start_scheduled_at,start_ready_at,has_started').eq('id',runId).single(),db.from('project_activity_log').select('event_type,metadata').eq('project_id',projectId).eq('project_run_id',runId).eq('event_type','project_start_schedule_cancelled').maybeSingle()]);expect(application?.status).toBe('withdrawn');expect(application?.withdrawn_at).toBeTruthy();expect(membership?.membership_status).toBe('left');expect(membership?.left_at).toBeTruthy();expect(run).toMatchObject({scheduled_start_at:null,start_scheduled_at:null,start_ready_at:null,has_started:false});expect(activity?.metadata).toMatchObject({reason:'membership_withdrawal_below_minimum',filled:0,required_team_size:1})});

 test('profile readiness is revalidated server-side before interest persistence',async({page})=>{const {db,member}=await seed();const update=await db.from('profiles').update({weekly_capacity:null}).eq('id',member.id);if(update.error)throw update.error;await signIn(page,required('E2E_MEMBER_EMAIL'),required('E2E_MEMBER_PASSWORD'));const response=await page.context().request.post('/api/project-applications',{data:{...interestBody,portfolio_url:null}});expect(response.status()).toBe(409);expect(await response.json()).toMatchObject({code:'PROFILE_INCOMPLETE'});const {count}=await db.from('project_applications').select('*',{count:'exact',head:true}).eq('project_id',projectId).eq('user_id',member.id);expect(count).toBe(0)});

 test('weekly-capacity mismatch is not invented as a hard Phase 5 rejection',async({page})=>{const {db,member}=await seed();const update=await db.from('profiles').update({weekly_capacity:'Up to 2 hours/week'}).eq('id',member.id);if(update.error)throw update.error;await signIn(page,required('E2E_MEMBER_EMAIL'),required('E2E_MEMBER_PASSWORD'));const response=await page.context().request.post('/api/project-applications',{data:{...interestBody,portfolio_url:null}});expect(response.status()).toBe(200);expect(await response.json()).toMatchObject({ok:true,message:'Interest submitted.'})});

 test('invalid link and terms fail before insert and retain retryable client state',async({page})=>{const {db,member}=await seed();await signIn(page,required('E2E_MEMBER_EMAIL'),required('E2E_MEMBER_PASSWORD'));const invalid=await page.context().request.post('/api/project-applications',{data:{...interestBody,portfolio_url:'javascript:alert(1)'}});expect(invalid.status()).toBe(400);expect(await invalid.json()).toMatchObject({code:'INVALID_PROFESSIONAL_LINK',field:'professional_link'});const terms=await page.context().request.post('/api/project-applications',{data:{...interestBody,portfolio_url:null,terms_accepted:false}});expect(terms.status()).toBe(400);expect(await terms.json()).toMatchObject({code:'TERMS_REQUIRED'});const {count}=await db.from('project_applications').select('*',{count:'exact',head:true}).eq('project_id',projectId).eq('user_id',member.id);expect(count).toBe(0)});

 test('legacy role application validation remains regression-safe without controlling initial interest',async({page})=>{await seed();await signIn(page,required('E2E_MEMBER_EMAIL'),required('E2E_MEMBER_PASSWORD'));const unavailable=await page.context().request.post('/api/project-applications',{data:{...legacyApplicationBody,project_role_id:unavailableRoleId,portfolio_url:null}});expect(unavailable.status()).toBe(409);expect(await unavailable.json()).toMatchObject({code:'ROLE_UNAVAILABLE'})});

 test('closed project and expired session return structured qualification states',async({page,request})=>{const {db}=await seed();await signIn(page,required('E2E_MEMBER_EMAIL'),required('E2E_MEMBER_PASSWORD'));await db.from('projects').update({applications_open:false,status:'active'}).eq('id',projectId);const closed=await page.context().request.post('/api/project-applications',{data:{...interestBody,portfolio_url:null}});expect(closed.status()).toBe(409);expect(await closed.json()).toMatchObject({code:'PROJECT_CLOSED'});const expired=await request.post('/api/project-applications',{data:interestBody});expect(expired.status()).toBe(401);expect(await expired.json()).toMatchObject({code:'AUTH_REQUIRED',error:'Your session has expired. Please sign in again.'})});
});
