import {createClient} from '@supabase/supabase-js';
import {expect,test,type Browser,type Page} from '@playwright/test';
import {PROJECT_PARTICIPATION_TERMS_VERSION} from '../lib/project-participation-terms';

const partnerProject='00000000-0000-4000-8000-00000000b811';
const reviewProject='00000000-0000-4000-8000-00000000b812';
const autoProject='00000000-0000-4000-8000-00000000b813';
function required(name:string){const value=process.env[name]?.trim();if(!value)throw new Error(`${name} is required`);return value}
function db(){const url=required('E2E_SUPABASE_URL');if(!['127.0.0.1','localhost'].includes(new URL(url).hostname))throw new Error('Phase 8 boundary tests refuse non-local Supabase hosts.');return createClient(url,required('E2E_SUPABASE_SERVICE_ROLE_KEY'),{auth:{persistSession:false,autoRefreshToken:false}})}
async function identities(){const client=db();const {data,error}=await client.auth.admin.listUsers({page:1,perPage:1000});if(error)throw error;const member=data.users.find(user=>user.email===required('E2E_MEMBER_EMAIL'));const architect=data.users.find(user=>user.email===required('E2E_ARCHITECT_EMAIL'));if(!member||!architect)throw new Error('Disposable member and architect identities are required.');return{member,architect}}
async function signIn(page:Page,email:string,password:string){await page.goto('/signin',{waitUntil:'networkidle'});const main=page.locator('#main-content');await main.locator('input[type="email"]').fill(email);await main.locator('input[type="password"]').fill(password);await main.getByRole('button',{name:'Sign in →'}).click();await page.waitForURL(url=>!url.pathname.startsWith('/signin'),{timeout:20_000})}
async function cleanup(client:ReturnType<typeof db>,projectId:string){const {data:apps}=await client.from('project_applications').select('id').eq('project_id',projectId);const appIds=(apps||[]).map(item=>item.id);await client.from('project_offers').delete().eq('project_id',projectId);if(appIds.length)await client.from('project_application_events').delete().in('application_id',appIds);await client.from('project_activity_log').delete().eq('project_id',projectId);await client.from('project_members').delete().eq('project_id',projectId);await client.from('project_applications').delete().eq('project_id',projectId);await client.from('project_runs').delete().eq('project_id',projectId);await client.from('project_roles').delete().eq('project_id',projectId);await client.from('projects').delete().eq('id',projectId)}
async function seedProject(client:ReturnType<typeof db>,projectId:string,type:'open'|'partner',mode:'auto'|'review_required',maximum=2){await cleanup(client,projectId);const {error}=await client.from('projects').insert({id:projectId,slug:`phase8-boundary-${projectId.slice(-4)}`,title:`Phase 8 ${type} ${mode}`,summary:'Disposable Phase 8 boundary fixture.',problem_statement:'Validate Phase 8 eligibility and concurrent project-place decisions.',status:'open',visibility:'private',project_type:type,partner_name:type==='partner'?'E2E Partner Organisation':null,applications_open:true,team_size_threshold:1,min_team_size:1,target_team_size:Math.min(2,maximum),max_team_size:maximum,participation_mode:'team',admission_mode:mode});if(error)throw error}
async function seedApplication(client:ReturnType<typeof db>,projectId:string,userId:string,decision:'review_required'|'auto_qualified'='review_required'){const now=new Date().toISOString();const {data,error}=await client.from('project_applications').insert({project_id:projectId,user_id:userId,status:'shortlisted',application_kind:'interest',admission_mode_snapshot:decision==='auto_qualified'?'auto':'review_required',admission_decision:decision,participation_preference:'team',availability:'Weekday evenings',leadership_interest:false,contribution_statement:'Phase 8 boundary fixture interest statement with sufficient detail.',terms_accepted_at:now,terms_version:PROJECT_PARTICIPATION_TERMS_VERSION,submitted_at:now}).select('id').single();if(error||!data)throw error||new Error('Could not seed Phase 8 boundary application.');return data.id}
async function serviceOffer(client:ReturnType<typeof db>,applicationId:string){return client.from('project_applications').update({status:'offered',updated_at:new Date().toISOString()}).eq('id',applicationId)}
async function offerFor(client:ReturnType<typeof db>,applicationId:string){const {data,error}=await client.from('project_offers').select('id,status,expires_at,capacity_released_at').eq('application_id',applicationId).single();if(error||!data)throw error||new Error('Expected Phase 8 Offer.');return data}
async function signedContexts(browser:Browser){const a=await browser.newContext();const b=await browser.newContext();const pa=await a.newPage();const pb=await b.newPage();await signIn(pa,required('E2E_MEMBER_EMAIL'),required('E2E_MEMBER_PASSWORD'));await signIn(pb,required('E2E_MEMBER_EMAIL'),required('E2E_MEMBER_PASSWORD'));return{a,b,pa,pb}}

test.describe('Project Experience Phase 8 eligibility and race boundaries',()=>{
  test('Partner and Open REVIEW_REQUIRED create canonical Offers; Open AUTO is rejected at database boundary',async()=>{const client=db();const {member}=await identities();try{await seedProject(client,partnerProject,'partner','review_required');const partnerApp=await seedApplication(client,partnerProject,member.id);expect((await serviceOffer(client,partnerApp)).error).toBeNull();expect((await offerFor(client,partnerApp)).status).toBe('pending');await cleanup(client,partnerProject);
    await seedProject(client,reviewProject,'open','review_required');const reviewApp=await seedApplication(client,reviewProject,member.id);expect((await serviceOffer(client,reviewApp)).error).toBeNull();expect((await offerFor(client,reviewApp)).status).toBe('pending');await cleanup(client,reviewProject);
    await seedProject(client,autoProject,'open','auto');const autoApp=await seedApplication(client,autoProject,member.id,'auto_qualified');const forbidden=await serviceOffer(client,autoApp);expect(forbidden.error?.message).toMatch(/OFFER_REQUIRES_REVIEW_REQUIRED|AUTO_OFFER_FORBIDDEN/);const {count}=await client.from('project_offers').select('id',{count:'exact',head:true}).eq('application_id',autoApp);expect(count).toBe(0)}finally{await cleanup(client,partnerProject);await cleanup(client,reviewProject);await cleanup(client,autoProject)}});

  test('member cannot forge application into OFFERED to create an Offer',async()=>{const client=db();const {member}=await identities();await seedProject(client,reviewProject,'open','review_required');try{const appId=await seedApplication(client,reviewProject,member.id);const userClient=createClient(required('E2E_SUPABASE_URL'),required('E2E_SUPABASE_ANON_KEY'),{auth:{persistSession:false,autoRefreshToken:false}});const signed=await userClient.auth.signInWithPassword({email:required('E2E_MEMBER_EMAIL'),password:required('E2E_MEMBER_PASSWORD')});if(signed.error)throw signed.error;const forged=await userClient.from('project_applications').update({status:'offered'}).eq('id',appId);expect(forged.error).toBeTruthy();const {count}=await client.from('project_offers').select('id',{count:'exact',head:true}).eq('application_id',appId);expect(count).toBe(0);await userClient.auth.signOut()}finally{await cleanup(client,reviewProject)}});

  test('Accept versus Decline race produces one terminal decision',async({browser})=>{const client=db();const {member}=await identities();await seedProject(client,reviewProject,'open','review_required');try{const appId=await seedApplication(client,reviewProject,member.id);expect((await serviceOffer(client,appId)).error).toBeNull();const offer=await offerFor(client,appId);const {a,b,pa,pb}=await signedContexts(browser);const [accept,decline]=await Promise.all([pa.context().request.patch('/api/project-offers',{data:{id:offer.id,action:'accept'}}),pb.context().request.patch('/api/project-offers',{data:{id:offer.id,action:'decline'}})]);expect([accept.status(),decline.status()].filter(status=>status===200)).toHaveLength(1);expect([accept.status(),decline.status()].sort()).toEqual([200,409]);const {data:stored}=await client.from('project_offers').select('status,accepted_at,declined_at').eq('id',offer.id).single();expect(['accepted','declined']).toContain(stored?.status);expect(Boolean(stored?.accepted_at)&&Boolean(stored?.declined_at)).toBe(false);await a.close();await b.close()}finally{await cleanup(client,reviewProject)}});

  test('Accept versus expiry race produces exactly one terminal state and one capacity release semantics',async({browser})=>{const client=db();const {member}=await identities();await seedProject(client,reviewProject,'open','review_required');try{const appId=await seedApplication(client,reviewProject,member.id);expect((await serviceOffer(client,appId)).error).toBeNull();const offer=await offerFor(client,appId);const offeredAt=new Date(Date.now()-60_000).toISOString();const deadline=new Date(Date.now()+250).toISOString();const forced=await client.from('project_offers').update({offered_at:offeredAt,expires_at:deadline,capacity_reserved_at:offeredAt}).eq('id',offer.id);if(forced.error)throw forced.error;const context=await browser.newContext();const page=await context.newPage();await signIn(page,required('E2E_MEMBER_EMAIL'),required('E2E_MEMBER_PASSWORD'));await new Promise(resolve=>setTimeout(resolve,300));const [accept,expiry]=await Promise.all([page.context().request.patch('/api/project-offers',{data:{id:offer.id,action:'accept'}}),client.rpc('phase8_expire_project_offers',{p_limit:100})]);if(expiry.error)throw expiry.error;expect([200,409]).toContain(accept.status());const {data:stored}=await client.from('project_offers').select('status,accepted_at,expired_at,capacity_released_at').eq('id',offer.id).single();expect(['accepted','expired']).toContain(stored?.status);expect(Boolean(stored?.accepted_at)&&Boolean(stored?.expired_at)).toBe(false);if(stored?.status==='accepted')expect(stored.capacity_released_at).toBeNull();if(stored?.status==='expired')expect(stored.capacity_released_at).toBeTruthy();await context.close()}finally{await cleanup(client,reviewProject)}});

  test('terminal Offer states are excluded from reminder claims',async({page})=>{const client=db();const {member}=await identities();await seedProject(client,reviewProject,'open','review_required');try{for(const action of ['accept','decline'] as const){const appId=await seedApplication(client,reviewProject,member.id);expect((await serviceOffer(client,appId)).error).toBeNull();const offer=await offerFor(client,appId);const nearExpiry=new Date(Date.now()+60*60_000).toISOString();const forced=await client.from('project_offers').update({expires_at:nearExpiry}).eq('id',offer.id);if(forced.error)throw forced.error;if(!page.url().includes('/member'))await signIn(page,required('E2E_MEMBER_EMAIL'),required('E2E_MEMBER_PASSWORD'));expect((await page.context().request.patch('/api/project-offers',{data:{id:offer.id,action}})).status()).toBe(200);const claim=await client.rpc('phase8_claim_offer_reminders',{p_limit:100});if(claim.error)throw claim.error;expect((claim.data||[]).find((row:{offer_id:string})=>row.offer_id===offer.id)).toBeUndefined();await client.from('project_offers').delete().eq('id',offer.id);await client.from('project_applications').delete().eq('id',appId)}
    const expiredApp=await seedApplication(client,reviewProject,member.id);expect((await serviceOffer(client,expiredApp)).error).toBeNull();const expiredOffer=await offerFor(client,expiredApp);const past=new Date(Date.now()-60_000).toISOString();const forcedExpired=await client.from('project_offers').update({offered_at:new Date(Date.now()-120_000).toISOString(),expires_at:past,capacity_reserved_at:new Date(Date.now()-120_000).toISOString()}).eq('id',expiredOffer.id);if(forcedExpired.error)throw forcedExpired.error;const expired=await client.rpc('phase8_expire_project_offers',{p_limit:100});if(expired.error)throw expired.error;const claim=await client.rpc('phase8_claim_offer_reminders',{p_limit:100});if(claim.error)throw claim.error;expect((claim.data||[]).find((row:{offer_id:string})=>row.offer_id===expiredOffer.id)).toBeUndefined()}finally{await cleanup(client,reviewProject)}});
});
