import {expect,test} from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';

const root=process.cwd();function read(file:string){return fs.readFileSync(path.join(root,file),'utf8')}

test.describe('Phase 19 completion operational UX',()=>{
 test('real Mettelo Lab mounts canonical final Proof and completion UI',()=>{const lab=read('components/MetteloLabPanel.tsx');expect(lab).toContain("import ProjectFinalProofPanel from '@/components/ProjectFinalProofPanel'");expect(lab).toContain('<ProjectFinalProofPanel');expect(lab).toContain('data-lab-review-section');expect(lab).toContain('lab-completion-review');});
 test('completion UI exposes readiness, submit, review, changes, history and completed state',()=>{const panel=read('components/ProjectFinalProofPanel.tsx');for(const text of ['COMPLETION READINESS','Submit final Proof for review','Request changes','Approve Partner completion','CHANGES REQUIRED','Resubmit final Proof for review','Completion history','PROJECT RUN COMPLETED'])expect(panel).toContain(text);});
 test('status projection includes readiness and completion history for the exact run',()=>{const status=read('app/api/project-final-proof/status/route.ts');for(const text of ["rpc('project_run_completion_readiness'","from('project_completion_requests')",'history:history||[]','readiness','project_run_id'])expect(status).toContain(text);});
 test('final review freezes recruitment and closes active collaboration intake',()=>{const route=read('app/api/project-final-proof/route.ts');for(const text of ['freezeRecruitment',"recruitment_open:false","from('project_collaboration_needs')","status:'closed'","closed_reason:reason","from('project_member_collaboration_invitations')","status:'revoked'",'phase19_final_review'])expect(route).toContain(text);});
 test('public and member recruitment surfaces reject review-state runs',()=>{const publicPage=read('app/collaborate/[id]/page.tsx'),grow=read('components/ProjectGrowTeamSection.tsx'),invites=read('app/api/member-collaboration-invitations/route.ts');expect(publicPage).toContain("!['forming','active'].includes(run.status)");expect(grow).toContain("run.status==='review'");expect(invites).toContain("['forming','active'].includes(run.status)");});
 test('changes requested returns work to active without reopening recruitment',()=>{const completion=read('app/api/project-completion/route.ts'),panel=read('components/ProjectFinalProofPanel.tsx');expect(completion).toContain("status:'active'");expect(completion).toContain('completion_requested_at:null');expect(completion).toContain('recruitment_open:false');expect(completion).not.toContain('recruitment_open:true');expect(panel).toContain("completion_request?.status==='changes_requested'");expect(panel).toContain('Resubmit final Proof for review');});
 test('completion controls retain accessible touch and status feedback',()=>{const panel=read('components/ProjectFinalProofPanel.tsx');expect(panel).toContain('min-height:44px');expect(panel).toContain(':focus-visible');expect(panel).toContain('@media(max-width:520px)');expect(panel).toContain('aria-live="polite"');expect(panel).toContain('role="status"');});
});
