import {createClient} from '@supabase/supabase-js';
import {expect,test} from '@playwright/test';
import {PROJECT_PARTICIPATION_TERMS_VERSION} from '../lib/project-participation-terms';

const teamProject='00000000-0000-4000-8000-00000000d101';

function required(name:string){const value=process.env[name]?.trim();if(!value)throw new Error(`${name} is required`);return value}
function db(){const url=required('E2E_SUPABASE_URL');if(!['127.0.0.1','localhost'].includes(new URL(url).hostname))throw new Error('Phase 10 formation tests refuse non-local Supabase hosts.');return createClient(url,required('E2E_SUPABASE_SERVICE_ROLE_KEY'),{auth:{persistSession:false,autoRefreshToken:false}})}
async function identities(){const client=db();const {data,error}=await client.auth.admin.listUsers({page:1,perPage:1000});if(error)throw error;const member=data.users.find(user=>user.email===required('E2E_MEMBER_EMAIL'));const architect=data.users.find(user=>user.email===required('E2E_ARCHITECT_EMAIL'));if(!member||!architect)throw new Error('Phase 10 requires disposable member and architect identities.');return{member,architect}}
async function cleanup(client:ReturnType<typeof db>,projectId:string){const {data:apps}=await client.from('project_applications').select('id').eq('project_id',projectId);const appIds=(apps||[]).map(row=>row.id);await client.from('project_offers').delete().eq('project_id',projectId);if(appIds.length)await client.from('project_application_events').delete().in('application_id',appIds);await client.from('project_activity_log').delete().eq('project_id',projectId);await client.from('project_members').delete().eq('project_id',projectId);await client.from('project_applications').delete().eq('project_id',projectId);await client.from('project_runs').delete().eq('project_id',projectId);await client.from('project_roles').delete().eq('project_id',projectId);await client.from('projects').delete().eq('id',projectId)}
async function seedProject(client:ReturnType<typeof db>){await cleanup(client,teamProject);const project=await client.from('projects').insert({id:teamProject,slug:'phase10-team-formation',title:'Phase 10 Team Formation',summary:'Disposable Phase 10 team-formation fixture.',problem_statement:'Validate accepted Offer conversion into canonical run membership without premature activation.',status:'open',visibility:'private',project_type:'open',applications_open:true,participation_mode:'team',team_size_threshold:2,min_team_size:2,target_team_size:3,max_team_size:3,admission_mode:'review_required'});if(project.error)throw project.error;const roles=await client.from('project_roles').insert([{project_id:teamProject,title:'Analyst',discipline:'Data & AI',description:'Own the analysis responsibility.',skills:['Analysis'],openings:2},{project_id:teamProject,title:'Engineer',discipline:'Data & AI',description:'Own the engineering responsibility.',skills:['Engineering'],openings:1}]).select('id,title');if(roles.error)throw roles.error;return roles.data||[]}
async function seedApplication(client:ReturnType<typeof db>,userId:string){const now=new Date().toISOString();const {data,error}=await client.from('project_applications').insert({project_id:teamProject,user_id:userId,status:'shortlisted',application_kind:'interest',admission_mode_snapshot:'review_required',admission_decision:'review_required',participation_preference:'team',availability:'Weekday evenings',leadership_interest:true,contribution_statement:'Disposable Phase 10 formation interest statement with sufficient detail.',terms_accepted_at:now,terms_version:PROJECT_PARTICIPATION_TERMS_VERSION,submitted_at:now}).select('id').single();if(error||!data)throw error||new Error('Could not seed Phase 10 application.');const offered=await client.from('project_applications').update({status:'offered',updated_at:new Date().toISOString()}).eq('id',data.id);if(offered.error)throw offered.error;return data.id}
async function acceptOffer(client:ReturnType<typeof db>,applicationId:string,userId:string){const {data:offer,error:offerError}=await client.from('project_offers').select('id').eq('application_id',applicationId).single();if(offerError||!offer)throw offerError||new Error('Expected Phase 10 Offer.');const auth=createClient(required('E2E_SUPABASE_URL'),required('E2E_SUPABASE_ANON_KEY'),{auth:{persistSession:false,autoRefreshToken:false}});const email=userId===(await identities()).member.id?required('E2E_MEMBER_EMAIL'):required('E2E_ARCHITECT_EMAIL');const password=userId===(await identities()).member.id?required('E2E_MEMBER_PASSWORD'):required('E2E_ARCHITECT_PASSWORD');const signed=await auth.auth.signInWithPassword({email,password});if(signed.error)throw signed.error;const accepted=await auth.rpc('phase8_respond_to_project_offer',{p_offer_id:offer.id,p_action:'accept'});await auth.auth.signOut();if(accepted.error)throw accepted.error;return offer.id}

test.describe('Project Experience Phase 10 canonical formation backend',()=>{
 test('two accepted Team Offers form one waiting run, consume reservations, remain unstarted and enforce one lead',async()=>{const client=db();const {member,architect}=await identities();const roles=await seedProject(client);try{const memberApp=await seedApplication(client,member.id);const architectApp=await seedApplication(client,architect.id);const memberOffer=await acceptOffer(client,memberApp,member.id);const architectOffer=await acceptOffer(client,architectApp,architect.id);
   const first=await client.rpc('phase10_form_accepted_offer',{p_application_id:memberApp});if(first.error)throw first.error;expect(first.data).toMatchObject({formed:true,already_formed:false,required_team_size:2,membership_status:'waiting',project_active:false});
   const second=await client.rpc('phase10_form_accepted_offer',{p_application_id:architectApp});if(second.error)throw second.error;expect(second.data).toMatchObject({formed:true,required_team_size:2,run_id:first.data?.run_id,project_active:false});
   const retry=await client.rpc('phase10_form_accepted_offer',{p_application_id:memberApp});if(retry.error)throw retry.error;expect(retry.data).toMatchObject({formed:false,already_formed:true,run_id:first.data?.run_id});
   const [{data:run,error:runError},{data:members,error:membersError},{data:apps,error:appsError},{data:offers,error:offersError}]=await Promise.all([client.from('project_runs').select('id,status,has_started,required_team_size').eq('project_id',teamProject),client.from('project_members').select('id,user_id,project_role_id,team_role,membership_status,project_run_id').eq('project_id',teamProject).order('user_id'),client.from('project_applications').select('id,status,project_run_id').eq('project_id',teamProject),client.from('project_offers').select('id,status,capacity_consumed_at,capacity_released_at').in('id',[memberOffer,architectOffer])]);if(runError)throw runError;if(membersError)throw membersError;if(appsError)throw appsError;if(offersError)throw offersError;expect(run).toHaveLength(1);expect(run?.[0]).toMatchObject({status:'forming',has_started:false,required_team_size:2});expect(members).toHaveLength(2);expect(members?.every(row=>row.membership_status==='waiting'&&row.project_run_id===run?.[0].id)).toBe(true);expect(apps?.every(row=>row.status==='waiting_for_team'&&row.project_run_id===run?.[0].id)).toBe(true);expect(offers).toHaveLength(2);expect(offers?.every(row=>row.status==='accepted'&&Boolean(row.capacity_consumed_at)&&row.capacity_released_at===null)).toBe(true);
   const memberMembership=members?.find(row=>row.user_id===member.id);const architectMembership=members?.find(row=>row.user_id===architect.id);expect(memberMembership).toBeTruthy();expect(architectMembership).toBeTruthy();const analyst=roles.find(row=>row.title==='Analyst');const engineer=roles.find(row=>row.title==='Engineer');expect(analyst).toBeTruthy();expect(engineer).toBeTruthy();
   const assignmentA=await client.rpc('phase10_assign_member_responsibility',{p_membership_id:memberMembership!.id,p_project_role_id:analyst!.id,p_make_project_lead:true,p_actor_user_id:null});if(assignmentA.error)throw assignmentA.error;expect(assignmentA.data).toMatchObject({team_role:'project_lead',project_active:false});
   const assignmentB=await client.rpc('phase10_assign_member_responsibility',{p_membership_id:architectMembership!.id,p_project_role_id:engineer!.id,p_make_project_lead:false,p_actor_user_id:null});if(assignmentB.error)throw assignmentB.error;expect(assignmentB.data).toMatchObject({team_role:'contributor',project_active:false});
   const secondLead=await client.rpc('phase10_assign_member_responsibility',{p_membership_id:architectMembership!.id,p_project_role_id:engineer!.id,p_make_project_lead:true,p_actor_user_id:null});expect(secondLead.error?.message).toContain('PROJECT_LEAD_ALREADY_ASSIGNED');
   const [{data:afterRun},{data:afterProject}]=await Promise.all([client.from('project_runs').select('status,has_started').eq('id',run![0].id).single(),client.from('projects').select('status').eq('id',teamProject).single()]);expect(afterRun).toMatchObject({status:'forming',has_started:false});expect(afterProject?.status).toBe('open');
 }finally{await cleanup(client,teamProject)}});

 test('ordinary authenticated member cannot execute Phase 10 formation or responsibility RPCs directly',async()=>{const client=db();const {member}=await identities();await seedProject(client);try{const appId=await seedApplication(client,member.id);await acceptOffer(client,appId,member.id);const user=createClient(required('E2E_SUPABASE_URL'),required('E2E_SUPABASE_ANON_KEY'),{auth:{persistSession:false,autoRefreshToken:false}});const signed=await user.auth.signInWithPassword({email:required('E2E_MEMBER_EMAIL'),password:required('E2E_MEMBER_PASSWORD')});if(signed.error)throw signed.error;const formation=await user.rpc('phase10_form_accepted_offer',{p_application_id:appId});expect(formation.error).toBeTruthy();const service=await client.rpc('phase10_form_accepted_offer',{p_application_id:appId});if(service.error)throw service.error;const responsibility=await user.rpc('phase10_assign_member_responsibility',{p_membership_id:service.data?.membership_id,p_project_role_id:null,p_make_project_lead:false,p_actor_user_id:null});expect(responsibility.error).toBeTruthy();await user.auth.signOut()}finally{await cleanup(client,teamProject)}});
});
