import {expect,test} from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';

const root=process.cwd();function read(file:string){return fs.readFileSync(path.join(root,file),'utf8')}
test.describe('Phase 18 recovery — operational collaboration UX',()=>{
 test('Mettelo Lab Team visibly mounts Grow the Team and all required destinations',()=>{const lab=read('components/MetteloLabPanel.tsx'),section=read('components/ProjectGrowTeamSection.tsx');expect(lab).toContain("import ProjectGrowTeamSection from '@/components/ProjectGrowTeamSection'");expect(lab).toContain('<ProjectGrowTeamSection');expect(lab.indexOf('<ProjectGrowTeamSection')).toBeGreaterThan(lab.indexOf('id="team"'));for(const text of ['CURRENT TEAM','RESPONSIBILITIES','CAPACITY','RECRUITMENT STATE','GROW THE TEAM'])expect(section).toContain(text);});
 test('Grow the Team never silently disappears and exposes every explicit state',()=>{const section=read('components/ProjectGrowTeamSection.tsx');expect(section).not.toContain('if(!policy)return null');for(const text of ['AVAILABLE','FULL','JOINING CLOSED','RECRUITMENT CLOSED','NOT AUTHORIZED','COMPLETION FREEZE','CONFIGURATION ERROR'])expect(section).toContain(text);});
 test('capacity snapshot uses canonical minimum target maximum and joining state',()=>{const section=read('components/ProjectGrowTeamSection.tsx'),actions=read('components/ProjectGrowTeamActions.tsx');for(const text of ['min_team_size','target_team_size','max_team_size','phase9_project_run_capacity','teamMinimum','teamTarget','teamMaximum','Open places','Recruitment','Joining until'])expect(section+actions).toContain(text);});
 test('direct Find People works without a public collaboration need and stays exact-run scoped',()=>{const actions=read('components/ProjectGrowTeamActions.tsx'),page=read('app/member/find-collaborators/page.tsx'),discovery=read('components/MemberCollaboratorDiscovery.tsx'),route=read('app/api/member-collaboration-invitations/route.ts');for(const text of ['Find people on Mettelo','project_run_id','Direct private team request','Send team request','direct_invite','projectRunId'])expect(actions+page+discovery+route).toContain(text);expect(actions).not.toContain('Post a collaborator need first.');expect(discovery).toContain('No membership was created');});
 test('direct team requests create only pending invitations and preserve canonical same-run admission',()=>{const route=read('app/api/member-collaboration-invitations/route.ts'),migration=read('supabase/migrations/20260912102000_grow_team_direct_member_requests.sql'),sameRun=read('supabase/migrations/20260908102000_project_experience_phase_18_same_run_interest.sql');expect(route).toContain("status:'pending'");expect(route).not.toContain("from('project_members').insert");expect(route).toContain('interest_target');expect(migration).toContain("source='direct_invite'");expect(migration).toContain("source<>'direct_invite'");expect(sameRun).toContain('new.project_run_id:=need.project_run_id');});
 test('project recruitment policy authorizes lead/member independently on UI and server',()=>{const section=read('components/ProjectGrowTeamSection.tsx'),needs=read('app/api/collaboration-needs/route.ts'),invites=read('app/api/member-collaboration-invitations/route.ts');for(const text of ['project_lead_invites_enabled','team_member_invites_enabled'])expect(section+needs+invites).toContain(text);expect(needs).not.toContain('activeCount===1');});
 test('collaborator-needed form publishes governed same-run opportunity with canonical context',()=>{const actions=read('components/ProjectGrowTeamActions.tsx'),route=read('app/api/collaboration-needs/route.ts');for(const text of ['Post collaborator needed','Responsibility needed','Target role','Relevant capabilities','Commitment','Joining deadline','Current team','Optional short team message','project_run_id','target_role_catalogue_id','target_domain_id','capability_ids'])expect(actions+route).toContain(text);for(const text of ['recruitment_open','late_joining_enabled','late_joining_cutoff_at','phase9_project_run_capacity'])expect(route).toContain(text);});
 test('Find a Team and Member Home are fed from canonical collaboration opportunities',()=>{const find=read('app/member/find-a-team/page.tsx'),home=read('components/MemberHomeCollaborationOpportunities.tsx'),publicRoute=read('app/api/public/collaboration-opportunities/route.ts');for(const text of ['project_collaboration_needs','COLLABORATOR NEEDED','I’m interested'])expect(find+publicRoute).toContain(text);expect(home).toContain('/member/find-a-team');expect(home).not.toContain('if(!items.length)return null');});
 test('private direct invitation contexts can never leak into public opportunities',()=>{const route=read('app/api/public/collaboration-opportunities/route.ts'),migration=read('supabase/migrations/20260912102000_grow_team_direct_member_requests.sql');expect(route).toContain("neq('source','direct_invite')");expect(route).toContain("if(need.source==='direct_invite')return null");expect(migration).toContain("source<>'direct_invite'");});
 test('sharing exposes LinkedIn X WhatsApp copy and native fallback using canonical public URL',()=>{const actions=read('components/ProjectGrowTeamActions.tsx'),sharing=read('components/CollaborationShareActions.tsx');for(const text of ['Share to find collaborators','/collaborate/','LinkedIn','>X<','WhatsApp','Copy link','navigator.share','More / native share'])expect(actions+sharing).toContain(text);expect(actions).toContain('Private Lab information is not included');});
 test('full joining cutoff and Phase 19 freeze disable recruitment server-side as well as in UI',()=>{const section=read('components/ProjectGrowTeamSection.tsx'),needs=read('app/api/collaboration-needs/route.ts'),invites=read('app/api/member-collaboration-invitations/route.ts');for(const text of ["run.status==='review'","stateLabel='COMPLETION FREEZE'",'TEAM FULL','JOINING CLOSED','RECRUITMENT CLOSED'])expect(section).toContain(text);for(const text of ['recruitment_open','late_joining_enabled','late_joining_cutoff_at','capacity_available'])expect(needs+invites).toContain(text);});
 test('operational controls retain mobile keyboard and screen-reader contracts',()=>{const actions=read('components/ProjectGrowTeamActions.tsx'),discovery=read('components/MemberCollaboratorDiscovery.tsx');expect(actions).toContain('min-height:44px');expect(actions).toContain(':focus-visible');expect(actions).toContain('@media(max-width:640px)');expect(actions).toContain('aria-live="polite"');expect(actions).toContain('aria-label="Grow the team routes"');expect(discovery).toContain('min-height:44px');expect(discovery).toContain('@media(max-width:640px)');expect(discovery).toContain('aria-live="polite"');});
});
