import {createClient} from '@supabase/supabase-js';
import {expect,test,type Page} from '@playwright/test';
import {PROJECT_PARTICIPATION_TERMS_VERSION} from '../lib/project-participation-terms';

const projectId='00000000-0000-4000-8000-00000000a901';
const roleId='00000000-0000-4000-8000-00000000a902';
const unavailableRoleId='00000000-0000-4000-8000-00000000a999';
function required(name:string){const value=process.env[name]?.trim();if(!value)throw new Error(`${name} is required`);return value}
async function signIn(page:Page,email:string,password:string){await page.goto('/signin',{waitUntil:'networkidle'});const main=page.locator('#main-content');await main.locator('input[type="email"]').fill(email);await main.locator('input[type="password"]').fill(password);await main.getByRole('button',{name:'Sign in →'}).click();await page.waitForURL(url=>!url.pathname.startsWith('/signin'),{timeout:20_000})}
function serviceDb(){const url=required('E2E_SUPABASE_URL');if(!['127.0.0.1','localhost'].includes(new URL(url).hostname))throw new Error('Project application E2E refuses non-local Supabase hosts.');return createClient(url,required('E2E_SUPABASE_SERVICE_ROLE_KEY'),{auth:{persistSession:false,autoRefreshToken:false}})}
async function seed(){const db=serviceDb();const {data:users,error:userError}=await db.auth.admin.listUsers({page:1,perPage:1000});if(userError)throw userError;const member=users.users.find(user=>user.email===required('E2E_MEMBER_EMAIL'));if(!member)throw new Error('E2E member missing');await db.from('project_applications').delete().eq('project_id',projectId).eq('user_id',member.id);await db.from('project_members').delete().eq('project_id',projectId).eq('user_id',member.id);const draft=await db.from('projects').upsert({id:projectId,slug:'e2e-project-application-submit',title:'E2E Project Application Submission',summary:'Deterministic isolated project application submission fixture.',problem_statement:'Exercise authenticated member application storage and Admin review.',status:'draft',visibility:'private',project_type:'open',applications_open:false,team_size_threshold:3,project_type_review_required:false,weekly_commitment:'3-5 hours/week'},{onConflict:'id'});if(draft.error)throw draft.error;const role=await db.from('project_roles').upsert({id:roleId,project_id:projectId,title:'Data Analyst',discipline:'Data & AI',description:'E2E application role',skills:['SQL'],openings:3},{onConflict:'id'});if(role.error)throw role.error;const opened=await db.from('projects').update({status:'open',visibility:'public',applications_open:true}).eq('id',projectId);if(opened.error)throw opened.error;return{db,member}}
const validBody={project_id:projectId,project_role_id:roleId,availability:'Weekday evenings',leadership_interest:true,contribution_statement:'I can own the analysis, validate the data quality and communicate findings to the project team.',portfolio_url:'example.com/member-proof',terms_accepted:true,terms_version:PROJECT_PARTICIPATION_TERMS_VERSION};

test.describe('final project application submission',()=>{
  test('authenticated member stores canonical application and Admin can review it',async({page,browser})=>{const {db,member}=await seed();await signIn(page,required('E2E_MEMBER_EMAIL'),required('E2E_MEMBER_PASSWORD'));const response=await page.context().request.post('/api/project-applications',{data:validBody});expect(response.status()).toBe(200);const payload=await response.json();expect(payload).toMatchObject({ok:true,message:'Application submitted.'});const {data:stored,error}=await db.from('project_applications').select('id,project_id,project_role_id,user_id,status,availability,leadership_interest,contribution_statement,portfolio_url,terms_accepted_at,terms_version').eq('id',payload.application.id).single();expect(error).toBeNull();expect(stored).toMatchObject({project_id:projectId,project_role_id:roleId,user_id:member.id,status:'submitted',availability:'Weekday evenings',leadership_interest:true,terms_version:PROJECT_PARTICIPATION_TERMS_VERSION});expect(stored?.portfolio_url).toBe('https://example.com/member-proof');expect(stored?.terms_accepted_at).toBeTruthy();const duplicate=await page.context().request.post('/api/project-applications',{data:validBody});expect(duplicate.status()).toBe(200);expect(await duplicate.json()).toMatchObject({ok:true,already_submitted:true,message:'You already have an application for this project.'});
    const adminContext=await browser.newContext();const adminPage=await adminContext.newPage();await signIn(adminPage,required('E2E_ADMIN_EMAIL'),required('E2E_ADMIN_PASSWORD'));await adminPage.goto(`/admin/project-operations/applications?project=${projectId}`,{waitUntil:'networkidle'});await expect(adminPage.getByRole('heading',{level:1,name:/^Applications\b/i})).toBeVisible();await expect(adminPage.getByText('E2E Project Application Submission',{exact:true}).first()).toBeVisible();await expect(adminPage.getByText('Data Analyst',{exact:true}).first()).toBeVisible();await adminContext.close()});

  test('rejects invalid link and terms before insert without losing retryable application state',async({page})=>{const {db,member}=await seed();await signIn(page,required('E2E_MEMBER_EMAIL'),required('E2E_MEMBER_PASSWORD'));const invalid=await page.context().request.post('/api/project-applications',{data:{...validBody,portfolio_url:'javascript:alert(1)'}});expect(invalid.status()).toBe(400);expect(await invalid.json()).toMatchObject({code:'INVALID_PROFESSIONAL_LINK',field:'professional_link'});const terms=await page.context().request.post('/api/project-applications',{data:{...validBody,portfolio_url:null,terms_accepted:false}});expect(terms.status()).toBe(400);expect(await terms.json()).toMatchObject({code:'TERMS_REQUIRED'});const {count}=await db.from('project_applications').select('*',{count:'exact',head:true}).eq('project_id',projectId).eq('user_id',member.id);expect(count).toBe(0)});

  test('returns explicit role unavailable and closed-project errors',async({page})=>{const {db}=await seed();await signIn(page,required('E2E_MEMBER_EMAIL'),required('E2E_MEMBER_PASSWORD'));const unavailable=await page.context().request.post('/api/project-applications',{data:{...validBody,project_role_id:unavailableRoleId,portfolio_url:null}});expect(unavailable.status()).toBe(409);expect(await unavailable.json()).toMatchObject({code:'ROLE_UNAVAILABLE'});await db.from('projects').update({applications_open:false,status:'active'}).eq('id',projectId);const closed=await page.context().request.post('/api/project-applications',{data:{...validBody,portfolio_url:null}});expect(closed.status()).toBe(409);expect(await closed.json()).toMatchObject({code:'PROJECT_CLOSED'})});

  test('expired session returns actionable auth error',async({request})=>{const response=await request.post('/api/project-applications',{data:validBody});expect(response.status()).toBe(401);expect(await response.json()).toMatchObject({code:'AUTH_REQUIRED',error:'Your session has expired. Please sign in again.'})});
});
