import {createClient} from '@supabase/supabase-js';
import {expect,test} from '@playwright/test';
import {startProjectRun} from '../lib/project-start-service';

const teamProject='00000000-0000-4000-8000-00000000c901';
const soloProject='00000000-0000-4000-8000-00000000c902';
const flexibleProject='00000000-0000-4000-8000-00000000c903';
function required(name:string){const value=process.env[name]?.trim();if(!value)throw new Error(`${name} is required`);return value}
function db(){const url=required('E2E_SUPABASE_URL');if(!['127.0.0.1','localhost'].includes(new URL(url).hostname))throw new Error('Phase 9 participation tests refuse non-local Supabase hosts.');return createClient(url,required('E2E_SUPABASE_SERVICE_ROLE_KEY'),{auth:{persistSession:false,autoRefreshToken:false}})}
async function identities(){const client=db();const {data,error}=await client.auth.admin.listUsers({page:1,perPage:1000});if(error)throw error;const member=data.users.find(user=>user.email===required('E2E_MEMBER_EMAIL'));const architect=data.users.find(user=>user.email===required('E2E_ARCHITECT_EMAIL'));const admin=data.users.find(user=>user.email===required('E2E_ADMIN_EMAIL'));if(!member||!architect||!admin)throw new Error('Phase 9 requires disposable member, architect and Admin identities.');return{member,architect,admin}}
async function cleanup(client:ReturnType<typeof db>,projectId:string){const {data:runs}=await client.from('project_runs').select('id').eq('project_id',projectId);const runIds=(runs||[]).map(run=>run.id);if(runIds.length){await client.from('project_activity_log').delete().in('project_run_id',runIds);await client.from('project_members').delete().in('project_run_id',runIds)}await client.from('project_activity_log').delete().eq('project_id',projectId);await client.from('project_offers').delete().eq('project_id',projectId);await client.from('project_applications').delete().eq('project_id',projectId);await client.from('project_milestones').delete().eq('project_id',projectId);await client.from('project_success_criteria').delete().eq('project_id',projectId);await client.from('project_deliverables').delete().eq('project_id',projectId);await client.from('project_problem_briefs').delete().eq('project_id',projectId);await client.from('project_runs').delete().eq('project_id',projectId);await client.from('project_roles').delete().eq('project_id',projectId);await client.from('projects').delete().eq('id',projectId)}
async function seedProject(client:ReturnType<typeof db>,projectId:string,mode:'solo'|'team'|'flexible',min:number,target:number,max:number,admission:'auto'|'review_required'='review_required'){await cleanup(client,projectId);const {error}=await client.from('projects').insert({id:projectId,slug:`phase9-${projectId.slice(-4)}`,title:`Phase 9 ${mode}`,summary:'Disposable Phase 9 participation fixture.',problem_statement:'Validate Team Solo Flexible runtime participation, maximum capacity and late joining.',status:'draft',visibility:'private',project_type:'open',applications_open:false,team_size_threshold:min,min_team_size:min,target_team_size:target,max_team_size:max,participation_mode:mode,admission_mode:admission,auto_start_delay_minutes:admission==='auto'?360:360,late_joining_enabled:true});if(error)throw error}
async function seedRun(client:ReturnType<typeof db>,projectId:string,requiredSize=50){const {data,error}=await client.from('project_runs').insert({project_id:projectId,run_number:1,status:'forming',team_size_threshold:requiredSize,required_team_size:requiredSize,has_started:false,recruitment_open:true}).select('id,required_team_size,team_size_threshold,status,has_started,scheduled_start_at,start_ready_at').single();if(error||!data)throw error||new Error('Could not seed Phase 9 run.');return data}
async function addMember(client:ReturnType<typeof db>,projectId:string,runId:string,userId:string,roleId:string|null=null,teamRole='contributor'){return client.from('project_members').insert({project_id:projectId,project_run_id:runId,user_id:userId,project_role_id:roleId,team_role:teamRole,membership_status:'waiting'}).select('id').single()}
async function seedLabReady(client:ReturnType<typeof db>,projectId:string){const results=await Promise.all([client.from('project_problem_briefs').insert({project_id:projectId,context:'Phase 9 runtime readiness context.',stakeholder:'Phase 9 acceptance test',expected_outcome:'Canonical participation can start safely.'}),client.from('project_deliverables').insert({project_id:projectId,project_run_id:null,title:'Phase 9 deliverable',deliverable_type:'document',acceptance_criteria:'Participation runtime works.',is_required:true}),client.from('project_milestones').insert({project_id:projectId,project_run_id:null,title:'Phase 9 kickoff',status:'planned'})]);for(const result of results)if(result.error)throw result.error}

test.describe('Project Experience Phase 9 runtime participation',()=>{
  test('Team run uses minimum, not target, and target remains planning capacity',async()=>{const client=db();const {member,architect}=await identities();await seedProject(client,teamProject,'team',2,5,5);try{const run=await seedRun(client,teamProject,50);expect(run.required_team_size).toBe(2);expect(run.team_size_threshold).toBe(2);expect((await addMember(client,teamProject,run.id,member.id)).error).toBeNull();const below=await client.rpc('phase9_project_run_capacity',{p_project_id:teamProject,p_run_id:run.id});if(below.error)throw below.error;expect(below.data).toMatchObject({participation_mode:'team',minimum:2,target:5,maximum:5,occupied:1,reserved:0,ready:false,target_reached:false});expect((await addMember(client,teamProject,run.id,architect.id)).error).toBeNull();const ready=await client.rpc('phase9_project_run_capacity',{p_project_id:teamProject,p_run_id:run.id});if(ready.error)throw ready.error;expect(ready.data).toMatchObject({minimum:2,target:5,occupied:2,ready:true,target_reached:false,available:3})}finally{await cleanup(client,teamProject)}});

  test('AUTO Team schedules exactly once at minimum, retains timer for ordinary joins, invalidates below minimum, then creates a fresh six-hour window',async()=>{const client=db();const {member,architect,admin}=await identities();await seedProject(client,teamProject,'team',2,5,5,'auto');try{const run=await seedRun(client,teamProject,2);const first=await addMember(client,teamProject,run.id,member.id);expect(first.error).toBeNull();let {data:stored}=await client.from('project_runs').select('scheduled_start_at,start_ready_at').eq('id',run.id).single();expect(stored?.scheduled_start_at).toBeNull();expect(stored?.start_ready_at).toBeNull();const second=await addMember(client,teamProject,run.id,architect.id);expect(second.error).toBeNull();({data:stored}=await client.from('project_runs').select('scheduled_start_at,start_ready_at').eq('id',run.id).single());expect(stored?.start_ready_at).toBeTruthy();expect(stored?.scheduled_start_at).toBeTruthy();const firstSchedule=String(stored?.scheduled_start_at);const deltaMs=new Date(firstSchedule).getTime()-new Date(String(stored?.start_ready_at)).getTime();expect(deltaMs).toBe(6*60*60*1000);const third=await addMember(client,teamProject,run.id,admin.id);expect(third.error).toBeNull();const {data:afterThird}=await client.from('project_runs').select('scheduled_start_at').eq('id',run.id).single();expect(afterThird?.scheduled_start_at).toBe(firstSchedule);await client.from('project_members').delete().eq('id',third.data!.id);await client.from('project_members').delete().eq('id',second.data!.id);const {data:below}=await client.from('project_runs').select('scheduled_start_at,start_ready_at').eq('id',run.id).single();expect(below).toMatchObject({scheduled_start_at:null,start_ready_at:null});const restored=await addMember(client,teamProject,run.id,architect.id);expect(restored.error).toBeNull();const {data:rearmed}=await client.from('project_runs').select('scheduled_start_at,start_ready_at').eq('id',run.id).single();expect(rearmed?.scheduled_start_at).toBeTruthy();expect(rearmed?.scheduled_start_at).not.toBe(firstSchedule);const rearmDelta=new Date(String(rearmed?.scheduled_start_at)).getTime()-new Date(String(rearmed?.start_ready_at)).getTime();expect(rearmDelta).toBe(6*60*60*1000)}finally{await cleanup(client,teamProject)}});

  test('Solo run normalizes to one, starts with one, and maximum is enforced at membership table',async()=>{const client=db();const {member,architect}=await identities();await seedProject(client,soloProject,'solo',1,1,1);try{const run=await seedRun(client,soloProject,10);expect(run.required_team_size).toBe(1);expect(run.team_size_threshold).toBe(1);await seedLabReady(client,soloProject);expect((await addMember(client,soloProject,run.id,member.id)).error).toBeNull();const capacity=await client.rpc('phase9_project_run_capacity',{p_project_id:soloProject,p_run_id:run.id});if(capacity.error)throw capacity.error;expect(capacity.data).toMatchObject({participation_mode:'solo',minimum:1,target:1,maximum:1,occupied:1,ready:true,capacity_available:false});const over=await addMember(client,soloProject,run.id,architect.id);expect(over.error?.message).toContain('PARTICIPATION_CAPACITY_FULL');const started=await startProjectRun({db:client,projectId:soloProject,runId:run.id,source:'manual'});expect(started).toMatchObject({started:true,filled:1,requiredTeamSize:1});const {data:storedRun}=await client.from('project_runs').select('status,has_started,required_team_size').eq('id',run.id).single();expect(storedRun).toMatchObject({status:'active',has_started:true,required_team_size:1})}finally{await cleanup(client,soloProject)}});

  test('Flexible Solo/Either geometry can use one while configured collaborative minimum remains two',async()=>{const client=db();const {member,architect,admin}=await identities();await seedProject(client,flexibleProject,'flexible',2,3,3);try{const independentRun=await seedRun(client,flexibleProject,1);expect(independentRun.required_team_size).toBe(1);await seedLabReady(client,flexibleProject);expect((await addMember(client,flexibleProject,independentRun.id,member.id)).error).toBeNull();const started=await startProjectRun({db:client,projectId:flexibleProject,runId:independentRun.id,source:'manual'});expect(started).toMatchObject({started:true,filled:1,requiredTeamSize:1});let capacity=await client.rpc('phase9_project_run_capacity',{p_project_id:flexibleProject,p_run_id:independentRun.id});if(capacity.error)throw capacity.error;expect(capacity.data).toMatchObject({participation_mode:'flexible',minimum:1,target:3,maximum:3,occupied:1,ready:true,capacity_available:true,late_join_allowed:true});const joined=await client.from('project_members').insert({project_id:flexibleProject,project_run_id:independentRun.id,user_id:architect.id,project_role_id:null,team_role:'contributor',membership_status:'active',activated_at:new Date().toISOString()});expect(joined.error).toBeNull();const joined2=await client.from('project_members').insert({project_id:flexibleProject,project_run_id:independentRun.id,user_id:admin.id,project_role_id:null,team_role:'contributor',membership_status:'active',activated_at:new Date().toISOString()});expect(joined2.error).toBeNull();capacity=await client.rpc('phase9_project_run_capacity',{p_project_id:flexibleProject,p_run_id:independentRun.id});if(capacity.error)throw capacity.error;expect(capacity.data).toMatchObject({occupied:3,target_reached:true,capacity_available:false,late_join_allowed:false})}finally{await cleanup(client,flexibleProject)}});

  test('Flexible Team preference uses configured team minimum rather than independent threshold',async()=>{const client=db();const {member,architect}=await identities();await seedProject(client,flexibleProject,'flexible',2,5,5);try{const teamRun=await seedRun(client,flexibleProject,2);expect(teamRun.required_team_size).toBe(2);expect((await addMember(client,flexibleProject,teamRun.id,member.id)).error).toBeNull();let capacity=await client.rpc('phase9_project_run_capacity',{p_project_id:flexibleProject,p_run_id:teamRun.id});if(capacity.error)throw capacity.error;expect(capacity.data).toMatchObject({minimum:2,occupied:1,ready:false,target:5});expect((await addMember(client,flexibleProject,teamRun.id,architect.id)).error).toBeNull();capacity=await client.rpc('phase9_project_run_capacity',{p_project_id:flexibleProject,p_run_id:teamRun.id});if(capacity.error)throw capacity.error;expect(capacity.data).toMatchObject({minimum:2,occupied:2,ready:true,target_reached:false})}finally{await cleanup(client,flexibleProject)}});

  test('late-join capacity and cutoff remain server-authoritative on the same active run',async()=>{const client=db();const {member,architect}=await identities();await seedProject(client,flexibleProject,'flexible',2,2,2);try{const run=await seedRun(client,flexibleProject,1);await seedLabReady(client,flexibleProject);expect((await addMember(client,flexibleProject,run.id,member.id)).error).toBeNull();expect((await startProjectRun({db:client,projectId:flexibleProject,runId:run.id,source:'manual'})).started).toBe(true);let capacity=await client.rpc('phase9_project_run_capacity',{p_project_id:flexibleProject,p_run_id:run.id});if(capacity.error)throw capacity.error;expect(capacity.data).toMatchObject({late_join_allowed:true,run_id:run.id});expect((await client.from('project_members').insert({project_id:flexibleProject,project_run_id:run.id,user_id:architect.id,team_role:'contributor',membership_status:'active',activated_at:new Date().toISOString()})).error).toBeNull();capacity=await client.rpc('phase9_project_run_capacity',{p_project_id:flexibleProject,p_run_id:run.id});if(capacity.error)throw capacity.error;expect(capacity.data).toMatchObject({occupied:2,capacity_available:false,late_join_allowed:false});await client.from('projects').update({max_team_size:3,target_team_size:2,late_joining_cutoff_at:new Date(Date.now()-60_000).toISOString()}).eq('id',flexibleProject);capacity=await client.rpc('phase9_project_run_capacity',{p_project_id:flexibleProject,p_run_id:run.id});if(capacity.error)throw capacity.error;expect(capacity.data).toMatchObject({maximum:3,capacity_available:true,late_join_allowed:false})}finally{await cleanup(client,flexibleProject)}});

  test('duplicate live membership is rejected and started run threshold history remains intact after configuration change',async()=>{const client=db();const {member}=await identities();await seedProject(client,flexibleProject,'flexible',2,3,3);try{const run=await seedRun(client,flexibleProject,1);expect((await addMember(client,flexibleProject,run.id,member.id)).error).toBeNull();const duplicate=await addMember(client,flexibleProject,run.id,member.id);expect(duplicate.error).toBeTruthy();await client.from('project_runs').update({status:'active',has_started:true,started_at:new Date().toISOString()}).eq('id',run.id);await client.from('projects').update({participation_mode:'team',min_team_size:2,target_team_size:3,max_team_size:3,team_size_threshold:2}).eq('id',flexibleProject);const {data:historic}=await client.from('project_runs').select('required_team_size,team_size_threshold,has_started').eq('id',run.id).single();expect(historic).toMatchObject({required_team_size:1,team_size_threshold:1,has_started:true})}finally{await cleanup(client,flexibleProject)}});
});