import {createClient} from '@supabase/supabase-js';
import {expect,test} from '@playwright/test';
import {PROJECT_PARTICIPATION_TERMS_VERSION} from '../lib/project-participation-terms';

const soloProject='00000000-0000-4000-8000-00000000b601';
const teamProject='00000000-0000-4000-8000-00000000b602';
const lateProject='00000000-0000-4000-8000-00000000b603';
function required(name:string){const value=process.env[name]?.trim();if(!value)throw new Error(`${name} is required`);return value}
function db(){const url=required('E2E_SUPABASE_URL');if(!['127.0.0.1','localhost'].includes(new URL(url).hostname))throw new Error('Phase 6 AUTO journey tests refuse non-local Supabase hosts.');return createClient(url,required('E2E_SUPABASE_SERVICE_ROLE_KEY'),{auth:{persistSession:false,autoRefreshToken:false}})}
async function users(){const client=db();const {data,error}=await client.auth.admin.listUsers({page:1,perPage:1000});if(error)throw error;const member=data.users.find(user=>user.email===required('E2E_MEMBER_EMAIL'));const architect=data.users.find(user=>user.email===required('E2E_ARCHITECT_EMAIL'));const admin=data.users.find(user=>user.email===required('E2E_ADMIN_EMAIL'));if(!member||!architect||!admin)throw new Error('Phase 6 AUTO journeys require disposable member, architect and Admin identities.');return{member,architect,admin}}
async function cleanup(client:ReturnType<typeof db>,projectId:string){const {data:runs}=await client.from('project_runs').select('id').eq('project_id',projectId);const runIds=(runs||[]).map(run=>run.id);if(runIds.length){await client.from('project_activity_log').delete().in('project_run_id',runIds);await client.from('project_members').delete().in('project_run_id',runIds)}await client.from('project_activity_log').delete().eq('project_id',projectId);await client.from('project_applications').delete().eq('project_id',projectId);await client.from('project_runs').delete().eq('project_id',projectId);await client.from('project_roles').delete().eq('project_id',projectId);await client.from('projects').delete().eq('id',projectId)}
async function seedProject(client:ReturnType<typeof db>,projectId:string,mode:'solo'|'team'|'flexible',min:number,target:number,max:number){await cleanup(client,projectId);const draft=await client.from('projects').insert({id:projectId,slug:`phase6-auto-${projectId.slice(-4)}`,title:`Phase 6 AUTO ${mode}`,summary:'Disposable isolated Phase 6 automatic admission fixture.',problem_statement:'Validate automatic qualification, run formation, scheduling, late joining and capacity without Admin review.',status:'draft',visibility:'private',project_type:'open',applications_open:false,team_size_threshold:min,min_team_size:min,target_team_size:target,max_team_size:max,participation_mode:mode,admission_mode:'auto',auto_start_delay_minutes:120,late_joining_enabled:true,project_sharing_enabled:true,member_invites_enabled:false});if(draft.error)throw draft.error;const role=await client.from('project_roles').insert({project_id:projectId,title:'Contributor',discipline:'Data & AI',description:'Capacity fixture only; AUTO initial interest remains role-neutral.',skills:['Collaboration'],openings:max});if(role.error)throw role.error;const opened=await client.from('projects').update({status:'open',visibility:'public',applications_open:true}).eq('id',projectId);if(opened.error)throw opened.error}
async function interest(client:ReturnType<typeof db>,projectId:string,userId:string){const now=new Date().toISOString();const {data,error}=await client.from('project_applications').insert({project_id:projectId,user_id:userId,project_role_id:null,status:'submitted',application_kind:'interest',contribution_statement:'Disposable Phase 6 AUTO journey interest with enough detail for the canonical request contract.',terms_accepted_at:now,terms_version:PROJECT_PARTICIPATION_TERMS_VERSION,submitted_at:now}).select('id').single();if(error||!data)throw error||new Error('Could not seed Phase 6 interest.');return data.id}

test.describe('Project Experience Phase 6 AUTO backend journeys',()=>{
 test('AUTO SOLO creates one canonical run/membership and durable start schedule idempotently',async()=>{const client=db();const {member}=await users();await seedProject(client,soloProject,'solo',1,1,2);try{const applicationId=await interest(client,soloProject,member.id);const first=await client.rpc('phase6_auto_admit_interest',{p_application_id:applicationId,p_participation_preference:null});expect(first.error).toBeNull();expect(first.data).toMatchObject({decision:'auto_qualified',team_ready:true,required_team_size:1,participation_preference:'solo'});expect(first.data?.scheduled_start_at).toBeTruthy();const second=await client.rpc('phase6_auto_admit_interest',{p_application_id:applicationId,p_participation_preference:null});expect(second.error).toBeNull();expect(second.data).toMatchObject({decision:'auto_qualified',already_admitted:true,run_id:first.data?.run_id});const [{count:members},{count:runs},{data:run}]=await Promise.all([client.from('project_members').select('id',{count:'exact',head:true}).eq('project_id',soloProject).eq('user_id',member.id),client.from('project_runs').select('id',{count:'exact',head:true}).eq('project_id',soloProject),client.from('project_runs').select('id,status,has_started,scheduled_start_at').eq('id',first.data?.run_id).single()]);expect(members).toBe(1);expect(runs).toBe(1);expect(run?.has_started).toBe(false);expect(run?.status).toBe('forming');expect(run?.scheduled_start_at).toBeTruthy()}finally{await cleanup(client,soloProject)}});

 test('AUTO TEAM schedules when minimum is reached and does not wait for target',async()=>{const client=db();const {member,architect}=await users();await seedProject(client,teamProject,'team',2,5,5);try{const firstId=await interest(client,teamProject,member.id);const first=await client.rpc('phase6_auto_admit_interest',{p_application_id:firstId,p_participation_preference:null});expect(first.error).toBeNull();expect(first.data).toMatchObject({decision:'auto_qualified',filled:1,required_team_size:2,maximum_team_size:5,team_ready:false});expect(first.data?.scheduled_start_at).toBeNull();const secondId=await interest(client,teamProject,architect.id);const second=await client.rpc('phase6_auto_admit_interest',{p_application_id:secondId,p_participation_preference:null});expect(second.error).toBeNull();expect(second.data).toMatchObject({decision:'auto_qualified',run_id:first.data?.run_id,filled:2,required_team_size:2,maximum_team_size:5,team_ready:true});expect(second.data?.scheduled_start_at).toBeTruthy();const {count}=await client.from('project_runs').select('id',{count:'exact',head:true}).eq('project_id',teamProject);expect(count).toBe(1)}finally{await cleanup(client,teamProject)}});

 test('late member joins same active run, maximum closes recruitment, cutoff blocks new run',async()=>{const client=db();const {member,architect,admin}=await users();await seedProject(client,lateProject,'flexible',1,2,2);try{const firstId=await interest(client,lateProject,member.id);const first=await client.rpc('phase6_auto_admit_interest',{p_application_id:firstId,p_participation_preference:'solo'});expect(first.error).toBeNull();const runId=first.data?.run_id as string;const now=new Date().toISOString();await client.from('project_runs').update({status:'active',has_started:true,started_at:now,kickoff_at:now,scheduled_start_at:null}).eq('id',runId);await client.from('project_members').update({membership_status:'active',activated_at:now}).eq('project_run_id',runId);const secondId=await interest(client,lateProject,architect.id);const second=await client.rpc('phase6_auto_admit_interest',{p_application_id:secondId,p_participation_preference:'either'});expect(second.error).toBeNull();expect(second.data).toMatchObject({decision:'auto_qualified',late_join:true,run_id:runId,filled:2,maximum_team_size:2,recruitment_open:false});const {data:run}=await client.from('project_runs').select('recruitment_open,recruitment_closed_at').eq('id',runId).single();expect(run?.recruitment_open).toBe(false);expect(run?.recruitment_closed_at).toBeTruthy();const thirdId=await interest(client,lateProject,admin.id);const full=await client.rpc('phase6_auto_admit_interest',{p_application_id:thirdId,p_participation_preference:'team'});expect(full.error?.message).toContain('CAPACITY_FULL');await client.from('project_applications').delete().eq('id',thirdId);await client.from('projects').update({max_team_size:3,late_joining_cutoff_at:new Date(Date.now()-60_000).toISOString()}).eq('id',lateProject);await client.from('project_runs').update({recruitment_open:true,recruitment_closed_at:null}).eq('id',runId);const cutoffId=await interest(client,lateProject,admin.id);const cutoff=await client.rpc('phase6_auto_admit_interest',{p_application_id:cutoffId,p_participation_preference:'team'});expect(cutoff.error?.message).toContain('LATE_JOINING_CLOSED');const {count:runs}=await client.from('project_runs').select('id',{count:'exact',head:true}).eq('project_id',lateProject);expect(runs).toBe(1)}finally{await cleanup(client,lateProject)}});
});
