import {expect,test} from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';

const root=process.cwd();function read(file:string){return fs.readFileSync(path.join(root,file),'utf8')}
test.describe('Phase 18 recovery — operational collaboration UX',()=>{
 test('Mettelo Lab Team visibly mounts Grow the Team',()=>{const lab=read('components/MetteloLabPanel.tsx');expect(lab).toContain("import ProjectGrowTeamSection from '@/components/ProjectGrowTeamSection'");expect(lab).toContain('<ProjectGrowTeamSection');expect(lab.indexOf('<ProjectGrowTeamSection')).toBeGreaterThan(lab.indexOf('id="team"'));});
 test('Grow the Team exposes all three governed routes without direct membership creation',()=>{const source=read('components/ProjectGrowTeamSection.tsx')+read('components/ProjectGrowTeamActions.tsx');for(const text of ['GROW THE TEAM','Find people on Mettelo','Post collaborator needed','Share to find collaborators','/api/collaboration-needs','/member/find-collaborators','/collaborate/'])expect(source).toContain(text);for(const forbidden of ["from('project_members').insert","from('project_runs').insert","from('project_applications').insert"])expect(source).not.toContain(forbidden);});
 test('Team shows capacity, recruitment, joining and current need from canonical state',()=>{const section=read('components/ProjectGrowTeamSection.tsx'),actions=read('components/ProjectGrowTeamActions.tsx');for(const text of ['phase9_project_run_capacity','recruitment_open','late_joining_enabled','late_joining_cutoff_at','Team','Open places','Recruitment','Joining','Current need','No current collaboration need'])expect(section+actions).toContain(text);});
 test('Phase 19 final review freezes ordinary recruitment actions',()=>{const section=read('components/ProjectGrowTeamSection.tsx');for(const text of ["run.status==='review'","stateLabel='FINAL REVIEW'",'TEAM FULL','JOINING CLOSED','RECRUITMENT CLOSED'])expect(section).toContain(text);});
 test('collaboration need form uses canonical role, domain, capability, commitment and cutoff context',()=>{const actions=read('components/ProjectGrowTeamActions.tsx');for(const text of ['Responsibility needed','Target role','Relevant capabilities','Commitment','Joining cutoff','Optional message','target_role_catalogue_id','target_domain_id','capability_ids','weekly_commitment'])expect(actions).toContain(text);});
 test('first unassigned Phase 10 responsibility is suggested and preserves its canonical source role',()=>{const section=read('components/ProjectGrowTeamSection.tsx'),actions=read('components/ProjectGrowTeamActions.tsx');for(const text of ["from('project_roles')","from('project_member_responsibilities')","assignment_status','suggestedResponsibility','suggestedSourceProjectRoleId','source_project_role_id','first unassigned Phase 10 responsibility'])expect(section+actions).toContain(text);});
 test('member discovery starts with need-aware recommendations and dedicated filters',()=>{const discovery=read('components/MemberCollaboratorDiscovery.tsx');for(const text of ['recommended discoverable member','Role','Capability','Domain','Availability','Commitment','Send team request','Team request context'])expect(discovery).toContain(text);expect(discovery).toContain("void runSearch(seed,true)");});
 test('member invitation preview is privacy-safe and shows complete governed context before send',()=>{const page=read('app/member/find-collaborators/page.tsx'),discovery=read('components/MemberCollaboratorDiscovery.tsx'),route=read('app/api/member-collaboration-invitations/route.ts');for(const text of ['projectTitle','teamOccupied','teamMaximum','openPlaces','runStatus','Review member profile','Invitation expires','Admission · governed same-run revalidation required','Inviting someone does not add them to your team'])expect(page+discovery).toContain(text);for(const text of ['7*24*60*60*1000','expires_at','phase9_project_run_capacity','membership_status','recruitment_open'])expect(route).toContain(text);});
 test('Find a Team cards show team size, stage, places and governed actions',()=>{const page=read('app/member/find-a-team/page.tsx');for(const text of ['COLLABORATOR NEEDED','Team','Open places','Project stage','View project','I’m interested','occupied','maximum'])expect(page).toContain(text);});
 test('public sharing supports LinkedIn, X, WhatsApp, copy and native device share end to end',()=>{const sharing=read('components/CollaborationShareActions.tsx'),route=read('app/api/collaboration-analytics/route.ts'),migration=read('supabase/migrations/20260911175500_phase18_native_share_analytics.sql');for(const text of ['LinkedIn','WhatsApp','Copy link','navigator.share','Share on device','share_native'])expect(sharing).toContain(text);expect(route).toContain('share_native');expect(migration).toContain('share_native');expect(migration).toContain('project_collaboration_analytics_events_event_type_check');});
 test('Grow Team share copy contains project, role or need, capabilities, commitment, stage and open places',()=>{const actions=read('components/ProjectGrowTeamActions.tsx');for(const text of ['projectTitle','capabilityLabels','weeklyCommitment','Project stage','openPlaces','View the collaboration opportunity on Mettelo'])expect(actions).toContain(text);});
 test('Member Home never hides Find a Team merely because recommendations are empty',()=>{const home=read('components/MemberHomeCollaborationOpportunities.tsx');expect(home).toContain('BrowseCollaborationFallback');expect(home).toContain('Browse collaboration opportunities');expect(home).toContain('/member/find-a-team');expect(home).not.toContain('if(!items.length)return null');expect(home).not.toContain('if(!db)return null');});
 test('operational controls retain keyboard, status and mobile contracts',()=>{const actions=read('components/ProjectGrowTeamActions.tsx'),discovery=read('components/MemberCollaboratorDiscovery.tsx');expect(actions).toContain('min-height:44px');expect(actions).toContain(':focus-visible');expect(actions).toContain('@media(max-width:640px)');expect(actions).toContain('aria-live="polite"');expect(actions).toContain('aria-label="Grow the team routes"');expect(discovery).toContain('min-height:44px');expect(discovery).toContain('@media(max-width:640px)');});
});
