import {createClient} from '@supabase/supabase-js';
import {expect,test} from '@playwright/test';
import {startProjectRun} from '../lib/project-start-service';
import {makeGovernedProjectPublicationReady} from './helpers/governed-project-fixture';

const CAPACITY_PROJECT='00000000-0000-4000-8000-000000004401';
const FORMATION_PROJECT='00000000-0000-4000-8000-000000004402';
const START_PROJECT='00000000-0000-4000-8000-000000004403';
const LEAVE_START_PROJECT='00000000-0000-4000-8000-000000004404';
const CAPABILITY='00000000-0000-4000-8000-0000000044c1';

function required(name:string){const value=process.env[name]?.trim();if(!value)throw new Error(`${name} is required`);return value}
function db(){const url=required('E2E_SUPABASE_URL');if(!['127.0.0.1','localhost'].includes(new URL(url).hostname))throw new Error('Workstream 4 race tests refuse non-local Supabase hosts.');return createClient(url,required('E2E_SUPABASE_SERVICE_ROLE_KEY'),{auth:{persistSession:false,autoRefreshToken:false}})}
async function identities(){const client=db();const {data,error}=await client.auth.admin.listUsers({page:1,perPage:1000});if(error)throw error;const member=data.users.find(user=>user.email===required('E2E_MEMBER_EMAIL'));const architect=data.users.find(user=>user.email===required('E2E_ARCHITECT_EMAIL'));const admin=data.users.find(user=>user.email===required('E2E_ADMIN_EMAIL'));if(!member||!architect||!admin)throw new Error('Workstream 4 race tests require disposable member, architect and admin identities.');return{member,architect,admin}}
async function cleanup(client:ReturnType<typeof db>,projectId:string){const {data:runs}=await client.from('project_runs').select('id').eq('project_id',projectId);const runIds=(runs||[]).map(row=>row.id);await client.from('project_member_responsibilities').delete().eq('project_id',projectId);await client.from('project_activity_log').delete().eq('project_id',projectId);await client.from('project_members').delete().eq('project_id',projectId);await client.from('project_offers').delete().eq('project_id',projectId);await client.from('project_applications').delete().eq('project_id',projectId);await client.from('project_milestones').delete().eq('project_id',projectId);await client.from('project_success_criteria').delete().eq('project_id',projectId);await client.from('project_deliverables').delete().eq('project_id',projectId);await client.from('project_problem_briefs').delete().eq('project_id',projectId);await client.from('project_capabilities').delete().eq('project_id',projectId);if(runIds.length)await client.from('project_runs').delete().in('id',runIds);await client.from('project_roles').delete().eq('project_id',projectId);await client.from('projects').delete().eq('id',projectId)}
async function seedProject(client:ReturnType<typeof db>,projectId:string,{mode,min,target,max,admission='auto'}:{mode:'solo'|'team'|'flexible';min:number;target:number;max:number;admission?:'auto'|'review_required'}){await cleanup(client,projectId);const created=await client.from('projects').insert({id:projectId,slug:`ws4-race-${projectId.slice(-4)}`,title:`Workstream 4 race ${projectId.slice(-4)}`,summary:'Disposable Workstream 4 concurrency fixture.',problem_statement:'Prove canonical project participation and start authority remains consistent under concurrent writes.',status:'draft',visibility:'private',project_type:'open',applications_open:false,participation_mode:mode,team_size_threshold:min,min_team_size:min,target_team_size:target,max_team_size:max,admission_mode:admission,auto_start_delay_minutes:360,late_joining_enabled:true});if(created.error)throw created.error;const roles=await client.from('project_roles').insert([{project_id:projectId,title:'Analyst',discipline:'Data & AI',description:'Workstream 4 race analysis responsibility.',skills:['Analysis'],responsibilities:['Analysis','Documentation'],openings:max},{project_id:projectId,title:'Engineer',discipline:'Data & AI',description:'Workstream 4 race engineering responsibility.',skills:['Engineering'],responsibilities:['Engineering','Documentation'],openings:max}]).select('id,title');if(roles.error)throw roles.error;await makeGovernedProjectPublicationReady(client,projectId);const opened=await client.from('projects').update({status:'open',visibility:'public',applications_open:true}).eq('id',projectId);if(opened.error)throw opened.error;return roles.data||[]}
async function seedRun(client:ReturnType<typeof db>,projectId:string,requiredSize:number){const run=await client.from('project_runs').insert({project_id:projectId,run_number:1,status:'forming',team_size_threshold:requiredSize,required_team_size:requiredSize,has_started:false,recruitment_open:true}).select('id').single();if(run.error||!run.data)throw run.error||new Error('Workstream 4 race run missing.');return run.data.id as string}
async function addMember(client:ReturnType<typeof db>,projectId:string,runId:string,userId:string){return client.from('project_members').insert({project_id:projectId,project_run_id:runId,user_id:userId,team_role:'contributor',membership_status:'waiting'}).select('id').single()}
async function seedReadiness(client:ReturnType<typeof db>,projectId:string,actorUserId:string){const capability=await client.from('capabilities').upsert({id:CAPABILITY,slug:'ws4-race-readiness',name:'Workstream 4 race readiness',capability_type:'professional',description:'Disposable capability for Workstream 4 start race readiness.',is_active:true},{onConflict:'id'});if(capability.error)throw capability.error;const link=await client.from('project_capabilities').upsert({project_id:projectId,capability_id:CAPABILITY,importance:'core',evidence_expected:true},{onConflict:'project_id,capability_id'});if(link.error)throw link.error;const results=await Promise.all([client.from('project_problem_briefs').insert({project_id:projectId,context:'Workstream 4 concurrency readiness context.',stakeholder:'Workstream 4 acceptance',expected_outcome:'One canonical activation.',primary_use_case:'Verify concurrent project start authority.',primary_objective:'Prevent duplicate or partial activation.',key_questions:['Can competing start and membership transitions remain consistent?'],in_scope:['Run readiness, activation and membership concurrency'],out_of_scope:['Alternative run systems']}),client.from('project_deliverables').insert({project_id:projectId,project_run_id:null,canonical_item_key:`ws4-race-${projectId.slice(-4)}`,title:'Workstream 4 race deliverable',deliverable_type:'document',acceptance_criteria:'Canonical activation remains singular.',is_required:true,created_by:actorUserId}),client.from('project_success_criteria').insert({project_id:projectId,title:'Exactly one canonical activation',is_required:true}),client.from('project_milestones').insert({project_id:projectId,project_run_id:null,title:'Workstream 4 kickoff',status:'planned',is_required:true})]);for(const result of results)if(result.error)throw result.error}
async function makeDue(client:ReturnType<typeof db>,runId:string){const reconciled=await client.rpc('phase9_reconcile_run_participation',{p_run_id:runId});if(reconciled.error)throw reconciled.error;const dueAt=new Date(Date.now()-1_000);const readyAt=new Date(dueAt.getTime()-6*60*60*1000);const updated=await client.from('project_runs').update({start_ready_at:readyAt.toISOString(),start_scheduled_at:readyAt.toISOString(),scheduled_start_at:dueAt.toISOString()}).eq('id',runId).eq('has_started',false);if(updated.error)throw updated.error}

 test.describe('Workstream 4 mandatory concurrency acceptance',()=>{
  test('two contenders for the last place produce exactly one canonical membership',async()=>{const client=db();const {member,architect}=await identities();await seedProject(client,CAPACITY_PROJECT,{mode:'solo',min:1,target:1,max:1});try{const runId=await seedRun(client,CAPACITY_PROJECT,1);const [first,second]=await Promise.all([addMember(client,CAPACITY_PROJECT,runId,member.id),addMember(client,CAPACITY_PROJECT,runId,architect.id)]);expect([first.error,second.error].filter(error=>!error)).toHaveLength(1);const rejected=[first.error,second.error].find(Boolean);expect(rejected?.message).toContain('PARTICIPATION_CAPACITY_FULL');const {count,error}=await client.from('project_members').select('id',{count:'exact',head:true}).eq('project_run_id',runId).in('membership_status',['waiting','active']);if(error)throw error;expect(count).toBe(1)}finally{await cleanup(client,CAPACITY_PROJECT)}});

  test('concurrent Lead and duplicate responsibility writers serialize to one canonical active state',async()=>{const client=db();const {member,architect,admin}=await identities();const roles=await seedProject(client,FORMATION_PROJECT,{mode:'team',min:2,target:2,max:2,admission:'review_required'});try{const runId=await seedRun(client,FORMATION_PROJECT,2);const memberRow=await addMember(client,FORMATION_PROJECT,runId,member.id);if(memberRow.error||!memberRow.data)throw memberRow.error||new Error('Member membership missing.');const architectRow=await addMember(client,FORMATION_PROJECT,runId,architect.id);if(architectRow.error||!architectRow.data)throw architectRow.error||new Error('Architect membership missing.');const analyst=roles.find(role=>role.title==='Analyst');if(!analyst)throw new Error('Analyst role missing.');const [responsibilityA,responsibilityB]=await Promise.all([client.rpc('phase10_assign_delivery_responsibility',{p_membership_id:memberRow.data.id,p_responsibility:'Analysis',p_source_project_role_id:analyst.id,p_actor_user_id:admin.id,p_reason:'Concurrent assignment A'}),client.rpc('phase10_assign_delivery_responsibility',{p_membership_id:memberRow.data.id,p_responsibility:'Analysis',p_source_project_role_id:analyst.id,p_actor_user_id:admin.id,p_reason:'Concurrent assignment B'})]);expect(responsibilityA.error).toBeNull();expect(responsibilityB.error).toBeNull();expect([responsibilityA.data?.assigned,responsibilityB.data?.assigned].filter(Boolean)).toHaveLength(1);const {count:responsibilityCount,error:responsibilityCountError}=await client.from('project_member_responsibilities').select('id',{count:'exact',head:true}).eq('project_run_id',runId).eq('project_member_id',memberRow.data.id).eq('responsibility','Analysis').eq('assignment_status','active');if(responsibilityCountError)throw responsibilityCountError;expect(responsibilityCount).toBe(1);const [leadA,leadB]=await Promise.all([client.rpc('phase10_confirm_project_lead',{p_membership_id:memberRow.data.id,p_actor_user_id:admin.id,p_reason:'Concurrent Lead A'}),client.rpc('phase10_confirm_project_lead',{p_membership_id:architectRow.data.id,p_actor_user_id:admin.id,p_reason:'Concurrent Lead B'})]);expect(leadA.error).toBeNull();expect(leadB.error).toBeNull();const {data:leadRows,error:leadRowsError}=await client.from('project_members').select('id,team_role').eq('project_run_id',runId).in('membership_status',['waiting','active']);if(leadRowsError)throw leadRowsError;expect(leadRows?.filter(row=>row.team_role==='project_lead')).toHaveLength(1)}finally{await cleanup(client,FORMATION_PROJECT)}});

  test('cron and Admin start callers produce one activation and one start event',async()=>{const client=db();const {member,admin}=await identities();await seedProject(client,START_PROJECT,{mode:'solo',min:1,target:1,max:1});try{const runId=await seedRun(client,START_PROJECT,1);const membership=await addMember(client,START_PROJECT,runId,member.id);if(membership.error)throw membership.error;await seedReadiness(client,START_PROJECT,admin.id);await makeDue(client,runId);const [cron,adminRetry]=await Promise.all([startProjectRun({db:client,projectId:START_PROJECT,runId,source:'auto_scheduler'}),startProjectRun({db:client,projectId:START_PROJECT,runId,source:'admin_retry',actorUserId:admin.id})]);expect([cron.started,adminRetry.started].filter(Boolean)).toHaveLength(1);expect([cron.alreadyStarted,adminRetry.alreadyStarted].filter(Boolean)).toHaveLength(1);const [{data:run,error:runError},{count:startEvents,error:eventError},{count:members,error:memberError}]=await Promise.all([client.from('project_runs').select('status,has_started,started_at').eq('id',runId).single(),client.from('project_activity_log').select('id',{count:'exact',head:true}).eq('project_run_id',runId).eq('event_type','project_started'),client.from('project_members').select('id',{count:'exact',head:true}).eq('project_run_id',runId).eq('membership_status','active')]);if(runError)throw runError;if(eventError)throw eventError;if(memberError)throw memberError;expect(run).toMatchObject({status:'active',has_started:true});expect(run?.started_at).toBeTruthy();expect(startEvents).toBe(1);expect(members).toBe(1)}finally{await cleanup(client,START_PROJECT)}});

  test('member removal racing start cannot create a partial pre-start activation',async()=>{const client=db();const {member,architect,admin}=await identities();const roles=await seedProject(client,LEAVE_START_PROJECT,{mode:'team',min:2,target:2,max:2});try{const runId=await seedRun(client,LEAVE_START_PROJECT,2);const first=await addMember(client,LEAVE_START_PROJECT,runId,member.id);const second=await addMember(client,LEAVE_START_PROJECT,runId,architect.id);if(first.error||!first.data)throw first.error||new Error('First membership missing.');if(second.error||!second.data)throw second.error||new Error('Second membership missing.');const analyst=roles.find(role=>role.title==='Analyst');if(!analyst)throw new Error('Analyst role missing.');for(const membershipId of [first.data.id,second.data.id]){const assignment=await client.rpc('phase10_assign_delivery_responsibility',{p_membership_id:membershipId,p_responsibility:'Analysis',p_source_project_role_id:analyst.id,p_actor_user_id:admin.id,p_reason:'Start readiness'});if(assignment.error)throw assignment.error}const lead=await client.rpc('phase10_confirm_project_lead',{p_membership_id:first.data.id,p_actor_user_id:admin.id,p_reason:'Start readiness'});if(lead.error)throw lead.error;await seedReadiness(client,LEAVE_START_PROJECT,admin.id);await makeDue(client,runId);const [startResult,departure]=await Promise.all([startProjectRun({db:client,projectId:LEAVE_START_PROJECT,runId,source:'auto_scheduler'}),client.from('project_members').delete().eq('id',second.data.id)]);if(departure.error)throw departure.error;const {data:run,error:runError}=await client.from('project_runs').select('status,has_started,started_at').eq('id',runId).single();if(runError)throw runError;const {count:liveMembers,error:liveError}=await client.from('project_members').select('id',{count:'exact',head:true}).eq('project_run_id',runId).in('membership_status',['waiting','active']);if(liveError)throw liveError;expect(liveMembers).toBe(1);if(startResult.started){expect(run).toMatchObject({status:'active',has_started:true});expect(run?.started_at).toBeTruthy()}else{expect(startResult.notReady||startResult.alreadyStarted).toBeTruthy();if(startResult.notReady)expect(run).toMatchObject({status:'forming',has_started:false})}const {count:startEvents,error:eventError}=await client.from('project_activity_log').select('id',{count:'exact',head:true}).eq('project_run_id',runId).eq('event_type','project_started');if(eventError)throw eventError;expect(startEvents||0).toBeLessThanOrEqual(1)}finally{await cleanup(client,LEAVE_START_PROJECT)}});
 });
