import {redirect} from 'next/navigation';
import {createServerSupabaseClient} from '@/lib/supabase/server';
import {serviceDb} from '@/lib/project-flow';
import AdminNotificationOps from '@/components/AdminNotificationOps';
import AdminCommunicationCentre from '@/components/AdminCommunicationCentre';

type DeliveryAttempt={attempt_number:number;status:string;error_message:string|null;http_status:number|null;provider_message_id:string|null;attempted_at:string};
type OutboxItem={id:string;recipient_email:string;template_key:string;subject:string;status:string;attempts:number;max_attempts:number;last_error:string|null;provider_message_id:string|null;created_at:string;sent_at:string|null;next_attempt_at:string|null;dead_letter_at:string|null;email_delivery_attempts?:DeliveryAttempt[]};
type RawOutboxItem=Omit<OutboxItem,'email_delivery_attempts'>&{email_delivery_attempts:DeliveryAttempt[]|null};
type CatalogueItem={event_key:string;product_area:string;description:string;default_channel:string;urgency:string;action_required:boolean;active:boolean};
type TemplateItem={id:string;template_key:string;journey:string;name:string;description:string|null;send_mode:'automatic'|'admin_review'|'manual';subject_template:string;body_template:string;cta_label:string|null;cta_url_template:string|null;variables:string[];active:boolean;version:number;updated_at:string};

export const dynamic='force-dynamic';
export default async function AdminNotificationsPage(){
 const auth=await createServerSupabaseClient();const {data:{user}}=await auth.auth.getUser();if(!user)redirect('/signin');if(user.app_metadata?.role!=='admin')redirect('/member');
 const db=serviceDb();let items:OutboxItem[]=[];let catalogue:CatalogueItem[]=[];let templates:TemplateItem[]=[];if(db){const [outbox,events,templateResult]=await Promise.all([db.from('email_outbox').select('id,recipient_email,template_key,subject,status,attempts,max_attempts,last_error,provider_message_id,created_at,sent_at,next_attempt_at,dead_letter_at,email_delivery_attempts(attempt_number,status,error_message,http_status,provider_message_id,attempted_at)').order('created_at',{ascending:false}).order('attempted_at',{referencedTable:'email_delivery_attempts',ascending:false}).limit(100),db.from('notification_event_catalogue').select('event_key,product_area,description,default_channel,urgency,action_required,active').order('product_area'),db.from('communication_templates').select('id,template_key,journey,name,description,send_mode,subject_template,body_template,cta_label,cta_url_template,variables,active,version,updated_at').order('journey').order('name')]);const raw=(outbox.data||[]) as unknown as RawOutboxItem[];items=raw.map(item=>({...item,email_delivery_attempts:item.email_delivery_attempts||undefined}));catalogue=(events.data||[]) as CatalogueItem[];templates=(templateResult.data||[]) as TemplateItem[];}
 const counts={queued:items.filter(i=>['queued','sending','retrying'].includes(i.status)).length,sent:items.filter(i=>i.status==='sent').length,failed:items.filter(i=>['failed','dead_letter'].includes(i.status)).length};
 const providerConfigured=Boolean(process.env.RESEND_API_KEY&&process.env.METTELO_EMAIL_FROM);
 return <section className="section softSection"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">Mettelo Admin · Communications</div><h1>Control journey emails and see delivery health in one place.</h1></div><p>Edit safe defaults, preview communication, send tests, and monitor what was queued, delivered or failed.</p></div>{!providerConfigured&&<div className="panel" style={{marginBottom:18,border:'1px solid #d7a446'}}><div className="panelHead"><div><span className="cardNumber">EMAIL PROVIDER ACTION REQUIRED</span><h3 style={{marginTop:8}}>Transactional email delivery is not configured.</h3></div><span className="chip">BLOCKED</span></div><p>Add both <code>RESEND_API_KEY</code> and <code>METTELO_EMAIL_FROM</code> to the production environment, then redeploy. In-app notifications continue to work and queued emails will retry automatically.</p></div>}<AdminCommunicationCentre initialTemplates={templates}/><div className="metricGrid" style={{marginTop:18}}><div className="metric"><strong>{counts.queued}</strong><span>Queued / retrying</span></div><div className="metric"><strong>{counts.sent}</strong><span>Sent</span></div><div className="metric"><strong>{counts.failed}</strong><span>Failed / dead-letter</span></div></div><AdminNotificationOps initialItems={items}/><section className="panel" style={{marginTop:18}}><div className="panelHead"><div><span className="cardNumber">EVENT CATALOGUE</span><h3 style={{marginTop:8}}>Platform notification rules</h3></div><span className="chip">{catalogue.length}</span></div><div className="applicationQueue">{catalogue.map(event=><article className="applicationReview" key={event.event_key}><div className="panelHead"><div><span className="chip">{event.product_area.toUpperCase()}</span><h3>{event.description}</h3><small>{event.event_key}</small></div><small>{event.default_channel.replaceAll('_',' ')} · {event.urgency}</small></div><p>{event.action_required?'Recipient action may be required.':'Informational unless the linked record says otherwise.'}</p></article>)}</div></section></div></section>;
}
