import {NextResponse} from 'next/server';
import {createServerSupabaseClient} from '@/lib/supabase/server';
import {serviceDb} from '@/lib/project-flow';

async function adminContext(){const auth=await createServerSupabaseClient();const {data:{user}}=await auth.auth.getUser();if(!user)return{error:NextResponse.json({error:'Authentication required.'},{status:401})};if(user.app_metadata?.role!=='admin')return{error:NextResponse.json({error:'Admin access required.'},{status:403})};const db=serviceDb();if(!db)return{error:NextResponse.json({error:'Admin data service is not configured.'},{status:503})};return{db,user};}
const allowedStatuses=['draft','pilot','recruiting','open','forming','active','review','completed','cancelled','archived'];
function clean(value:unknown,max=2000){return String(value??'').trim().slice(0,max)}
function slugify(value:string){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80)}
const fields='id,slug,title,summary,problem_statement,status,visibility,project_type,partner_name,team_size_threshold,duration_weeks,weekly_commitment,application_deadline,applications_open,project_type_review_required,created_at,updated_at,updated_by_user_id';

export async function GET(){try{const ctx=await adminContext();if('error'in ctx)return ctx.error;const {db}=ctx;const {data:projects,error}=await db.from('projects').select(fields).order('created_at',{ascending:false});if(error)throw error;const ids=(projects||[]).map(project=>project.id);const [{data:members},{data:runs}]=ids.length?await Promise.all([db.from('project_members').select('project_id,project_run_id,membership_status').in('project_id',ids).in('membership_status',['waiting','active']),db.from('project_runs').select('id,project_id,run_number,status,required_team_size,has_started').in('project_id',ids).order('run_number',{ascending:false})]):[{data:[]},{data:[]}];const items=(projects||[]).map(project=>{const projectRuns=(runs||[]).filter(run=>run.project_id===project.id);const currentRun=projectRuns.find(run=>!['completed','cancelled'].includes(run.status))||projectRuns[0]||null;const filled=currentRun?(members||[]).filter(member=>member.project_run_id===currentRun.id).length:(members||[]).filter(member=>member.project_id===project.id).length;return{...project,filled,current_run_id:currentRun?.id||null,current_run_status:currentRun?.status||null,current_run_number:currentRun?.run_number||null,current_run_required_team_size:currentRun?.required_team_size||project.team_size_threshold||null}});return NextResponse.json({items});}catch(error){console.error('admin projects list error',error);return NextResponse.json({error:'Unable to load projects.'},{status:500})}}

export async function POST(request:Request){try{const ctx=await adminContext();if('error'in ctx)return ctx.error;const {db,user}=ctx;const body=await request.json();const title=clean(body.title,180),summary=clean(body.summary,900),projectType=clean(body.project_type,20),problem=clean(body.problem_statement,4000),partnerName=clean(body.partner_name,180);if(!title||!summary)return NextResponse.json({error:'Project title and summary are required.'},{status:400});if(!['open','partner'].includes(projectType))return NextResponse.json({error:'Choose Open Project or Partner Project. Project type cannot be inferred.'},{status:400});if(projectType==='partner'&&!partnerName)return NextResponse.json({error:'Partner Project requires a partner name.'},{status:400});const teamSize=Math.max(1,Math.min(50,Number(body.team_size_threshold)||0));if(!Number(body.team_size_threshold)||teamSize<1)return NextResponse.json({error:'Team size required is mandatory.'},{status:400});const now=new Date().toISOString(),slug=`${slugify(title)||'project'}-${Date.now().toString(36)}`;const {data:project,error}=await db.from('projects').insert({slug,title,summary,problem_statement:problem||summary,status:'draft',visibility:'private',project_type:projectType,partner_name:partnerName||null,team_size_threshold:teamSize,duration_weeks:body.duration_weeks?Math.max(1,Math.min(104,Number(body.duration_weeks))):null,weekly_commitment:clean(body.weekly_commitment,120)||null,application_deadline:body.application_deadline||null,applications_open:Boolean(body.applications_open),project_type_review_required:false,project_type_reviewed_at:now,project_type_reviewed_by:user.id,created_by_user_id:user.id,updated_by_user_id:user.id,updated_at:now}).select(fields).single();if(error)throw error;if(projectType==='partner'){const {error:runError}=await db.from('project_runs').insert({project_id:project.id,run_number:1,status:'forming',team_size_threshold:teamSize,required_team_size:teamSize,has_started:false});if(runError){await db.from('projects').delete().eq('id',project.id);throw runError}}await db.from('project_activity_log').insert({project_id:project.id,event_type:'project_created',actor_type:'user',actor_user_id:user.id,from_status:null,to_status:'draft',metadata:{project_type:projectType,required_team_size:teamSize}});return NextResponse.json({ok:true,item:{...project,filled:0,current_run_id:null,current_run_status:projectType==='partner'?'forming':null,current_run_number:projectType==='partner'?1:null}},{status:201});}catch(error){console.error('admin project create error',error);return NextResponse.json({error:'Unable to create this project.'},{status:500})}}

export async function PATCH(request:Request){try{const ctx=await adminContext();if('error'in ctx)return ctx.error;const {db,user}=ctx;const body=await request.json();const id=clean(body.id,80);if(!id)return NextResponse.json({error:'Project is required.'},{status:400});const status=clean(body.status,30);if(status&&!allowedStatuses.includes(status))return NextResponse.json({error:'Invalid project status.'},{status:400});const patch:Record<string,unknown>={updated_at:new Date().toISOString(),updated_by_user_id:user.id};if('title'in body){const title=clean(body.title,180);if(!title)return NextResponse.json({error:'Project title is required.'},{status:400});patch.title=title}if('summary'in body){const summary=clean(body.summary,900);if(!summary)return NextResponse.json({error:'Project summary is required.'},{status:400});patch.summary=summary}if('problem_statement'in body)patch.problem_statement=clean(body.problem_statement,4000)||null;if('team_size_threshold'in body)patch.team_size_threshold=Math.max(1,Math.min(50,Number(body.team_size_threshold)||1));if('duration_weeks'in body)patch.duration_weeks=body.duration_weeks?Math.max(1,Math.min(104,Number(body.duration_weeks))):null;if('weekly_commitment'in body)patch.weekly_commitment=clean(body.weekly_commitment,120)||null;if('application_deadline'in body)patch.application_deadline=body.application_deadline||null;if('applications_open'in body)patch.applications_open=body.applications_open===true||body.applications_open==='true'||body.applications_open==='on';if(status)patch.status=status;if('visibility'in body)patch.visibility=body.visibility==='private'?'private':'public';if('project_type'in body){const type=clean(body.project_type,20);if(!['open','partner'].includes(type))return NextResponse.json({error:'Choose Open Project or Partner Project.'},{status:400});patch.project_type=type;patch.project_type_review_required=false;patch.project_type_reviewed_at=new Date().toISOString();patch.project_type_reviewed_by=user.id}if('partner_name'in body)patch.partner_name=clean(body.partner_name,180)||null;if(body.action==='archive'){patch.status='archived';patch.visibility='private'}const {data,error}=await db.from('projects').update(patch).eq('id',id).select(fields).single();if(error)throw error;return NextResponse.json({ok:true,item:data});}catch(error){console.error('admin project update error',error);return NextResponse.json({error:'Unable to update this project.'},{status:500})}}

export async function DELETE(request:Request){try{const ctx=await adminContext();if('error'in ctx)return ctx.error;const {db}=ctx;const body=await request.json();const id=clean(body.id,80);if(!id)return NextResponse.json({error:'Project is required.'},{status:400});const tables=['project_applications','project_runs','project_members','project_tasks','contributions'];const counts=await Promise.all(tables.map(table=>db.from(table).select('id',{count:'exact',head:true}).eq('project_id',id)));const dependent=counts.reduce((sum,result)=>sum+(result.count||0),0);if(dependent>0)return NextResponse.json({error:'This project already has applications, team activity or evidence. Archive it instead so member history stays intact.'},{status:409});const {error}=await db.from('projects').delete().eq('id',id);if(error)throw error;return NextResponse.json({ok:true});}catch(error){console.error('admin project delete error',error);return NextResponse.json({error:'Unable to delete this project. Archive it instead if activity already exists.'},{status:500})}}
