import type { Metadata } from 'next';

export const metadata:Metadata={title:'Insights & News',description:'Practical Mettelo thinking on Data & AI careers, real work, capability, projects and the systems behind professional growth.'};

export default function BlogPage(){return <>
<section className="hero"><div className="shell heroGrid"><div><div className="eyebrow">Mettelo Insights & News</div><h1>Useful thinking for people building careers and systems in Data & AI.</h1><p className="heroLead">Career reality, practical frameworks, Labs case studies, research and transparent updates on what Mettelo is building.</p><div className="actions"><a className="button dark" href="/newsletter">Get new insights →</a></div></div><aside className="heroPanel"><span className="chip">EDITORIAL PRINCIPLE</span><h3 style={{marginTop:18}}>Show, don’t inflate.</h3><p>Mettelo content should come from real practitioner experience, project work, research and useful community questions — not a generic SaaS content treadmill.</p><div className="path"><span>Career reality</span><span>Labs</span><span>Research</span><span>Data & AI</span><span>Building Mettelo</span></div></aside></div></section>
<section className="section"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">Editorial areas</div><h2>What belongs here.</h2></div><p>Individual article pages publish when the content is ready. We are not presenting draft headlines as already-published articles.</p></div><div className="grid4"><article className="card"><span className="chip">CAREER REALITY</span><h3 style={{marginTop:18}}>What work actually requires</h3><p>Hiring, progression, stakeholder judgement, commercial or public value, and the gap between junior reporting and senior impact.</p></article><article className="card"><span className="chip">LABS</span><h3 style={{marginTop:18}}>Case studies from real work</h3><p>Problem framing, methods, trade-offs, review, team roles and what contributors can credibly claim.</p></article><article className="card"><span className="chip">RESEARCH</span><h3 style={{marginTop:18}}>Practical evidence</h3><p>Surveys, benchmarks, datasets and insight on Data, AI and the future of professional capability.</p></article><article className="card"><span className="chip">BUILDING METTELO</span><h3 style={{marginTop:18}}>Transparent product updates</h3><p>What is live, what is being tested, what changed and why.</p></article></div></div></section>
<section className="section softSection"><div className="shell"><div className="ctaBand"><div><div className="cardNumber">CONTENT ENGINE</div><h2>One useful input. Many useful outputs.</h2><p>Sessions, project learning and research can become articles, newsletters, social posts and resources — without pretending unfinished content already exists.</p></div><div className="actions"><a className="button dark" href="/newsletter">Subscribe for updates →</a></div></div></div></section>
</>}
