import type {Metadata} from 'next';
import Image from 'next/image';
import {getPublicWebsitePage} from '@/lib/website-pages';
import './about.css';

export const metadata:Metadata={
  title:'About Mettelo',
  description:'Mettelo is a technology-led organisation building professional capability infrastructure for Data & AI across Africa and beyond.'
};

const problems=[
  ['01','Knowledge is abundant. Meaningful experience is not.','Professionals can complete courses, certifications and tool training yet still struggle to access the real environments where judgement, collaboration and delivery are developed.'],
  ['02','Capability is difficult to prove from a CV alone.','Titles and keywords say little about how someone handles ambiguity, works with others, communicates with stakeholders or creates measurable value.'],
  ['03','Professional growth is fragmented across separate systems.','Learning platforms teach. Communities converse. Networks connect. Recruiters match CVs. Projects, Proof and opportunity rarely form one continuous journey.'],
  ['04','Opportunity still depends too heavily on signalling and access.','Capable people can remain invisible because they lack the right title, geography, network or prior opportunity to demonstrate what they can actually do.']
];

const pillars=[
  ['Mettelo Community','The front door','Where Data & AI professionals connect, form teams, share knowledge, attend events, join open source and discover opportunities.'],
  ['Mettelo Labs','The innovation engine','Where people build technology together: open-source tools, AI applications, APIs, data products, datasets, frameworks and prototypes.'],
  ['Mettelo Proof','Professional credibility','Where contribution becomes portable evidence through verified work, profiles, showcases, recognition and measurable outcomes.'],
  ['Mettelo Talent','Capability meets opportunity','Where demonstrated work connects to jobs, referrals, employer discovery, freelance work and future consulting pathways.'],
  ['Mettelo Research','Practical intelligence','Reports, benchmarks, surveys and practitioner insight on Data, AI and the future of work.'],
  ['Mettelo AI','Intelligent products','AI products designed to improve how professionals work, collaborate, demonstrate capability and get discovered.'],
  ['Mettelo Summit','The flagship gathering','Talks, launches, hackathons, networking and showcases that bring the wider ecosystem together.']
];

export default async function AboutPage(){const copy=(await getPublicWebsitePage('about')).values;return <>
  <section className="hero" aria-labelledby="about-title"><div className="shell heroGrid"><div><div className="eyebrow">{copy.hero_eyebrow}</div><h1 id="about-title">{copy.hero_title}</h1><p className="heroLead">{copy.hero_lead}</p><div className="actions"><a className="button dark" href={copy.hero_primary_href}>{copy.hero_primary_label}</a><a className="button ghost" href={copy.hero_secondary_href}>{copy.hero_secondary_label}</a></div></div><aside className="heroPanel aboutHeroNote" aria-label="Mettelo thesis"><span className="chip">OUR THESIS</span><h3>{copy.thesis_title}</h3><p>{copy.thesis_body}</p><div className="listRow"><strong>Real problems</strong><span>→ Capability</span></div><div className="listRow"><strong>Contribution</strong><span>→ Proof</span></div><div className="listRow"><strong>Proof</strong><span>→ Trust</span></div><div className="listRow"><strong>Trust</strong><span>→ Opportunity</span></div></aside></div></section>

  <section className="section" aria-labelledby="story-title"><div className="shell aboutSplit"><div><div className="eyebrow">{copy.story_eyebrow}</div><h2 id="story-title" style={{fontSize:'clamp(2.5rem,5vw,4.7rem)',margin:0}}>{copy.story_title}</h2></div><div className="aboutCopy"><p>Technology evolves daily. Artificial intelligence is reshaping industries, changing how work is done and creating roles that barely existed a few years ago. Organisations increasingly need people who can think critically, adapt quickly, collaborate across disciplines and solve problems that do not come with a ready-made answer.</p><p>Yet professionals are still told that the path forward is another certificate, another tool or another course. Those things can help, but they do not answer the questions that matter most in real work: <strong>Can you solve an ambiguous problem? Can you turn information into a decision? Can you work with others, communicate clearly and create measurable value?</strong></p><p>Those questions are answered by capability. And capability becomes trusted when it is demonstrated.</p><p><strong>That is where Mettelo begins.</strong></p></div></div></section>

  <section className="section softSection" aria-labelledby="gap-title"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">{copy.gap_eyebrow}</div><h2 id="gap-title">{copy.gap_title}</h2></div><p>{copy.gap_body}</p></div><div className="problemList">{problems.map(([n,t,c])=><article className="problemItem" key={t}><div className="problemIndex" aria-hidden="true">{n}</div><div><h3 style={{margin:'0 0 6px'}}>{t}</h3><p style={{margin:0,color:'var(--slate)'}}>{c}</p></div></article>)}</div></div></section>

  <section className="section" aria-labelledby="what-title"><div className="shell aboutSplit"><div><div className="eyebrow">What Mettelo is</div><h2 id="what-title" style={{fontSize:'clamp(2.5rem,5vw,4.7rem)',margin:0}}>Not another learning platform. Not another community. Not another job board.</h2></div><div className="aboutCopy"><p>Each of those products solves a useful fragment. Mettelo is being built as the <strong>connective infrastructure between them</strong>.</p><p>People should be able to move from a real problem to collaborative work, from collaborative work to credible evidence, from evidence to trust, and from trust to opportunity without losing the context that makes their contribution meaningful.</p><p>For professionals, that creates a clearer route from potential to demonstrated capability. For organisations, it creates a stronger way to discover people through evidence of judgement, collaboration and impact — not only titles and CV keywords.</p></div></div></section>

  <section className="section dark" aria-labelledby="ecosystem-title"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">{copy.ecosystem_eyebrow}</div><h2 id="ecosystem-title">{copy.ecosystem_title}</h2></div><p>{copy.ecosystem_body}</p></div><div className="principleGrid">{pillars.map(([name,role,body])=><article className="principle" key={name}><span className="chip">{role}</span><strong>{name}</strong><span>{body}</span></article>)}</div></div></section>

  <section className="section" aria-labelledby="system-title"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">How the system works</div><h2 id="system-title">Build. Prove. Get discovered.</h2></div><p>The value compounds when each stage strengthens the next.</p></div><div className="principleGrid"><article className="principle"><strong>01 · Real problems</strong><span>Professionals work through genuine organisational challenges and messy, realistic situations — not idealised exercises.</span></article><article className="principle"><strong>02 · Build together</strong><span>Multidisciplinary teams collaborate on projects, open source, data products, tools and prototypes.</span></article><article className="principle"><strong>03 · Proof that travels</strong><span>Contribution becomes visible evidence: verified work, portfolios, peer signals, recognition and measurable outcomes.</span></article><article className="principle"><strong>04 · Relationships that matter</strong><span>Mentors, collaborators and peers build trust through shared work rather than passive networking.</span></article><article className="principle"><strong>05 · Opportunity by merit</strong><span>Jobs, referrals, projects and future employer discovery connect back to demonstrated capability.</span></article><article className="principle"><strong>06 · Technology that compounds it</strong><span>Over time, intelligent products make capability easier to understand, match, verify and mobilise across the ecosystem.</span></article></div></div></section>

  <section className="section softSection" aria-labelledby="future-title"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">{copy.future_eyebrow}</div><h2 id="future-title">{copy.future_title}</h2></div><p>{copy.future_body}</p></div><div className="statementGrid"><article className="statementCard"><span className="chip">NOW</span><h3>Build the working capability loop.</h3><p>Community, projects, contribution records, Proof, Showcase, people discovery, Opportunities, Events and Careers create the first connected operating layers.</p></article><article className="statementCard"><span className="chip">NEXT</span><h3>Make capability more intelligent and useful.</h3><p>Develop stronger matching, richer contribution signals, organisational workflows, research, talent intelligence and AI-assisted discovery.</p></article></div><div className="statementGrid" style={{marginTop:18}}><article className="statementCard"><span className="chip">THEN</span><h3>Build products from the ecosystem.</h3><p>Open-source tools, AI applications, APIs, datasets, frameworks and Mettelo-built intelligent products can solve real professional and organisational problems while creating new Proof.</p></article><article className="statementCard"><span className="chip">LONG TERM</span><h3>Become global infrastructure for professional capability.</h3><p>Our ambition is a system through which capability can be developed, demonstrated, discovered and deployed across borders, industries and professions.</p></article></div></div></section>

  <section className="section" aria-labelledby="mission-title"><div className="shell"><div className="statementGrid"><article className="statementCard"><span className="chip">MISSION</span><h2 id="mission-title">{copy.mission_title}</h2><p>{copy.mission_body}</p></article><article className="statementCard"><span className="chip">VISION</span><h2>{copy.vision_title}</h2><p>{copy.vision_body}</p></article></div></div></section>

  <section className="section" aria-labelledby="founder-title"><div className="shell founderGrid"><figure className="founderMedia"><Image src="/api/founder-image" alt="O. Johnson Taiwo, Founder of Mettelo" width={640} height={640} sizes="(max-width: 1080px) 90vw, 38vw"/><figcaption className="founderCaption"><small>FOUNDER</small><strong>O. Johnson Taiwo</strong><span>Data & AI Professional · Founder, Mettelo</span></figcaption></figure><div className="founderBio"><div className="eyebrow">{copy.founder_eyebrow}</div><h2 id="founder-title" style={{fontSize:'clamp(2.5rem,5vw,4.6rem)',margin:'0 0 20px'}}>{copy.founder_title}</h2><p><strong>O. Johnson Taiwo</strong> has worked across analytics, data science, digital transformation and commercial decision-making in public- and private-sector environments. Across those roles, one lesson kept repeating: technical knowledge matters, but organisations ultimately need people who can apply it with judgement, communicate clearly, collaborate well and produce useful outcomes.</p><p>At the same time, he saw capable people invest heavily in courses and tools while still struggling to access the situations where their skills could become trusted experience. The missing layer was between <strong>knowledge and application, application and evidence, evidence and opportunity</strong>.</p><p>Mettelo was created to build that missing layer — first for Data & AI, then wherever the same problem exists.</p><div className="quotePanel"><p>“{copy.founder_quote}”</p></div></div></div></section>

  <section className="section compact" aria-labelledby="about-cta-title"><div className="shell"><div className="ctaBand"><div><div className="cardNumber">{copy.cta_eyebrow}</div><h2 id="about-cta-title">{copy.cta_title}</h2><p>{copy.cta_body}</p></div><div className="actions"><a className="button dark" href={copy.cta_primary_href}>{copy.cta_primary_label}</a><a className="button ghost" href={copy.cta_secondary_href}>{copy.cta_secondary_label}</a></div></div></div></section>
</>}
