import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'About',
  description: 'The Mettelo story, the problem we are solving, our vision, mission and founder.',
};

export default function AboutPage(){
  const problems=[
    ['01','Learning is abundant. Meaningful experience is not.','Professionals can complete courses and certifications yet still struggle to find credible opportunities to apply what they know in real teams.'],
    ['02','Capability is difficult to prove from a CV alone.','Hiring decisions often rely on similar-looking CVs, while useful contribution, judgement, collaboration and delivery remain hard to see.'],
    ['03','Professional growth is fragmented across too many places.','Courses, projects, jobs, referrals, mentors, open source, events and communities sit in separate systems with little continuity between them.'],
    ['04','Access to opportunity is still uneven.','Talented professionals can be overlooked because they lack the right network, location, previous title or visible evidence of what they can actually do.']
  ];
  return <>
    <section className="hero"><div className="shell heroGrid"><div><div className="eyebrow">About Mettelo</div><h1>We are building what should exist between learning and opportunity.</h1><p className="heroLead">Mettelo began with a simple observation: professional capability is often stronger than the systems available to reveal it. We are building an ecosystem where people can connect, contribute to meaningful work, create credible proof and become easier to discover for the right opportunities.</p><div className="actions"><a className="button dark" href="/membership#signup">Join Mettelo →</a><a className="button ghost" href="/partnership">Partner with us</a></div></div><aside className="heroPanel aboutHeroNote"><span className="chip">OUR THESIS</span><h3>Capability should become professional currency.</h3><p>What you can contribute should matter more than where you started, how polished your CV looks or whether someone already gave you the title.</p><div className="listRow"><strong>Real work</strong><span>→ Experience</span></div><div className="listRow"><strong>Contribution</strong><span>→ Evidence</span></div><div className="listRow"><strong>Evidence</strong><span>→ Trust</span></div><div className="listRow"><strong>Trust</strong><span>→ Opportunity</span></div></aside></div></section>

    <section className="section"><div className="shell aboutSplit"><div><div className="eyebrow">The Mettelo story</div><h2 style={{fontSize:'clamp(2.5rem,5vw,4.7rem)',margin:0}}>Why Mettelo exists.</h2></div><div className="aboutCopy"><p>Mettelo was created from seeing the same pattern repeatedly across Data & AI careers: people were learning, applying and networking, but the pieces rarely connected into a credible professional journey.</p><p>A person might learn SQL in one place, join a community somewhere else, build a personal project alone, search for jobs on another platform and still struggle to answer the most important question: <strong>where is the visible evidence that I can contribute in a real environment?</strong></p><p>Mettelo is designed to connect those missing pieces. Community creates relationships. Labs creates meaningful work. Proof captures contribution. Talent connects evidence to opportunity. Research, AI and future flagship experiences extend the system over time.</p><p>We are beginning with Data & AI professionals, with a strong connection to African and diaspora talent, while building an infrastructure designed to become globally relevant.</p></div></div></section>

    <section className="section softSection"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">The problem</div><h2>The professional growth system is fragmented.</h2></div><p>Mettelo is not being built because the world needs another course library or another chat group. It is being built because important parts of professional development still do not connect.</p></div><div className="problemList">{problems.map(([n,t,c])=><div className="problemItem" key={t}><div className="problemIndex">{n}</div><div><h3 style={{margin:'0 0 6px'}}>{t}</h3><p style={{margin:0,color:'var(--slate)'}}>{c}</p></div></div>)}</div></div></section>

    <section className="section"><div className="shell"><div className="statementGrid"><article className="statementCard"><span className="chip">VISION</span><h3>A world where capability can become visible proof, meaningful contribution and real opportunity.</h3><p>We want every professional to have a clearer route to demonstrate what they can do — regardless of where they start.</p></article><article className="statementCard"><span className="chip">MISSION</span><h3>Build a contribution-led professional ecosystem where people learn through doing.</h3><p>Mettelo connects real work, open collaboration, credible evidence, leadership development, relationships and access to opportunity.</p></article></div></div></section>

    <section className="section dark"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">How we build</div><h2>Principles before scale.</h2></div><p>The platform should grow without losing the qualities that make contribution credible and community useful.</p></div><div className="principleGrid"><div className="principle"><strong>Build proof before scale</strong><span>Useful outcomes and repeatable systems matter more than vanity growth.</span></div><div className="principle"><strong>Contribution over credentials</strong><span>Qualifications matter, but visible judgement and delivery should also be recognised.</span></div><div className="principle"><strong>Quality over noise</strong><span>Trust, strong project standards and good contributor experience come first.</span></div><div className="principle"><strong>Global relevance</strong><span>Begin with real problems close to our communities while designing for global usefulness.</span></div><div className="principle"><strong>Community as infrastructure</strong><span>Community helps identify problems, form teams, transfer knowledge and create opportunity.</span></div><div className="principle"><strong>Systems that compound</strong><span>Every project, contribution, partnership and insight should make the ecosystem more useful.</span></div></div></div></section>

    <section className="section"><div className="shell founderGrid"><div className="founderPortrait"><div><small>FOUNDER</small><strong>Olaoluwa Johnson Taiwo</strong><span>Founder, Mettelo</span></div></div><div className="founderBio"><div className="eyebrow">The founder</div><h2 style={{fontSize:'clamp(2.5rem,5vw,4.6rem)',margin:'0 0 20px'}}>Built from a personal belief in practical capability.</h2><p>Olaoluwa Johnson Taiwo, also known professionally as Johnson Taiwo, is a UK-based data and analytics professional with experience across public-sector and private-sector environments. His background spans data, analytics, digital transformation and commercial decision-making, supported by an MBA and Chartered Marketer (MCIM) status.</p><p>Across his career and community work, he has spent significant time helping aspiring and developing data professionals understand what employers actually value beyond tools and certificates: clear thinking, practical delivery, stakeholder judgement, communication and evidence of impact.</p><p>His passion for Mettelo comes from wanting to close the gap between <strong>potential and meaningful opportunity</strong> — particularly for talented professionals who can contribute but do not yet have the network, experience or visible proof that opens the next door.</p><div className="quotePanel"><p>“People should not have to wait for permission to prove they can create value. We can build better systems for contribution to become evidence — and for evidence to create opportunity.”</p></div></div></div></section>

    <section className="section compact"><div className="shell"><div className="ctaBand"><div><div className="cardNumber">BUILD WITH US</div><h2>Mettelo is being built in public, with the people it is meant to serve.</h2><p>Join as a member, contribute to the ecosystem, bring a problem worth solving or partner with us to create stronger pathways into meaningful work.</p></div><div className="actions"><a className="button dark" href="/membership#signup">Join Mettelo →</a><a className="button ghost" href="/partnership">Explore partnership</a></div></div></div></section>
  </>;
}
