import type {Metadata} from 'next';
import HardenedCard from '@/components/HardenedCard';
import './about.css';

export const metadata:Metadata={title:'About Mettelo',description:'Mettelo is a technology-led organisation building professional capability infrastructure for Africa and beyond.'};

export default function AboutPage(){return <>
<section className="hero"><div className="shell heroGrid"><div><div className="eyebrow">About Mettelo</div><h1>Infrastructure for how professionals build and prove capability.</h1><p className="heroLead">Mettelo is a technology-led organisation building the systems professionals use to do meaningful work, turn contribution into verified evidence and become discoverable through stronger signals than claims alone.</p><div className="actions"><a className="button dark" href="/auth/signup">Join Mettelo →</a><a className="button ghost" href="/projects">Explore projects</a></div></div><aside className="heroPanel"><span className="chip">OUR THESIS</span><h3>Capability becomes more valuable when the evidence behind it is visible.</h3><p>Structured project delivery, governed contribution records, verified Proof and recruitment-grade workflows make professional capability easier to build, trust and use.</p></aside></div></section>
<section className="section"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">Mission</div><h2>Build the infrastructure that helps professionals develop, demonstrate and deploy real capability.</h2></div><p>We connect real work, team delivery, evidence, verification, reputation and opportunity so professional growth is not fragmented across disconnected systems.</p></div><div className="statementGrid"><HardenedCard className="statementCard"><span className="chip">BUILD</span><h3>Real delivery environments</h3><p>Clear briefs, roles, milestones, tasks, data, events, governance and project completion.</p></HardenedCard><HardenedCard className="statementCard"><span className="chip">PROVE</span><h3>Evidence that can be trusted</h3><p>Contribution records connect the work, evidence, review and verification state behind a professional claim.</p></HardenedCard><HardenedCard className="statementCard"><span className="chip">DISCOVER</span><h3>Stronger professional signals</h3><p>Projects, Proof and structured recruitment help employers, partners and collaborators discover people through demonstrated value.</p></HardenedCard></div></div></section>
<section className="section softSection"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">Vision</div><h2>Build professional capability infrastructure for Africa and beyond.</h2></div><p>We believe professionals across Africa should be able to access serious delivery environments, create credible evidence of what they can do and carry that evidence across borders. Mettelo is building infrastructure with African ambition and global usefulness: technology that helps capability become visible, trusted and easier to connect to opportunity wherever professionals and organisations are based.</p></div></div></section>
<section className="section dark"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">What Mettelo is not</div><h2>Not a course platform. Not a community forum. Not a passive job board.</h2></div><p>Those products can be useful, but Mettelo focuses on the connective infrastructure between real work, evidence, reputation and opportunity.</p></div><div className="principleGrid"><HardenedCard className="card"><h3>Project infrastructure</h3><p>Team formation, delivery workflows, data, events, evidence and governed completion.</p></HardenedCard><HardenedCard className="card"><h3>Proof infrastructure</h3><p>Evidence-backed contribution records, visibility controls, credentials and verification.</p></HardenedCard><HardenedCard className="card"><h3>Opportunity infrastructure</h3><p>Professional discovery and recruitment workflows that keep status, communication and next steps coherent.</p></HardenedCard></div></div></section>
<section className="section compact"><div className="shell"><div className="ctaBand"><div><div className="cardNumber">BUILT FOR WHAT COMES NEXT</div><h2>Put real evidence behind your next move.</h2><p>Create your account or explore the projects already moving through Mettelo.</p></div><div className="actions"><a className="button dark" href="/auth/signup">Join Mettelo →</a><a className="button ghost" href="/faq">Read the FAQ</a></div></div></div></section>
</>}
