import {NextResponse} from 'next/server';
import {createServerSupabaseClient} from '@/lib/supabase/server';
import {serviceDb,notifyUser} from '@/lib/project-flow';

const types=new Set(['team_working_session','project_review','final_presentation','learning_session']);
const visibilities=new Set(['project_team','named_members','community_learning','approval_required']);
const roles=new Set(['learner','observer','presenter','required_attendee']);
const outcomes=new Set(['pass','revisions_required','not_passed']);
const text=(value:unknown,max=2000)=>String(value??'').trim().slice(0,max);
const ids=(value:unknown)=>Array.isArray(value)?[...new Set(value.map(item=>text(item,80)).filter(Boolean))].slice(0,100):[];

async function actor(projectId:string,runId:string){
 const auth=await createServerSupabaseClient();const {data:{user}}=await auth.auth.getUser();const db=serviceDb();
 if(!user||!db)return {user,db,membership:null,architect:false,isAdmin:false};
 const [{data:membership},{data:assignment}]=await Promise.all([
  db.from('project_members').select('team_role,membership_status').eq('project_id',projectId).eq('project_run_id',runId).eq('user_id',user.id).in('membership_status',['active','completed']).maybeSingle(),
  db.from('project_architect_assignments').select('id').eq('project_id',projectId).eq('user_id',user.id).eq('assignment_status','active').limit(1).maybeSingle()
 ]);
 return {user,db,membership,architect:Boolean(assignment),isAdmin:user.app_metadata?.role==='admin'};
}

async function audit(db:NonNullable<ReturnType<typeof serviceDb>>,eventId:string,runId:string,userId:string,action:string,metadata:Record<string,unknown>={}){await db.from('project_event_audit').insert({event_id:eventId,project_run_id:runId,actor_user_id:userId,action,metadata});}

export async function POST(request:Request){
 try{
  const body=await request.json();const action=text(body.action,40),projectId=text(body.project_id,80),runId=text(body.project_run_id,80);if(!projectId||!runId)return NextResponse.json({error:'Project and project run are required.'},{status:400});
  const ctx=await actor(projectId,runId);if(!ctx.user)return NextResponse.json({error:'Authentication required.'},{status:401});if(!ctx.db)return NextResponse.json({error:'Project event service is unavailable.'},{status:503});
  const canLead=ctx.membership?.team_role==='project_lead',canOversee=ctx.architect||ctx.isAdmin,canManage=canLead||canOversee;
  if(action==='create'){
   if(!canLead&&!ctx.isAdmin)return NextResponse.json({error:'Only the assigned Project Lead can schedule an event. Admin may use an override.'},{status:403});
   const title=text(body.title,180),purpose=text(body.purpose,1200),agenda=text(body.agenda,5000),learningObjectives=text(body.learning_objectives,3000),eventType=text(body.event_type,40),visibility=text(body.visibility,40),startsAt=text(body.starts_at,80),endsAt=text(body.ends_at,80),timezone=text(body.timezone,80)||'Europe/London',capacity=body.capacity?Number(body.capacity):null;const meetingMode=text(body.meeting_mode,30)||'mettelo_video';const externalMeetingUrl=text(body.external_meeting_url,1200);
   const start=new Date(startsAt),end=new Date(endsAt);if(!title||!purpose||!types.has(eventType)||!visibilities.has(visibility)||!startsAt||!endsAt||Number.isNaN(start.valueOf())||Number.isNaN(end.valueOf())||end<=start)return NextResponse.json({error:'Add a title, purpose, valid event type and a valid start/end time.'},{status:400});if(eventType==='learning_session'&&!learningObjectives)return NextResponse.json({error:'Add clear learning objectives for a learning session.'},{status:400});
   if(capacity!==null&&(!Number.isInteger(capacity)||capacity<1||capacity>500))return NextResponse.json({error:'Capacity must be between 1 and 500.'},{status:400});
   if(!['mettelo_video','external'].includes(meetingMode))return NextResponse.json({error:'Choose Mettelo Video or External Meeting.'},{status:400});
   if(meetingMode==='external'){try{const parsed=new URL(externalMeetingUrl);if(parsed.protocol!=='https:')throw new Error('https required')}catch{return NextResponse.json({error:'External Meeting requires a valid HTTPS meeting URL.'},{status:400})}}
   const eventId=crypto.randomUUID(),room=`mettelo-${runId.slice(0,8)}-${eventId.slice(0,8)}`;const joinUrl=meetingMode==='external'?externalMeetingUrl:`/member/events/${eventId}/join`;const provider=meetingMode==='external'?'external':'livekit';const {error}=await ctx.db.from('project_meetings').insert({id:eventId,project_id:projectId,project_run_id:runId,title,purpose,platform:meetingMode==='external'?'external':'other',starts_at:start.toISOString(),ends_at:end.toISOString(),join_url:joinUrl,status:'scheduled',organiser_user_id:ctx.user.id,event_type:eventType,visibility,agenda:agenda||null,learning_objectives:learningObjectives||null,timezone,registration_deadline:body.registration_deadline?new Date(text(body.registration_deadline,80)).toISOString():null,capacity,approval_required:visibility==='approval_required',linked_milestone_id:text(body.linked_milestone_id,80)||null,linked_deliverable_id:text(body.linked_deliverable_id,80)||null,previous_event_id:text(body.previous_event_id,80)||null,provider,provider_room_name:meetingMode==='external'?null:room});if(error)throw error;
   const participantRows:[string,string][]=[];for(const userId of ids(body.presenter_ids))participantRows.push([userId,'presenter']);for(const userId of ids(body.required_attendee_ids))participantRows.push([userId,'required_attendee']);const unique=new Map(participantRows);if(unique.size){const requested=[...unique.keys()],{data:eligible}=await ctx.db.from('project_members').select('user_id').eq('project_run_id',runId).in('membership_status',['active','completed']).in('user_id',requested);if((eligible||[]).length!==requested.length)return NextResponse.json({error:'Presenters and required attendees must belong to this project run.'},{status:400});await ctx.db.from('project_event_participants').insert([...unique].map(([user_id,event_role])=>({event_id:eventId,project_run_id:runId,user_id,event_role,invited_by:ctx.user!.id})))}
   await audit(ctx.db,eventId,runId,ctx.user.id,ctx.isAdmin?'admin_created_event':'lead_created_event',{event_type:eventType,visibility,meeting_mode:meetingMode});
   for(const [userId,eventRole] of unique)if(userId!==ctx.user.id)await notifyUser(ctx.db,{userId,projectId,type:'event_changed',title:`You are a ${eventRole.replaceAll('_',' ')} for ${title}`,body:`The session starts ${start.toLocaleString('en-GB')} (${timezone}).`,actionUrl:joinUrl,dedupeKey:`project-event:${eventId}:${userId}:created`});
   return NextResponse.json({ok:true,event_id:eventId,message:'Project event scheduled.'});
  }
  const eventId=text(body.event_id,80);if(!eventId)return NextResponse.json({error:'Event is required.'},{status:400});const {data:event}=await ctx.db.from('project_meetings').select('id,project_id,project_run_id,title,event_type,visibility,status,capacity,approval_required,registration_deadline,organiser_user_id,starts_at').eq('id',eventId).eq('project_id',projectId).eq('project_run_id',runId).maybeSingle();if(!event)return NextResponse.json({error:'Project event not found.'},{status:404});
  if(action==='update'){
   if(!canManage)return NextResponse.json({error:'Project Lead, assigned Project Architect or Admin access is required.'},{status:403});const title=text(body.title,180),purpose=text(body.purpose,1200),visibility=text(body.visibility,40),timezone=text(body.timezone,80),startsAt=new Date(text(body.starts_at,80)),endsAt=new Date(text(body.ends_at,80));if(!title||!purpose||!visibilities.has(visibility)||!timezone||Number.isNaN(startsAt.valueOf())||Number.isNaN(endsAt.valueOf())||endsAt<=startsAt)return NextResponse.json({error:'Add valid event details and an end time after the start.'},{status:400});await ctx.db.from('project_meetings').update({title,purpose,visibility,timezone,starts_at:startsAt.toISOString(),ends_at:endsAt.toISOString(),approval_required:visibility==='approval_required',updated_at:new Date().toISOString()}).eq('id',eventId);await audit(ctx.db,eventId,runId,ctx.user.id,ctx.isAdmin?'admin_updated_event':ctx.architect?'architect_updated_event':'lead_updated_event');return NextResponse.json({ok:true,message:'Event details updated.'});
  }
  if(action==='cancel'){
   if(!canManage)return NextResponse.json({error:'Project Lead, assigned Project Architect or Admin access is required.'},{status:403});const reason=text(body.reason,1000);if(!reason)return NextResponse.json({error:'Explain why this event is being cancelled.'},{status:400});await ctx.db.from('project_meetings').update({status:'cancelled',cancelled_at:new Date().toISOString(),cancelled_by:ctx.user.id,updated_at:new Date().toISOString()}).eq('id',eventId);await audit(ctx.db,eventId,runId,ctx.user.id,ctx.isAdmin?'admin_cancelled_event':ctx.architect?'architect_cancelled_event':'lead_cancelled_event',{reason});return NextResponse.json({ok:true,message:'Event cancelled and recorded in the audit history.'});
  }
  if(action==='restrict'){
   if(!canOversee)return NextResponse.json({error:'Assigned Project Architect or Admin access is required.'},{status:403});await ctx.db.from('project_meetings').update({visibility:'project_team',approval_required:false,updated_at:new Date().toISOString()}).eq('id',eventId);await audit(ctx.db,eventId,runId,ctx.user.id,ctx.isAdmin?'admin_restricted_event':'architect_restricted_event');return NextResponse.json({ok:true,message:'Event access is now restricted to the project team.'});
  }
  if(action==='register'){
   if(!['community_learning','approval_required'].includes(event.visibility)||event.event_type!=='learning_session')return NextResponse.json({error:'This event is not open for community registration.'},{status:403});if(event.status!=='scheduled')return NextResponse.json({error:'Registration is not available for this event.'},{status:409});if(event.registration_deadline&&new Date(event.registration_deadline)<=new Date())return NextResponse.json({error:'Registration has closed.'},{status:409});
   const {count}=await ctx.db.from('project_event_registrations').select('id',{count:'exact',head:true}).eq('event_id',eventId).eq('status','reserved');const full=event.capacity!==null&&(count||0)>=event.capacity;const status=event.approval_required?'pending_approval':full?'waitlisted':'reserved';await ctx.db.from('project_event_registrations').upsert({event_id:eventId,project_run_id:runId,user_id:ctx.user.id,event_role:roles.has(text(body.event_role,30))&&['learner','observer'].includes(text(body.event_role,30))?text(body.event_role,30):'learner',status,registered_at:new Date().toISOString(),cancelled_at:null},{onConflict:'event_id,user_id'});await audit(ctx.db,eventId,runId,ctx.user.id,'registration_requested',{status});return NextResponse.json({ok:true,status,message:status==='reserved'?'Your place is confirmed.':status==='waitlisted'?'The event is full, so you joined the waitlist.':'Your request is awaiting approval.'});
  }
  if(action==='cancel_registration'){
   await ctx.db.from('project_event_registrations').update({status:'cancelled',cancelled_at:new Date().toISOString()}).eq('event_id',eventId).eq('user_id',ctx.user.id);const {data:next}=await ctx.db.from('project_event_registrations').select('id,user_id').eq('event_id',eventId).eq('status','waitlisted').order('registered_at').limit(1).maybeSingle();if(next){const until=new Date(Date.now()+24*60*60*1000).toISOString();await ctx.db.from('project_event_registrations').update({status:'offered',offered_until:until}).eq('id',next.id);await notifyUser(ctx.db,{userId:next.user_id,projectId,type:'event_changed',title:`A place is available for ${event.title}`,body:'Accept the offered place within 24 hours from My Events.',actionUrl:'/member/events',dedupeKey:`project-event:${eventId}:${next.user_id}:offer`});}await audit(ctx.db,eventId,runId,ctx.user.id,'registration_cancelled');return NextResponse.json({ok:true,message:'Registration cancelled.'});
  }
  if(action==='accept_offer'){
   const {data:offer}=await ctx.db.from('project_event_registrations').select('id,offered_until').eq('event_id',eventId).eq('user_id',ctx.user.id).eq('status','offered').maybeSingle();if(!offer)return NextResponse.json({error:'No active waitlist offer was found.'},{status:404});if(!offer.offered_until||new Date(offer.offered_until)<=new Date()){await ctx.db.from('project_event_registrations').update({status:'cancelled',cancelled_at:new Date().toISOString()}).eq('id',offer.id);return NextResponse.json({error:'This offer has expired.'},{status:410})}await ctx.db.from('project_event_registrations').update({status:'reserved',decided_at:new Date().toISOString()}).eq('id',offer.id);await audit(ctx.db,eventId,runId,ctx.user.id,'waitlist_offer_accepted');return NextResponse.json({ok:true,message:'Your event place is confirmed.'});
  }
  if(action==='decide_registration'){
   if(!canManage)return NextResponse.json({error:'Project Lead, assigned Project Architect or Admin access is required.'},{status:403});const registrationId=text(body.registration_id,80),decision=text(body.decision,20);if(!registrationId||!['reserved','declined'].includes(decision))return NextResponse.json({error:'Choose approve or decline.'},{status:400});await ctx.db.from('project_event_registrations').update({status:decision,decided_by:ctx.user.id,decided_at:new Date().toISOString()}).eq('id',registrationId).eq('event_id',eventId).eq('status','pending_approval');await audit(ctx.db,eventId,runId,ctx.user.id,'registration_decided',{registration_id:registrationId,decision});return NextResponse.json({ok:true,message:'Registration decision recorded.'});
  }
  if(action==='review'){
   const isReviewer=ctx.membership?.team_role==='reviewer';if(!isReviewer&&!ctx.isAdmin)return NextResponse.json({error:'The assigned Project Reviewer or Admin fallback is required.'},{status:403});const outcome=text(body.outcome,30),reason=text(body.reason,3000),actionItems=text(body.action_items,3000);if(!outcomes.has(outcome)||!reason)return NextResponse.json({error:'Choose an outcome and explain the decision.'},{status:400});const {data:presenter}=await ctx.db.from('project_event_participants').select('id').eq('event_id',eventId).eq('user_id',ctx.user.id).eq('event_role','presenter').maybeSingle();if(presenter)return NextResponse.json({error:'A presenter cannot review their own event.'},{status:409});const {error}=await ctx.db.from('project_event_reviews').insert({event_id:eventId,project_run_id:runId,reviewer_user_id:ctx.user.id,outcome,reason,action_items:actionItems||null});if(error)return NextResponse.json({error:error.code==='23505'?'This event already has a formal outcome. Schedule a revision event to preserve history.':error.message},{status:409});await audit(ctx.db,eventId,runId,ctx.user.id,ctx.isAdmin?'admin_review_fallback':'review_recorded',{outcome});return NextResponse.json({ok:true,message:'Formal review outcome recorded.'});
  }
  return NextResponse.json({error:'Unknown project-event action.'},{status:400});
 }catch(error){console.error('project events error',error);return NextResponse.json({error:'Unable to update this project event.'},{status:500});}
}
