import {notFound,redirect} from 'next/navigation';
import {serviceDb} from '@/lib/project-flow';
import {createServerSupabaseClient} from '@/lib/supabase/server';
import ProjectDataGovernance from '@/components/ProjectDataGovernance';
import ProjectConversationReadMarker from '@/components/ProjectConversationReadMarker';
import ProjectCompletionRequestPanel from '@/components/ProjectCompletionRequestPanel';
import ProjectContributionStatusPanel from '@/components/ProjectContributionStatusPanel';
import styles from './phase4-workspace.module.css';

type Membership={membership_status:string;project_run_id:string|null;team_role:string;project_runs:{status:string}|null};type TeamRow={user_id:string;team_role:string;membership_status:string};type ProfileRow={id:string;full_name:string|null};type DataSourceRow={id:string;name:string;owner_user_id:string|null;version_label:string|null;external_url:string;provenance:string|null;download_policy:string;publish_policy:string};type DataVersionRow={id:string;data_source_id:string;version_label:string;external_url:string;change_summary:string|null;created_at:string};type ConversationRow={id:string;author_user_id:string;created_at:string};
type Readiness={ready:boolean;required_milestones:number;completed_milestones:number;required_tasks:number;completed_tasks:number;project_members_requiring_proof:number;members_with_verified_proof:number;pending_contributions:number;presentation_required:boolean;presentation_status:string};type CompletionRequest={id:string;status:string;review_notes:string|null;requested_at:string;reviewed_at:string|null};
const emptyReadiness:Readiness={ready:false,required_milestones:0,completed_milestones:0,required_tasks:0,completed_tasks:0,project_members_requiring_proof:0,members_with_verified_proof:0,pending_contributions:0,presentation_required:false,presentation_status:'not_booked'};
function humanise(value:string|undefined|null){return(value||'member').replaceAll('_',' ').replace(/\b\w/g,letter=>letter.toUpperCase())}

export default async function ProjectWorkspaceGate({children,params}:{children:React.ReactNode;params:Promise<{id:string}>}){
 const {id}=await params;const supabase=await createServerSupabaseClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect(`/signin?next=${encodeURIComponent(`/member/projects/${id}`)}`);const isAdmin=user.app_metadata?.role==='admin';const service=serviceDb();const gateDb=service||supabase;const [{data:project},{data:membershipResult}]=await Promise.all([gateDb.from('projects').select('id,title,summary,status').eq('id',id).maybeSingle(),gateDb.from('project_members').select('membership_status,project_run_id,team_role,project_runs(status)').eq('project_id',id).eq('user_id',user.id).in('membership_status',['waiting','active','completed']).order('joined_at',{ascending:false}).limit(1).maybeSingle()]);const membership=membershipResult as unknown as Membership|null;if(!project||(!membership&&!isAdmin))notFound();
 let runStatus=membership?.project_runs?.status||null;if(!isAdmin&&(!membership||!['active','completed'].includes(membership.membership_status)||!runStatus||!['active','review','completed'].includes(runStatus)))redirect('/member#applications');let runId=membership?.project_run_id||null;if(!runId&&isAdmin){const {data:latestRun}=await gateDb.from('project_runs').select('id,status').eq('project_id',id).in('status',['active','review','completed']).order('run_number',{ascending:false}).limit(1).maybeSingle();runId=latestRun?.id||null;runStatus=latestRun?.status||null}
 let teamRows:TeamRow[]=[],dataSources:DataSourceRow[]=[],dataVersions:DataVersionRow[]=[],conversationRows:ConversationRow[]=[];let architectUserId:string|null=null,lastReadAt:string|null=null;let readiness:Readiness=emptyReadiness;let completionRequest:CompletionRequest|null=null;
 if(runId){const [teamResult,dataResult,versionResult,architectResult,conversationResult,readResult,readinessResult,completionResult]=await Promise.all([
  supabase.from('project_members').select('user_id,team_role,membership_status').eq('project_id',id).eq('project_run_id',runId).in('membership_status',['waiting','active','completed']).order('joined_at'),
  supabase.from('project_data_sources').select('id,name,owner_user_id,version_label,external_url,provenance,download_policy,publish_policy').eq('project_id',id).eq('project_run_id',runId).order('updated_at',{ascending:false}),
  supabase.from('project_data_source_versions').select('id,data_source_id,version_label,external_url,change_summary,created_at').eq('project_run_id',runId).order('created_at',{ascending:false}).limit(100),
  supabase.from('project_architect_assignments').select('user_id').eq('project_id',id).eq('assignment_status','active').limit(1).maybeSingle(),
  supabase.from('project_discussions').select('id,author_user_id,created_at').eq('project_id',id).eq('project_run_id',runId).order('created_at',{ascending:false}).limit(100),
  supabase.from('project_discussion_reads').select('last_read_at').eq('project_run_id',runId).eq('user_id',user.id).maybeSingle(),
  supabase.rpc('project_run_completion_readiness',{target_run:runId}),
  supabase.from('project_completion_requests').select('id,status,review_notes,requested_at,reviewed_at').eq('project_run_id',runId).order('requested_at',{ascending:false}).limit(1).maybeSingle()
 ]);teamRows=(teamResult.data||[]) as TeamRow[];dataSources=(dataResult.data||[]) as DataSourceRow[];dataVersions=(versionResult.data||[]) as DataVersionRow[];architectUserId=architectResult.data?.user_id||null;conversationRows=(conversationResult.data||[]) as ConversationRow[];lastReadAt=readResult.data?.last_read_at||null;readiness=(readinessResult.data||emptyReadiness) as Readiness;completionRequest=(completionResult.data||null) as CompletionRequest|null}
 const unreadCount=conversationRows.filter(row=>row.author_user_id!==user.id&&(!lastReadAt||new Date(row.created_at)>new Date(lastReadAt))).length;const lastMessageId=conversationRows[0]?.id||null;const profileIds=[...new Set([...teamRows.map(member=>member.user_id),...dataSources.map(source=>source.owner_user_id).filter((value):value is string=>Boolean(value)),...(architectUserId?[architectUserId]:[])])];const {data:profilesData}=profileIds.length?await supabase.from('profiles').select('id,full_name').in('id',profileIds):{data:[] as ProfileRow[]};const profiles=(profilesData||[]) as ProfileRow[];const profileNames=new Map(profiles.map(profile=>[profile.id,profile.full_name||'Mettelo member']));const workspaceStatus=(runStatus||project.status||'active').replaceAll('_',' ');const canLead=isAdmin||membership?.team_role==='project_lead';const canReviewCompletion=isAdmin||architectUserId===user.id;const governedSources=dataSources.map(source=>({...source,owner_name:source.owner_user_id?profileNames.get(source.owner_user_id)||'Project member':'Not assigned'}));
 return <div className={styles.workspace}><a className={styles.skipLink} href="#project-workspace-content">Skip to project workspace</a><header className={styles.header}><div className={styles.headerInner}><div><p className={styles.breadcrumb}><a href="/member#projects">My Mettelo</a> / Project workspace</p><h1 className={styles.title}>{project.title}</h1><div className={styles.meta} aria-label="Project status and your role"><span className={styles.badge}>{humanise(workspaceStatus)}</span><span className={styles.badge}>Your role: {humanise(membership?.team_role||(isAdmin?'admin':'member'))}</span></div></div></div></header><div className={styles.body}>
  <nav className={styles.nav} aria-label="Project workspace navigation"><p className={styles.navTitle}>Project workspace</p><a href="#phase4-overview">Overview</a><a href="#delivery">Tasks</a><a href="#discussion">Conversation{unreadCount>0?` · ${unreadCount} unread`:''}</a><a href="#phase4-data-governance">Data</a><a href="#meetings">Events</a><a href="#phase4-contributions">Contributions</a><a href="#mettelo-lab">Mettelo Lab</a>{(canLead||canReviewCompletion)&&<a href="#phase4-completion">Delivery health</a>}</nav>
  <main id="project-workspace-content" className={styles.main} tabIndex={-1}><section id="phase4-overview" className={styles.kickoff} aria-labelledby="phase4-overview-title"><span className={styles.cardLabel}>PROJECT WORKSPACE</span><h2 id="phase4-overview-title">Move through the project with confidence.</h2><p className={styles.kickoffLead}>Start with the plan, organise the work, collaborate in Mettelo Lab, run project events and finish with verified Proof.</p><div className={styles.grid}><a className={styles.card} href="#problem"><span className={styles.cardLabel}>01</span><strong>Plan</strong><span>Define the problem and governed data sources.</span></a><a className={styles.card} href="#delivery"><span className={styles.cardLabel}>02</span><strong>Work</strong><span>Organise workstreams, tasks and reviewed deliverables.</span></a><a className={styles.card} href="#mettelo-lab"><span className={styles.cardLabel}>03</span><strong>Mettelo Lab</strong><span>Collaborate with your cohort and see what to do next.</span></a><a className={styles.card} href="#meetings"><span className={styles.cardLabel}>04</span><strong>Events</strong><span>Run working sessions, reviews and final presentations.</span></a><a className={styles.card} href="#completion"><span className={styles.cardLabel}>05</span><strong>Finish</strong><span>Complete verified Proof and project close-out.</span></a></div></section>
   <ProjectDataGovernance projectId={id} projectRunId={runId} currentUserId={user.id} canLead={canLead} sources={governedSources} versions={dataVersions}/><ProjectContributionStatusPanel projectId={id} projectRunId={runId}/><ProjectCompletionRequestPanel projectId={id} projectRunId={runId} readiness={readiness} initialRequest={completionRequest} canLead={Boolean(membership?.team_role==='project_lead')} canReview={canReviewCompletion} projectStatus={workspaceStatus}/><div className={styles.content}>{children}</div><ProjectConversationReadMarker projectRunId={runId} lastMessageId={lastMessageId}/>
  </main></div></div>;
}
