import type { Metadata } from 'next';
import SubmissionForm from '@/components/SubmissionForm';

export const metadata:Metadata={title:'Mettelo Labs Projects',description:'Explore Mettelo Labs project briefs and apply to build real work with multidisciplinary Data & AI teams.'};

export default function ProjectsPage(){
  const projects=[
    {status:'PILOT BRIEF',tone:'blue',title:'Nigeria Cost of Living Data Explorer',copy:'A proposed public-facing data product turning fragmented price and location data into useful household insight.',meta:['8-week pilot','Remote','Multidisciplinary'],roles:'Data Analyst · Data Engineer · UX · Research · Project Lead · QA'},
    {status:'PILOT BRIEF',tone:'blue',title:'Open Data Quality Monitor',copy:'A proposed reusable framework for profiling public datasets and surfacing missingness, freshness and consistency issues.',meta:['6-week pilot','Remote','Data + Engineering'],roles:'Analytics Engineer · Data Analyst · Python · Documentation · QA'},
    {status:'IN DESIGN',tone:'',title:'Graduate Data Job Market Tracker',copy:'A proposed recurring insight product on early-career Data & AI hiring patterns across Nigeria and the UK.',meta:['Research','Nigeria + UK','Remote'],roles:'Research · Data Analyst · NLP · Visualisation · Storytelling'}
  ];
  return <>
    <section className="hero"><div className="shell heroGrid"><div><div className="eyebrow">Mettelo Labs · Projects</div><h1>Build work that proves what you can do.</h1><p className="heroLead">Labs turns real problems into structured briefs with clear roles, ownership, review and contributor credit. The first public pilot briefs are being prepared now.</p><div className="actions"><a className="button dark" href="#pilot-projects">Explore pilot briefs →</a></div></div><aside className="heroPanel"><div className="heroPanelTop"><span className="liveDot">Labs workflow ready</span><span className="chip">PILOT</span></div><h3>One brief. One team. Visible contribution.</h3><p>Every launched project should have a defined outcome, role expectations, weekly commitment, a Project Lead, technical review and a contribution record.</p><div className="path"><span>Discover</span><span>Apply</span><span>Build</span><span>Review</span><span>Publish</span><span>Credit</span></div></aside></div></section>

    <section className="section" id="pilot-projects"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">First Labs briefs</div><h2>See what is being prepared.</h2></div><p>These are pilot briefs, not open vacancies. Application status becomes live only when a brief has an assigned lead, scope and confirmed start window.</p></div><div className="projectGrid">{projects.map(p=><article className="projectCard" key={p.title}><div><span className={`chip ${p.tone}`}>{p.status}</span><h3>{p.title}</h3><p>{p.copy}</p><div className="metaRow">{p.meta.map(m=><span className="metaPill" key={m}>{m}</span>)}</div><small><strong>Likely roles:</strong> {p.roles}</small></div><div className="projectFoot"><span>{p.status==='IN DESIGN'?'Scope in design':'Pilot brief being finalised'}</span><a className="button ghost" href="#interest">Register interest</a></div></article>)}</div></div></section>

    <section className="section softSection" id="how-it-works"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">Labs operating model</div><h2>Real work needs structure, not chat-room coordination.</h2></div><p>Project Leads own delivery. Mettelo provides governance, application routing, GitHub structure, review controls and the proof layer.</p></div><div className="grid4"><article className="card"><div className="cardNumber">01 / PUBLISH</div><h3 style={{marginTop:24}}>Clear project brief</h3><p>Problem, outcomes, dataset, roles, skills, duration, weekly commitment, lead and deadline.</p></article><article className="card"><div className="cardNumber">02 / SELECT</div><h3 style={{marginTop:24}}>Structured applications</h3><p>Applications land in one review queue and route to the relevant Project Lead.</p></article><article className="card"><div className="cardNumber">03 / DELIVER</div><h3 style={{marginTop:24}}>GitHub + project team</h3><p>Accepted contributors work through issues, milestones, documentation and an accountable project rhythm.</p></article><article className="card"><div className="cardNumber">04 / PROVE</div><h3 style={{marginTop:24}}>Review and contribution credit</h3><p>QA closes the project; outputs become a showcase and verified contribution becomes professional evidence.</p></article></div></div></section>

    <section className="section" id="interest"><div className="shell formShell"><div><div className="eyebrow">Project interest</div><h2 style={{fontSize:'clamp(2.5rem,4vw,4rem)',margin:0}}>Tell us where you could contribute.</h2><p className="lead">This registers interest in a pilot brief. It is not an acceptance or confirmed project place. We will only move to selection when the brief is live.</p></div><SubmissionForm formType="project_application" submitLabel="Register project interest →" successMessage="Interest received. We will contact you if this brief opens and your selected contribution area is relevant."><label htmlFor="project-name">Full name *</label><input id="project-name" required name="name" autoComplete="name"/><label htmlFor="project-email">Email *</label><input id="project-email" required name="email" type="email" autoComplete="email"/><label htmlFor="project-choice">Pilot brief *</label><select id="project-choice" name="project" required defaultValue=""><option value="" disabled>Select a brief</option><option>Nigeria Cost of Living Data Explorer</option><option>Open Data Quality Monitor</option><option>Graduate Data Job Market Tracker</option></select><label htmlFor="project-role">Contribution area *</label><select id="project-role" name="role" required defaultValue=""><option value="" disabled>Select a role area</option><option>Data Analysis / BI</option><option>Data Engineering</option><option>AI / ML</option><option>Research / UX</option><option>Project Lead</option><option>QA / Technical Review</option><option>Documentation / Storytelling</option></select><label htmlFor="project-profile">GitHub, LinkedIn or portfolio</label><input id="project-profile" name="profile" type="url" placeholder="https://"/><label htmlFor="project-contribution">What specifically could you contribute? *</label><textarea id="project-contribution" name="contribution" required/><label className="consent"><input required type="checkbox" name="consent" value="yes"/><span>I agree that Mettelo can use this information to assess and respond to my project interest.</span></label></SubmissionForm></div></section>

    <section className="section compact"><div className="shell"><div className="ctaBand"><div><div className="cardNumber">FOR ORGANISATIONS</div><h2>Have a real problem worth solving?</h2><p>Organisations can bring a scoped challenge, data, expertise or resources into the Labs review process.</p></div><div className="actions"><a className="button dark" href="/partnership">Submit a problem brief →</a><a className="button ghost" href="https://github.com/Mettelo" target="_blank" rel="noopener noreferrer">Explore GitHub</a></div></div></div></section>
  </>;
}
