import type { Metadata } from 'next';
import SubmissionForm from '@/components/SubmissionForm';
import ProjectApplicationForm from '@/components/ProjectApplicationForm';
import { createPublicSupabaseClient } from '@/lib/supabase/public';

export const metadata:Metadata={title:'Mettelo Labs Projects',description:'Explore Mettelo Labs project briefs by domain, tools and level, then build real work with multidisciplinary Data & AI teams.'};
export const dynamic='force-dynamic';

type Role={id:string;title:string;discipline:string|null;openings:number};
type TaxonomyRef={slug:string;name:string};
type Project={id:string;slug:string;title:string;summary:string;status:string;location:string|null;location_type:string|null;difficulty_level:string|null;duration_weeks:number|null;weekly_commitment:string|null;application_deadline:string|null;github_url:string|null;project_roles?:Role[];project_domains?:{is_primary:boolean;domains:TaxonomyRef|null}[];project_tools?:{tools:TaxonomyRef|null}[];project_methods?:{methods:TaxonomyRef|null}[]};
type Search={domain?:string|string[];tool?:string|string[];level?:string|string[];status?:string|string[]};

function one(value:string|string[]|undefined){return Array.isArray(value)?value[0]||'':value||'';}
function statusLabel(status:string){return status==='pilot'?'PILOT BRIEF':status==='recruiting'?'RECRUITING':status==='active'?'IN DELIVERY':status==='review'?'IN REVIEW':status==='completed'?'COMPLETED':status.toUpperCase();}
function tone(status:string){return status==='recruiting'?'green':status==='pilot'?'blue':'';}
function titleCase(value:string){return value.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());}

export default async function ProjectsPage({searchParams}:{searchParams?:Promise<Search>}){
  const params=await searchParams||{};const domain=one(params.domain);const tool=one(params.tool);const level=one(params.level);const statusFilter=one(params.status);
  const supabase=createPublicSupabaseClient();let projects:Project[]=[];let domains:TaxonomyRef[]=[];let tools:TaxonomyRef[]=[];let loadError=false;
  if(supabase){
    const [projectResult,domainResult,toolResult]=await Promise.all([
      supabase.from('projects').select('id,slug,title,summary,status,location,location_type,difficulty_level,duration_weeks,weekly_commitment,application_deadline,github_url,project_roles(id,title,discipline,openings),project_domains(is_primary,domains(slug,name)),project_tools(tools(slug,name)),project_methods(methods(slug,name))').in('status',['pilot','recruiting','active','review','completed']).eq('visibility','public').order('created_at',{ascending:false}),
      supabase.from('domains').select('slug,name').eq('is_active',true).order('sort_order'),supabase.from('tools').select('slug,name').eq('is_active',true).order('sort_order')
    ]);
    if(projectResult.error)loadError=true;else projects=(projectResult.data||[]) as unknown as Project[];domains=(domainResult.data||[]) as TaxonomyRef[];tools=(toolResult.data||[]) as TaxonomyRef[];
  }else loadError=true;
  const filtered=projects.filter(p=>(!domain||p.project_domains?.some(x=>x.domains?.slug===domain))&&(!tool||p.project_tools?.some(x=>x.tools?.slug===tool))&&(!level||p.difficulty_level===level)&&(!statusFilter||p.status===statusFilter));
  const pilotTitles=projects.filter(p=>p.status==='pilot').map(p=>p.title);const recruiting=projects.filter(p=>p.status==='recruiting'&&(p.project_roles||[]).length>0).map(p=>({id:p.id,title:p.title,roles:(p.project_roles||[]).map(r=>({id:r.id,title:r.title}))}));const hasFilters=Boolean(domain||tool||level||statusFilter);

  return <>
    <section className="hero"><div className="shell heroGrid"><div><div className="eyebrow">Mettelo Labs · Projects</div><h1>Find work that matches what you want to build.</h1><p className="heroLead">Explore real Data & AI project briefs by industry, tools, level and stage. Join work where your contribution can become credible professional Proof.</p><div className="actions"><a className="button dark" href="#open-projects">Explore Projects →</a></div></div><aside className="heroPanel"><div className="heroPanelTop"><span className="liveDot">Labs database live</span><span className="chip">REAL WORK</span></div><h3>Domain. Tools. Role. Contribution.</h3><p>Choose work that fits the capability you already have, the capability you want to build and the evidence you want to leave with.</p><div className="path"><span>Discover</span><span>Apply</span><span>Build</span><span>Review</span><span>Prove</span></div></aside></div></section>

    <section className="section" id="open-projects"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">Find your project</div><h2>Filter by what matters to you.</h2></div><p>Start with a domain or tool, then narrow by experience level and project stage. Filters are shareable in the page URL.</p></div>
      <form className="projectFilterPanel" method="get" action="/projects#open-projects"><div><label htmlFor="domain-filter">Domain</label><select id="domain-filter" name="domain" defaultValue={domain}><option value="">All domains</option>{domains.map(item=><option key={item.slug} value={item.slug}>{item.name}</option>)}</select></div><div><label htmlFor="tool-filter">Tool / technology</label><select id="tool-filter" name="tool" defaultValue={tool}><option value="">All tools</option>{tools.map(item=><option key={item.slug} value={item.slug}>{item.name}</option>)}</select></div><div><label htmlFor="level-filter">Level</label><select id="level-filter" name="level" defaultValue={level}><option value="">All levels</option><option value="entry">Entry</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select></div><div><label htmlFor="status-filter">Stage</label><select id="status-filter" name="status" defaultValue={statusFilter}><option value="">All stages</option><option value="pilot">Pilot</option><option value="recruiting">Recruiting</option><option value="active">Active</option><option value="review">Review</option><option value="completed">Completed</option></select></div><div className="projectFilterActions"><button className="button dark" type="submit">Apply filters</button>{hasFilters&&<a className="button ghost" href="/projects#open-projects">Clear</a>}</div></form>
      <div className="projectResultsMeta"><strong>{filtered.length}</strong><span>{filtered.length===1?'project matches':'projects match'} your filters</span></div>
      {loadError?<div className="emptyState panel"><h3>Projects are temporarily unavailable.</h3><p>The project database could not be reached. Please try again later or use the Community page for current updates.</p></div>:filtered.length?<div className="projectGrid">{filtered.map(p=>{const roles=(p.project_roles||[]).map(r=>r.title).join(' · ');const primary=p.project_domains?.find(x=>x.is_primary)?.domains||p.project_domains?.[0]?.domains;const projectTools=(p.project_tools||[]).map(x=>x.tools).filter(Boolean) as TaxonomyRef[];const projectMethods=(p.project_methods||[]).map(x=>x.methods).filter(Boolean) as TaxonomyRef[];const meta=[p.difficulty_level?titleCase(p.difficulty_level):null,p.duration_weeks?`${p.duration_weeks} weeks`:null,p.location_type?titleCase(p.location_type):p.location,p.weekly_commitment].filter(Boolean) as string[];return <article className="projectCard" key={p.id}><div><div className="projectCardTop"><span className={`chip ${tone(p.status)}`}>{statusLabel(p.status)}</span>{primary&&<span className="domainTag">{primary.name}</span>}</div><h3>{p.title}</h3><p>{p.summary}</p>{projectTools.length>0&&<div className="projectTagRow" aria-label="Project tools">{projectTools.slice(0,5).map(item=><span key={item.slug}>{item.name}</span>)}</div>}{projectMethods.length>0&&<div className="projectMethodLine"><strong>Methods:</strong> {projectMethods.slice(0,3).map(item=>item.name).join(' · ')}</div>}<div className="metaRow">{meta.map(m=><span className="metaPill" key={m}>{m}</span>)}</div>{roles&&<small><strong>Roles:</strong> {roles}</small>}</div><div className="projectFoot"><span>{p.status==='recruiting'?'Applications open':p.status==='pilot'?'Register interest':p.status==='completed'?'Published proof':'Project in progress'}</span>{p.status==='recruiting'?<a className="button dark" href="/signin?next=%2Fprojects%23apply">Sign in & apply →</a>:p.status==='completed'?<a className="button ghost" href="/showcase">View proof →</a>:p.status==='pilot'?<a className="button ghost" href="#interest">Register interest</a>:<a className="button ghost" href="/newsletter">Follow updates</a>}</div></article>;})}</div>:<div className="emptyState panel"><h3>{hasFilters?'No projects match those filters yet.':'No public Labs projects right now.'}</h3><p>{hasFilters?'Try removing one filter or explore another domain. New tagged projects will appear here as they are published.':'New briefs appear here only after they pass the Mettelo project review process.'}</p>{hasFilters?<a className="button ghost" href="/projects#open-projects">Clear filters</a>:<a className="button ghost" href="/newsletter">Get project alerts →</a>}</div>}
    </div></section>

    {recruiting.length>0&&<section className="section softSection" id="apply"><div className="shell formShell"><div><div className="eyebrow">Labs application</div><h2>Apply to work you are ready to own.</h2><p className="lead">Applications are tied to your My Mettelo account. Be specific about the role, your evidence and what you can deliver. Your status appears in the member workspace after submission.</p></div><ProjectApplicationForm projects={recruiting}/></div></section>}

    <section className="section softSection" id="how-it-works"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">Labs operating model</div><h2>Real work needs structure, not chat-room coordination.</h2></div><p>Project Leads own delivery. Mettelo provides governance, application routing, collaboration, review controls and the Proof layer.</p></div><div className="grid4"><article className="card"><div className="cardNumber">01 / PUBLISH</div><h3>Clear project brief</h3><p>Problem, domain, tools, roles, skills, duration, commitment, lead and deadline.</p></article><article className="card"><div className="cardNumber">02 / SELECT</div><h3>Structured applications</h3><p>Applications route into a controlled review workflow instead of email chains.</p></article><article className="card"><div className="cardNumber">03 / DELIVER</div><h3>Project workspace</h3><p>Accepted contributors work through accountable tasks, milestones, meetings and documentation.</p></article><article className="card"><div className="cardNumber">04 / PROVE</div><h3>Review and contribution credit</h3><p>Reviewed outputs become a showcase and verified contribution becomes professional evidence.</p></article></div></div></section>

    {pilotTitles.length>0&&<section className="section" id="interest"><div className="shell formShell"><div><div className="eyebrow">Pilot interest</div><h2>Tell us where you could contribute.</h2><p className="lead">This registers interest only. A pilot becomes an application only when the project status changes to Recruiting.</p></div><SubmissionForm formType="project_application" submitLabel="Register project interest →" successMessage="Interest received. We will contact you if the project opens and your contribution area is relevant."><label htmlFor="project-name">Full name *</label><input id="project-name" required name="name" autoComplete="name"/><label htmlFor="project-email">Email *</label><input id="project-email" required name="email" type="email" autoComplete="email"/><label htmlFor="project-choice">Pilot brief *</label><select id="project-choice" name="project" required defaultValue=""><option value="" disabled>Select a brief</option>{pilotTitles.map(title=><option key={title}>{title}</option>)}</select><label htmlFor="project-role">Contribution area *</label><select id="project-role" name="role" required defaultValue=""><option value="" disabled>Select a role area</option><option>Data Analysis / BI</option><option>Data Engineering</option><option>AI / ML</option><option>Research / UX</option><option>Project Lead</option><option>QA / Technical Review</option><option>Documentation / Storytelling</option></select><label htmlFor="project-profile">GitHub, LinkedIn or portfolio</label><input id="project-profile" name="profile" type="url" placeholder="https://"/><label htmlFor="project-contribution">What specifically could you contribute? *</label><textarea id="project-contribution" name="contribution" required/><label className="consent"><input required type="checkbox" name="consent" value="yes"/><span>I agree that Mettelo can use this information to assess and respond to my project interest.</span></label></SubmissionForm></div></section>}

    <section className="section compact"><div className="shell"><div className="ctaBand"><div><div className="cardNumber">FOR ORGANISATIONS</div><h2>Have a real problem worth solving?</h2><p>Bring a scoped challenge, data, expertise or resources into the Labs review process.</p></div><div className="actions"><a className="button dark" href="/partnership">Submit a problem brief →</a><a className="button ghost" href="https://github.com/Mettelo" target="_blank" rel="noopener noreferrer">Explore GitHub</a></div></div></div></section>
  </>;
}
