import type {Metadata} from 'next';
import {notFound} from 'next/navigation';
import {getPublishedCapabilityPath,projectAvailability} from '@/lib/capability-paths-public';
import '../../capability-paths-public.css';

export const dynamic='force-dynamic';

export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{
 const {slug}=await params;const path=await getPublishedCapabilityPath(slug);if(!path)return{title:'Capability Path'};
 return{title:`${path.name} Capability Path`,description:path.short_description||path.progression_summary||`Build toward ${path.target_outcome} through real Mettelo projects.`,alternates:{canonical:`/projects/paths/${path.slug}`}};
}

export default async function CapabilityPathDetailPage({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const path=await getPublishedCapabilityPath(slug);if(!path)notFound();
 const publicPlacements=path.placements.filter(item=>item.project);const availableCount=publicPlacements.filter(item=>projectAvailability(item.project!.status,item.project!.application_deadline).available).length;
 return <>
  <section className="capabilityPathDetailHero"><div className="shell"><div className="capabilityPathBreadcrumb"><a href="/projects">Projects</a><span aria-hidden="true">/</span><a href="/projects/paths">Capability Paths</a><span aria-hidden="true">/</span><span>{path.name}</span></div><div className="capabilityPathSummaryGrid"><div><div className="eyebrow">{path.target_role}</div><h1>{path.name}</h1><p>{path.description||path.short_description||path.progression_summary||`A recommended sequence of real projects designed to build toward ${path.target_outcome}.`}</p><div className="actions"><a className="button dark" href="#path-roadmap">Explore the roadmap ↓</a><a className="button ghost" href={`/projects?path=${encodeURIComponent(path.slug)}#projects`}>View Path projects in discovery →</a></div></div><aside className="capabilityPathFacts" aria-label="Capability Path facts"><div><span>Target capability</span><strong>{path.target_outcome}</strong></div><div><span>Path structure</span><strong>{path.project_count} projects · {path.stage_count} stages</strong></div><div><span>Currently available</span><strong>{availableCount} project{availableCount===1?'':'s'}</strong></div><div><span>Progression</span><strong>Recommended, not restrictive</strong></div></aside></div></div></section>
  <main className="capabilityPathRoadmap" id="path-roadmap"><div className="shell">{path.stages.map(stage=>{const stageProjects=path.placements.filter(item=>item.stage_id===stage.id);if(!stageProjects.length)return null;return <section className="capabilityPathStage" key={stage.id} aria-labelledby={`stage-${stage.slug}`}><header className="capabilityPathStageHead"><small>STAGE {String(stage.position).padStart(2,'0')}</small><h2 id={`stage-${stage.slug}`}>{stage.name}</h2>{stage.description&&<p>{stage.description}</p>}</header><div className="capabilityPathProjects">{stageProjects.map(item=>{const project=item.project;const availability=project?projectAvailability(project.status,project.application_deadline):{label:'Upcoming project',available:false};return <article className="capabilityPathProject" key={item.project_id}><div className="capabilityPathProjectNo">{String(item.position).padStart(2,'0')}</div><div><h3>{project?.title||'Upcoming project'}</h3>{project?.summary&&<p>{project.summary}</p>}<div className="capabilityPathProjectMeaning"><div><small>Competency focus</small><p>{item.competency_focus}</p></div><div><small>Capability built</small><p>{item.capability_built}</p></div>{item.path_outcome&&<div><small>Path outcome</small><p>{item.path_outcome}</p></div>}{item.prerequisite_project_id&&<div><small>Recommended prerequisite</small><p>Builds on an earlier project in this Path.</p></div>}</div></div><div className="capabilityPathProjectState"><span className={availability.available?'available':''}>{availability.label}</span>{project?<a href={`/projects/${project.id}?path=${encodeURIComponent(path.slug)}`}>View project →</a>:<span>Details not public yet</span>}</div></article>})}</div></section>})}<section className="capabilityPathFlexibility"><h2>A Path gives direction, not restriction.</h2><p>You can explore projects outside this sequence at any time. Prerequisites shown here describe recommended progression; the actual project brief and role requirements determine whether applications or interest are currently available.</p></section></div></main>
 </>;
}
