import type { Metadata } from 'next';
import SubmissionForm from '@/components/SubmissionForm';
export const metadata:Metadata={title:'Contribute',description:'Apply to contribute to Mettelo Labs, open source, community, product, research, content and operations.'};

export default function ContributePage(){
 const areas=[['Labs & Projects','Data, AI, engineering, analytics, research, UX and project delivery.'],['Open Source','Code, datasets, documentation, QA, tooling and reusable frameworks.'],['Community','Moderation, member support, focused groups, mentoring and community operations.'],['Product & Design','Platform research, UX, UI, product thinking and member experience.'],['Content & Media','Editorial, social content, documentation, video, event content and storytelling.'],['Partnerships & Growth','Organisations, speakers, ecosystem relationships, outreach and partnership operations.'],['Research','Surveys, reports, benchmarks, data collection and practical insight.'],['Operations','Project coordination, processes, contributor support, QA and internal systems.']];
 return <>
 <section className="hero"><div className="shell heroGrid"><div><div className="eyebrow">Build Mettelo</div><h1>Contribution is where capability becomes visible.</h1><p className="heroLead">Apply where you can create clear value, take ownership and help the ecosystem become more useful.</p></div><aside className="heroPanel"><span className="chip">WHAT MATTERS</span><h3 style={{marginTop:18}}>Specific contribution beats a generic offer to help.</h3><p>Tell us what you can own, what you have done before, how much time you can commit and the outcome you can help create.</p><div className="path"><span>Choose</span><span>Own</span><span>Deliver</span><span>Review</span><span>Credit</span></div></aside></div></section>
 <section className="section"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">Contribution areas</div><h2>Choose where your capability is most useful.</h2></div><p>Mettelo is not asking everyone to do everything. Good contribution has a defined owner, a useful outcome and enough evidence to review.</p></div><div className="grid4">{areas.map(([t,c])=><article className="card" key={t}><h3>{t}</h3><p>{c}</p></article>)}</div></div></section>
 <section className="section softSection"><div className="shell formShell"><div><div className="eyebrow">Contributor application</div><h2 style={{fontSize:'clamp(2.5rem,5vw,4.4rem)',margin:0}}>Apply around a concrete contribution.</h2><p className="lead">Your application enters a shared review queue and can be routed to the Mettelo function that best matches the work.</p></div><SubmissionForm formType="contributor" submitLabel="Submit contributor application →" successMessage="Application received. We will review the contribution area and route it to the relevant lead."><label htmlFor="contributor-name">Full name *</label><input id="contributor-name" required name="name" autoComplete="name"/><label htmlFor="contributor-email">Email *</label><input id="contributor-email" required name="email" type="email" autoComplete="email"/><label htmlFor="contributor-link">LinkedIn or portfolio</label><input id="contributor-link" name="profile" type="url" placeholder="https://"/><label htmlFor="contribution-area">Primary contribution area *</label><select id="contribution-area" name="area" defaultValue="" required><option value="" disabled>Select one</option>{areas.map(([t])=><option key={t}>{t}</option>)}</select><label htmlFor="contribution-specific">What specifically can you help build or improve? *</label><textarea id="contribution-specific" name="contribution" required/><label htmlFor="contribution-evidence">Relevant experience or evidence *</label><textarea id="contribution-evidence" name="evidence" required/><label htmlFor="availability">Weekly availability *</label><select id="availability" name="availability" required defaultValue=""><option value="" disabled>Select one</option><option>1–2 hours</option><option>3–5 hours</option><option>6–8 hours</option><option>8+ hours</option></select><label htmlFor="success-eight-weeks">What would successful contribution look like after 8 weeks?</label><textarea id="success-eight-weeks" name="successOutcome"/><label className="consent"><input required type="checkbox" name="consent" value="yes"/><span>I agree that Mettelo can use this information to assess and respond to my contributor application.</span></label></SubmissionForm></div></section>
 </>;
}
