export default function HomePage(){
  const journeys=[
    ['01 / BUILD','Find a real project','Join multidisciplinary Labs work with clear roles, commitments, outcomes and contributor credits.','/projects','Browse projects'],
    ['02 / ACCESS','Find an opportunity','Discover jobs, referrals, fellowships and volunteer roles with clearer eligibility and trusted sources.','/opportunities','Explore opportunities'],
    ['03 / CONNECT','Join the room','Attend workshops, AMAs, showcases and build sessions with professionals solving similar problems.','/events','See events'],
    ['04 / PROVE','Build your professional record','Turn completed contribution into project credits, capability evidence and recognition.','/spotlight','See recognition']
  ];
  const benefits=[
    ['01','Build experience before opportunity arrives','Work on structured projects and open-source problems instead of waiting for a job title to give you experience.'],
    ['02','Turn contribution into credible proof','Create a stronger professional story through visible project credits, outputs, leadership and peer-reviewed contribution.'],
    ['03','Find people solving similar problems','Meet analysts, engineers, scientists, researchers, mentors and builders who understand the journey you are on.'],
    ['04','Access useful opportunities','Discover jobs, referrals, volunteer roles, fellowships, projects and collaborations with clearer context and eligibility.'],
    ['05','Grow beyond technical skills','Use projects and events to practise communication, leadership, stakeholder thinking, delivery and collaboration.'],
    ['06','Be recognised for useful work','Spotlight and awards make meaningful contribution easier to see.']
  ];
  return <>
    <section className="hero"><div className="shell"><div className="heroGrid">
      <div><div className="eyebrow">Professional capability infrastructure for Data & AI</div><h1>Build capability. Prove it. Get discovered.</h1><p className="heroLead">Mettelo connects Data & AI professionals to serious peers, meaningful work, credible proof and opportunities that can move a career forward.</p><div className="actions"><a className="button dark" href="/join">Join Mettelo free →</a><a className="button ghost" href="/projects">Explore open projects</a></div></div>
      <aside className="heroPanel"><div className="heroPanelTop"><span className="liveDot">Mettelo in motion</span><span className="chip">LIVE</span></div><h3>Something useful should always be happening.</h3><p>Discover projects, events, opportunities and community activity from one public front door.</p><div className="listRow"><div><strong>Labs projects</strong><br/><small>Data · AI · Research · Open source</small></div><a className="chip green" href="/projects">Explore</a></div><div className="listRow"><div><strong>Community events</strong><br/><small>AMAs · Workshops · Showcases</small></div><a className="chip blue" href="/events">Register</a></div><div className="listRow"><div><strong>Opportunity feed</strong><br/><small>Jobs · Referrals · Fellowships · Volunteer</small></div><a className="chip" href="/opportunities">Browse</a></div><div className="path"><span>Connect</span><span>Build</span><span>Contribute</span><span>Prove</span><span>Get discovered</span></div></aside>
    </div><div className="trustStrip"><div className="trustItem"><strong>Community</strong><span>Start with people, not content libraries.</span></div><div className="trustItem"><strong>Real work</strong><span>Build against briefs with accountable teams.</span></div><div className="trustItem"><strong>Credible proof</strong><span>Record contribution, not attendance.</span></div><div className="trustItem"><strong>Opportunity</strong><span>Connect evidence to jobs, referrals and partnerships.</span></div></div></div></section>

    <section className="section compact"><div className="shell"><div className="impactBand"><div className="impactStat"><strong>40+</strong><span>Founding members and growing</span></div><div className="impactStat"><strong>Live</strong><span>Community across Data & AI disciplines</span></div><div className="impactStat"><strong>Open</strong><span>Projects, opportunities and contributor pathways</span></div><div className="impactStat"><strong>Active</strong><span>Events, peer support and community sessions</span></div></div></div></section>

    <section className="section softSection" id="about"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">The problem</div><h2>Talent is everywhere. Meaningful proof and access are not.</h2></div><p>Professional growth is fragmented across courses, portfolios, communities, job boards and networks that rarely connect into one credible journey.</p></div><div className="grid4"><article className="card"><div className="cardNumber">01</div><h3>Learning without experience</h3><p>People can keep collecting knowledge without getting a credible environment to practise delivery.</p></article><article className="card"><div className="cardNumber">02</div><h3>CVs don’t show enough</h3><p>Skills are often claimed rather than demonstrated through useful, visible contribution.</p></article><article className="card"><div className="cardNumber">03</div><h3>Growth is fragmented</h3><p>Projects, mentors, jobs, referrals, events and community often live in separate places.</p></article><article className="card"><div className="cardNumber">04</div><h3>Access is uneven</h3><p>Opportunity still depends too heavily on prior experience, geography and who already knows you.</p></article></div></div></section>

    <section className="section"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">How Mettelo works</div><h2>Turn participation into professional evidence.</h2></div><p>Connect → Build → Contribute → Prove → Get discovered.</p></div><div className="grid4">{journeys.map(([num,title,copy,href,cta])=><article className="card featureCard" key={title}><div><div className="cardNumber">{num}</div><h3 style={{marginTop:28}}>{title}</h3><p>{copy}</p></div><a className="linkArrow" href={href}>{cta} →</a></article>)}</div></div></section>

    <section className="section softSection"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">Why join Mettelo?</div><h2>Because professional growth needs more than information.</h2></div><p>The value is practical: experience, proof, people, opportunity, leadership and recognition.</p></div><div className="benefitGrid">{benefits.map(([n,t,c])=><article className="benefitCard" key={t}><div><div className="benefitIcon">{n}</div><h3>{t}</h3><p>{c}</p></div></article>)}</div></div></section>

    <section className="section" id="projects"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">Featured in Mettelo Labs</div><h2>Open work you can join.</h2></div><a className="linkArrow" href="/projects">Explore all projects →</a></div><div className="projectGrid"><article className="projectCard"><div><span className="chip green">RECRUITING</span><h3>Nigeria Cost of Living Data Explorer</h3><p>Build a public-facing data product around prices, location and household insight.</p><div className="metaRow"><span className="metaPill">8 weeks</span><span className="metaPill">Remote</span><span className="metaPill">6 roles</span></div></div><div className="projectFoot"><span className="statusText">Applications open</span><a className="button dark" href="/projects">View project →</a></div></article><article className="projectCard"><div><span className="chip green">RECRUITING</span><h3>Open Data Quality Monitor</h3><p>Create a reusable approach for profiling datasets and communicating quality issues.</p><div className="metaRow"><span className="metaPill">6 weeks</span><span className="metaPill">Data + Engineering</span><span className="metaPill">5 roles</span></div></div><div className="projectFoot"><span className="statusText">Applications open</span><a className="button dark" href="/projects">View project →</a></div></article><article className="projectCard"><div><span className="chip blue">UPCOMING</span><h3>Graduate Data Job Market Tracker</h3><p>Build recurring insight on early-career Data & AI hiring patterns.</p><div className="metaRow"><span className="metaPill">Research</span><span className="metaPill">Nigeria + UK</span><span className="metaPill">7 roles</span></div></div><div className="projectFoot"><span>Opening soon</span><a className="button ghost" href="/membership">Get alerts</a></div></article></div></div></section>

    <section className="section softSection" id="opportunities"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">Opportunity</div><h2>Useful openings, with enough context to act.</h2></div><a className="linkArrow" href="/opportunities">Explore all opportunities →</a></div><div className="grid3"><article className="card"><span className="chip">JOBS</span><h3>Jobs & referrals</h3><p>Roles with clearer eligibility, location and application context.</p></article><article className="card"><span className="chip">EXPERIENCE</span><h3>Volunteer opportunities</h3><p>Routes to build experience through meaningful external work.</p></article><article className="card"><span className="chip">GROWTH</span><h3>Fellowships & programmes</h3><p>Selected professional development and research opportunities.</p></article></div></div></section>

    <section className="section" id="community"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">Community</div><h2>Find serious peers. Build stronger relationships.</h2></div><a className="linkArrow" href="/community">Explore community →</a></div><div className="grid3"><article className="card"><h3>Discussion & peer support</h3><p>Focused spaces for Data & AI professionals to learn from one another.</p></article><article className="card"><h3>People & mentors</h3><p>Find collaborators, experienced professionals and office hours.</p></article><article className="card"><h3>Pathways into Labs</h3><p>Move from conversation into projects, contribution and proof.</p></article></div></div></section>

    <section className="section softSection" id="events"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">Upcoming events</div><h2>Be in the room.</h2></div><a className="linkArrow" href="/events">View all events →</a></div><div className="grid3"><article className="card"><span className="chip">AMA</span><h3>Breaking into Data & AI in the UK</h3><p>Applications, interviews, evidence and what hiring teams actually look for.</p></article><article className="card"><span className="chip">SHOWCASE</span><h3>Mettelo Labs Project Showcase</h3><p>See what teams are building and how contribution becomes proof.</p></article><article className="card"><span className="chip">WORKSHOP</span><h3>From analysis to commercial impact</h3><p>Practical ways to move beyond reporting into stronger decision support.</p></article></div></div></section>

    <section className="section"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">Proof</div><h2>Completed work becomes evidence.</h2></div><p>The public showcase connects each project to its problem, output, team, repository and verified contributor roles.</p></div><div className="ctaBand"><div><div className="cardNumber">PROJECT SHOWCASE</div><h2>What a completed Mettelo project shows.</h2><p>Problem · Method · Tools · Output · Contributors · Roles · Lessons · Repository · Verified credits.</p></div><div className="actions"><a className="button dark" href="/showcase">Explore project showcase →</a></div></div></div></section>

    <section className="section softSection" id="spotlight"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">Member Spotlight</div><h2>Recognition follows useful contribution.</h2></div><p>Spotlight recognises builders, mentors, project leads, open-source contributors and community champions based on evidence.</p></div><div className="ctaBand"><div><div className="cardNumber">RECOGNITION</div><h2>Not “member of the month.” A record of meaningful impact.</h2><p>Mettelo Spotlight shows what someone built, led, reviewed, mentored or improved — with context other professionals can understand.</p></div><div className="actions"><a className="button dark" href="/spotlight">Explore Spotlight & Awards →</a></div></div></div></section>

    <section className="section" id="insights"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">Insights & Mettelo News</div><h2>Ideas, lessons and what we are building.</h2></div><a className="linkArrow" href="/blog">View all insights →</a></div><div className="grid3"><article className="card"><span className="chip">FEATURED</span><h3>Why another Data & AI community is not enough</h3><p>Connection matters, but professional growth also needs work, evidence and opportunity.</p></article><article className="card"><span className="chip">CAREER</span><h3>What hiring teams need to see beyond your CV</h3><p>How stronger evidence can make capability easier to evaluate.</p></article><article className="card"><span className="chip">BUILDING IN PUBLIC</span><h3>How Mettelo projects work</h3><p>From project brief to application, delivery, review and contributor credit.</p></article></div></div></section>

    <section className="section dark"><div className="shell"><div className="ctaBand"><div><div className="cardNumber">FOR ORGANISATIONS</div><h2>Bring a real problem. Build value with the ecosystem.</h2><p>Partner on problem briefs, Labs projects, events, research, talent discovery and ecosystem support.</p></div><div className="actions"><a className="button primary" href="/partnership">Partner with Mettelo →</a><a className="button ghost" href="/contact">Contact us</a></div></div></div></section>

    <section className="section compact"><div className="shell"><div className="ctaBand"><div><div className="cardNumber">START HERE</div><h2>Don’t just join another community. Build something that becomes proof.</h2><p>Join the network, find useful people and opportunities, contribute when the right work appears, and make that contribution visible.</p></div><div className="actions"><a className="button dark" href="/join">Join Mettelo →</a><a className="button ghost" href="/contribute">Become a Contributor</a></div></div></div></section>
  </>;
}
