export default function HomePage(){
  const journeys=[
    ['01 / BUILD','Find a real project','Join multidisciplinary Labs work with clear roles, commitments, outcomes and contributor credits.','/projects','Browse projects'],
    ['02 / ACCESS','Find an opportunity','Discover jobs, referrals, fellowships and volunteer roles with clearer eligibility and trusted sources.','/opportunities','Explore opportunities'],
    ['03 / CONNECT','Join the room','Attend workshops, AMAs, showcases and build sessions with professionals solving similar problems.','/events','See events'],
    ['04 / PROVE','Build your professional record','Turn completed contribution into project credits, capability evidence and recognition.','/spotlight','See recognition']
  ];
  const ecosystem=[['01','Community','Belonging, discussion, peer support and project formation.'],['02','Labs','Real briefs, teams, open source, datasets and prototypes.'],['03','Proof','Verified contribution, project credits and capability profiles.'],['04','Talent','Jobs, referrals, project work and employer discovery.'],['05','Research','Reports, surveys, benchmarks and practical sector intelligence.'],['06','AI','Tools for matching, evaluation, workflow and discovery.'],['07','Summit','Showcases, hackathons, thought leadership and partnerships.']];
  return <>
    <section className="hero"><div className="shell">
      <div className="heroGrid">
        <div><div className="eyebrow">The professional capability network</div><h1>Build work that proves what you can do.</h1><p className="heroLead">Mettelo connects Data & AI professionals to community, real projects, open source, events, credible proof and meaningful opportunity — so professional growth is not left to courses and CV claims alone.</p><div className="actions"><a className="button dark" href="/membership#signup">Join Mettelo free →</a><a className="button ghost" href="/projects">Explore open projects</a></div></div>
        <aside className="heroPanel"><div className="heroPanelTop"><span className="liveDot">Ecosystem active</span><span className="chip">FOUNDING STAGE</span></div><h3>Your Mettelo activity layer</h3><p>One place to discover what you can join, build, attend and eventually prove.</p><div className="listRow"><div><strong>Open Labs projects</strong><br/><small>Data · AI · Research · Open source</small></div><span className="chip green">Apply</span></div><div className="listRow"><div><strong>Upcoming community sessions</strong><br/><small>AMAs · Workshops · Showcases</small></div><span className="chip blue">Register</span></div><div className="listRow"><div><strong>Member proof</strong><br/><small>Credits · Leadership · Recognition</small></div><span className="chip">Build</span></div><div className="path"><span>Connect</span><span>Build</span><span>Contribute</span><span>Prove</span><span>Get discovered</span></div></aside>
      </div>
      <div className="trustStrip"><div className="trustItem"><strong>Community</strong><span>Start with people, not content libraries.</span></div><div className="trustItem"><strong>Real work</strong><span>Build against briefs with accountable teams.</span></div><div className="trustItem"><strong>Credible proof</strong><span>Record contribution, not attendance.</span></div><div className="trustItem"><strong>Opportunity</strong><span>Connect evidence to jobs, referrals and partnerships.</span></div></div>
    </div></section>

    <section className="section"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">What can I do here?</div><h2>Mettelo should always give you a useful next move.</h2></div><p>Whether you are job searching, building experience, contributing open source, growing into leadership or simply looking for stronger peers, the platform should make the next action obvious.</p></div><div className="grid4">{journeys.map(([num,title,copy,href,cta])=><article className="card featureCard" key={title}><div><div className="cardNumber">{num}</div><h3 style={{marginTop:28}}>{title}</h3><p>{copy}</p></div><div className="actions"><a className="linkArrow" href={href}>{cta} →</a></div></article>)}</div></div></section>

    <section className="section softSection"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">Featured in Mettelo Labs</div><h2>Open projects you can actually join.</h2></div><a className="linkArrow" href="/projects">See all projects →</a></div><div className="projectGrid">
      <article className="projectCard"><div><span className="chip green">RECRUITING</span><h3>Nigeria Cost of Living Data Explorer</h3><p>Build a public-facing data product that turns fragmented price and location data into useful household insight.</p><div className="metaRow"><span className="metaPill">8 weeks</span><span className="metaPill">Remote</span><span className="metaPill">6 roles</span><span className="metaPill">Intermediate</span></div></div><div className="projectFoot"><span className="statusText">Applications open</span><a className="button dark" href="/projects">View project →</a></div></article>
      <article className="projectCard"><div><span className="chip green">RECRUITING</span><h3>Open Data Quality Monitor</h3><p>Create a reusable framework for profiling public datasets and making quality issues easier to identify and explain.</p><div className="metaRow"><span className="metaPill">6 weeks</span><span className="metaPill">Remote</span><span className="metaPill">5 roles</span><span className="metaPill">Data + Engineering</span></div></div><div className="projectFoot"><span className="statusText">Applications open</span><a className="button dark" href="/projects">View project →</a></div></article>
      <article className="projectCard"><div><span className="chip blue">UPCOMING</span><h3>Graduate Data Job Market Tracker</h3><p>Build recurring insight on early-career Data & AI demand, skills, locations and hiring patterns.</p><div className="metaRow"><span className="metaPill">8 weeks</span><span className="metaPill">Research</span><span className="metaPill">7 roles</span><span className="metaPill">Nigeria + UK</span></div></div><div className="projectFoot"><span>Opening soon</span><a className="button ghost" href="/membership">Get project alerts</a></div></article>
    </div></div></section>

    <section className="section dark"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">The Mettelo ecosystem</div><h2>Community is the front door. Capability infrastructure is the system.</h2></div><p>Each layer creates value on its own, but the advantage comes from connecting them: relationships create work, work creates evidence, evidence creates trust and trust improves access.</p></div><div className="grid4">{ecosystem.map(([n,t,c])=><article className="card" key={t}><div className="cardNumber">{n}</div><h3 style={{marginTop:24}}>{t}</h3><p>{c}</p></article>)}</div></div></section>

    <section className="section"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">Beyond projects</div><h2>Return for people, insight, events and opportunity.</h2></div><p>A professional platform needs recurring value. Mettelo should remain useful even when a member is not actively building a project.</p></div><div className="grid3"><article className="card"><span className="chip">NEXT EVENT</span><h3 style={{marginTop:18}}>Breaking into Data & AI in the UK</h3><p>Community AMA on applications, interviews, evidence and what hiring teams actually look for.</p><div className="actions"><a className="linkArrow" href="/events">Register →</a></div></article><article className="card"><span className="chip">LATEST INSIGHT</span><h3 style={{marginTop:18}}>Why another Data & AI community is not enough</h3><p>Connection matters, but professional growth also needs real work, visible evidence and opportunity.</p><div className="actions"><a className="linkArrow" href="/blog">Read insight →</a></div></article><article className="card"><span className="chip">SPOTLIGHT</span><h3 style={{marginTop:18}}>Recognition should follow contribution</h3><p>Spotlight and future awards will recognise people who build, lead, mentor, review and help others move.</p><div className="actions"><a className="linkArrow" href="/spotlight">Explore Spotlight →</a></div></article></div></div></section>

    <section className="section compact"><div className="shell"><div className="ctaBand"><div><div className="cardNumber">METTELO MEMBERSHIP</div><h2>Don’t just join another community. Build a professional record.</h2><p>Start free. Meet people. Join projects and events when they fit your goals. Contribute when you are ready. Let the work become proof.</p></div><div className="actions"><a className="button dark" href="/membership#signup">Create free account →</a><a className="button ghost" href="/membership">See membership</a></div></div></div></section>
  </>;
}
