export default function HomePage(){
  const loop=[
    ['01 / CONNECT','Find serious peers','Join focused community spaces, events and conversations with Data & AI professionals who want to build, not only consume.','/community','Explore community'],
    ['02 / BUILD','Work on real problems','Move into structured Mettelo Labs briefs with clear roles, ownership, review and outcomes.','/projects','Explore Labs'],
    ['03 / CONTRIBUTE','Own useful work','Contribute through projects, open source, community, research, product, content or operations.','/contribute','Contribution pathways'],
    ['04 / PROVE','Make the work visible','Turn reviewed contribution into project credits, showcases and evidence that other professionals can understand.','/showcase','See the proof model'],
    ['05 / GET DISCOVERED','Connect evidence to access','Mettelo Talent is the destination: opportunity connected to demonstrated capability rather than claims alone.','/opportunities','See Talent']
  ];
  return <>
    <section className="hero"><div className="shell"><div className="heroGrid"><div><div className="eyebrow">Professional capability infrastructure for Data & AI</div><h1>Build capability. Prove it. Get discovered.</h1><p className="heroLead">Mettelo is where Data & AI professionals come together to solve real problems, build meaningful work, demonstrate capability and create opportunity.</p><div className="actions"><a className="button dark" href="/join">Start with Mettelo →</a></div></div><aside className="heroPanel"><div className="heroPanelTop"><span className="liveDot">Launch foundation</span><span className="chip">EARLY</span></div><h3>Not a course platform. Not a bootcamp. Not a job board.</h3><p>Mettelo connects the parts that usually sit apart: community, real work, contribution, credible proof and opportunity.</p><div className="path"><span>Connect</span><span>Build</span><span>Contribute</span><span>Prove</span><span>Get discovered</span></div></aside></div>
    <div className="trustStrip"><div className="trustItem"><strong>Community</strong><span>The front door: relationships, discussion and belonging.</span></div><div className="trustItem"><strong>Mettelo Labs</strong><span>Structured real work and open contribution.</span></div><div className="trustItem"><strong>Mettelo Proof</strong><span>Evidence built from useful, reviewed contribution.</span></div><div className="trustItem"><strong>Mettelo Talent</strong><span>The destination: access through demonstrated capability.</span></div></div></div></section>

    <section className="section softSection"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">The reality</div><h2>You need experience to earn opportunity — and opportunity to gain experience.</h2></div><p>Data & AI professionals have no shortage of information. The harder problem is access to meaningful work that turns knowledge into evidence other people can trust.</p></div><div className="grid3"><article className="card"><div className="cardNumber">01</div><h3>More learning does not automatically create proof</h3><p>Certificates can show study. They rarely show judgement, collaboration, ownership or delivery in messy real work.</p></article><article className="card"><div className="cardNumber">02</div><h3>Professional growth is fragmented</h3><p>Community, projects, mentors, events, jobs and open source often live in disconnected systems.</p></article><article className="card"><div className="cardNumber">03</div><h3>Opportunity still relies on weak signals</h3><p>CVs and titles can hide capable people while useful contribution remains difficult to see.</p></article></div></div></section>

    <section className="section"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">The Mettelo loop</div><h2>Contribution is the bridge between potential and proof.</h2></div><p>Each stage creates a reason to move to the next. The loop is the product — not a slogan placed only on the homepage.</p></div><div className="grid3">{loop.map(([num,title,copy,href,cta])=><article className="card featureCard" key={title}><div><div className="cardNumber">{num}</div><h3 style={{marginTop:28}}>{title}</h3><p>{copy}</p></div><a className="linkArrow" href={href}>{cta} →</a></article>)}</div></div></section>

    <section className="section dark"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">Community is the front door</div><h2>Where Data & AI Builders Grow Together.</h2></div><p>Start with people. Join discussions, meet collaborators, attend useful sessions and find the route that matches what you need now.</p></div><div className="grid3"><article className="card"><span className="chip darkchip">CONNECT</span><h3 style={{marginTop:18}}>Community spaces</h3><p>Focused discussion, networking, opportunities, project formation and peer support.</p><div className="actions"><a className="linkArrow" href="/community">Explore Community →</a></div></article><article className="card"><span className="chip darkchip">BUILD</span><h3 style={{marginTop:18}}>Labs pilot briefs</h3><p>See the first structured project concepts and register useful interest without pretending a place is already open.</p><div className="actions"><a className="linkArrow" href="/projects">Explore Labs →</a></div></article><article className="card"><span className="chip darkchip">STAY CLOSE</span><h3 style={{marginTop:18}}>Events & updates</h3><p>Get confirmed sessions, new briefs and verified opportunities when they publish.</p><div className="actions"><a className="linkArrow" href="/newsletter">Get updates →</a></div></article></div></div></section>

    <section className="section softSection"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">Built through contribution</div><h2>Mettelo itself is part of the proof model.</h2></div><p>People can contribute beyond Labs: open source, community, product, research, content, partnerships and operations all need clear ownership and visible outcomes.</p></div><div className="ctaBand"><div><div className="cardNumber">CONTRIBUTORS</div><h2>Specific contribution beats a generic offer to help.</h2><p>Choose an area, explain what you can own and show the evidence that makes you useful there.</p></div><div className="actions"><a className="button dark" href="/contribute">Become a Contributor →</a></div></div></div></section>

    <section className="section"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">For organisations</div><h2>Discover capability through what people have actually done.</h2></div><p>Organisations can bring real problems, expertise, events, research and opportunity into the ecosystem. Mettelo is designed to make contribution more visible and talent signals more useful.</p></div><div className="ctaBand"><div><div className="cardNumber">PARTNERS</div><h2>Bring a problem, opportunity or idea worth building around.</h2><p>Partnerships should create useful work, a clear audience or a stronger path into professional opportunity.</p></div><div className="actions"><a className="button dark" href="/partnership">Partner with Mettelo →</a></div></div></div></section>

    <section className="section compact"><div className="shell"><div className="ctaBand"><div><div className="cardNumber">START HERE</div><h2>Choose the route that matches what you want to do now.</h2><p>Join the community, contribute, register interest in Labs or bring an organisational problem. You do not need to understand the whole ecosystem before taking the first useful step.</p></div><div className="actions"><a className="button dark" href="/join">Start with Mettelo →</a></div></div></div></section>
  </>;
}
