export default function SpotlightPage(){
  const categories=[['Builder Spotlight','Outstanding Labs, open-source or technical contribution.'],['Community Champion','Consistent support, inclusion and practical help for other members.'],['Project Leader','Strong delivery, coordination, judgement and team leadership.'],['Rising Professional','Visible growth through meaningful contribution and learning.'],['Mentor Spotlight','Guidance that helps other professionals move forward.'],['Open Source Contributor','Reusable code, documentation, data or review contribution.']];
  return <>
    <section className="hero"><div className="shell heroGrid"><div><div className="eyebrow">Mettelo Spotlight & Awards</div><h1>Recognition should follow contribution.</h1><p>Mettelo Spotlight celebrates people who build, lead, mentor, review, share and create measurable value — giving members recognition they can connect back to real evidence.</p><div className="actions"><a className="button dark" href="#spotlight">View current Spotlight →</a><a className="button ghost" href="#nominate">Nominate a member</a></div></div><aside className="heroPanel"><span className="chip">RECOGNITION LOOP</span><h3 style={{marginTop:18}}>Useful work should become visible reputation.</h3><div className="path"><span>Contribute</span><span>Verify</span><span>Recognise</span><span>Share</span><span>Opportunity</span></div><p>Spotlight should never become a popularity contest. Nominations should point to specific contribution, evidence and impact.</p></aside></div></section>
    <section className="section" id="spotlight"><div className="shell spotlightHero"><div className="portraitCard"><div><span className="chip">CURRENT SPOTLIGHT</span><h3 style={{fontSize:'1.8rem',margin:'12px 0 4px'}}>Member name</h3><p>Data Professional · Mettelo Contributor</p></div></div><div><div className="eyebrow">Member Spotlight</div><h2 style={{fontSize:'clamp(2.6rem,4.6vw,4.5rem)',margin:0}}>Celebrate the work behind the profile.</h2><p className="lead">A Spotlight page should explain what the member contributed, the project or community outcome, the role they played and why that contribution deserves recognition.</p><div className="recognitionRow"><span className="chip">2 LABS PROJECTS</span><span className="chip">PROJECT LEAD</span><span className="chip">OPEN SOURCE</span><span className="chip">MENTORING</span></div><div className="actions"><a className="button dark" href="#">Read Spotlight →</a></div></div></div></section>
    <section className="section softSection"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">Recognition categories</div><h2>Multiple ways to create value. Multiple ways to recognise it.</h2></div><p>Categories make sure technical work is not the only visible contribution. Leadership, mentoring, review, documentation and community work also matter.</p></div><div className="grid3">{categories.map(([title,copy])=><article className="card" key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    <section className="section dark"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">Mettelo Awards</div><h2>Build toward an annual flagship recognition programme.</h2></div><p>Future annual awards can create a high-trust public moment around demonstrated work, community contribution and impact across the ecosystem.</p></div><div className="grid4"><article className="card"><span className="cardNumber">ANNUAL</span><h3 style={{marginTop:20}}>Builder of the Year</h3><p>Outstanding practical contribution across Labs and open source.</p></article><article className="card"><span className="cardNumber">ANNUAL</span><h3 style={{marginTop:20}}>Community Champion</h3><p>Exceptional contribution to the quality and health of the community.</p></article><article className="card"><span className="cardNumber">ANNUAL</span><h3 style={{marginTop:20}}>Project of the Year</h3><p>The strongest combination of useful output, teamwork and evidence.</p></article><article className="card"><span className="cardNumber">ANNUAL</span><h3 style={{marginTop:20}}>Emerging Talent</h3><p>A member demonstrating significant growth through contribution.</p></article></div></div></section>
    <section className="section" id="nominate"><div className="shell formShell"><div><div className="eyebrow">Nominate someone</div><h2 style={{fontSize:'clamp(2.5rem,4vw,4rem)',margin:0}}>Make the evidence part of the nomination.</h2><p className="lead">The form should ask what the person actually did, where the contribution can be seen and what changed because of it.</p></div><form className="formCard"><label>Member you are nominating</label><input placeholder="Name or Mettelo profile"/><label>Recognition category</label><select><option>Builder Spotlight</option><option>Community Champion</option><option>Project Leader</option><option>Rising Professional</option><option>Mentor Spotlight</option></select><label>What did they contribute?</label><textarea placeholder="Describe the specific contribution and why it matters."/><label>Evidence or project link</label><input placeholder="Project, GitHub, event, documentation or other evidence"/><button type="button" className="button primary" style={{width:'100%',marginTop:18}}>Submit nomination →</button></form></div></section>
  </>;
}
