'use client';

import {useState} from 'react';

type Item={id:string;full_name:string;email:string;status:string;submitted_at:string;location:string|null;linkedin_url:string|null;portfolio_url:string|null;work_authorisation:string|null;motivation:string;relevant_experience:string;interview_at:string|null;interview_details:string|null;offer_details:string|null;cv_url:string|null;career_roles:{title:string}|null};
const stages=['in_review','shortlisted','interview','offer','hired','rejected'];
export default function AdminCareerApplicationQueue({initialItems}:{initialItems:Item[]}){const [items,setItems]=useState(initialItems);const [notes,setNotes]=useState<Record<string,string>>({});const [interviewAt,setInterviewAt]=useState<Record<string,string>>({});const [message,setMessage]=useState('');const [busy,setBusy]=useState('');
async function move(id:string,status:string){setBusy(id);setMessage('');try{const r=await fetch('/api/admin/careers/applications',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,status,note:notes[id]||'',interview_at:interviewAt[id]||null})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Unable to update application.');setItems(c=>c.map(x=>x.id===id?{...x,status}:x));setMessage(b.email_sent?'Candidate updated and email sent.':'Candidate updated. Email was queued but delivery is not confirmed.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to update application.');}finally{setBusy('')}}
return <div className="applicationQueue">{items.length?items.map(item=><article className="applicationReview" key={item.id}><div className="panelHead"><div><span className="chip">{item.status.replaceAll('_',' ').toUpperCase()}</span><h3 style={{margin:'10px 0 4px'}}>{item.full_name}</h3><small>{item.career_roles?.title||'Mettelo role'} · {item.email}</small></div><small>{new Date(item.submitted_at).toLocaleDateString('en-GB')}</small></div><div className="metaRow">{item.location&&<span className="metaPill">{item.location}</span>}{item.work_authorisation&&<span className="metaPill">{item.work_authorisation}</span>}</div><p><strong>Motivation:</strong> {item.motivation}</p><p><strong>Relevant experience:</strong> {item.relevant_experience}</p><div className="actions">{item.cv_url&&<a className="linkArrow" href={item.cv_url} target="_blank" rel="noopener noreferrer">CV →</a>}{item.linkedin_url&&<a className="linkArrow" href={item.linkedin_url} target="_blank" rel="noopener noreferrer">LinkedIn →</a>}{item.portfolio_url&&<a className="linkArrow" href={item.portfolio_url} target="_blank" rel="noopener noreferrer">Portfolio →</a>}</div><label>Admin note<textarea value={notes[item.id]||''} onChange={e=>setNotes(c=>({...c,[item.id]:e.target.value}))} rows={2}/></label><label>Interview date/time<input type="datetime-local" value={interviewAt[item.id]||''} onChange={e=>setInterviewAt(c=>({...c,[item.id]:e.target.value}))}/></label><div className="reviewActions">{stages.map(stage=><button key={stage} type="button" className={stage==='hired'?'button dark':'button ghost'} disabled={busy===item.id||item.status===stage} onClick={()=>move(item.id,stage)}>{stage.replaceAll('_',' ')}</button>)}</div></article>):<div className="emptyState"><h3>No career applications yet.</h3><p>Applications will appear here as soon as candidates apply for a published Mettelo role.</p></div>}<div className="formStatus" role="status">{message}</div></div>}
