'use client';

import {useEffect,useRef,useState} from 'react';

type Attachment={id:string;file_name:string;content_type:string;size_bytes:number;sort_order:number;active:boolean;created_at:string};
const MAX_FILES=4,MAX_BYTES=10*1024*1024;const allowed=new Set(['application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document']);

export default function AdminTemplateAttachments({templateKey,enabled}:{templateKey:string;enabled:boolean}){
  const [items,setItems]=useState<Attachment[]>([]);const [status,setStatus]=useState('');const [busy,setBusy]=useState(false);const input=useRef<HTMLInputElement>(null);
  async function load(){if(!enabled){setItems([]);return}try{const r=await fetch(`/api/admin/communications/attachments?template_key=${encodeURIComponent(templateKey)}`);const b=await r.json();if(!r.ok)throw new Error(b.error||'Unable to load attachments.');setItems(b.attachments||[]);}catch(error){setStatus(error instanceof Error?error.message:'Unable to load attachments.')}}
  useEffect(()=>{void load()},[templateKey,enabled]);
  async function upload(file:File){if(!allowed.has(file.type)||file.size<=0||file.size>MAX_BYTES){setStatus('Choose a PDF or DOCX file up to 10MB.');return}if(items.length>=MAX_FILES){setStatus(`A template can have at most ${MAX_FILES} active attachments.`);return}setBusy(true);setStatus('');try{const form=new FormData();form.set('template_key',templateKey);form.set('file',file);const r=await fetch('/api/admin/communications/attachments',{method:'POST',body:form});const b=await r.json();if(!r.ok)throw new Error(b.error||'Unable to upload attachment.');setItems(current=>[...current,b.attachment]);setStatus(`${file.name} attached.`);if(input.current)input.current.value='';}catch(error){setStatus(error instanceof Error?error.message:'Unable to upload attachment.')}finally{setBusy(false)}}
  async function remove(item:Attachment){setBusy(true);setStatus('');try{const r=await fetch('/api/admin/communications/attachments',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({id:item.id})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Unable to remove attachment.');setItems(current=>current.filter(row=>row.id!==item.id));setStatus(`${item.file_name} removed.`);}catch(error){setStatus(error instanceof Error?error.message:'Unable to remove attachment.')}finally{setBusy(false)}}
  async function move(index:number,direction:-1|1){const target=index+direction;if(target<0||target>=items.length)return;const next=[...items];[next[index],next[target]]=[next[target],next[index]];setItems(next);setBusy(true);try{const r=await fetch('/api/admin/communications/attachments',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({ordered_ids:next.map(item=>item.id)})});if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(b.error||'Unable to reorder attachments.')}setStatus('Attachment order updated.')}catch(error){setItems(items);setStatus(error instanceof Error?error.message:'Unable to reorder attachments.')}finally{setBusy(false)}}
  if(!enabled)return <section className="templateAttachments disabled"><div><span className="cardNumber">ATTACHMENTS</span><h3>Attachments are disabled for this template.</h3><p>Enable this capability only for governed communications that should always include documents.</p></div><style jsx>{styles}</style></section>;
  return <section className="templateAttachments" aria-labelledby="template-attachment-title"><div className="attachmentHead"><div><span className="cardNumber">ATTACHMENTS</span><h3 id="template-attachment-title">Governed template documents</h3><p>These files are attached automatically whenever this template sends. Up to 4 files, 10MB each; PDF or DOCX.</p></div><strong>{items.length}/{MAX_FILES}</strong></div>{items.length>0&&<div className="attachmentList">{items.map((item,index)=><article key={item.id}><div><strong>{item.file_name}</strong><small>{(item.size_bytes/1024/1024).toFixed(1)} MB · {item.content_type==='application/pdf'?'PDF':'DOCX'}</small></div><div className="attachmentActions"><button type="button" aria-label={`Move ${item.file_name} up`} disabled={busy||index===0} onClick={()=>void move(index,-1)}>↑</button><button type="button" aria-label={`Move ${item.file_name} down`} disabled={busy||index===items.length-1} onClick={()=>void move(index,1)}>↓</button><button type="button" disabled={busy} onClick={()=>void remove(item)}>Remove</button></div></article>)}</div>}{items.length<MAX_FILES&&<label className="attachmentPicker">Add document<input ref={input} type="file" accept="application/pdf,.docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file)}}/></label>}<div className="formStatus" role="status" aria-live="polite">{status}</div><style jsx>{styles}</style></section>
}

const styles=`.templateAttachments{display:grid;gap:12px;padding:16px;border:1px solid #ddd5c4;border-radius:12px;background:#fffdf8}.templateAttachments.disabled{background:#f8f9fa;border-color:#e0e4e8}.attachmentHead{display:flex;justify-content:space-between;gap:14px}.attachmentHead h3,.templateAttachments h3{margin:5px 0 4px;font-size:.95rem}.attachmentHead p,.templateAttachments p{margin:0;max-width:620px;color:#5b6470;font-size:.7rem;line-height:1.5}.attachmentHead>strong{align-self:start;padding:5px 8px;border-radius:999px;background:#f1eadb;color:#72501b;font-size:.68rem}.attachmentList{display:grid;gap:7px}.attachmentList article{display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:center;gap:10px;padding:10px;border:1px solid #e0e3e7;border-radius:9px;background:#fff}.attachmentList article>div:first-child{display:grid;gap:2px;min-width:0}.attachmentList strong{font-size:.72rem;overflow-wrap:anywhere}.attachmentList small{color:#66707e;font-size:.64rem}.attachmentActions{display:flex;gap:5px}.attachmentActions button{min-width:44px;min-height:44px;border:1px solid #d4d9df;border-radius:8px;background:#fff;font-size:.66rem;font-weight:800}.attachmentActions button:last-child{color:#7a1e2c}.attachmentPicker{display:grid;gap:6px;font-size:.7rem;font-weight:800}.attachmentPicker input{min-height:44px}.templateAttachments button:focus-visible,.templateAttachments input:focus-visible{outline:3px solid rgba(198,137,42,.35);outline-offset:2px}@media(max-width:560px){.attachmentList article{grid-template-columns:1fr}.attachmentActions{justify-content:flex-start}.attachmentHead{display:grid}.attachmentHead>strong{width:max-content}}`;
