'use client';

import {FormEvent,useState} from 'react';

type Account={id:string;email:string;name:string;username:string;member_id:string};
type Result={users?:Account[];error?:string};

export default function AdminMemberIdentityLookup(){
 const[query,setQuery]=useState('');const[status,setStatus]=useState<'idle'|'working'|'error'|'success'>('idle');const[message,setMessage]=useState('');const[results,setResults]=useState<Account[]>([]);
 async function submit(event:FormEvent){event.preventDefault();const clean=query.trim();if(!clean){setStatus('error');setMessage('Enter a full name, email, @username or Member ID.');setResults([]);return}setStatus('working');setMessage('');try{const params=new URLSearchParams({q:clean,page:'1',page_size:'25',access:'all',sort:'newest'});const response=await fetch(`/api/admin/access?${params}`,{cache:'no-store'});const body=await response.json() as Result;if(!response.ok)throw new Error(body.error||'Unable to resolve member identity.');const users=body.users||[];setResults(users);setStatus('success');setMessage(users.length?`${users.length} matching account${users.length===1?'':'s'} found.`:'No account matches that identity.')}catch(error){setResults([]);setStatus('error');setMessage(error instanceof Error?error.message:'Unable to resolve member identity.')}}
 return <section className="adminIdentityLookup" aria-labelledby="admin-identity-title"><div><span className="eyebrow">MEMBER IDENTITY</span><h2 id="admin-identity-title">Resolve a member</h2><p>Use a member’s name, email, @username or Mettelo Member ID before taking an account-level Admin action.</p></div><form onSubmit={submit}><label htmlFor="admin-identity-query">Member identity</label><div><input id="admin-identity-query" value={query} onChange={event=>setQuery(event.target.value)} placeholder="e.g. @username or MTL-100001" autoComplete="off"/><button className="button ghost" type="submit" disabled={status==='working'}>{status==='working'?'Searching…':'Find member'}</button></div></form><div className={`formStatus ${status}`} role="status" aria-live="polite">{message}</div>{results.length>0&&<div className="identityResults" aria-label="Member identity matches">{results.map(account=><article key={account.id}><div><strong>{account.name||'Mettelo member'}</strong>{account.username&&<span>@{account.username}</span>}</div><dl><div><dt>Member ID</dt><dd>{account.member_id||'Not assigned'}</dd></div><div><dt>Email</dt><dd>{account.email||'Not available'}</dd></div></dl></article>)}</div>}<style jsx>{`.adminIdentityLookup{display:grid;grid-template-columns:minmax(0,.8fr) minmax(300px,1.2fr);gap:18px;align-items:end;padding:16px;border:1px solid #d9dde2;border-radius:14px;background:#fff}.adminIdentityLookup h2{margin:4px 0 6px;font-size:1.15rem}.adminIdentityLookup p{margin:0;color:#65707d;font-size:.76rem;line-height:1.5}.adminIdentityLookup form{display:grid;gap:6px}.adminIdentityLookup label{font-size:.68rem;font-weight:800}.adminIdentityLookup form>div{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px}.adminIdentityLookup input{width:100%;min-width:0;min-height:44px;padding:9px 10px;border:1px solid #cbd2da;border-radius:9px;background:#fff;color:#10131d}.adminIdentityLookup button{min-height:44px}.identityResults{grid-column:1/-1;display:grid;gap:8px}.identityResults article{display:grid;grid-template-columns:minmax(0,.7fr) minmax(0,1.3fr);gap:12px;padding:12px;border:1px solid #e2e6ea;border-radius:10px;background:#fcfbf7;min-width:0}.identityResults strong,.identityResults span{display:block;overflow-wrap:anywhere}.identityResults span{margin-top:2px;color:#5b6472;font:650 .7rem var(--font-plex-mono),ui-monospace,monospace}.identityResults dl{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin:0}.identityResults dl div{min-width:0}.identityResults dt{color:#68717d;font-size:.62rem}.identityResults dd{margin:2px 0 0;font-size:.72rem;overflow-wrap:anywhere}@media(max-width:760px){.adminIdentityLookup{grid-template-columns:1fr;align-items:start}.adminIdentityLookup form>div{grid-template-columns:1fr}.adminIdentityLookup button{width:100%}.identityResults article,.identityResults dl{grid-template-columns:1fr}}`}</style></section>
}
