'use client';

import { useState } from 'react';

type Item={id:string;title:string;organisation:string|null;location:string|null;role_family:string|null;data_ai_relevance_score:number|null;data_ai_relevance_status:string;verification_score:number|null;verification_status:string;verification_reasons:string[];source_type:string|null;source_url:string|null;official_application_url:string|null;eligibility_status:string;sponsorship_status:string;suspicion_score:number;updated_at:string};

export default function AdminOpportunityReviewQueue({initialItems}:{initialItems:Item[]}){
  const [items,setItems]=useState(initialItems);const [working,setWorking]=useState('');const [notes,setNotes]=useState<Record<string,string>>({});const [message,setMessage]=useState('');
  async function act(id:string,action:'approve'|'reject'|'recheck'){
    setWorking(id);setMessage('');
    try{const response=await fetch('/api/admin/opportunities/review',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,action,note:notes[id]||''})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'Unable to update opportunity.');if(action==='recheck')setItems(current=>current.map(item=>item.id===id?{...item,verification_status:'needs_review'}:item));else setItems(current=>current.filter(item=>item.id!==id));setMessage(action==='approve'?'Opportunity approved and published.':action==='reject'?'Opportunity rejected.':'Opportunity returned for re-verification.');}catch(error){setMessage(error instanceof Error?error.message:'Unable to update opportunity.');}finally{setWorking('');}
  }
  if(!items.length)return <div className="emptyState"><h3>No opportunities need review.</h3><p>Only ambiguous, weakly verified or suspicious listings appear here. High-confidence verified jobs can publish automatically.</p></div>;
  return <div className="applicationQueue">{items.map(item=><article className="applicationReview" key={item.id}><div className="panelHead"><div><span className="chip">NEEDS REVIEW</span><h3 style={{margin:'10px 0 4px'}}>{item.title}</h3><small>{item.organisation||'Employer unclear'}{item.location?` · ${item.location}`:''}</small></div><small>{new Date(item.updated_at).toLocaleString('en-GB')}</small></div><div className="metaRow"><span className="metaPill">Data/AI {item.data_ai_relevance_score??'—'}/100</span><span className="metaPill">Verification {item.verification_score??'—'}/100</span><span className="metaPill">Suspicion {item.suspicion_score}/100</span>{item.role_family&&<span className="metaPill">{item.role_family}</span>}</div><div className="grid3"><div><small>Relevance</small><strong>{item.data_ai_relevance_status.replace('_',' ')}</strong></div><div><small>Eligibility</small><strong>{item.eligibility_status}</strong></div><div><small>Sponsorship</small><strong>{item.sponsorship_status.replace('_',' ')}</strong></div></div>{item.verification_reasons?.length>0&&<p><strong>Why flagged:</strong> {item.verification_reasons.join(' · ')}</p>}<div className="actions">{item.official_application_url&&<a className="linkArrow" href={item.official_application_url} target="_blank" rel="noopener noreferrer">Official application →</a>}{item.source_url&&<a className="linkArrow" href={item.source_url} target="_blank" rel="noopener noreferrer">Source →</a>}</div><label htmlFor={`opportunity-review-${item.id}`}>Admin note</label><textarea id={`opportunity-review-${item.id}`} value={notes[item.id]||''} onChange={event=>setNotes(current=>({...current,[item.id]:event.target.value}))} placeholder="Why you approved, rejected or want this rechecked."/><div className="reviewActions"><button className="button dark" type="button" disabled={working===item.id} onClick={()=>act(item.id,'approve')}>Approve & publish</button><button className="button ghost" type="button" disabled={working===item.id} onClick={()=>act(item.id,'recheck')}>Recheck</button><button className="button ghost" type="button" disabled={working===item.id} onClick={()=>act(item.id,'reject')}>Reject</button></div></article>)}<div className="formStatus" role="status" aria-live="polite">{message}</div></div>;
}
