'use client';

import { FormEvent, useState } from 'react';

type Source={id:string;provider:'greenhouse'|'lever';organisation_name:string;source_key:string;region:'global'|'eu';employer_domain:string|null;is_active:boolean;auto_publish_enabled:boolean;last_synced_at:string|null;last_sync_status:string|null;last_sync_error:string|null};
type SourceStat={source:string;discovered:number;configured:boolean;error:string|null};

export default function AdminOpportunitySources({initialSources}:{initialSources:Source[]}){
  const [sources,setSources]=useState(initialSources);const [working,setWorking]=useState('');const [message,setMessage]=useState('');const [sourceStats,setSourceStats]=useState<SourceStat[]>([]);
  async function refreshSources(){const refreshed=await fetch('/api/admin/opportunity-sources').then(r=>r.json());if(refreshed.sources)setSources(refreshed.sources);}
  async function discover(){setWorking('discover');setMessage('');try{const response=await fetch('/api/admin/opportunities/discover',{method:'POST'});const data=await response.json();if(!response.ok)throw new Error(data.error||'Discovery failed.');setSourceStats(data.source_stats||[]);setMessage(`Latest-job scan complete: ${data.scanned} scanned · ${data.relevant} Data/AI matches · ${data.published} published · ${data.duplicates} existing listings refreshed/skipped.${data.source_errors?.length?` Source warning: ${data.source_errors.join(' · ')}`:''}`);}catch(error){setMessage(error instanceof Error?error.message:'Discovery failed.');}finally{setWorking('');}}
  async function syncAll(){const active=sources.filter(source=>source.is_active);if(!active.length){setMessage('No official ATS sources are registered yet. Use Latest Data & AI discovery instead.');return;}setWorking('sync-all');setMessage('');let discovered=0,published=0,review=0,rejected=0,failed=0;for(const source of active){try{const response=await fetch('/api/admin/opportunity-sources/sync',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({source_id:source.id})});const data=await response.json();if(!response.ok)throw new Error();discovered+=data.discovered||0;published+=data.published||0;review+=data.needs_review||0;rejected+=data.rejected||0;}catch{failed++;}}await refreshSources();setWorking('');setMessage(`Official ATS sync complete: ${discovered} discovered · ${published} published · ${review} review · ${rejected} rejected${failed?` · ${failed} source(s) failed`:''}.`);}
  async function add(event:FormEvent<HTMLFormElement>){event.preventDefault();setWorking('add');setMessage('');const form=event.currentTarget;const fd=new FormData(form);try{const response=await fetch('/api/admin/opportunity-sources',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(Object.fromEntries(fd.entries()))});const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to add source.');setSources(current=>[...current,data.source].sort((a,b)=>a.organisation_name.localeCompare(b.organisation_name)));form.reset();setMessage('Official ATS source added.');}catch(error){setMessage(error instanceof Error?error.message:'Unable to add source.');}finally{setWorking('');}}
  async function patch(source:Source,changes:Partial<Source>){setWorking(source.id);setMessage('');try{const response=await fetch('/api/admin/opportunity-sources',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:source.id,...changes})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to update source.');setSources(current=>current.map(item=>item.id===source.id?data.source:item));}catch(error){setMessage(error instanceof Error?error.message:'Unable to update source.');}finally{setWorking('');}}
  async function sync(source:Source){setWorking(source.id);setMessage('');try{const response=await fetch('/api/admin/opportunity-sources/sync',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({source_id:source.id})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Sync failed.');setMessage(`${source.organisation_name}: ${data.discovered} discovered · ${data.published} published · ${data.needs_review} review · ${data.rejected} rejected.`);await refreshSources();}catch(error){setMessage(error instanceof Error?error.message:'Sync failed.');}finally{setWorking('');}}

  return <>
    <section className="panel">
      <div className="panelHead"><div><span className="cardNumber">AUTOMATIC JOB DISCOVERY</span><h3 style={{marginTop:8}}>Load current Data & AI opportunities across markets</h3></div><span className="chip green">NO EMPLOYER ENTRY</span></div>
      <p>Mettelo scans broad feeds, applies the Data & AI relevance rule, normalises country and opportunity type, extracts sponsorship and international-applicant signals, deduplicates, then publishes qualifying roles automatically.</p>
      <div className="reviewActions" style={{marginTop:16}}><button className="button dark" type="button" disabled={working==='discover'} onClick={discover}>{working==='discover'?'Scanning latest jobs…':'Run latest Data & AI jobs →'}</button><a className="button ghost" href="/opportunities">View public board →</a></div>
      <div className="formStatus" role="status" aria-live="polite">{message}</div>
      {sourceStats.length>0&&<div className="grid4" style={{marginTop:18}}>{sourceStats.map(stat=><article className="card" key={stat.source}><div className="panelHead"><strong>{stat.source}</strong><span className={`chip ${stat.configured&&!stat.error?'green':''}`}>{stat.configured?(stat.error?'ERROR':'READY'):'NEEDS KEY'}</span></div><p style={{marginTop:12}}><strong>{stat.discovered}</strong> jobs returned in the latest run.</p>{stat.error&&<small>{stat.error}</small>}</article>)}</div>}
    </section>

    <section className="panel" style={{marginTop:18}}>
      <div className="panelHead"><div><span className="cardNumber">OFFICIAL ATS VERIFICATION</span><h3 style={{marginTop:8}}>Known Greenhouse & Lever employers</h3></div><span className="chip">{sources.filter(source=>source.is_active).length} ACTIVE</span></div>
      <p>Optional source registry for employers Mettelo already knows. These official feeds carry stronger authenticity evidence and can publish automatically when relevance is high.</p>
      <div className="reviewActions" style={{marginTop:16}}><button className="button ghost" type="button" disabled={working==='sync-all'} onClick={syncAll}>{working==='sync-all'?'Syncing all sources…':'Sync all official sources →'}</button></div>
      {sources.length?<div className="applicationQueue" style={{marginTop:16}}>{sources.map(source=><article className="applicationReview" key={source.id}><div className="panelHead"><div><span className="chip">{source.provider.toUpperCase()}</span><h3 style={{margin:'10px 0 4px'}}>{source.organisation_name}</h3><small>{source.source_key}{source.employer_domain?` · ${source.employer_domain}`:''}</small></div><span className={`chip ${source.is_active?'green':''}`}>{source.is_active?'ACTIVE':'DISABLED'}</span></div><div className="metaRow"><span className="metaPill">Auto-publish {source.auto_publish_enabled?'on':'off'}</span><span className="metaPill">{source.last_synced_at?`Last sync ${new Date(source.last_synced_at).toLocaleString('en-GB')}`:'Never synced'}</span>{source.last_sync_status&&<span className="metaPill">{source.last_sync_status}</span>}</div>{source.last_sync_error&&<p><strong>Last error:</strong> {source.last_sync_error}</p>}<div className="reviewActions"><button className="button ghost" type="button" disabled={working===source.id} onClick={()=>patch(source,{is_active:!source.is_active})}>{source.is_active?'Disable':'Enable'}</button><button className="button ghost" type="button" disabled={working===source.id} onClick={()=>patch(source,{auto_publish_enabled:!source.auto_publish_enabled})}>Auto-publish {source.auto_publish_enabled?'off':'on'}</button><button className="button dark" type="button" disabled={working===source.id||!source.is_active} onClick={()=>sync(source)}>{working===source.id?'Working…':'Sync source →'}</button></div></article>)}</div>:<div className="emptyState" style={{marginTop:16}}><h3>No official ATS employers registered yet.</h3><p>That does not stop automatic discovery. Use the latest-jobs scan above.</p></div>}
    </section>

    <details className="panel" style={{marginTop:18}}><summary style={{cursor:'pointer',fontWeight:700}}>Advanced: add a specific official employer source</summary><p style={{marginTop:14}}>Use this only when you want Mettelo to verify an employer directly against its Greenhouse or Lever job board.</p><form className="formCard" onSubmit={add} style={{marginTop:16}}><div className="fieldRow"><div><label>Provider</label><select name="provider" defaultValue="greenhouse"><option value="greenhouse">Greenhouse</option><option value="lever">Lever</option></select></div><div><label>Organisation *</label><input name="organisation_name" required placeholder="Employer name"/></div></div><div className="fieldRow"><div><label>Board token / site key *</label><input name="source_key" required placeholder="e.g. companyname"/><small>Greenhouse board token or Lever site name.</small></div><div><label>Employer domain</label><input name="employer_domain" placeholder="company.com"/></div></div><div className="fieldRow"><div><label>Region</label><select name="region" defaultValue="global"><option value="global">Global</option><option value="eu">EU</option></select></div><div style={{display:'flex',alignItems:'end'}}><button className="button dark" type="submit" disabled={working==='add'} style={{width:'100%'}}>{working==='add'?'Adding…':'Add official source →'}</button></div></div></form></details>
  </>;
}
