'use client';

import {useState} from 'react';
import styles from './AdminProjectArchitectQueue.module.css';

export type ArchitectReviewItem={id:string;user_id:string;name:string;email:string;status:string;submitted_at:string|null;updated_at:string;data_ai_experience:string;project_delivery_experience:string;coordination_experience:string;proposed_first_project:string;availability:string;motivation:string;reviewer_notes:string|null;evidence:{id:string;label:string;external_url:string|null;contribution_id:string|null;proof_title?:string|null}[]};
const decisions=[['under_review','Mark under review'],['additional_evidence_required','Request evidence'],['approved','Approve identity'],['declined','Decline'],['suspended','Suspend']] as const;
function canApply(status:string,action:string){if(action==='under_review')return ['submitted','additional_evidence_required'].includes(status);if(action==='additional_evidence_required')return ['submitted','under_review'].includes(status);if(action==='approved'||action==='declined')return ['submitted','under_review','additional_evidence_required'].includes(status);if(action==='suspended')return status==='approved';return false}
export default function AdminProjectArchitectQueue({initialItems}:{initialItems:ArchitectReviewItem[]}){
  const [items,setItems]=useState(initialItems);const [notes,setNotes]=useState<Record<string,string>>({});const [working,setWorking]=useState('');const [message,setMessage]=useState('');
  async function decide(id:string,action:string){setWorking(id);setMessage('Recording decision…');try{const response=await fetch('/api/admin/project-architect-applications',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,action,notes:notes[id]||''})});const body=await response.json();if(!response.ok)throw new Error(body.error||'Unable to record decision.');setItems(current=>current.map(item=>item.id===id?{...item,status:action,reviewer_notes:notes[id]||null}:item));setMessage(action==='approved'?'Project Architect approved. The identity and credential were created in one transaction.':'Decision recorded without granting elevated permissions.');}catch(error){setMessage(error instanceof Error?error.message:'Unable to record decision.');}finally{setWorking('');}}
  return <div className={styles.queue}>{items.length?items.map(item=><article className={styles.card} key={item.id}><header><div><span className="chip">{item.status.replaceAll('_',' ').toUpperCase()}</span><h2>{item.name}</h2><p>{item.email}{item.submitted_at?` · submitted ${new Date(item.submitted_at).toLocaleDateString('en-GB')}`:''}</p></div></header><div className={styles.grid}><section><span>DATA &amp; AI EXPERIENCE</span><p>{item.data_ai_experience}</p></section><section><span>PROJECT DELIVERY</span><p>{item.project_delivery_experience}</p></section><section><span>COLLABORATION &amp; COORDINATION</span><p>{item.coordination_experience}</p></section><section><span>PROJECT THEY WOULD LIKE TO SHAPE</span><p>{item.proposed_first_project}</p></section><section><span>PREFERRED AVAILABILITY</span><p>{item.availability}</p></section><section><span>MOTIVATION</span><p>{item.motivation}</p></section></div><section className={styles.evidence}><h3>Supporting work</h3>{item.evidence.length?<div>{item.evidence.map(entry=>entry.external_url?<a key={entry.id} href={entry.external_url} target="_blank" rel="noopener noreferrer">{entry.label} ↗</a>:<span key={entry.id}>{entry.proof_title||entry.label} · verified Mettelo Proof</span>)}</div>:<p>No supporting work attached.</p>}</section><section className={styles.decision}><label htmlFor={`architect-note-${item.id}`}>Decision note</label><textarea id={`architect-note-${item.id}`} rows={3} maxLength={2000} value={notes[item.id]??item.reviewer_notes??''} onChange={event=>setNotes(current=>({...current,[item.id]:event.target.value}))} placeholder="Explain requests for more information, declined applications or suspensions."/><div>{decisions.map(([action,label])=><button className={action==='approved'?'button dark':'button ghost'} type="button" key={action} disabled={working===item.id||!canApply(item.status,action)} onClick={()=>void decide(item.id,action)}>{label}</button>)}</div></section></article>):<div className="emptyState"><h3>No Project Architect applications yet.</h3><p>New applications will appear here for review.</p></div>}<div className="formStatus" role="status" aria-live="polite">{message}</div></div>;
}
