'use client';

import {useMemo,useState} from 'react';
import styles from './AdminReview.module.css';

type Item={id:string;name:string;email:string;project:string;role:string;status:string;submitted_at:string;statement:string;portfolio_url:string|null;availability:string|null;reviewer_notes?:string|null;profile:{headline:string|null;skills:string[];experience_level:string|null;project_availability:string|null;weekly_capacity:string|null};communications:{title:string;body:string;created_at:string}[]};
const defaults:Record<string,(item:Item)=>string>={in_review:item=>`Your application for ${item.project} is now in review. No action is required from you right now. We will update My Mettelo when the next decision is available.`,shortlisted:item=>`You have been shortlisted for ${item.project}. No action is required right now; we will contact you if we need more information before the final decision.`,approved:item=>`Your application for ${item.project} has been approved. Your place is confirmed and will move into team formation. Keep your availability current while the team is completed.`,declined:item=>`Your application for ${item.project} was not selected for this team. You can continue exploring other Mettelo projects that match your profile.`};

export default function AdminApplicationQueue({initialItems}:{initialItems:Item[]}){
  const [items,setItems]=useState(initialItems);const [working,setWorking]=useState('');const [message,setMessage]=useState('');const [notes,setNotes]=useState<Record<string,string>>(()=>Object.fromEntries(initialItems.map(item=>[item.id,item.reviewer_notes||''])));const [customMessages,setCustomMessages]=useState<Record<string,string>>({});const [selected,setSelected]=useState<string[]>([]);
  const selectedItems=useMemo(()=>items.filter(item=>selected.includes(item.id)),[items,selected]);const selectedProject=selectedItems[0]?.project||'';
  async function update(id:string,status:string){const item=items.find(candidate=>candidate.id===id);const memberMessage=(customMessages[id]||'').trim()||(item&&defaults[status]?defaults[status](item):'');const response=await fetch('/api/admin/applications',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,status,reviewer_notes:notes[id]||'',custom_message:memberMessage})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'Unable to update application.');setItems(current=>current.map(currentItem=>currentItem.id===id?{...currentItem,status:payload.application?.status||status,communications:memberMessage?[{title:`Application ${status.replaceAll('_',' ')}`,body:memberMessage,created_at:new Date().toISOString()},...currentItem.communications].slice(0,5):currentItem.communications}:currentItem));return payload;}
  async function updateOne(id:string,status:string){setWorking(id);setMessage('');try{const payload=await update(id,status);setMessage(status==='approved'?(payload.team?.full?`Approved. Team reached ${payload.team.filled}/${payload.team.threshold}; project kicked off.`:`Approved. Team is forming at ${payload.team?.filled||0}/${payload.team?.threshold||'—'} spots.`):'Application status and member communication updated.');}catch(error){setMessage(error instanceof Error?error.message:'Unable to update application.');}finally{setWorking('')}}
  function toggle(item:Item){setSelected(current=>current.includes(item.id)?current.filter(id=>id!==item.id):selectedProject&&selectedProject!==item.project?current:[...current,item.id]);}
  async function bulk(status:'approved'|'shortlisted'|'in_review'|'declined'){if(!selectedItems.length)return;setWorking('bulk');setMessage('');let changed=0;try{for(const item of selectedItems){const payload=await update(item.id,status);changed++;if(status==='approved'&&payload.team?.full){setMessage(`Approved ${changed} selected applicant${changed===1?'':'s'}. ${item.project} reached ${payload.team.filled}/${payload.team.threshold}; bulk approval stopped because the team is now full. Remaining applicants stay in review.`);break;}}if(status!=='approved')setMessage(`${changed} selected application${changed===1?'':'s'} updated with member communication.`);setSelected([]);}catch(error){setMessage(error instanceof Error?error.message:'Bulk review could not be completed.');}finally{setWorking('')}}
  return <div className="applicationQueue"><div className="panel" style={{marginBottom:16,padding:14}}><div className="panelHead"><div><strong>Bulk review</strong><small style={{display:'block',marginTop:4}}>Select applicants from one project at a time. Individual messages use the safe default unless you personalise them below.</small></div><span className="chip">{selected.length} SELECTED</span></div><div className="actions" style={{marginTop:10}}><button className="button ghost" type="button" disabled={!selected.length||working==='bulk'} onClick={()=>bulk('in_review')}>Mark under review</button><button className="button ghost" type="button" disabled={!selected.length||working==='bulk'} onClick={()=>bulk('shortlisted')}>Shortlist selected</button><button className="button dark" type="button" disabled={!selected.length||working==='bulk'} onClick={()=>bulk('approved')}>{working==='bulk'?'Processing…':'Approve selected → team'}</button><button className="button ghost" type="button" disabled={!selected.length||working==='bulk'} onClick={()=>bulk('declined')}>Decline selected</button></div></div>
    {!items.length?<div className="emptyState"><h3>No applications on this page.</h3><p>New project requests appear here automatically.</p></div>:items.map(item=>{const locked=Boolean(selectedProject&&selectedProject!==item.project&&!selected.includes(item.id));return <article className={styles.card} key={item.id}><div className={styles.header}><div className={styles.heading}><div className={styles.statusLine}><input type="checkbox" checked={selected.includes(item.id)} disabled={locked||working==='bulk'} onChange={()=>toggle(item)} aria-label={`Select ${item.name}`}/><span className="chip">{item.status.replaceAll('_',' ').toUpperCase()}</span>{item.availability&&<span className="metaPill">{item.availability}</span>}</div><h3>{item.name}</h3><small>{item.project} · {item.role} · {item.email}</small></div><small className={styles.date}>{new Date(item.submitted_at).toLocaleString('en-GB')}</small></div>
      <div className="adminApplicationContext"><section><span className={styles.label}>Applicant profile</span><p className={styles.copy}>{item.profile.headline||'No professional headline supplied.'}</p><div className="metaRow">{item.profile.experience_level&&<span className="metaPill">{item.profile.experience_level.replaceAll('_',' ')}</span>}{item.profile.project_availability&&<span className="metaPill">{item.profile.project_availability.replaceAll('_',' ')}</span>}{item.profile.weekly_capacity&&<span className="metaPill">{item.profile.weekly_capacity}</span>}</div>{item.profile.skills.length?<div className="metaRow" style={{marginTop:8}}>{item.profile.skills.slice(0,8).map(skill=><span className="metaPill" key={skill}>{skill}</span>)}</div>:null}</section>
      <section><span className={styles.label}>Application</span><p className={styles.copy}>{item.statement}</p></section>
      <section><span className={styles.label}>Evidence</span><div className={styles.links}>{item.portfolio_url?<a className="linkArrow" href={item.portfolio_url} target="_blank" rel="noopener noreferrer">Open portfolio / evidence →</a>:<span className={styles.copy}>No evidence link supplied.</span>}</div></section>
      <section><span className={styles.label}>Communication history</span>{item.communications.length?<div className="communicationHistory">{item.communications.map((entry,index)=><div key={`${entry.created_at}-${index}`}><strong>{entry.title}</strong><small>{new Date(entry.created_at).toLocaleString('en-GB')}</small><p>{entry.body}</p></div>)}</div>:<p className={styles.copy}>No member communication has been recorded for this application yet.</p>}</section></div>
      <div className={styles.adminPanel}><span className={styles.adminPanelTitle}>Admin review & communication</span><div className={styles.field}><label htmlFor={`project-note-${item.id}`}>Internal reviewer note / decision reason</label><textarea id={`project-note-${item.id}`} value={notes[item.id]||''} onChange={event=>setNotes(current=>({...current,[item.id]:event.target.value}))} maxLength={1500} rows={3}/><small>Internal context is stored with the application. Decline reasons may also be reflected in the member-facing decision where appropriate.</small></div><div className={styles.field}><label htmlFor={`project-message-${item.id}`}>Member message</label><textarea id={`project-message-${item.id}`} value={customMessages[item.id]||''} onChange={event=>setCustomMessages(current=>({...current,[item.id]:event.target.value}))} maxLength={1800} rows={4} placeholder="Optional: personalise the communication. Leave blank to use Mettelo's safe default for the selected status."/><small>Review this before changing status. The same message is recorded in the member communication history.</small></div><div className={styles.field}><span className={styles.label}>Application status</span><div className={styles.statusGroup}><button className={`${styles.statusButton} ${item.status==='in_review'?styles.active:''}`} type="button" disabled={working===item.id||working==='bulk'||item.status==='in_review'} onClick={()=>updateOne(item.id,'in_review')}>Under review</button><button className={`${styles.statusButton} ${item.status==='shortlisted'?styles.active:''}`} type="button" disabled={working===item.id||working==='bulk'||item.status==='shortlisted'} onClick={()=>updateOne(item.id,'shortlisted')}>Shortlist</button><button className={`${styles.statusButton} ${item.status==='approved'?styles.active:''}`} type="button" disabled={working===item.id||working==='bulk'||item.status==='approved'} onClick={()=>updateOne(item.id,'approved')}>Approve → team</button><button className={`${styles.statusButton} ${item.status==='declined'?styles.active:''}`} type="button" disabled={working===item.id||working==='bulk'||item.status==='declined'} onClick={()=>updateOne(item.id,'declined')}>Decline</button></div></div></div></article>})}<div className="formStatus" role="status" aria-live="polite">{message}</div><style jsx>{`.adminApplicationContext{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin:16px 0}.adminApplicationContext section{padding:14px;border:1px solid rgba(16,19,29,.08);border-radius:12px;background:#fff}.communicationHistory{display:grid;gap:8px;margin-top:8px}.communicationHistory>div{padding:10px;border-radius:9px;background:#f7f7f6}.communicationHistory strong,.communicationHistory small{display:block}.communicationHistory small{margin-top:2px;color:#6f7782}.communicationHistory p{margin:5px 0 0;color:#596371;font-size:.78rem;line-height:1.45}@media(max-width:760px){.adminApplicationContext{grid-template-columns:1fr}}`}</style></div>;
}
