'use client';

import {FormEvent,useState} from 'react';

export default function AdminProjectCreateForm(){
  const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage('');setError(false);const form=event.currentTarget;const data=Object.fromEntries(new FormData(form).entries());try{const response=await fetch('/api/admin/projects',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Unable to create project.');setMessage(`Project created: ${body.project?.title||'Project'}.`);form.reset();}catch(e){setError(true);setMessage(e instanceof Error?e.message:'Unable to create project.');}finally{setBusy(false)}}
  return <form className="adminProjectForm" onSubmit={submit}>
    <div className="adminProjectGrid"><label>Project title *<input name="title" required maxLength={160}/></label><label>Project type *<select name="project_type" defaultValue="open" required><option value="open">Open Project</option><option value="partner">Partner Project</option></select></label><label className="adminProjectFull">Short summary *<textarea name="summary" required minLength={30} maxLength={1200} rows={4}/></label><label>Partner name<input name="partner_name" placeholder="Required for Partner Projects"/></label><label>Status *<select name="status" defaultValue="draft"><option value="draft">Draft</option><option value="open">Open</option><option value="recruiting">Recruiting</option><option value="pilot">Pilot / interest only</option></select></label><label>Visibility *<select name="visibility" defaultValue="public"><option value="public">Public</option><option value="private">Private</option></select></label><label>Location type<select name="location_type" defaultValue="remote"><option value="remote">Remote</option><option value="hybrid">Hybrid</option><option value="in_person">In person</option></select></label><label>Location<input name="location" placeholder="e.g. UK / Global / Lagos"/></label><label>Difficulty<select name="difficulty_level" defaultValue="intermediate"><option value="entry">Entry</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select></label><label>Duration (weeks)<input name="duration_weeks" type="number" min="1" max="52"/></label><label>Weekly commitment<input name="weekly_commitment" placeholder="e.g. 4–6 hours"/></label><label>Team size<input name="team_size_threshold" type="number" min="1" max="30" defaultValue="5"/></label><label>Application deadline<input name="application_deadline" type="datetime-local"/></label><label className="adminProjectFull">Initial roles *<textarea name="roles" required rows={5} placeholder={'One role per line\nAnalytics Engineer\nData Analyst\nProject Lead'}/><small>At least one role is required before members can apply.</small></label></div>
    <div className="adminProjectSubmit"><button className="button dark" type="submit" disabled={busy}>{busy?'Creating project…':'Create project →'}</button><span className={error?'formError':'formSuccess'} role="status">{message}</span></div>
    <style jsx>{`.adminProjectForm{padding:22px;border:1px solid var(--line);border-radius:18px;background:#fff}.adminProjectGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.adminProjectGrid label{display:grid;gap:7px;font-size:.75rem;font-weight:750;color:#303743}.adminProjectGrid input,.adminProjectGrid select,.adminProjectGrid textarea{width:100%;padding:11px 12px;border:1px solid rgba(16,19,29,.14);border-radius:10px;background:#fff;font:inherit}.adminProjectGrid textarea{resize:vertical}.adminProjectFull{grid-column:1/-1}.adminProjectGrid small{color:var(--slate);font-weight:500}.adminProjectSubmit{display:flex;align-items:center;gap:16px;margin-top:18px}.formError{color:#b42318}.formSuccess{color:#13734c}@media(max-width:720px){.adminProjectGrid{grid-template-columns:1fr}.adminProjectFull{grid-column:auto}.adminProjectSubmit{align-items:stretch;flex-direction:column}.adminProjectSubmit .button{width:100%;min-height:44px}}`}</style>
  </form>;
}
