'use client';

import {useEffect,useMemo,useRef,useState} from 'react';
import AdminCareerInterviewComposer from './AdminCareerInterviewComposer';
import AdminCareerFormalOfferComposer from './AdminCareerFormalOfferComposer';
import AdminCareerMessageComposer from './AdminCareerMessageComposer';
import AdminCareerOnboarding,{type CareerOnboardingItem} from './AdminCareerOnboarding';

type Question={id?:string;label?:string;required?:boolean}|string;
type Profile={id:string;full_name:string|null;headline:string|null;current_job_title:string|null;professional_area:string|null;skills:string[]|null;project_availability:string|null};
type Communication={id:string;template_key:string;subject:string;status:string;recipient_email:string;actor_user_id:string|null;created_at:string;sent_at:string|null};
export type CareerApplicationAdminItemV2={
 id:string;user_id:string|null;role_id?:string;full_name:string;email:string;status:string;final_outcome:string;final_outcome_updated_at:string|null;offer_status:string;offer_sent_at:string|null;submitted_at:string;location:string|null;linkedin_url:string|null;portfolio_url:string|null;work_authorisation:string|null;motivation:string;relevant_experience:string;answers:Record<string,string>;admin_notes:string|null;interview_at:string|null;interview_timezone:string|null;interview_format:string|null;interview_url:string|null;interviewer:string|null;interview_instructions:string|null;offer_salary_rate:string|null;offer_start_date:string|null;offer_employment_type:string|null;offer_manager:string|null;offer_working_arrangement:string|null;offer_conditions:string|null;offer_acceptance_deadline:string|null;offer_personal_message:string|null;cv_url:string|null;career_roles:{id?:string;title:string;application_questions:Question[]}|null;profile:Profile|null;communications:Communication[];onboarding_items:CareerOnboardingItem[];
};

type MessageKind='hired'|'rejected'|'custom';
const stages=[
 {value:'submitted',label:'Application Received'},
 {value:'in_review',label:'Under Review'},
 {value:'shortlisted',label:'Shortlisted'},
 {value:'interview',label:'Interview & Final Decision'}
] as const;

function normalisedStage(status:string){return ['offer','hired','rejected'].includes(status)?'interview':status;}
function stageLabel(status:string){if(status==='withdrawn')return'Withdrawn';return stages.find(item=>item.value===normalisedStage(status))?.label||status.replaceAll('_',' ');}
function outcomeLabel(outcome:string){return outcome==='hired'?'Hired':outcome==='rejected'?'Rejected':'Decision Pending';}
function offerLabel(status:string){return status==='sent'?'Sent':status==='ready'?'Ready / queued':status==='send_failed'?'Send failed':'Not prepared';}
function qid(item:Question,index:number){return typeof item==='string'?`q${index+1}`:item.id||`q${index+1}`;}
function qlabel(item:Question,index:number){return typeof item==='string'?item:item.label||`Question ${index+1}`;}
function localDate(value:string|null){return value?new Date(value).toISOString().slice(0,16):'';}
function latestCommunication(item:CareerApplicationAdminItemV2,key:string){return item.communications.find(record=>record.template_key===key);}

export default function AdminCareerApplicationQueueV2({initialItems,initialRoleFilter=''}:{initialItems:CareerApplicationAdminItemV2[];initialRoleFilter?:string}){
 const [items,setItems]=useState(initialItems);
 const [q,setQ]=useState('');const [role,setRole]=useState(initialRoleFilter);const [stageFilter,setStageFilter]=useState('');const [outcomeFilter,setOutcomeFilter]=useState('');const [offerFilter,setOfferFilter]=useState('');const [dateFrom,setDateFrom]=useState('');const [dateTo,setDateTo]=useState('');const [sort,setSort]=useState('newest');const [page,setPage]=useState(1);const [rows,setRows]=useState(25);
 const [selected,setSelected]=useState<string[]>([]);const [active,setActive]=useState<CareerApplicationAdminItemV2|null>(null);const [notes,setNotes]=useState<Record<string,string>>(Object.fromEntries(initialItems.map(item=>[item.id,item.admin_notes||''])));const [stageDraft,setStageDraft]=useState<Record<string,string>>({});const [message,setMessage]=useState('');const [busy,setBusy]=useState('');const [interviewFor,setInterviewFor]=useState('');const [offerFor,setOfferFor]=useState('');const [messageFor,setMessageFor]=useState<{id:string;kind:MessageKind}|null>(null);const detailRef=useRef<HTMLDialogElement>(null);

 const roles=useMemo(()=>[...new Map(items.map(item=>[item.career_roles?.id||item.career_roles?.title||'',{id:item.career_roles?.id||'',title:item.career_roles?.title||'Mettelo role'}])).values()].filter(x=>x.title),[items]);
 const filtered=useMemo(()=>items.filter(item=>(!q||`${item.full_name} ${item.email}`.toLowerCase().includes(q.toLowerCase()))&&(!role||(item.career_roles?.id===role||item.career_roles?.title===role))&&(!stageFilter||normalisedStage(item.status)===stageFilter)&&(!outcomeFilter||item.final_outcome===outcomeFilter)&&(!offerFilter||item.offer_status===offerFilter)&&(!dateFrom||new Date(item.submitted_at)>=new Date(dateFrom))&&(!dateTo||new Date(item.submitted_at)<=new Date(`${dateTo}T23:59:59`))).sort((a,b)=>(sort==='oldest'?1:-1)*(new Date(a.submitted_at).getTime()-new Date(b.submitted_at).getTime())),[items,q,role,stageFilter,outcomeFilter,offerFilter,dateFrom,dateTo,sort]);
 const pages=Math.max(1,Math.ceil(filtered.length/rows));const visible=filtered.slice((page-1)*rows,page*rows);const allVisibleSelected=visible.length>0&&visible.every(item=>selected.includes(item.id));

 useEffect(()=>{if(active&&detailRef.current&&!detailRef.current.open)detailRef.current.showModal();if(!active&&detailRef.current?.open)detailRef.current.close();},[active]);
 function patchItem(id:string,patch:Partial<CareerApplicationAdminItemV2>){setItems(current=>current.map(item=>item.id===id?{...item,...patch}:item));setActive(current=>current?.id===id?{...current,...patch}:current);}
 async function jsonRequest(url:string,payload:Record<string,unknown>){const r=await fetch(url,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const b=await r.json();if(!r.ok)throw new Error(b.error||'Unable to update candidate.');return b;}

 async function saveNote(item:CareerApplicationAdminItemV2){setBusy(`note-${item.id}`);setMessage('');try{await jsonRequest('/api/admin/careers/notes',{id:item.id,note:notes[item.id]||''});patchItem(item.id,{admin_notes:notes[item.id]||null});setMessage('Internal note saved. It remains private to authorised Admin users.');}catch(error){setMessage(error instanceof Error?error.message:'Unable to save internal note.');}finally{setBusy('');}}
 async function changeStage(item:CareerApplicationAdminItemV2,target?:string){const stage=target||stageDraft[item.id]||normalisedStage(item.status);if(stage===normalisedStage(item.status)){setMessage('Choose a different recruitment stage.');return false;}setBusy(item.id);setMessage('');try{const b=await jsonRequest('/api/admin/careers/workflow',{id:item.id,action:'stage',stage,note:notes[item.id]||''});patchItem(item.id,{status:b.status,final_outcome:b.final_outcome,admin_notes:notes[item.id]||null});setStageDraft(current=>({...current,[item.id]:b.status}));if(stage==='interview')setMessage('Candidate moved to Interview & Final Decision. No final-stage communication was sent.');else if(b.email_sent)setMessage(`${b.stage_label} saved and the configured candidate update was sent.`);else if(b.email_queued)setMessage(`${b.stage_label} saved and the configured candidate update is queued.`);else if(b.email_skipped)setMessage(`${b.stage_label} saved. An earlier candidate update for this stage already exists, so no duplicate email was sent.`);else setMessage(`${b.stage_label} saved. No candidate communication was sent.`);return true;}catch(error){setMessage(error instanceof Error?error.message:'Unable to update recruitment stage.');return false;}finally{setBusy('');}}
 async function changeOutcome(item:CareerApplicationAdminItemV2,outcome:string){if(item.final_outcome===outcome)return;setBusy(item.id);setMessage('');try{const b=await jsonRequest('/api/admin/careers/workflow',{id:item.id,action:'outcome',outcome,note:notes[item.id]||''});patchItem(item.id,{status:'interview',final_outcome:b.final_outcome,final_outcome_updated_at:new Date().toISOString(),admin_notes:notes[item.id]||null,onboarding_items:Array.isArray(b.onboarding_items)&&outcome==='hired'?b.onboarding_items:item.onboarding_items});setMessage(`Final outcome updated to ${outcomeLabel(outcome)}. No candidate communication was sent.`);}catch(error){setMessage(error instanceof Error?error.message:'Unable to update final outcome.');}finally{setBusy('');}}
 async function sendCommunication(item:CareerApplicationAdminItemV2,kind:string,payload:Record<string,unknown>){setBusy(item.id);setMessage('');const sendToken=crypto.randomUUID();try{const b=await jsonRequest('/api/admin/careers/workflow',{id:item.id,action:'communicate',kind,confirm_send:true,send_token:sendToken,...payload});const now=new Date().toISOString();const record:Communication={id:b.communication?.id||`local-${sendToken}`,template_key:`career_${kind}`,subject:String(payload.subject||'Candidate communication'),status:b.email_sent?'sent':'queued',recipient_email:item.email,actor_user_id:null,created_at:now,sent_at:b.email_sent?now:null};const patch:Partial<CareerApplicationAdminItemV2>={communications:[record,...item.communications].slice(0,20)};if(kind==='interview')Object.assign(patch,{interview_at:String(payload.interview_at||''),interview_timezone:String(payload.interview_timezone||''),interview_format:String(payload.interview_format||''),interview_url:String(payload.interview_url||''),interviewer:String(payload.interviewer||''),interview_instructions:String(payload.interview_instructions||'')});if(kind==='offer')Object.assign(patch,{offer_status:b.offer_status||'ready',offer_sent_at:b.email_sent?now:item.offer_sent_at,offer_salary_rate:String(payload.offer_salary_rate||''),offer_start_date:String(payload.offer_start_date||''),offer_employment_type:String(payload.offer_employment_type||''),offer_manager:String(payload.offer_manager||''),offer_working_arrangement:String(payload.offer_working_arrangement||''),offer_conditions:String(payload.offer_conditions||''),offer_acceptance_deadline:String(payload.offer_acceptance_deadline||''),offer_personal_message:String(payload.offer_personal_message||'')});patchItem(item.id,patch);setInterviewFor('');setOfferFor('');setMessageFor(null);setMessage(b.email_sent?'Candidate communication sent successfully.':'Candidate communication is queued for delivery.');return true;}catch(error){setMessage(error instanceof Error?error.message:'Unable to send candidate communication.');return false;}finally{setBusy('');}}
 async function bulkMove(target:string){const eligible=selected.map(id=>items.find(item=>item.id===id)).filter((item):item is CareerApplicationAdminItemV2=>item!==undefined&&item.status!=='withdrawn');setBusy('bulk');let completed=0;for(const item of eligible){if(await changeStage(item,target))completed+=1;}setSelected([]);setBusy('');setMessage(`${completed} candidate${completed===1?'':'s'} updated.`);}
 const toggleAll=()=>setSelected(current=>allVisibleSelected?current.filter(id=>!visible.some(item=>item.id===id)):[...new Set([...current,...visible.map(item=>item.id)])]);

 return <>
  <div className="adminTableShell"><div className="adminToolbar"><input type="search" aria-label="Search candidates" placeholder="Search name or email" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/><select aria-label="Filter by role" value={role} onChange={e=>{setRole(e.target.value);setPage(1)}}><option value="">All roles</option>{roles.map(item=><option value={item.id||item.title} key={item.id||item.title}>{item.title}</option>)}</select><select aria-label="Filter by recruitment stage" value={stageFilter} onChange={e=>{setStageFilter(e.target.value);setPage(1)}}><option value="">All stages</option>{stages.map(stage=><option key={stage.value} value={stage.value}>{stage.label}</option>)}</select><select aria-label="Filter by final outcome" value={outcomeFilter} onChange={e=>{setOutcomeFilter(e.target.value);setPage(1)}}><option value="">All outcomes</option><option value="pending">Decision Pending</option><option value="hired">Hired</option><option value="rejected">Rejected</option></select><select aria-label="Filter by offer status" value={offerFilter} onChange={e=>{setOfferFilter(e.target.value);setPage(1)}}><option value="">All offer statuses</option><option value="not_prepared">Not prepared</option><option value="ready">Ready / queued</option><option value="sent">Sent</option><option value="send_failed">Send failed</option></select><input type="date" aria-label="Applied from" value={dateFrom} onChange={e=>setDateFrom(e.target.value)}/><input type="date" aria-label="Applied to" value={dateTo} onChange={e=>setDateTo(e.target.value)}/><select aria-label="Sort candidates" value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Newest</option><option value="oldest">Oldest</option></select><span className="toolbarCount">{filtered.length} candidates</span></div>
   {visible.length?<div className="adminDataTableWrap"><table className="adminDataTable"><thead><tr><th><input type="checkbox" aria-label="Select visible candidates" checked={allVisibleSelected} onChange={toggleAll}/></th><th>Candidate</th><th>Applied role</th><th>Recruitment stage</th><th>Final outcome</th><th>Offer</th><th>Applied</th><th></th></tr></thead><tbody>{visible.map(item=><tr key={item.id}><td className="adminCheckboxCell"><input type="checkbox" aria-label={`Select ${item.full_name}`} checked={selected.includes(item.id)} onChange={e=>setSelected(current=>e.target.checked?[...current,item.id]:current.filter(id=>id!==item.id))}/></td><td data-label="Candidate"><strong>{item.full_name}</strong><small>{item.email}</small></td><td data-label="Role"><strong>{item.career_roles?.title||'Mettelo role'}</strong></td><td data-label="Stage"><span className="workflowBadge">{stageLabel(item.status)}</span></td><td data-label="Outcome"><span className={`outcomeBadge ${item.final_outcome}`}>{normalisedStage(item.status)==='interview'?outcomeLabel(item.final_outcome):'—'}</span></td><td data-label="Offer">{item.final_outcome==='hired'?offerLabel(item.offer_status):'—'}</td><td data-label="Applied">{new Date(item.submitted_at).toLocaleDateString('en-GB')}</td><td className="adminActionCell"><button className="candidateView" type="button" onClick={()=>{setActive(item);setStageDraft(current=>({...current,[item.id]:normalisedStage(item.status)}))}}>View →</button></td></tr>)}</tbody></table></div>:<div className="adminEmpty"><h3>No candidates match these filters.</h3><p>Clear filters or choose another stage, outcome or role.</p></div>}
   <div className="adminPagination"><span className="adminPaginationMeta">{filtered.length} applications · Page {page} of {pages}</span><div className="adminPaginationControls"><select aria-label="Rows per page" value={rows} onChange={e=>{setRows(Number(e.target.value));setPage(1)}}><option>25</option><option>50</option><option>100</option></select><button type="button" disabled={page<=1} onClick={()=>setPage(x=>x-1)}>Previous</button><button type="button" disabled={page>=pages} onClick={()=>setPage(x=>x+1)}>Next</button></div></div>
   {selected.length>0&&<div className="adminBulkBar" role="region" aria-label="Candidate bulk actions"><strong>{selected.length} selected</strong><button type="button" disabled={busy==='bulk'} onClick={()=>void bulkMove('in_review')}>Mark under review</button><button type="button" disabled={busy==='bulk'} onClick={()=>void bulkMove('shortlisted')}>Shortlist selected</button><button type="button" onClick={()=>setSelected([])}>Clear</button></div>}
  </div>
  <div className="formStatus" role="status" aria-live="polite">{message}</div>

  <dialog ref={detailRef} className="candidateDetail workflowDetail" aria-labelledby="career-candidate-detail-title" onClose={()=>setActive(null)}>{active&&<><header><div><span className="cardNumber">CANDIDATE APPLICATION</span><h2 id="career-candidate-detail-title">{active.full_name}</h2><p>{active.career_roles?.title||'Mettelo role'} · {active.email}</p></div><button type="button" aria-label="Close candidate detail" onClick={()=>setActive(null)}>×</button></header><div className="candidateDetailBody"><div className="candidateSummary"><span className="workflowBadge">{stageLabel(active.status)}</span>{normalisedStage(active.status)==='interview'&&<span className={`outcomeBadge ${active.final_outcome}`}>{outcomeLabel(active.final_outcome)}</span>}<span>Applied {new Date(active.submitted_at).toLocaleDateString('en-GB')}</span>{active.location&&<span>{active.location}</span>}{active.profile&&<a href={`/people/${active.profile.id}`} target="_blank" rel="noopener noreferrer">Profile ↗</a>}</div>
   {active.profile&&<section><h3>Profile context</h3><p>{active.profile.headline||active.profile.current_job_title||active.profile.professional_area||'Mettelo profile available'}</p>{active.profile.skills?.length?<small>{active.profile.skills.slice(0,10).join(' · ')}</small>:null}</section>}
   <section><h3>Motivation</h3><p className="candidateLongText">{active.motivation}</p></section><section><h3>Relevant experience</h3><p className="candidateLongText">{active.relevant_experience}</p></section>
   {(active.career_roles?.application_questions||[]).length>0&&<section><h3>Role-specific answers</h3>{(active.career_roles?.application_questions||[]).map((question,index)=><div className="candidateAnswer" key={qid(question,index)}><strong>{qlabel(question,index)}</strong><p>{active.answers?.[qid(question,index)]||'No answer recorded.'}</p></div>)}</section>}
   <section><h3>Evidence &amp; links</h3><div className="candidateLinks">{active.cv_url&&<a href={active.cv_url} target="_blank" rel="noopener noreferrer">Open CV ↗</a>}{active.linkedin_url&&<a href={active.linkedin_url} target="_blank" rel="noopener noreferrer">LinkedIn ↗</a>}{active.portfolio_url&&<a href={active.portfolio_url} target="_blank" rel="noopener noreferrer">Portfolio ↗</a>}</div></section>
   <section className="workflowPanel"><div className="workflowPanelHead"><div><span>ADMIN REVIEW</span><h3>Recruitment workspace</h3></div><small>Stage and communication are deliberately separate.</small></div><label>Internal note <small>Never visible to the candidate.</small><textarea rows={4} value={notes[active.id]||''} onChange={e=>setNotes(current=>({...current,[active.id]:e.target.value}))}/></label><button className="button ghost" type="button" disabled={busy===`note-${active.id}`} onClick={()=>void saveNote(active)}>{busy===`note-${active.id}`?'Saving…':'Save internal note'}</button>
    <div className="workflowBlock"><div><span>RECRUITMENT STAGE</span><h4>{stageLabel(active.status)}</h4><p>Stages 1–3 may use their configured automatic updates. Entering the final stage sends nothing automatically.</p></div><label>Change stage<select aria-label="Recruitment stage" value={stageDraft[active.id]||normalisedStage(active.status)} onChange={e=>setStageDraft(current=>({...current,[active.id]:e.target.value}))}>{stages.map(stage=><option key={stage.value} value={stage.value}>{stage.label}</option>)}</select></label><button className="button dark" type="button" disabled={busy===active.id||(stageDraft[active.id]||normalisedStage(active.status))===normalisedStage(active.status)} onClick={()=>void changeStage(active)}>Update stage</button></div>
    {normalisedStage(active.status)==='interview'&&<><div className="workflowBlock"><div><span>INTERVIEW</span><h4>Schedule or update interview</h4><p>Interview details are managed here without creating another pipeline stage. Each explicit send is recorded in Communication History.</p>{active.interview_at&&<small>Latest scheduled interview: {new Date(active.interview_at).toLocaleString('en-GB')} · {active.interview_timezone||'Timezone not recorded'}</small>}</div><button className="button ghost" type="button" disabled={busy===active.id||active.final_outcome!=='pending'} onClick={()=>setInterviewFor(active.id)}>Schedule Interview</button></div>
     <div className="workflowBlock"><div><span>FINAL OUTCOME</span><h4>{outcomeLabel(active.final_outcome)}</h4><p>Changing the outcome never contacts the candidate.</p></div><div className="outcomeActions"><button type="button" className={active.final_outcome==='pending'?'selected':''} disabled={busy===active.id} onClick={()=>void changeOutcome(active,'pending')}>Decision Pending</button><button type="button" className={active.final_outcome==='hired'?'selected':''} disabled={busy===active.id} onClick={()=>void changeOutcome(active,'hired')}>Hired</button><button type="button" className={active.final_outcome==='rejected'?'selected':''} disabled={busy===active.id} onClick={()=>void changeOutcome(active,'rejected')}>Rejected</button></div></div>
     <div className="workflowBlock"><div><span>CANDIDATE COMMUNICATION</span><h4>Send deliberately</h4><p>No final-stage message is sent merely because stage or outcome changes.</p></div><div className="communicationActions"><button type="button" disabled={busy===active.id||active.final_outcome!=='hired'} onClick={()=>setMessageFor({id:active.id,kind:'hired'})}>Send hired notification</button><button type="button" disabled={busy===active.id||active.final_outcome!=='rejected'} onClick={()=>setMessageFor({id:active.id,kind:'rejected'})}>Send rejection message</button><button type="button" disabled={busy===active.id} onClick={()=>setMessageFor({id:active.id,kind:'custom'})}>Send custom message</button></div>{latestCommunication(active,'career_hired')&&<small>Hired notification: {latestCommunication(active,'career_hired')?.status}</small>}{latestCommunication(active,'career_rejected')&&<small>Rejection message: {latestCommunication(active,'career_rejected')?.status}</small>}</div>
     <div className="workflowBlock offerWorkflow"><div><span>FORMAL OFFER</span><h4>{offerLabel(active.offer_status)}</h4><p>The offer is independent of the recruitment stage and Hired notification.</p>{active.offer_sent_at&&<small>Sent {new Date(active.offer_sent_at).toLocaleString('en-GB')}</small>}</div><button className="button dark" type="button" disabled={busy===active.id||active.final_outcome!=='hired'} onClick={()=>setOfferFor(active.id)}>Prepare &amp; Send Offer</button></div>
     {active.final_outcome==='hired'&&<AdminCareerOnboarding applicationId={active.id} initialItems={active.onboarding_items}/>}</>}
   </section>
   <details><summary>Communication history ({active.communications.length})</summary><ul className="candidateComms">{active.communications.length?active.communications.map(record=><li key={record.id}><strong>{record.subject}</strong><span>{record.template_key.replaceAll('_',' ')} · {record.status}</span><small>To {record.recipient_email} · {new Date(record.sent_at||record.created_at).toLocaleString('en-GB')}</small></li>):<li>No candidate communications recorded yet.</li>}</ul></details>
  </div></>}
  </dialog>

  {active&&<><AdminCareerInterviewComposer open={interviewFor===active.id} candidateName={active.full_name} roleTitle={active.career_roles?.title||'Mettelo role'} busy={busy===active.id} initial={{interview_at:localDate(active.interview_at),interview_timezone:active.interview_timezone||'',interview_format:active.interview_format||'',interview_url:active.interview_url||'',interviewer:active.interviewer||'',interview_instructions:active.interview_instructions||''}} onClose={()=>setInterviewFor('')} onSend={payload=>void sendCommunication(active,'interview',payload)}/><AdminCareerFormalOfferComposer open={offerFor===active.id} applicationId={active.id} candidateName={active.full_name} candidateEmail={active.email} roleTitle={active.career_roles?.title||'Mettelo role'} busy={busy===active.id} initial={{offer_salary_rate:active.offer_salary_rate||'',offer_start_date:active.offer_start_date||'',offer_employment_type:active.offer_employment_type||'',offer_manager:active.offer_manager||'',offer_working_arrangement:active.offer_working_arrangement||'',offer_conditions:active.offer_conditions||'',offer_acceptance_deadline:localDate(active.offer_acceptance_deadline),offer_personal_message:active.offer_personal_message||''}} onClose={()=>setOfferFor('')} onSend={payload=>void sendCommunication(active,'offer',payload)}/>{messageFor?.id===active.id&&<AdminCareerMessageComposer open kind={messageFor.kind} candidateName={active.full_name} candidateEmail={active.email} roleTitle={active.career_roles?.title||'Mettelo role'} busy={busy===active.id} onClose={()=>setMessageFor(null)} onSend={payload=>void sendCommunication(active,messageFor.kind,payload)}/>}</>}
  <style jsx>{`.workflowBadge,.outcomeBadge{display:inline-flex;align-items:center;min-height:28px;padding:5px 9px;border-radius:999px;background:#eff6ff;color:#1e40af;font-size:.66rem;font-weight:850}.outcomeBadge.pending{background:#f1f2f4;color:#4b5563}.outcomeBadge.hired{background:#eaf7ef;color:#0f5132}.outcomeBadge.rejected{background:#fff1ed;color:#8a341f}.workflowPanel{display:grid;gap:14px}.workflowPanelHead{display:flex;justify-content:space-between;gap:16px;align-items:start}.workflowPanelHead span,.workflowBlock>div>span{color:#72501b;font-size:.63rem;font-weight:900;letter-spacing:.08em}.workflowPanelHead h3,.workflowBlock h4{margin:4px 0}.workflowPanelHead>small,.workflowBlock p,.workflowBlock small{color:#64707d;font-size:.68rem;line-height:1.5}.workflowPanel>label{display:grid;gap:6px;font-size:.72rem;font-weight:800}.workflowPanel textarea,.workflowBlock select{width:100%;min-height:44px;padding:10px;border:1px solid #cfd4da;border-radius:9px;background:#fff;font:inherit}.workflowBlock{display:grid;grid-template-columns:minmax(0,1fr) minmax(190px,280px) auto;gap:12px;align-items:end;padding:14px;border:1px solid #dfe3e7;border-radius:12px;background:#f8f8f6}.workflowBlock>div:first-child{align-self:start}.workflowBlock label{display:grid;gap:6px;font-size:.7rem;font-weight:800}.workflowBlock .button{min-height:44px}.outcomeActions,.communicationActions{display:flex;flex-wrap:wrap;gap:7px;grid-column:2/-1}.outcomeActions button,.communicationActions button{min-height:44px;padding:0 12px;border:1px solid #c7cdd4;border-radius:9px;background:#fff;font-weight:800;cursor:pointer}.outcomeActions button.selected{background:#111318;color:#fff;border-color:#111318}.outcomeActions button:disabled,.communicationActions button:disabled{opacity:.48;cursor:not-allowed}.communicationActions+small{grid-column:2/-1}.offerWorkflow{background:#fffaf0;border-color:#e5d7b8}.workflowDetail{width:min(980px,calc(100vw - 24px))}@media(max-width:820px){.workflowBlock{grid-template-columns:1fr}.outcomeActions,.communicationActions,.communicationActions+small{grid-column:auto}.workflowPanelHead{display:grid}}@media(max-width:480px){.workflowDetail{width:calc(100vw - 16px)}.outcomeActions,.communicationActions{display:grid}.outcomeActions button,.communicationActions button{width:100%}}`}</style>
 </>;
}
