'use client';

import {FormEvent,useEffect,useMemo,useState} from 'react';
import styles from './ArchitectProjectParticipationPanel.module.css';

type Mode='solo'|'team'|'flexible';
type Participation={participation_mode:Mode;min_team_size:number;target_team_size:number;max_team_size:number;team_size_threshold:number};
type Props={projectId:string};
const defaults:Participation={participation_mode:'team',min_team_size:2,target_team_size:5,max_team_size:5,team_size_threshold:2};

export default function ArchitectProjectParticipationPanel({projectId}:Props){
  const[value,setValue]=useState<Participation>(defaults);const[editable,setEditable]=useState(false);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[error,setError]=useState('');
  useEffect(()=>{let active=true;(async()=>{try{const response=await fetch(`/api/architect-projects/${projectId}/participation`,{cache:'no-store'});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Unable to load participation.');if(active){setValue(body.item);setEditable(Boolean(body.editable))}}catch(cause){if(active)setError(cause instanceof Error?cause.message:'Unable to load participation.')}finally{if(active)setLoading(false)}})();return()=>{active=false}},[projectId]);
  const capacityHelp=useMemo(()=>value.participation_mode==='solo'?'Solo becomes participation-ready with one member. Target and maximum may be higher only to support optional later collaborators on the same run where project policy permits.':value.participation_mode==='flexible'?'Flexible members choosing Solo or Either can satisfy participation readiness independently. Members choosing Team use the configured minimum below. Target is desirable capacity and maximum is the hard limit.':'Team projects become participation-ready at the minimum. The target is the preferred planning size, and the maximum is the hard capacity limit.',[value.participation_mode]);

  function setMode(mode:Mode){
    if(mode==='solo'){setValue(current=>({participation_mode:'solo',min_team_size:1,target_team_size:Math.max(1,current.target_team_size),max_team_size:Math.max(current.max_team_size,current.target_team_size,1),team_size_threshold:1}));return}
    if(mode==='flexible'){setValue(current=>{const min=Math.max(2,current.min_team_size);const target=Math.max(min,current.target_team_size);return{...current,participation_mode:'flexible',min_team_size:min,target_team_size:target,max_team_size:Math.max(current.max_team_size,target),team_size_threshold:min}});return}
    setValue(current=>{const min=Math.max(2,current.min_team_size);const target=Math.max(min,current.target_team_size);return{...current,participation_mode:'team',min_team_size:min,target_team_size:target,max_team_size:Math.max(target,current.max_team_size),team_size_threshold:min}})
  }
  function setCapacity(key:'min_team_size'|'target_team_size'|'max_team_size',raw:string){const next=Math.max(1,Math.min(50,Number(raw)||1));setValue(current=>{if(key==='min_team_size'){const min=current.participation_mode==='solo'?1:Math.max(current.participation_mode==='team'?2:1,next);return{...current,min_team_size:min,target_team_size:Math.max(current.target_team_size,min),max_team_size:Math.max(current.max_team_size,current.target_team_size,min),team_size_threshold:min}}if(key==='target_team_size'){const target=Math.max(current.min_team_size,next);return{...current,target_team_size:target,max_team_size:Math.max(current.max_team_size,target)}}return{...current,max_team_size:Math.max(current.target_team_size,next)}})}
  async function save(event:FormEvent){event.preventDefault();setBusy(true);setError('');setMessage('');try{const response=await fetch(`/api/architect-projects/${projectId}/participation`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(value)});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Unable to update participation.');setValue(body.item);setMessage('Participation model saved to the canonical project definition.')}catch(cause){setError(cause instanceof Error?cause.message:'Unable to update participation.')}finally{setBusy(false)}}

  return <section className={styles.panel} aria-labelledby="project-participation-heading"><div className={styles.heading}><div><span>PROJECT PARTICIPATION</span><h2 id="project-participation-heading">Define how this project can form.</h2></div><strong>{value.participation_mode.toUpperCase()}</strong></div><p className={styles.intro}>Choose the canonical participation model and capacity. Minimum controls participation readiness. Target is desirable planning capacity and never blocks start after the applicable minimum is reached. Maximum is the hard capacity limit.</p>{loading?<p className={styles.status}>Loading participation…</p>:<form onSubmit={save}><fieldset disabled={!editable||busy} className={styles.fieldset}><legend>Participation mode</legend><div className={styles.modes}>{(['solo','team','flexible'] as Mode[]).map(mode=><label key={mode} className={styles.mode}><input type="radio" name="participation-mode" value={mode} checked={value.participation_mode===mode} onChange={()=>setMode(mode)}/><span><strong>{mode[0].toUpperCase()+mode.slice(1)}</strong><small>{mode==='solo'?'Starts independently with one; optional later collaborators may share the same run.':mode==='team'?'Starts when the minimum viable team is ready.':'Solo/Either can start independently; Team preference uses the configured minimum.'}</small></span></label>)}</div></fieldset><div className={styles.capacity}><label>{value.participation_mode==='flexible'?'Team minimum':'Minimum to start'}<input aria-describedby="participation-capacity-help" type="number" min="1" max="50" value={value.participation_mode==='solo'?1:value.min_team_size} disabled={!editable||busy||value.participation_mode==='solo'} onChange={event=>setCapacity('min_team_size',event.target.value)}/></label><label>{value.participation_mode==='solo'?'Target capacity':'Target size'}<input aria-describedby="participation-capacity-help" type="number" min="1" max="50" value={value.target_team_size} disabled={!editable||busy} onChange={event=>setCapacity('target_team_size',event.target.value)}/></label><label>Maximum capacity<input aria-describedby="participation-capacity-help" type="number" min="1" max="50" value={value.max_team_size} disabled={!editable||busy} onChange={event=>setCapacity('max_team_size',event.target.value)}/></label></div><p id="participation-capacity-help" className={styles.help}>{capacityHelp}</p>{!editable&&<p className={styles.status}>Participation is read-only once the proposal leaves Draft or Changes Requested.</p>}{error&&<p className={`${styles.status} ${styles.error}`} role="alert">{error}</p>}{message&&<p className={styles.status} role="status" aria-live="polite">{message}</p>}{editable&&<button className={styles.save} type="submit" disabled={busy}>{busy?'Saving…':'Save participation'}</button>}</form>}</section>;
}