'use client';

import {useEffect,useState} from 'react';

type Item={username:string;full_name:string|null;created_at:string};
export default function BlockedMembersManager(){
 const[items,setItems]=useState<Item[]>([]);const[status,setStatus]=useState('Loading blocked members…');const[working,setWorking]=useState('');
 async function load(){try{const response=await fetch('/api/member-blocks',{cache:'no-store'});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Unable to load blocked members.');setItems(body.items||[]);setStatus((body.items||[]).length?'':'You have not blocked any members.')}catch(error){setStatus(error instanceof Error?error.message:'Unable to load blocked members.')}}
 useEffect(()=>{void load()},[]);
 async function unblock(username:string){setWorking(username);setStatus('');try{const response=await fetch('/api/member-blocks',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({username})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Unable to unblock this member.');setItems(current=>current.filter(item=>item.username!==username));setStatus(`@${username} is no longer blocked. Future discovery still depends on each member’s visibility and invitation preferences.`)}catch(error){setStatus(error instanceof Error?error.message:'Unable to unblock this member.')}finally{setWorking('')}}
 return <div className="bmRoot"><section className="bmIntro"><span className="cardNumber">PRIVACY & SAFETY</span><h1>Blocked members</h1><p>Blocked members cannot discover you through Phase 18 member search or exchange project invitations with you. Mettelo does not tell another member that you blocked them.</p><a href="/member/account">Back to account & privacy →</a></section><div className="bmStatus" role="status" aria-live="polite">{status}</div><section className="bmList" aria-label="Blocked members">{items.map(item=><article className="bmCard" key={item.username}><div><strong>{item.full_name||`@${item.username}`}</strong><p>@{item.username} · blocked {new Date(item.created_at).toLocaleDateString('en-GB')}</p></div><button className="button ghost" type="button" disabled={Boolean(working)} onClick={()=>void unblock(item.username)}>{working===item.username?'Unblocking…':'Unblock'}</button></article>)}</section><style jsx>{`.bmRoot{display:grid;gap:18px;min-width:0}.bmIntro,.bmCard{border:1px solid var(--line);border-radius:18px;background:var(--white);padding:20px;min-width:0}.bmIntro h1{margin:8px 0;font-size:clamp(1.9rem,5vw,3.3rem);line-height:1}.bmIntro p,.bmCard p,.bmStatus{color:var(--slate);line-height:1.55}.bmStatus{min-height:24px}.bmList{display:grid;gap:12px}.bmCard{display:flex;justify-content:space-between;align-items:center;gap:14px}.bmCard p{margin:4px 0 0}.bmCard .button{min-height:44px;flex:0 0 auto}@media(max-width:560px){.bmIntro,.bmCard{padding:15px}.bmCard{align-items:stretch;flex-direction:column}.bmCard .button{width:100%}}`}</style></div>;
}
