import { createPublicSupabaseClient } from '@/lib/supabase/public';

type TaxonomyRef={slug:string;name:string};
type Project={id:string;title:string;summary:string;status:string;difficulty_level:string|null;project_domains?:{is_primary:boolean;domains:TaxonomyRef|null}[];project_tools?:{tools:TaxonomyRef|null}[]};
type Event={id:string;title:string;summary:string|null;starts_at:string;location_label:string|null;registration_url:string|null;event_type:string};
type Opportunity={id:string;title:string;organisation:string|null;summary:string|null;location:string|null;opportunity_type:string;source_url:string|null;closes_at:string|null};
type Proof={id:string;title:string;contribution_type:string;verified_at:string|null;projects:{title:string}|null};

function fmtDate(value:string){return new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric'}).format(new Date(value));}
function safeText(value:string|null|undefined,max=220){
  if(!value)return '';
  const normal=value.replace(/\s+/g,' ').trim().replace(/\S{56,}/g,token=>`${token.slice(0,52)}…`);
  return normal.length>max?`${normal.slice(0,max-1).trimEnd()}…`:normal;
}

export default async function HomeLiveContent(){
  const db=createPublicSupabaseClient();let project:Project|null=null;let event:Event|null=null;let opportunity:Opportunity|null=null;let proof:Proof|null=null;
  if(db){
    const now=new Date().toISOString();
    const [projects,events,opportunities,proofs]=await Promise.all([
      db.from('projects').select('id,title,summary,status,difficulty_level,project_domains(is_primary,domains(slug,name)),project_tools(tools(slug,name))').eq('visibility','public').in('status',['pilot','recruiting','active','review','completed']).order('created_at',{ascending:false}).limit(1),
      db.from('events').select('id,title,summary,starts_at,location_label,registration_url,event_type').eq('status','published').gte('starts_at',now).order('starts_at',{ascending:true}).limit(1),
      db.from('opportunities').select('id,title,organisation,summary,location,opportunity_type,source_url,closes_at').eq('status','published').eq('access_level','public').or(`closes_at.is.null,closes_at.gte.${now}`).order('published_at',{ascending:false}).limit(1),
      db.from('contributions').select('id,title,contribution_type,verified_at,projects(title)').eq('verification_status','verified').eq('is_public',true).order('verified_at',{ascending:false}).limit(1)
    ]);
    project=(projects.data?.[0]||null) as unknown as Project|null;event=(events.data?.[0]||null) as Event|null;opportunity=(opportunities.data?.[0]||null) as Opportunity|null;proof=(proofs.data?.[0]||null) as unknown as Proof|null;
  }
  const primary=project?.project_domains?.find(item=>item.is_primary)?.domains||project?.project_domains?.[0]?.domains;const projectTools=(project?.project_tools||[]).map(item=>item.tools).filter(Boolean) as TaxonomyRef[];
  return <section className="section homeLiveSection" aria-labelledby="home-live-title"><div className="shell"><div className="homeLiveHead"><div><div className="eyebrow">Explore what is live</div><h2 id="home-live-title">Projects, events, opportunities and Proof — in one place.</h2></div><div className="homeLiveIntro"><p>These cards come from the live Mettelo database. Published activity appears here automatically; if nothing is live, we show a clear empty state instead of inventing content.</p><a className="linkArrow" href="/search">Search all Mettelo →</a></div></div><div className="homeExploreGrid">
    <article className="homeExploreCard liveDiscoveryCard liveProjectCard"><span className="cardNumber">LATEST PROJECT</span>{project?<><div className="liveCardMeta">{primary&&<span className="domainTag">{safeText(primary.name,40)}</span>}<span className="chip">{safeText(project.status,24).toUpperCase()}</span></div><h3 className="liveCardTitle">{safeText(project.title,96)}</h3><p className="liveCardSummary">{safeText(project.summary,210)}</p>{projectTools.length>0&&<div className="projectTagRow" aria-label="Project tools">{projectTools.slice(0,3).map(item=><span key={item.slug}>{safeText(item.name,28)}</span>)}</div>}<a className="linkArrow" href="/projects">Explore projects →</a></>:<><div className="liveEmptyState"><span aria-hidden="true">PROJECTS</span><h3>No public project yet</h3><p>New Labs briefs will appear here after they pass the Mettelo publishing process.</p></div><a className="linkArrow" href="/projects">Explore projects →</a></>}</article>
    <article className="homeExploreCard liveDiscoveryCard liveEventCard"><span className="cardNumber">NEXT EVENT</span>{event?<><div className="liveCardMeta"><span className="chip">{safeText(event.event_type.replace('_',' '),32).toUpperCase()}</span><span>{fmtDate(event.starts_at)}</span></div><h3 className="liveCardTitle">{safeText(event.title,96)}</h3><p className="liveCardSummary">{safeText(event.summary||event.location_label||'Confirmed Mettelo event.',190)}</p><a className="linkArrow" href="/events">View event →</a></>:<><div className="liveEmptyState"><span aria-hidden="true">EVENTS</span><h3>No event published right now</h3><p>Confirmed workshops, AMAs, showcases and community sessions will appear here.</p></div><a className="linkArrow" href="/events">View events →</a></>}</article>
    <article className="homeExploreCard liveDiscoveryCard liveOpportunityCard"><span className="cardNumber">CURRENT OPPORTUNITY</span>{opportunity?<><div className="liveCardMeta"><span className="chip">{safeText(opportunity.opportunity_type,28).toUpperCase()}</span>{opportunity.location&&<span>{safeText(opportunity.location,42)}</span>}</div><h3 className="liveCardTitle">{safeText(opportunity.title,96)}</h3><p className="liveCardSummary">{safeText(`${opportunity.organisation?`${opportunity.organisation} · `:''}${opportunity.summary||'Published Mettelo opportunity.'}`,210)}</p>{opportunity.closes_at&&<small>Closes {fmtDate(opportunity.closes_at)}</small>}<a className="linkArrow" href="/opportunities">View opportunities →</a></>:<><div className="liveEmptyState"><span aria-hidden="true">OPPORTUNITIES</span><h3>No public opportunity right now</h3><p>Verified jobs, referrals, volunteering and fellowships will appear here when published.</p></div><a className="linkArrow" href="/opportunities">View opportunities →</a></>}</article>
    <article className="homeExploreCard liveDiscoveryCard liveProofCard"><span className="cardNumber">VERIFIED PROOF</span>{proof?<><div className="liveCardMeta"><span className="chip green">VERIFIED</span>{proof.verified_at&&<span>{fmtDate(proof.verified_at)}</span>}</div><h3 className="liveCardTitle">{safeText(proof.title,96)}</h3><p className="liveCardSummary">{safeText(`${proof.projects?.title||'Mettelo contribution'} · ${proof.contribution_type.replace('_',' ')}`,170)}</p><a className="linkArrow" href="/showcase">Explore Proof →</a></>:<><div className="liveEmptyState"><span aria-hidden="true">PROOF</span><h3>Verified Proof is building</h3><p>Public, reviewed contribution will appear here when the first verified records are published.</p></div><a className="linkArrow" href="/showcase">Explore Proof →</a></>}</article>
  </div></div></section>;
}
