'use client';

import {useMemo,useState} from 'react';
import ProfileEditor,{MemberProfile} from '@/components/ProfileEditor';
import {calculateMemberReadiness} from '@/lib/member-readiness';

type TaxonomyItem={slug:string;name:string};
type ProfileWithReadiness=MemberProfile&{profile_readiness?:number|null};

export default function MemberProfileSection({userId,profile,domains,tools,domainPreferences,toolPreferences}:{userId:string;profile:ProfileWithReadiness;domains:TaxonomyItem[];tools:TaxonomyItem[];domainPreferences:string[];toolPreferences:string[]}){
  const [savedProfile,setSavedProfile]=useState<ProfileWithReadiness>(profile);const [savedDomains,setSavedDomains]=useState(domainPreferences);const [savedTools,setSavedTools]=useState(toolPreferences);
  const isComplete=Boolean(savedProfile.full_name?.trim()&&(savedProfile.headline?.trim()||savedProfile.professional_area?.trim()||savedProfile.current_job_title?.trim()));
  const [editing,setEditing]=useState(!isComplete);
  const domainNames=savedDomains.map(slug=>domains.find(item=>item.slug===slug)?.name||slug);const toolNames=savedTools.map(slug=>tools.find(item=>item.slug===slug)?.name||slug);
  const availabilityLabels:{[key:string]:string}={available_now:'Available now',available_soon:'Available soon',limited:'Limited availability',not_available:'Not currently available'};
  const experienceLabels:{[key:string]:string}={entry:'Entry / early career',mid:'Mid-level',senior:'Senior',lead:'Lead / manager',executive:'Executive / head of function'};
  const readiness=useMemo(()=>calculateMemberReadiness({profile:savedProfile,domainCount:savedDomains.length,toolCount:savedTools.length}),[savedProfile,savedDomains,savedTools]);
  const recommendations=readiness.applicationReadiness.missing.slice(0,3);
  const statusLabel=readiness.applicationReadiness.ready?'APPLICATION READY':readiness.matchingReadiness.ready?'MATCHING READY':'BUILD PROFILE';

  if(editing)return <div><div className="panelHead" style={{marginBottom:14}}><div><span className="cardNumber">EDIT PROFILE</span><h3 style={{margin:'7px 0 0'}}>Keep your Mettelo identity useful for matching and collaboration.</h3></div>{isComplete&&<button className="button ghost" type="button" onClick={()=>setEditing(false)}>Cancel edit</button>}</div><ProfileEditor profile={savedProfile} domains={domains} tools={tools} domainPreferences={savedDomains} toolPreferences={savedTools} onSaved={(next,nextDomains,nextTools)=>{setSavedProfile(next as ProfileWithReadiness);setSavedDomains(nextDomains);setSavedTools(nextTools);setEditing(false);}}/></div>;

  return <>
    <section className="panel profileHealth" aria-labelledby="profile-health-heading">
      <div className="panelHead"><div><span className="cardNumber">PROFILE COMPLETION</span><h3 id="profile-health-heading" style={{margin:'7px 0 0'}}>Profile completion {readiness.profileCompletion.percentage}%</h3></div><span className={`chip ${readiness.applicationReadiness.ready?'green':''}`}>{statusLabel}</span></div>
      <div className="profileCompletionTrack" role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={readiness.profileCompletion.percentage} aria-label={`Profile completion ${readiness.profileCompletion.percentage}%`}><span style={{width:`${readiness.profileCompletion.percentage}%`}}/></div>
      <p className="profileThresholdCopy">Profile completion, matching, applications and public visibility are separate states. Complete information helps Mettelo understand you; each capability unlocks only when its own requirements are met.</p>
      <div className="readinessMilestones" aria-label="Readiness states"><div className={readiness.matchingReadiness.ready?'complete':''}><strong>{readiness.matchingReadiness.ready?'Ready':'Not ready'}</strong><span>Matching</span></div><div className={readiness.applicationReadiness.ready?'complete':''}><strong>{readiness.applicationReadiness.ready?'Ready':'Not ready'}</strong><span>Applications</span></div><div className={readiness.publicProfileReadiness.ready?'complete':''}><strong>{readiness.publicProfileReadiness.ready?'Ready':'Not ready'}</strong><span>Public profile</span></div></div>
      {recommendations.length?<div className="profileRecommendations" aria-label="Application requirements remaining">{recommendations.map(item=><div key={item.key}><span aria-hidden="true">→</span><p><strong>{item.label}</strong><br/>{item.action}</p></div>)}</div>:<p className="profileReadyCopy">You have the core profile information required to apply for Mettelo projects. Verified Proof remains separate and grows through completed work.</p>}
      <div className="actions" style={{marginTop:16}}><a className="button ghost" href="/member/discover">Discover projects →</a>{savedProfile.is_public&&readiness.publicProfileReadiness.ready&&<a className="button ghost" href={`/people/${userId}`}>Preview public profile →</a>}</div>
    </section>
    <section className="panel memberProfileSummary" aria-labelledby="member-profile-heading" style={{marginTop:18}}>
      <div className="panelHead"><div><span className="cardNumber">PROFESSIONAL IDENTITY</span><h3 id="member-profile-heading" style={{margin:'7px 0 0'}}>Your Mettelo profile</h3></div><button className="button dark" type="button" onClick={()=>setEditing(true)}>Edit profile →</button></div>
      <div className="memberProfileOverview"><div className="memberProfileAvatar" style={savedProfile.avatar_url?{backgroundImage:`url(${savedProfile.avatar_url})`}:undefined}>{savedProfile.avatar_url?'':(savedProfile.full_name?.[0]||'M').toUpperCase()}</div><div className="memberProfileIdentity"><h2>{savedProfile.full_name||'Mettelo member'}</h2><p>{savedProfile.headline||savedProfile.current_job_title||savedProfile.professional_area||'Add a professional headline'}</p>{savedProfile.current_job_title&&<small>{savedProfile.current_job_title}{savedProfile.organisation?` · ${savedProfile.organisation}`:''}</small>}<div className="metaRow">{savedProfile.location&&<span className="metaPill">{savedProfile.location}</span>}{savedProfile.experience_level&&<span className="metaPill">{experienceLabels[savedProfile.experience_level]||savedProfile.experience_level}</span>}<span className={`chip ${savedProfile.is_public&&readiness.publicProfileReadiness.ready?'green':''}`}>{savedProfile.is_public?(readiness.publicProfileReadiness.ready?'PUBLIC PROFILE':'PUBLIC PROFILE · REQUIREMENTS REMAIN'):'PRIVATE PROFILE'}</span></div></div></div>
      {savedProfile.bio&&<p className="memberProfileBio">{savedProfile.bio}</p>}
      <div className="memberProfileDetails">
        <div><span className="cardNumber">PROJECT AVAILABILITY</span><p>{savedProfile.project_availability?availabilityLabels[savedProfile.project_availability]||savedProfile.project_availability:'Not specified'}{savedProfile.weekly_capacity?` · ${savedProfile.weekly_capacity}`:''}</p></div>
        <div><span className="cardNumber">PREFERRED ROLES</span><div className="metaRow">{savedProfile.preferred_roles?.length?savedProfile.preferred_roles.map(role=><span className="metaPill" key={role}>{role}</span>):<small>Add the project roles you want to be considered for.</small>}</div></div>
        <div><span className="cardNumber">SKILLS</span><div className="metaRow">{savedProfile.skills?.length?savedProfile.skills.slice(0,12).map(skill=><span className="metaPill" key={skill}>{skill}</span>):<small>Add the skills you want Mettelo to recognise.</small>}</div></div>
        <div><span className="cardNumber">PROJECT INTERESTS</span><div className="metaRow">{domainNames.length?domainNames.map(name=><span className="metaPill" key={name}>{name}</span>):<small>Add domains to improve project matching.</small>}</div></div>
        <div><span className="cardNumber">TOOLS</span><div className="metaRow">{toolNames.length?toolNames.slice(0,12).map(name=><span className="metaPill" key={name}>{name}</span>):<small>Add tools you use or want to develop.</small>}</div></div>
        <div><span className="cardNumber">WORKING TOWARD</span><p>{savedProfile.primary_goal||'Add the capability, project or opportunity you want to move toward.'}</p></div>
      </div>
      <div className="profilePreviewLinks">{savedProfile.linkedin_url&&<a href={savedProfile.linkedin_url} target="_blank" rel="noopener noreferrer">LinkedIn ↗</a>}{savedProfile.github_url&&<a href={savedProfile.github_url} target="_blank" rel="noopener noreferrer">GitHub ↗</a>}{savedProfile.portfolio_url&&<a href={savedProfile.portfolio_url} target="_blank" rel="noopener noreferrer">Portfolio ↗</a>}</div>
      <style jsx>{`.profileHealth{padding:22px}.profileCompletionTrack{height:10px;overflow:hidden;border-radius:999px;background:#e7e8eb;margin-top:18px}.profileCompletionTrack span{display:block;height:100%;border-radius:inherit;background:#c6892a}.profileThresholdCopy{margin:12px 0 0;color:#596371;line-height:1.55}.readinessMilestones{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-top:14px}.readinessMilestones>div{display:grid;gap:2px;padding:10px 12px;border:1px solid #e4dfd5;border-radius:10px;background:#fafafa}.readinessMilestones>div.complete{background:#f2f8f4;border-color:#cfe3d6}.readinessMilestones strong{font-size:.86rem}.readinessMilestones span{color:#68717e;font-size:.78rem}.profileRecommendations{display:grid;gap:9px;margin-top:16px}.profileRecommendations>div{display:grid;grid-template-columns:auto 1fr;gap:10px;align-items:start;padding:10px 12px;border-radius:10px;background:#faf7f0}.profileRecommendations>div>span{font-weight:800;color:#8b5a17}.profileRecommendations p,.profileReadyCopy{margin:0;color:#596371;line-height:1.55}.profileRecommendations p strong{color:#303845}.profileReadyCopy{margin-top:16px}.memberProfileOverview{display:flex;align-items:center;gap:18px;margin-top:22px}.memberProfileAvatar{width:76px;height:76px;flex:none;display:grid;place-items:center;border-radius:22px;background:#f1e7d1 center/cover no-repeat;font:700 1.6rem var(--font-space);color:#8b5a17}.memberProfileIdentity h2{margin:0 0 5px;font-size:1.55rem}.memberProfileIdentity p{margin:0;color:#333b46}.memberProfileIdentity small{display:block;margin-top:4px;color:#66707e}.memberProfileBio{max-width:800px;margin:20px 0 0;color:#596371;line-height:1.7}.memberProfileDetails{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-top:24px;padding-top:22px;border-top:1px solid rgba(16,19,29,.08)}.memberProfileDetails>div{min-width:0;padding:15px;border-radius:12px;background:#fafafa}.memberProfileDetails p{margin:8px 0 0;color:#596371}.memberProfileDetails small{display:block;margin-top:9px;color:#7a8390}.profilePreviewLinks{display:flex;gap:12px;flex-wrap:wrap;margin-top:22px}.profilePreviewLinks a{font-weight:750}@media(max-width:700px){.readinessMilestones,.memberProfileDetails{grid-template-columns:1fr}.memberProfileOverview{align-items:flex-start}.memberProfileAvatar{width:62px;height:62px;border-radius:18px}.profileHealth .actions{display:grid}.profileHealth .button{width:100%}}`}</style>
    </section>
  </>;
}
