'use client';

import Image from 'next/image';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {Suspense,useEffect,useRef,useState} from 'react';
import {createClient} from '@/lib/supabase/client';
import NotificationMenu from './NotificationMenu';
import WorkspaceRouteTabs from './WorkspaceRouteTabs';
import styles from './MemberAppShell.module.css';

type Account={name:string;email:string;avatarUrl:string|null;isAdmin:boolean;accountType:'member'|'project_architect'}|null;
const groups=[
  {label:'',items:[['Dashboard','/member'],['Recommended','/member/recommended']]},
  {label:'My work',items:[['Applications','/member/applications'],['Saved Opportunities','/member/saved-opportunities'],['My Projects','/member/projects'],['Proof','/member/proof'],['Project Architect','/member/project-architect']]},
  {label:'Discover',items:[['Projects','/projects'],['Opportunities','/opportunities'],['Events','/events'],['People','/people'],['Community','/community']]},
  {label:'Account',items:[['Profile','/member/profile']]}
] as const;
function HomeIcon(){return <svg viewBox="0 0 24 24" width="19" height="19" aria-hidden="true"><path d="M3.5 10.5 12 3l8.5 7.5v9a1.5 1.5 0 0 1-1.5 1.5h-4.5v-6h-5v6H5a1.5 1.5 0 0 1-1.5-1.5v-9Z" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinejoin="round"/></svg>}
function SearchIcon(){return <svg viewBox="0 0 24 24" width="19" height="19" aria-hidden="true"><circle cx="11" cy="11" r="6.5" fill="none" stroke="currentColor" strokeWidth="1.8"/><path d="m16 16 4 4" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"/></svg>}

export default function MemberAppShell({children}:{children:React.ReactNode}){
  const pathname=usePathname();const [account,setAccount]=useState<Account>(null);const [accountOpen,setAccountOpen]=useState(false);const [moreOpen,setMoreOpen]=useState(false);const accountRef=useRef<HTMLDetailsElement>(null);const moreRef=useRef<HTMLDetailsElement>(null);
  useEffect(()=>{document.body.classList.add('memberAppActive');const publicTopbar=document.querySelector<HTMLElement>('body > .topbar');const publicHeader=document.querySelector<HTMLElement>('body > .siteHeader');const publicFooter=document.querySelector<HTMLElement>('body > footer');const previous=[publicTopbar?.style.display,publicHeader?.style.display,publicFooter?.style.display];if(publicTopbar)publicTopbar.style.display='none';if(publicHeader)publicHeader.style.display='none';if(publicFooter)publicFooter.style.display='none';const supabase=createClient();let active=true;async function load(){const {data:{user}}=await supabase.auth.getUser();if(!active||!user)return;const email=user.email||'';let name=(typeof user.user_metadata?.full_name==='string'&&user.user_metadata.full_name.trim())||email.split('@')[0]||'Member';let avatarUrl:string|null=null;const [{data:profile},{data:identity}]=await Promise.all([supabase.from('profiles').select('full_name,avatar_url').eq('id',user.id).maybeSingle(),supabase.from('account_identities').select('account_type').eq('user_id',user.id).maybeSingle()]);if(profile?.full_name?.trim())name=profile.full_name.trim();if(profile?.avatar_url)avatarUrl=profile.avatar_url;if(active)setAccount({name,email,avatarUrl,isAdmin:user.app_metadata?.role==='admin',accountType:identity?.account_type==='project_architect'?'project_architect':'member'})}void load();const profileListener=(event:Event)=>{const detail=(event as CustomEvent<{name?:string;avatarUrl?:string|null}>).detail;setAccount(current=>current?{...current,name:detail?.name||current.name,avatarUrl:detail?.avatarUrl===undefined?current.avatarUrl:detail.avatarUrl}:current)};window.addEventListener('mettelo:profile-updated',profileListener);return()=>{active=false;window.removeEventListener('mettelo:profile-updated',profileListener);document.body.classList.remove('memberAppActive');if(publicTopbar)publicTopbar.style.display=previous[0]||'';if(publicHeader)publicHeader.style.display=previous[1]||'';if(publicFooter)publicFooter.style.display=previous[2]||''}},[]);
  const closeMenus=()=>{setAccountOpen(false);setMoreOpen(false)};
  async function signOut(){closeMenus();const supabase=createClient();await supabase.auth.signOut();window.location.assign('/')}
  const isActive=(href:string)=>href==='/member'?pathname==='/member':pathname===href||pathname.startsWith(`${href}/`);
  useEffect(()=>{setAccountOpen(false);setMoreOpen(false)},[pathname]);
  useEffect(()=>{function closeOutside(event:PointerEvent){const target=event.target as Node;if(!accountRef.current?.contains(target)&&!moreRef.current?.contains(target)){setAccountOpen(false);setMoreOpen(false)}}function escape(event:KeyboardEvent){if(event.key==='Escape'){setAccountOpen(false);setMoreOpen(false)}}document.addEventListener('pointerdown',closeOutside);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('pointerdown',closeOutside);document.removeEventListener('keydown',escape)}},[]);
  const nav=<>{groups.map(group=><div className={styles.navGroup} key={group.label||'primary'}>{group.label&&<span className={styles.navLabel}>{group.label}</span>}{group.items.map(([label,href])=><Link className={isActive(href)?styles.activeLink:styles.navLink} href={href} key={href}><span>{label}</span><span aria-hidden="true">→</span></Link>)}</div>)}</>;
  return <div className={styles.appShell}>
    <header className={styles.appHeader}><div className={styles.headerInner}><Link className={styles.brand} href="/member" aria-label="Mettelo member dashboard" onClick={closeMenus}><Image src="/mettelo-logo-dark.svg" alt="Mettelo" width={1630} height={370} priority unoptimized style={{width:126,height:'auto'}}/></Link><Link className={styles.homeButton} href="/" aria-label="Mettelo home" title="Home" onClick={closeMenus}><HomeIcon/></Link><Link className={styles.searchButton} href="/search" aria-label="Search Mettelo" title="Search" onClick={closeMenus}><SearchIcon/></Link><div className={styles.headerActions}>{account?.isAdmin&&<Link className={styles.modeSwitch} href="/admin/project-operations" onClick={closeMenus}>Admin</Link>}<NotificationMenu/><details ref={accountRef} open={accountOpen} className={styles.accountMenu} onToggle={event=>{const open=event.currentTarget.open;setAccountOpen(open);if(open)setMoreOpen(false)}}><summary aria-label="Open account menu"><span className={styles.avatar} style={account?.avatarUrl?{backgroundImage:`url(${account.avatarUrl})`}:undefined}>{account?.avatarUrl?'':(account?.name?.[0]||'M').toUpperCase()}</span><span className={styles.accountCopy}><strong>{account?.name?.split(' ')[0]||'Member'}</strong><small>{account?.isAdmin?'Admin access':account?.accountType==='project_architect'?'Project Architect':'Member'}</small></span><span aria-hidden="true">⌄</span></summary><div className={styles.accountPanel} onClickCapture={event=>{if((event.target as Element).closest('a,button'))closeMenus()}}>{account&&<div className={styles.accountIdentity}><strong>{account.name}</strong><small>{account.email} · {account.accountType==='project_architect'?'Project Architect':'Member'}</small></div>}<Link href="/member">Dashboard <span>→</span></Link><Link href="/member/profile">Profile <span>→</span></Link>{account?.isAdmin&&<Link href="/admin/project-operations">Admin console <span>→</span></Link>}<button type="button" onClick={signOut}>Sign out <span>→</span></button></div></details></div></div></header>
    <div className={styles.appBody}><aside className={styles.sidebar} aria-label="Mettelo member navigation"><div className={styles.sidebarIntro}><span>Workspace</span><strong>My Mettelo</strong></div>{account?.isAdmin&&<Link className={styles.modeCard} href="/admin/project-operations"><small>ADMIN</small><strong>Open admin console</strong><span>Manage projects and access →</span></Link>}<nav>{nav}</nav><div className={styles.sidebarHelp}><Link href="/feedback">Give feedback →</Link><Link href="/contact">Help & support →</Link></div></aside><main className={styles.content}><Suspense fallback={null}><WorkspaceRouteTabs/></Suspense>{children}</main></div>
    <nav className={styles.bottomNav} aria-label="Member mobile navigation"><Link className={isActive('/member')?styles.bottomActive:''} href="/member" onClick={closeMenus}><span>⌂</span><small>Home</small></Link><Link className={isActive('/member/projects')?styles.bottomActive:''} href="/member/projects" onClick={closeMenus}><span>▦</span><small>Projects</small></Link><Link className={isActive('/member/applications')?styles.bottomActive:''} href="/member/applications" onClick={closeMenus}><span>✓</span><small>Applications</small></Link><details ref={moreRef} open={moreOpen} className={styles.moreMenu} onToggle={event=>{const open=event.currentTarget.open;setMoreOpen(open);if(open)setAccountOpen(false)}}><summary><span>•••</span><small>More</small></summary><div className={styles.morePanel} onClickCapture={event=>{if((event.target as Element).closest('a,button'))closeMenus()}}><div className={styles.moreIdentity}>{account&&<><strong>{account.name}</strong><small>{account.email}</small></>}</div><Link href="/member/saved-opportunities">Saved opportunities <span>→</span></Link><Link href="/member/proof">Proof <span>→</span></Link><Link href="/member/project-architect">Project Architect <span>→</span></Link><Link href="/member/recommended">Recommended <span>→</span></Link><Link href="/opportunities">Find opportunities <span>→</span></Link><Link href="/events">Events <span>→</span></Link><Link href="/people">People <span>→</span></Link><Link href="/member/profile">Profile <span>→</span></Link>{account?.isAdmin&&<Link href="/admin/project-operations">Admin console <span>→</span></Link>}<button type="button" onClick={signOut}>Sign out <span>→</span></button></div></details></nav>
    <style jsx global>{`.memberAppActive .memberSidebar{display:none!important}.memberAppActive .memberDashboard{display:block!important;width:100%!important}.memberAppActive .memberWorkspace{padding-top:0!important;background:#f6f7f9!important}.memberAppActive .memberDashboardMain{max-width:none!important}.memberAppActive #main-content{min-height:100vh;background:#f6f7f9;overflow-x:clip}.memberAppActive .shell,.memberAppActive .panel,.memberAppActive .card{min-width:0;max-width:100%}@media(max-width:900px){.memberAppActive .memberWorkspace>.shell{width:min(calc(100% - 24px),1240px)}.memberAppActive .sectionHead{display:grid;gap:10px}.memberAppActive .sectionHead h1,.memberAppActive .sectionHead h2{overflow-wrap:anywhere}.memberAppActive .dashboardGrid,.memberAppActive .metricGrid,.memberAppActive .grid3,.memberAppActive .grid4{grid-template-columns:1fr!important}.memberAppActive table{min-width:680px}.memberAppActive .tableWrap{overflow-x:auto;-webkit-overflow-scrolling:touch}}`}</style>
  </div>;
}
