import Link from 'next/link';
import type {MemberCapabilityPathOverview} from '@/lib/member-capability-paths';

type Props={overview:MemberCapabilityPathOverview;context:'home'|'profile'};

export default function MemberCapabilityPathSummary({overview,context}:Props){
  const primary=overview.primary;const home=context==='home';
  return <aside className={`mcpSummary ${home?'home':'profile'}`} aria-labelledby={`mcp-summary-${context}`}>
    <div className="mcpSummaryCopy"><span className="mcpSummaryEyebrow">{home?'YOUR DIRECTION':'PROFESSIONAL DIRECTION'}</span><h2 id={`mcp-summary-${context}`}>{primary?primary.name:'Choose a Capability Path when you want direction'}</h2><p>{primary?`${primary.targetRole} · ${primary.followStatus==='paused'?'Paused':'Primary direction'}${overview.followedCount>1?` · ${overview.followedCount} Paths followed`:''}`:home?'Paths give you a recommended sequence through real Mettelo projects without limiting what you can discover.':'Your profile describes who you are. Capability Paths describe professional directions you want your project work to build toward.'}</p></div>
    <div className="mcpSummaryActions">{primary&&primary.pathStatus==='published'&&<Link className="mcpSummaryPrimary" href={`/member/discover?path=${encodeURIComponent(primary.slug)}`}>Explore this Path</Link>}<Link href="/member/paths">{primary?'Manage Paths':'Explore Capability Paths'}</Link></div>
    <style jsx global>{`.mcpSummary{margin:0 0 16px;padding:15px 17px;border:1px solid #d8dde3;border-left:4px solid #c6892a;border-radius:13px;background:#fbf7ee;color:#111318;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:18px;align-items:center;min-width:0}.mcpSummaryCopy{min-width:0}.mcpSummaryEyebrow{display:block;font:800 9px var(--font-plex-mono),monospace;letter-spacing:.1em;color:#8b5a17}.mcpSummary h2{margin:4px 0 3px;font:760 18px/1.2 var(--font-space-grotesk),Inter,sans-serif;overflow-wrap:anywhere}.mcpSummary p{margin:0;color:#59636f;font-size:11.5px;line-height:1.5;overflow-wrap:anywhere}.mcpSummaryActions{display:flex;gap:7px;flex-wrap:wrap;justify-content:flex-end}.mcpSummaryActions a{min-height:40px;padding:0 11px;border:1px solid #b8c0c9;border-radius:8px;background:#fff;color:#111318;display:inline-flex;align-items:center;justify-content:center;text-decoration:none;font-size:11px;font-weight:800}.mcpSummaryActions a.mcpSummaryPrimary{background:#111318;border-color:#111318;color:#fff}.mcpSummaryActions a:focus-visible{outline:3px solid #e0ad59;outline-offset:2px}@media(max-width:720px){.mcpSummary{grid-template-columns:1fr;padding:14px}.mcpSummaryActions{display:grid;justify-content:stretch}.mcpSummaryActions a{width:100%}}`}</style>
  </aside>;
}
