'use client';

import {useEffect,useState} from 'react';

type Invite={id:string;project_title:string;project_id:string;project_run_id:string;collaboration_need_id:string;status:string;expires_at:string;created_at:string};

export default function MemberCollaborationInvitations(){
 const[items,setItems]=useState<Invite[]>([]);const[status,setStatus]=useState('Loading invitations…');const[working,setWorking]=useState('');
 async function load(){try{const response=await fetch('/api/member-collaboration-invitations?scope=received',{cache:'no-store'});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Unable to load invitations.');setItems(body.items||[]);setStatus((body.items||[]).length?'':'You have no project collaboration invitations.')}catch(error){setStatus(error instanceof Error?error.message:'Unable to load invitations.')}}
 useEffect(()=>{void load()},[]);
 async function act(id:string,action:'accept'|'decline'){setWorking(`${id}:${action}`);setStatus('');try{const response=await fetch('/api/member-collaboration-invitations',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,action})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Unable to update invitation.');if(action==='accept'&&body.interest_target){window.location.assign(String(body.interest_target));return}setStatus('Invitation declined.');await load()}catch(error){setStatus(error instanceof Error?error.message:'Unable to update invitation.')}finally{setWorking('')}}
 const pending=items.filter(item=>item.status==='pending');const history=items.filter(item=>item.status!=='pending');
 return <div className="mciRoot"><section className="mciIntro"><span className="cardNumber">COLLABORATION INVITATIONS</span><h1>Project invitations</h1><p>A Project Lead can invite you to review a collaboration need, but an invitation never places you into a project automatically. Accepting continues to the normal project-interest journey where Mettelo rechecks eligibility, capacity and the joining window.</p></section><div className="mciStatus" role="status" aria-live="polite">{status}</div><section aria-labelledby="pending-invites"><h2 id="pending-invites">Needs your response</h2><div className="mciGrid">{pending.map(item=><article className="mciCard" key={item.id}><span className="cardNumber">PENDING</span><h3>{item.project_title}</h3><p>Received {new Date(item.created_at).toLocaleDateString('en-GB')} · expires {new Date(item.expires_at).toLocaleDateString('en-GB')}</p><div className="mciActions"><button className="button dark" type="button" disabled={Boolean(working)} onClick={()=>void act(item.id,'accept')}>{working===`${item.id}:accept`?'Opening…':'Accept & review project'}</button><button className="button ghost" type="button" disabled={Boolean(working)} onClick={()=>void act(item.id,'decline')}>{working===`${item.id}:decline`?'Declining…':'Decline'}</button></div></article>)}{!pending.length&&<div className="mciEmpty"><p>No pending invitations.</p></div>}</div></section>{history.length>0&&<section aria-labelledby="invite-history"><h2 id="invite-history">Recent invitation history</h2><div className="mciGrid">{history.map(item=><article className="mciCard" key={item.id}><span className="cardNumber">{item.status.toUpperCase()}</span><h3>{item.project_title}</h3><p>{new Date(item.created_at).toLocaleDateString('en-GB')}</p></article>)}</div></section>}<style jsx>{`.mciRoot{display:grid;gap:20px;min-width:0}.mciIntro,.mciCard,.mciEmpty{min-width:0;border:1px solid var(--line);border-radius:18px;background:var(--white);padding:20px}.mciIntro h1{margin:8px 0;font-size:clamp(1.9rem,5vw,3.3rem);line-height:1}.mciIntro p,.mciCard p,.mciEmpty p{color:var(--slate);line-height:1.55}.mciStatus{min-height:24px;color:var(--slate);overflow-wrap:anywhere}.mciRoot section>h2{margin:0 0 12px}.mciGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.mciCard h3{margin:7px 0;font-size:1.2rem}.mciActions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.mciActions .button{min-height:44px}@media(max-width:640px){.mciGrid{grid-template-columns:1fr}.mciIntro,.mciCard,.mciEmpty{padding:15px}.mciActions{display:grid}.mciActions .button{width:100%}}`}</style></div>;
}
