'use client';

import {useMemo,useState} from 'react';

type TaxonomyItem={slug:string;name:string};
type Profile={full_name?:string|null;headline?:string|null;bio?:string|null;location?:string|null;professional_area?:string|null;primary_goal?:string|null;linkedin_url?:string|null;github_url?:string|null;portfolio_url?:string|null;avatar_url?:string|null;skills?:string[]|null;preferred_roles?:string[]|null;languages?:string[]|null;is_public?:boolean|null;current_job_title?:string|null;organisation?:string|null;experience_level?:string|null;employment_status?:string|null;project_availability?:string|null;weekly_capacity?:string|null;onboarding_step?:number|null;onboarding_completed_at?:string|null};

type Props={initialProfile:Profile;initialStep:number;domains:TaxonomyItem[];tools:TaxonomyItem[];domainPreferences:string[];toolPreferences:string[]};
const steps=['About you','Skills & interests','Project goals','Availability','Review profile'];
const areaOptions=['Data Analysis / BI','Data Science / ML','Data Engineering','AI / Generative AI','Analytics Engineering','Research / Product / Design','Career transition / Student','Other'];
const toggleTargetStyle={display:'inline-flex',alignItems:'center',minHeight:44,padding:'10px 12px'} as const;

export default function OnboardingFlow({initialProfile,initialStep,domains,tools,domainPreferences,toolPreferences}:Props){
  const [step,setStep]=useState(initialStep);const [status,setStatus]=useState<'idle'|'saving'|'success'|'error'>('idle');const [message,setMessage]=useState('');
  const [profile,setProfile]=useState(()=>({...initialProfile,full_name:initialProfile.full_name||'',headline:initialProfile.headline||'',location:initialProfile.location||'',professional_area:initialProfile.professional_area||'',primary_goal:initialProfile.primary_goal||'',skills:initialProfile.skills||[],preferred_roles:initialProfile.preferred_roles||[],project_availability:initialProfile.project_availability||'',weekly_capacity:initialProfile.weekly_capacity||'',is_public:Boolean(initialProfile.is_public)}));
  const [selectedDomains,setSelectedDomains]=useState(domainPreferences);const [selectedTools,setSelectedTools]=useState(toolPreferences);
  const completion=Math.round(((step+1)/steps.length)*100);
  const canContinue=useMemo(()=>{if(step===0)return Boolean(profile.full_name.trim()&&profile.professional_area);if(step===1)return profile.skills.length>0;if(step===2)return Boolean(profile.primary_goal.trim()||profile.preferred_roles.length);if(step===3)return Boolean(profile.project_availability);return true},[step,profile]);
  function setField(name:string,value:string|boolean|string[]){setProfile(current=>({...current,[name]:value}))}
  function toggle(list:string[],value:string,setter:(next:string[])=>void){setter(list.includes(value)?list.filter(item=>item!==value):[...list,value])}
  async function save(nextStep?:number,complete=false){setStatus('saving');setMessage('Saving your progress…');try{const persistedStep=typeof nextStep==='number'?nextStep:step;const response=await fetch('/api/profile',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...profile,domain_preferences:selectedDomains,tool_preferences:selectedTools,onboarding_step:persistedStep,onboarding_complete:complete})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Unable to save onboarding progress.');setProfile(current=>({...current,...body.profile}));setStatus('success');setMessage(complete?'Profile setup complete. You can keep refining it as your experience changes.':nextStep===undefined?'Progress saved. You can safely continue later.':'Progress saved.');if(typeof nextStep==='number')setStep(nextStep);return true}catch(error){setStatus('error');setMessage(error instanceof Error?error.message:'Unable to save onboarding progress.');return false}}
  async function continueFlow(){if(!canContinue){setStatus('error');setMessage('Complete the required details before continuing.');return}if(step<steps.length-1){const saved=await save(step+1);if(saved)window.scrollTo({top:0,behavior:'smooth'})}else{const saved=await save(4,true);if(saved)window.location.assign('/onboarding/complete')}}
  async function saveForLater(){const saved=await save(step);if(saved)window.location.assign('/member')}

  return <section className="section softSection"><div className="shell" style={{maxWidth:980}}><header style={{marginBottom:24}}><div className="eyebrow">Welcome to Mettelo</div><h1 style={{fontSize:'clamp(2.5rem,6vw,4.5rem)',margin:'0 0 12px'}}>Set up your professional profile.</h1><p className="lead" style={{maxWidth:760}}>Tell Mettelo about your professional background, skills, project interests and availability. We use these signals to make project discovery and recommendations more relevant. You can save and continue later at any point.</p></header><div className="panel" style={{padding:'clamp(20px,4vw,38px)'}}><div aria-label={`Onboarding progress: ${completion}%`} style={{marginBottom:24}}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap',marginBottom:8}}><strong>Step {step+1} of {steps.length}</strong><span>{completion}% complete</span></div><div style={{height:8,borderRadius:999,background:'rgba(16,19,29,.09)',overflow:'hidden'}}><div style={{width:`${completion}%`,height:'100%',background:'currentColor'}}/></div><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:12}}>{steps.map((item,index)=><button key={item} type="button" className={`chip ${index===step?'green':''}`} style={{minHeight:40}} onClick={()=>index<step&&setStep(index)} disabled={index>step}>{index+1}. {item}</button>)}</div></div>

  {step===0&&<div><h2>About you</h2><p>Add enough professional context for project teams to understand your background. These details describe your profile; they are not verified Mettelo Proof.</p><div className="fieldRow"><div><label htmlFor="onboarding-name">Full name *</label><input id="onboarding-name" value={profile.full_name} onChange={e=>setField('full_name',e.target.value)} autoComplete="name"/></div><div><label htmlFor="onboarding-location">Location</label><input id="onboarding-location" value={profile.location||''} onChange={e=>setField('location',e.target.value)} autoComplete="address-level2"/></div></div><label htmlFor="onboarding-area">Professional area *</label><select id="onboarding-area" value={profile.professional_area||''} onChange={e=>setField('professional_area',e.target.value)}><option value="">Select one</option>{areaOptions.map(item=><option key={item}>{item}</option>)}</select><label htmlFor="onboarding-headline">Professional headline</label><input id="onboarding-headline" value={profile.headline||''} onChange={e=>setField('headline',e.target.value)} placeholder="e.g. Data analyst focused on healthcare operations"/></div>}

  {step===1&&<div><h2>Skills &amp; interests</h2><p>Add the skills you use, the domains you are interested in and the tools you work with. These profile signals help Mettelo show more relevant project work; they are not contribution evidence.</p><label htmlFor="onboarding-skills">Core skills * <small>(comma separated)</small></label><input id="onboarding-skills" value={profile.skills.join(', ')} onChange={e=>setField('skills',e.target.value.split(',').map(v=>v.trim()).filter(Boolean))} placeholder="SQL, Power BI, Python"/><h3 style={{marginTop:22}}>Domains of interest</h3><div className="metaRow">{domains.map(item=><label className="metaPill" style={toggleTargetStyle} key={item.slug}><input type="checkbox" checked={selectedDomains.includes(item.slug)} onChange={()=>toggle(selectedDomains,item.slug,setSelectedDomains)}/> {item.name}</label>)}</div><h3 style={{marginTop:22}}>Tools and technologies</h3><div className="metaRow">{tools.map(item=><label className="metaPill" style={toggleTargetStyle} key={item.slug}><input type="checkbox" checked={selectedTools.includes(item.slug)} onChange={()=>toggle(selectedTools,item.slug,setSelectedTools)}/> {item.name}</label>)}</div></div>}

  {step===2&&<div><h2>Project goals</h2><p>Tell Mettelo what kind of project experience or responsibility you want to build next.</p><label htmlFor="onboarding-goal">What are you working toward?</label><textarea id="onboarding-goal" value={profile.primary_goal||''} onChange={e=>setField('primary_goal',e.target.value)} placeholder="Describe the project experience, responsibility or opportunity you want to move toward."/><label htmlFor="onboarding-roles">Preferred project roles <small>(comma separated)</small></label><input id="onboarding-roles" value={profile.preferred_roles.join(', ')} onChange={e=>setField('preferred_roles',e.target.value.split(',').map(v=>v.trim()).filter(Boolean))} placeholder="Data analyst, Researcher"/></div>}

  {step===3&&<div><h2>Availability</h2><p>Set realistic availability so Mettelo and project teams have useful context about the commitment you can make.</p><label htmlFor="onboarding-availability">Project availability *</label><select id="onboarding-availability" value={profile.project_availability||''} onChange={e=>setField('project_availability',e.target.value)}><option value="">Select one</option><option value="available_now">Available now</option><option value="available_soon">Available soon</option><option value="limited">Limited availability</option><option value="not_available">Not currently available</option></select><label htmlFor="onboarding-capacity">Weekly collaboration capacity</label><input id="onboarding-capacity" value={profile.weekly_capacity||''} onChange={e=>setField('weekly_capacity',e.target.value)} placeholder="e.g. 5–8 hours per week"/></div>}

  {step===4&&<div><h2>Review profile</h2><p>Check the information Mettelo will use for your profile, project discovery and recommendations. Completing setup does not create Mettelo Proof; Proof starts with real project contributions and review.</p><div className="memberProfileDetails"><div><span className="cardNumber">NAME</span><p>{profile.full_name||'Not provided'}</p></div><div><span className="cardNumber">AREA</span><p>{profile.professional_area||'Not provided'}</p></div><div><span className="cardNumber">SKILLS</span><p>{profile.skills.join(', ')||'Not provided'}</p></div><div><span className="cardNumber">PROJECT GOALS</span><p>{profile.primary_goal||profile.preferred_roles.join(', ')||'Not provided'}</p></div><div><span className="cardNumber">AVAILABILITY</span><p>{profile.project_availability?.replaceAll('_',' ')||'Not provided'}</p></div><div><span className="cardNumber">VISIBILITY</span><label className="consent" style={{minHeight:44,alignItems:'center',paddingBlock:8}}><input type="checkbox" checked={profile.is_public} onChange={e=>setField('is_public',e.target.checked)}/><span>Show my professional profile in Mettelo People when the public-profile requirements are met.</span></label></div></div></div>}

  <div className={`formStatus ${status}`} role="status" aria-live="polite">{message}</div><div className="actions" style={{marginTop:24,justifyContent:'space-between',flexWrap:'wrap'}}><div>{step>0&&<button className="button ghost" type="button" onClick={()=>setStep(step-1)} disabled={status==='saving'}>← Back</button>}</div><div className="actions" style={{margin:0,flexWrap:'wrap'}}><button className="button ghost" type="button" onClick={saveForLater} disabled={status==='saving'}>Save and continue later</button><button className="button dark" type="button" onClick={continueFlow} disabled={status==='saving'||!canContinue}>{status==='saving'?'Saving…':step===steps.length-1?'Complete profile setup →':'Save & continue →'}</button></div></div></div></div></section>;
}
