'use client';

import {ChangeEvent,FormEvent,useState} from 'react';

export type MemberProfile={full_name:string|null;headline:string|null;bio:string|null;location:string|null;professional_area:string|null;primary_goal:string|null;linkedin_url:string|null;github_url:string|null;portfolio_url?:string|null;avatar_url?:string|null;skills:string[];is_public:boolean;current_job_title?:string|null;organisation?:string|null;experience_level?:string|null;employment_status?:string|null;project_availability?:string|null;weekly_capacity?:string|null;preferred_roles?:string[];languages?:string[]};
type TaxonomyItem={slug:string;name:string};

export default function ProfileEditor({profile,domains,tools,domainPreferences,toolPreferences,onSaved}:{userId?:string;profile:MemberProfile;domains:TaxonomyItem[];tools:TaxonomyItem[];domainPreferences:string[];toolPreferences:string[];onSaved?:(profile:MemberProfile,domains:string[],tools:string[])=>void}){
  const [status,setStatus]=useState<'idle'|'saving'|'success'|'error'>('idle');const [message,setMessage]=useState('');
  const [imageFile,setImageFile]=useState<File|null>(null);const [localImageUrl,setLocalImageUrl]=useState<string|null>(null);const [removeAvatar,setRemoveAvatar]=useState(false);
  function chooseImage(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0]||null;if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){setStatus('error');setMessage('Choose a JPG, PNG or WebP image.');event.target.value='';return;}if(file.size>5*1024*1024){setStatus('error');setMessage('Profile images must be 5 MB or smaller.');event.target.value='';return;}if(localImageUrl)URL.revokeObjectURL(localImageUrl);setImageFile(file);setLocalImageUrl(URL.createObjectURL(file));setRemoveAvatar(false);setStatus('idle');setMessage('Photo selected. Save your profile to apply it.');}
  function removeImage(){if(localImageUrl)URL.revokeObjectURL(localImageUrl);setLocalImageUrl(null);setImageFile(null);setRemoveAvatar(true);setStatus('idle');setMessage('Photo will be removed when you save.');}

  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setStatus('saving');setMessage('Saving your profile…');const form=new FormData(event.currentTarget);
    const basePayload={full_name:String(form.get('full_name')||''),headline:String(form.get('headline')||''),bio:String(form.get('bio')||''),location:String(form.get('location')||''),professional_area:String(form.get('professional_area')||''),primary_goal:String(form.get('primary_goal')||''),current_job_title:String(form.get('current_job_title')||''),organisation:String(form.get('organisation')||''),experience_level:String(form.get('experience_level')||''),employment_status:String(form.get('employment_status')||''),project_availability:String(form.get('project_availability')||''),weekly_capacity:String(form.get('weekly_capacity')||''),linkedin_url:String(form.get('linkedin_url')||''),github_url:String(form.get('github_url')||''),portfolio_url:String(form.get('portfolio_url')||''),skills:String(form.get('skills')||'').split(',').map(v=>v.trim()).filter(Boolean),preferred_roles:String(form.get('preferred_roles')||'').split(',').map(v=>v.trim()).filter(Boolean),languages:String(form.get('languages')||'').split(',').map(v=>v.trim()).filter(Boolean),is_public:form.get('is_public')==='on',domain_preferences:form.getAll('domain_preferences').map(String),tool_preferences:form.getAll('tool_preferences').map(String)};
    try{
      let avatarUrl=removeAvatar?null:profile.avatar_url||null;
      if(removeAvatar){const response=await fetch('/api/profile/avatar',{method:'DELETE'});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Unable to remove profile photo.');avatarUrl=null;}
      if(imageFile){const upload=new FormData();upload.append('avatar',imageFile);const response=await fetch('/api/profile/avatar',{method:'POST',body:upload});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Unable to upload profile photo.');avatarUrl=body.avatar_url||null;}
      const response=await fetch('/api/profile',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...basePayload,avatar_url:avatarUrl})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Unable to save profile.');
      const saved=data.profile as MemberProfile;setImageFile(null);setRemoveAvatar(false);if(localImageUrl){URL.revokeObjectURL(localImageUrl);setLocalImageUrl(null);}setStatus('success');setMessage('Profile saved.');
      window.dispatchEvent(new CustomEvent('mettelo:profile-updated',{detail:{name:saved.full_name,avatarUrl:saved.avatar_url||avatarUrl}}));
      onSaved?.(saved,data.domain_preferences||basePayload.domain_preferences,data.tool_preferences||basePayload.tool_preferences);
    }catch(error){setStatus('error');setMessage(error instanceof Error?error.message:'Unable to save profile.');}
  }

  const visibleAvatar=localImageUrl||(removeAvatar?null:profile.avatar_url||null);const displayName=profile.full_name||'Your name';
  return <div className="profileEditorLayout"><form className="formCard profileEditorForm" onSubmit={submit}>
    <div className="panelHead"><div><span className="cardNumber">EDIT PROFESSIONAL PROFILE</span><h3 style={{marginTop:7}}>Make your capability easy to understand.</h3></div><span className="chip">MATCHING PROFILE</span></div>
    <div className="profilePhotoField"><div className="profilePhotoPreview" style={visibleAvatar?{backgroundImage:`url(${visibleAvatar})`}:undefined}>{visibleAvatar?'':displayName.slice(0,1).toUpperCase()}</div><div><strong>Profile photo</strong><p>JPG, PNG or WebP up to 5 MB. It becomes your top-menu avatar immediately after save.</p><div className="profilePhotoActions"><label className="button ghost profilePhotoButton" htmlFor="profile-photo">{visibleAvatar?'Change photo':'Add photo'}</label><input id="profile-photo" type="file" accept="image/jpeg,image/png,image/webp" onChange={chooseImage} style={{position:'absolute',width:1,height:1,opacity:0,overflow:'hidden'}}/>{visibleAvatar&&<button className="profileRemovePhoto" type="button" onClick={removeImage}>Remove</button>}</div></div></div>
    <div className="fieldRow"><div><label htmlFor="profile-name">Full name *</label><input id="profile-name" name="full_name" required defaultValue={profile.full_name||''}/></div><div><label>Professional headline</label><input name="headline" defaultValue={profile.headline||''}/></div></div>
    <div className="fieldRow"><div><label>Current job title</label><input name="current_job_title" defaultValue={profile.current_job_title||''}/></div><div><label>Organisation</label><input name="organisation" defaultValue={profile.organisation||''}/></div></div>
    <div className="fieldRow"><div><label>Professional area</label><select name="professional_area" defaultValue={profile.professional_area||''}><option value="">Select one</option><option>Data Analysis / BI</option><option>Data Science / ML</option><option>Data Engineering</option><option>AI / Generative AI</option><option>Analytics Engineering</option><option>Research / Product / Design</option><option>Career transition / Student</option><option>Other</option></select></div><div><label>Experience level</label><select name="experience_level" defaultValue={profile.experience_level||''}><option value="">Select one</option><option value="entry">Entry / early career</option><option value="mid">Mid-level</option><option value="senior">Senior</option><option value="lead">Lead / manager</option><option value="executive">Executive / head of function</option></select></div></div>
    <div className="fieldRow"><div><label>Employment status</label><select name="employment_status" defaultValue={profile.employment_status||''}><option value="">Select one</option><option value="employed">Employed</option><option value="self_employed">Self-employed / freelance</option><option value="student">Student</option><option value="career_transition">Career transition</option><option value="seeking_work">Seeking work</option><option value="not_disclosed">Prefer not to say</option></select></div><div><label>Location</label><input name="location" defaultValue={profile.location||''}/></div></div>
    <div className="preferencePanel"><span className="cardNumber">PROJECT FIT</span><h3>How should Mettelo match you to work?</h3><div className="fieldRow"><div><label>Project availability</label><select name="project_availability" defaultValue={profile.project_availability||''}><option value="">Select one</option><option value="available_now">Available now</option><option value="available_soon">Available soon</option><option value="limited">Limited availability</option><option value="not_available">Not available currently</option></select></div><div><label>Weekly collaboration capacity</label><input name="weekly_capacity" defaultValue={profile.weekly_capacity||''}/></div></div><label>Preferred project roles</label><input name="preferred_roles" defaultValue={(profile.preferred_roles||[]).join(', ')}/><div className="fieldRow"><div><label>Domains of interest</label><select name="domain_preferences" multiple size={7} defaultValue={domainPreferences}>{domains.map(item=><option key={item.slug} value={item.slug}>{item.name}</option>)}</select></div><div><label>Tools / technologies</label><select name="tool_preferences" multiple size={7} defaultValue={toolPreferences}>{tools.map(item=><option key={item.slug} value={item.slug}>{item.name}</option>)}</select></div></div></div>
    <label>What are you working toward?</label><input name="primary_goal" defaultValue={profile.primary_goal||''}/><label>Core skills</label><input name="skills" defaultValue={(profile.skills||[]).join(', ')}/><label>Languages</label><input name="languages" defaultValue={(profile.languages||[]).join(', ')}/><div className="fieldRow"><div><label>LinkedIn</label><input name="linkedin_url" type="url" defaultValue={profile.linkedin_url||''}/></div><div><label>GitHub</label><input name="github_url" type="url" defaultValue={profile.github_url||''}/></div></div><label>Portfolio / personal site</label><input name="portfolio_url" type="url" defaultValue={profile.portfolio_url||''}/><label>Professional bio</label><textarea name="bio" defaultValue={profile.bio||''}/><label className="consent"><input name="is_public" type="checkbox" defaultChecked={profile.is_public}/><span>Show this professional profile in Mettelo People.</span></label>
    <button className="button dark" type="submit" disabled={status==='saving'} style={{width:'100%',marginTop:20}}>{status==='saving'?'Saving profile…':'Save & view profile →'}</button><div className={`formStatus ${status}`} role="status" aria-live="polite">{message}</div>
  </form><aside className="profilePreviewCard"><span className="cardNumber">PHOTO PREVIEW</span><div className="profilePreviewAvatar" style={visibleAvatar?{backgroundImage:`url(${visibleAvatar})`}:undefined}>{visibleAvatar?'':displayName.slice(0,1).toUpperCase()}</div><h3>{displayName}</h3><p>{profile.headline||profile.current_job_title||profile.professional_area||'Your professional profile'}</p></aside></div>;
}
