'use client';

import {FormEvent,useState} from 'react';

type Source={id:string;name:string;owner_user_id:string|null;owner_name:string;version_label:string|null;external_url:string;provenance:string|null;download_policy:string;publish_policy:string};
type Version={id:string;data_source_id:string;version_label:string;external_url:string;change_summary:string|null;created_at:string};

const downloadLabels:Record<string,string>={allowed:'Download allowed',team_only:'Project team only',not_allowed:'Download not allowed'};
const publishLabels:Record<string,string>={permitted:'Publication permitted',approval_required:'Approval required before publishing',not_permitted:'Publication not permitted'};

export default function ProjectDataGovernance({projectId,projectRunId,currentUserId,canLead,sources:initialSources,versions:initialVersions}:{projectId:string;projectRunId:string|null;currentUserId:string;canLead:boolean;sources:Source[];versions:Version[]}){
  const [sources,setSources]=useState(initialSources);const [versions,setVersions]=useState(initialVersions);const [busy,setBusy]=useState('');const [message,setMessage]=useState('');
  if(!projectRunId)return null;
  async function send(action:string,sourceId:string,payload:Record<string,unknown>){setBusy(`${action}:${sourceId}`);setMessage('');try{const response=await fetch('/api/project-data-governance',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,project_id:projectId,project_run_id:projectRunId,data_source_id:sourceId,...payload})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Unable to update data governance.');if(action==='governance')setSources(current=>current.map(item=>item.id===sourceId?{...item,...body.item}:item));if(action==='version'){setVersions(current=>[body.item,...current]);setSources(current=>current.map(item=>item.id===sourceId?{...item,version_label:body.item.version_label,external_url:body.item.external_url}:item));}setMessage(body.message||'Saved.');}catch(error){setMessage(error instanceof Error?error.message:'Unable to update data governance.');}finally{setBusy('')}}
  function governance(event:FormEvent<HTMLFormElement>,source:Source){event.preventDefault();void send('governance',source.id,Object.fromEntries(new FormData(event.currentTarget).entries()))}
  function version(event:FormEvent<HTMLFormElement>,source:Source){event.preventDefault();const form=event.currentTarget;void send('version',source.id,Object.fromEntries(new FormData(form).entries())).then(()=>form.reset())}
  return <section className="panel" id="phase4-data-governance" aria-labelledby="phase4-data-title">
    <div className="panelHead"><div><span className="cardNumber">DATA GOVERNANCE</span><h2 id="phase4-data-title" style={{marginTop:8}}>Know who owns the data and how it may be used</h2></div><a className="linkArrow" href="#data-sources">Open full data workspace →</a></div>
    <p className="panelNote">Every project data source should answer three questions before work begins: who owns it, may I download it, and what may I publish?</p>
    {sources.length?<div className="workspaceCollection">{sources.map(source=>{const canManage=canLead||source.owner_user_id===currentUserId;const sourceVersions=versions.filter(item=>item.data_source_id===source.id);return <article className="dataRecord" key={source.id}>
      <div className="dataRecordHead"><div><span className="chip">DATA SOURCE</span><h3>{source.name}</h3></div><span className="chip">{source.version_label||'Version not set'}</span></div>
      <dl className="recordFacts"><div><dt>Who owns it?</dt><dd>{source.owner_name}</dd></div><div><dt>May I download it?</dt><dd>{downloadLabels[source.download_policy]||'Rule not set'}</dd></div><div><dt>What can I publish?</dt><dd>{publishLabels[source.publish_policy]||'Rule not set'}</dd></div><div><dt>Provenance</dt><dd>{source.provenance||'Not documented yet'}</dd></div></dl>
      <a className="linkArrow" href={source.external_url} target="_blank" rel="noopener noreferrer">Open current version →</a>
      {sourceVersions.length>0&&<details className="inlineEditor"><summary>Version history ({sourceVersions.length})</summary><ul>{sourceVersions.map(item=><li key={item.id}><strong>{item.version_label}</strong> · {new Date(item.created_at).toLocaleDateString('en-GB')}{item.change_summary?` — ${item.change_summary}`:''} · <a href={item.external_url} target="_blank" rel="noopener noreferrer">Open</a></li>)}</ul></details>}
      {canManage&&<><details className="workspaceComposer"><summary>Edit governance rules</summary><form className="formCard compactForm" onSubmit={event=>governance(event,source)}><label htmlFor={`provenance-${source.id}`}>Provenance</label><textarea id={`provenance-${source.id}`} name="provenance" defaultValue={source.provenance||''} rows={3} placeholder="Where did this data come from and what transformations have already happened?"/><label htmlFor={`download-${source.id}`}>Download rule</label><select id={`download-${source.id}`} name="download_policy" defaultValue={source.download_policy||'team_only'}><option value="allowed">Download allowed</option><option value="team_only">Project team only</option><option value="not_allowed">Download not allowed</option></select><label htmlFor={`publish-${source.id}`}>Publication rule</label><select id={`publish-${source.id}`} name="publish_policy" defaultValue={source.publish_policy||'not_permitted'}><option value="permitted">Publication permitted</option><option value="approval_required">Approval required</option><option value="not_permitted">Publication not permitted</option></select><button className="button dark" disabled={busy===`governance:${source.id}`}>{busy===`governance:${source.id}`?'Saving…':'Save governance rules'}</button></form></details><details className="workspaceComposer"><summary>Register a new version</summary><form className="formCard compactForm" onSubmit={event=>version(event,source)}><label htmlFor={`version-${source.id}`}>Version label</label><input id={`version-${source.id}`} name="version_label" required maxLength={120} placeholder="v2 / 2026-08-16"/><label htmlFor={`version-url-${source.id}`}>HTTPS location</label><input id={`version-url-${source.id}`} name="external_url" type="url" pattern="https://.*" required defaultValue={source.external_url}/><label htmlFor={`version-summary-${source.id}`}>What changed?</label><textarea id={`version-summary-${source.id}`} name="change_summary" rows={3} maxLength={1800}/><button className="button dark" disabled={busy===`version:${source.id}`}>{busy===`version:${source.id}`?'Saving…':'Register version'}</button></form></details></>}
    </article>})}</div>:<div className="emptyState"><h3>No project data registered yet.</h3><p>Add the first data source in the Data workspace, then its ownership and usage rules will appear here.</p></div>}
    <div className="formStatus" role="status" aria-live="polite">{message}</div>
  </section>;
}
