'use client';

import Link from 'next/link';
import {FormEvent,useState} from 'react';
import SocialShare from '@/components/SocialShare';
import styles from './ProjectArchitectApplication.module.css';

type Application={id:string;status:string;data_ai_experience:string;project_delivery_experience:string;coordination_experience:string;proposed_first_project:string;availability:string;motivation:string;reviewer_notes:string|null;submitted_at:string|null};
type Evidence={id:string;evidence_type:string;label:string;external_url:string|null;contribution_id:string|null};
type Proof={id:string;title:string;projects:{title:string}|null};
type Credential={credential_id:string;status:string;issued_at:string}|null;
type Identity={account_type:string;show_project_architect_designation:boolean};
type LinkRow={label:string;url:string};

const statusCopy:Record<string,string>={draft:'Draft',submitted:'Submitted',under_review:'Under review',additional_evidence_required:'More evidence requested',approved:'Approved',declined:'Declined',withdrawn:'Withdrawn',suspended:'Suspended'};
const fieldCopy=[
  ['data_ai_experience','Data & AI experience','Describe relevant work you have completed, the tools you used and the decisions you owned.'],
  ['project_delivery_experience','Project delivery experience','Explain how you moved a problem or requirement towards a useful, reviewed outcome.'],
  ['coordination_experience','Collaboration and coordination','Share how you have scoped work, supported contributors, managed risks or reviewed delivery.'],
  ['proposed_first_project','A project you would like to shape','Describe the Data & AI problem, intended users, likely data sources, delivery stages and useful outcome.'],
  ['availability','Preferred availability','Share your weekly capacity, time zone and preferred collaboration times so we can assess a suitable project match.'],
  ['motivation','Why do you want to become a Project Architect?','Tell us what you hope to contribute, practise and learn through this opportunity.']
] as const;

export default function ProjectArchitectApplication({initialApplication,initialEvidence,proof,identity,credential}:{initialApplication:Application|null;initialEvidence:Evidence[];proof:Proof[];identity:Identity;credential:Credential}){
  const [application,setApplication]=useState(initialApplication);const [editing,setEditing]=useState(!initialApplication||['draft','additional_evidence_required'].includes(initialApplication.status));
  const [links,setLinks]=useState<LinkRow[]>(initialEvidence.filter(x=>x.evidence_type==='external_link').map(x=>({label:x.label,url:x.external_url||''})).concat(initialEvidence.some(x=>x.evidence_type==='external_link')?[]:[{label:'',url:''}]));
  const [selectedProof,setSelectedProof]=useState(initialEvidence.filter(x=>x.contribution_id).map(x=>x.contribution_id as string));const [working,setWorking]=useState('');const [message,setMessage]=useState('');const [visible,setVisible]=useState(identity.show_project_architect_designation);
  const elevated=identity.account_type==='project_architect'&&credential?.status==='active';
  function addLink(){setLinks(current=>[...current,{label:'',url:''}])}function removeLink(index:number){setLinks(current=>current.filter((_,i)=>i!==index))}
  async function save(event:FormEvent<HTMLFormElement>,status:'draft'|'submitted'){
    event.preventDefault();setWorking(status);setMessage(status==='draft'?'Saving draft…':'Submitting evidence…');const form=new FormData(event.currentTarget);
    const payload:Record<string,unknown>={status,proof_ids:selectedProof,external_evidence:links.filter(row=>row.label.trim()||row.url.trim())};for(const [key] of fieldCopy)payload[key]=String(form.get(key)||'');
    try{const response=await fetch('/api/project-architect-application',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const body=await response.json();if(!response.ok)throw new Error(body.error||'Unable to save application.');setApplication(body.application);setEditing(status==='draft');setMessage(body.message);}catch(error){setMessage(error instanceof Error?error.message:'Unable to save application.');}finally{setWorking('');}
  }
  async function withdraw(){setWorking('withdraw');try{const response=await fetch('/api/project-architect-application',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({action:'withdraw'})});const body=await response.json();if(!response.ok)throw new Error(body.error||'Unable to withdraw.');setApplication(current=>current?{...current,status:'withdrawn'}:current);setMessage('Application withdrawn.');}catch(error){setMessage(error instanceof Error?error.message:'Unable to withdraw.');}finally{setWorking('');}}
  async function changeVisibility(next:boolean){setWorking('visibility');try{const response=await fetch('/api/project-architect-application',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({action:'visibility',visible:next})});const body=await response.json();if(!response.ok)throw new Error(body.error||'Unable to update visibility.');setVisible(next);setMessage(next?'External designation is now visible on your public profile.':'External designation hidden from your public profile.');}catch(error){setMessage(error instanceof Error?error.message:'Unable to update visibility.');}finally{setWorking('');}}

  if(elevated)return <div className={styles.stack}>
    <section className={`${styles.heroCard} ${styles.approved}`}><span className="chip green">ACTIVE IDENTITY</span><h2>Project Architect</h2><p>Your external professional designation is <strong>Mettelo Data &amp; AI Project Architect</strong>. This is an evidence-backed Mettelo designation—not employment or professional certification.</p><div className={styles.credential}><span>Credential ID</span><strong>{credential?.credential_id}</strong><small>Issued {credential&&new Date(credential.issued_at).toLocaleDateString('en-GB',{dateStyle:'long'})}</small></div><label className={styles.toggle}><input type="checkbox" checked={visible} disabled={working==='visibility'} onChange={event=>void changeVisibility(event.target.checked)}/><span>Show the designation on my public Mettelo profile</span></label><div className={styles.actions}><Link className="button dark" href={`/credentials/${credential?.credential_id}`}>Open verification page →</Link><SocialShare url={`https://mettelo.com/credentials/${credential?.credential_id}`} text="I am a Mettelo Data & AI Project Architect. View my evidence-backed Mettelo record." label="Share designation"/></div></section><div className="formStatus" role="status" aria-live="polite">{message}</div>
  </div>;

  const readOnly=application&&!editing&&!['declined','withdrawn'].includes(application.status);
  return <div className={styles.stack}>
    <section className={styles.heroCard}><span className="chip">UNPAID VOLUNTARY OPPORTUNITY</span><h2>Help teams turn Data &amp; AI ideas into deliverable projects.</h2><p>Project Architect is Mettelo&apos;s trusted community identity for experienced members who can shape a useful project, coordinate delivery, support review and work within Admin oversight.</p><div className={styles.boundary}><strong>Important before you apply</strong><span>This is flexible, unpaid participation—not employment, professional certification or a promise of future paid work. You may decline a project or withdraw. Acceptance also depends on project availability and eligibility in your location.</span></div></section>
    <section className={styles.experienceCard}><div><span className="cardNumber">WHAT YOU CAN GAIN</span><h3>Build experience you can explain and verify.</h3></div><div className={styles.experienceGrid}><div><strong>Project leadership</strong><span>Practise scoping, planning, coordination and review on real Data &amp; AI projects.</span></div><div><strong>Collaboration</strong><span>Work with contributors, reviewers and Admin across different disciplines.</span></div><div><strong>Feedback and skills</strong><span>Receive structured review that helps strengthen your judgement and delivery practice.</span></div><div><strong>Career evidence</strong><span>Build a traceable record of approved responsibilities, decisions and outcomes.</span></div><div><strong>Participation verification</strong><span>After meaningful completed work, Mettelo may confirm your role, dates and verified contribution for a reference request.</span></div><div><strong>Professional recognition</strong><span>If approved, choose whether to show and share the Mettelo Data &amp; AI Project Architect designation.</span></div></div><p className={styles.referenceNote}>A personal recommendation is not automatic. Any reference will reflect the contribution Mettelo actually observed.</p></section>
    {application&&<section className={styles.statusCard}><div><span className="cardNumber">APPLICATION STATUS</span><h3>{statusCopy[application.status]||application.status}</h3>{application.reviewer_notes&&<p><strong>Admin note:</strong> {application.reviewer_notes}</p>}</div>{application.status==='submitted'&&<button className="button ghost" type="button" disabled={working==='withdraw'} onClick={withdraw}>Withdraw</button>}{['declined','withdrawn'].includes(application.status)&&<button className="button dark" type="button" onClick={()=>setEditing(true)}>Start a new application →</button>}</section>}
    {readOnly?<section className="panel"><h3>Your application is with the Mettelo team.</h3><p className="panelNote">We will notify you in Mettelo and by email when the status changes. A reviewer may ask for more information before making a decision.</p></section>:editing&&<form className={`${styles.form} formCard`} onSubmit={event=>void save(event,(event.nativeEvent as SubmitEvent).submitter?.getAttribute('data-status')==='draft'?'draft':'submitted')}>
      <div className="panelHead"><div><span className="cardNumber">PROJECT ARCHITECT APPLICATION</span><h3>Tell us what you can contribute and what you want to develop.</h3></div><span className="chip">COMPLETE EVERY SECTION</span></div>
      {fieldCopy.map(([key,label,hint])=><div className={styles.field} key={key}><label htmlFor={`architect-${key}`}>{label}</label><p>{hint}</p><textarea id={`architect-${key}`} name={key} rows={key==='availability'?3:5} maxLength={3000} defaultValue={application?.[key]||''}/></div>)}
      <fieldset className={styles.evidence}><legend>Work examples and supporting links</legend><p>Add relevant case studies, repositories, dashboards, reports or documents. Use secure HTTPS links; Mettelo stores the link rather than the file or dataset.</p>{links.map((row,index)=><div className={styles.linkRow} key={index}><label><span>Work example</span><input value={row.label} onChange={event=>setLinks(current=>current.map((item,i)=>i===index?{...item,label:event.target.value}:item))} placeholder="Customer churn analysis"/></label><label><span>Secure link</span><input type="url" value={row.url} onChange={event=>setLinks(current=>current.map((item,i)=>i===index?{...item,url:event.target.value}:item))} placeholder="https://…"/></label>{links.length>1&&<button type="button" aria-label={`Remove work example ${index+1}`} onClick={removeLink.bind(null,index)}>Remove</button>}</div>)}<button className="button ghost" type="button" onClick={addLink} disabled={links.length>=6}>Add another work example</button></fieldset>
      <fieldset className={styles.evidence}><legend>Your verified Mettelo Proof</legend><p>If you already have verified work on Mettelo, select the most relevant records to support your application.</p>{proof.length?<div className={styles.proofList}>{proof.map(item=><label key={item.id}><input type="checkbox" checked={selectedProof.includes(item.id)} onChange={event=>setSelectedProof(current=>event.target.checked?[...current,item.id]:current.filter(id=>id!==item.id))}/><span><strong>{item.title}</strong><small>{item.projects?.title||'Mettelo Proof'}</small></span></label>)}</div>:<p className={styles.empty}>You do not need existing Mettelo Proof to apply. Add a strong external work example above instead.</p>}</fieldset>
      <div className={styles.actions}><button className="button ghost" type="submit" data-status="draft" formNoValidate disabled={Boolean(working)}>Save draft</button><button className="button dark" type="submit" data-status="submitted" disabled={Boolean(working)}>{working==='submitted'?'Submitting…':'Submit for Admin review →'}</button></div>
    </form>}
    <div className="formStatus" role="status" aria-live="polite">{message}</div>
  </div>;
}
