'use client';

import {FormEvent,useCallback,useEffect,useMemo,useState} from 'react';

type ReviewEvent={id:string;event_type:string;comment:string|null;evidence_url:string|null;created_at:string;actor_name:string};
type Contribution={id:string;title:string;description:string;evidence_url:string|null;verification_status:string;review_notes:string|null;created_at:string;updated_at:string;verified_at:string|null;events:ReviewEvent[]};
const statusLabels:Record<string,string>={pending:'Under review',needs_changes:'Changes requested',verified:'Approved',rejected:'Not approved'};

export default function ProjectContributionStatusPanel({projectId,projectRunId}:{projectId:string;projectRunId:string|null}){
 const [items,setItems]=useState<Contribution[]>([]);const [loading,setLoading]=useState(Boolean(projectRunId));const [message,setMessage]=useState('');const [working,setWorking]=useState('');
 const endpoint=useMemo(()=>projectRunId?`/api/project-contribution-status?project_id=${encodeURIComponent(projectId)}&project_run_id=${encodeURIComponent(projectRunId)}`:'',[projectId,projectRunId]);
 const load=useCallback(async()=>{if(!endpoint)return;setLoading(true);try{const response=await fetch(endpoint,{cache:'no-store'});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Unable to load contributions.');setItems(body.items||[])}catch(error){setMessage(error instanceof Error?error.message:'Unable to load contributions.')}finally{setLoading(false)}},[endpoint]);
 useEffect(()=>{void load()},[load]);
 async function resubmit(event:FormEvent<HTMLFormElement>,item:Contribution){event.preventDefault();const form=event.currentTarget,values=Object.fromEntries(new FormData(form).entries());setWorking(item.id);setMessage('');try{const response=await fetch('/api/contributions',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:item.id,description:values.description,evidence_url:values.evidence_url})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Unable to resubmit contribution.');setMessage(body.message||'Contribution resubmitted for review.');await load()}catch(error){setMessage(error instanceof Error?error.message:'Unable to resubmit contribution.')}finally{setWorking('')}}
 if(!projectRunId)return null;
 return <section className="panel" id="phase4-contributions" aria-labelledby="phase4-contributions-title"><div className="panelHead"><div><span className="cardNumber">MY CONTRIBUTIONS</span><h2 id="phase4-contributions-title" style={{marginTop:8}}>Contribution evidence and review</h2></div><a className="linkArrow" href="#proof">Submit new evidence →</a></div><p className="panelNote">Track what you submitted, what reviewers decided, and whether you need to act.</p>
  {loading?<div className="emptyState"><h3>Loading contribution status…</h3></div>:items.length?<div className="workspaceCollection">{items.map(item=><article className="dataRecord" key={item.id}><div className="dataRecordHead"><div><span className="chip">{statusLabels[item.verification_status]||item.verification_status.replaceAll('_',' ')}</span><h3>{item.title}</h3></div><small>Submitted {new Date(item.created_at).toLocaleString('en-GB')}</small></div><p>{item.description}</p>{item.evidence_url&&<a className="linkArrow" href={item.evidence_url} target="_blank" rel="noopener noreferrer">Open submitted evidence →</a>}
   {item.review_notes&&<div className="formStatus"><strong>Reviewer comments:</strong> {item.review_notes}</div>}
   <div className="contributionTimeline" aria-label={`Review timeline for ${item.title}`}><strong>Review timeline</strong>{item.events.length?item.events.map(event=><div className="taskActivityItem" key={event.id}><strong>{event.event_type.replaceAll('_',' ')}</strong><small>{event.actor_name} · {new Date(event.created_at).toLocaleString('en-GB')}</small>{event.comment&&<p>{event.comment}</p>}{event.evidence_url&&<a href={event.evidence_url} target="_blank" rel="noopener noreferrer">Open evidence</a>}</div>):<small>No review activity recorded yet.</small>}</div>
   {item.verification_status==='pending'&&<p className="panelNote"><strong>No action required.</strong> Your evidence is waiting for project review.</p>}
   {item.verification_status==='verified'&&<p className="panelNote"><strong>Approved.</strong> This contribution can now flow into your verified Proof according to its visibility settings.</p>}
   {item.verification_status==='rejected'&&<p className="panelNote"><strong>No further action is currently available.</strong> Contact your Project Lead if you need to discuss this decision.</p>}
   {item.verification_status==='needs_changes'&&<form className="formCard compactForm" onSubmit={event=>void resubmit(event,item)}><h4>Update and resubmit</h4><label htmlFor={`contribution-description-${item.id}`}>What did you change?</label><textarea id={`contribution-description-${item.id}`} name="description" required minLength={30} defaultValue={item.description} rows={5}/><label htmlFor={`contribution-evidence-${item.id}`}>Updated evidence URL</label><input id={`contribution-evidence-${item.id}`} name="evidence_url" type="url" defaultValue={item.evidence_url||''} placeholder="https://"/><button className="button dark" disabled={working===item.id}>{working===item.id?'Resubmitting…':'Resubmit for review'}</button></form>}
  </article>)}</div>:<div className="emptyState"><h3>No contribution evidence submitted yet.</h3><p>When your work is ready, submit evidence below. You will be able to track review and requested changes here.</p><a className="button dark" href="#proof">Submit contribution evidence</a></div>}
  <div className="formStatus" role="status" aria-live="polite">{message}</div>
 </section>;
}
