'use client';

import {useEffect,useState} from 'react';

type Policy={public_path:string;can_share:boolean;invite_ready:boolean;late_joining_open:boolean;filled:number;maximum:number|null};
export default function ProjectRecruitmentActions({projectId}:{projectId:string}){
 const[policy,setPolicy]=useState<Policy|null>(null);const[message,setMessage]=useState('');const[working,setWorking]=useState('');
 useEffect(()=>{let active=true;void fetch(`/api/project-recruitment?project_id=${encodeURIComponent(projectId)}`).then(async response=>{const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Unable to load recruitment state.');if(active)setPolicy(body as Policy)}).catch(()=>{if(active)setPolicy(null)});return()=>{active=false}},[projectId]);
 async function record(action:'share'|'invite_intent',channel?:string){const response=await fetch('/api/project-recruitment',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({project_id:projectId,action,channel})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Unable to complete this action.');return body}
 async function share(channel:'copy'|'native'){if(!policy?.can_share)return;setWorking(channel);setMessage('');try{const body=await record('share',channel);const url=new URL(String(body.public_path||policy.public_path),window.location.origin).toString();if(channel==='native'&&navigator.share)await navigator.share({title:'Mettelo project',url});else await navigator.clipboard.writeText(url);setMessage(channel==='native'&&navigator.share?'Share sheet opened.':'Public project link copied. Anyone who opens it still follows the normal Mettelo eligibility and capacity journey.')}catch(error){setMessage(error instanceof Error?error.message:'Unable to share this project.')}finally{setWorking('')}}
 async function invite(){if(!policy?.invite_ready)return;setWorking('invite');setMessage('');try{const body=await record('invite_intent');setMessage(body.message||'Invitation readiness confirmed.')}catch(error){setMessage(error instanceof Error?error.message:'Unable to prepare an invitation.')}finally{setWorking('')}}
 if(!policy)return null;
 const full=policy.maximum!==null&&policy.filled>=policy.maximum;
 return <section className="recruitmentActions" aria-labelledby="recruitment-actions-title"><div><span className="cardNumber">COLLABORATION</span><h3 id="recruitment-actions-title">Grow this project where policy allows</h3><p>{full?'This run is full. Recruitment is closed.':policy.late_joining_open?'Eligible collaborators can still join this same project run through the normal Mettelo journey.':'Late joining is currently closed for this run.'}</p></div><div className="recruitmentButtons">{policy.can_share&&<><button className="button ghost" type="button" disabled={Boolean(working)} onClick={()=>void share('copy')}>{working==='copy'?'Copying…':'Copy public project link'}</button>{typeof navigator!=='undefined'&&'share'in navigator&&<button className="button ghost" type="button" disabled={Boolean(working)} onClick={()=>void share('native')}>{working==='native'?'Opening…':'Share project'}</button>}</>}{policy.invite_ready&&<button className="button dark" type="button" disabled={Boolean(working)} onClick={()=>void invite()}>{working==='invite'?'Checking…':'Invite collaborator'}</button>}</div>{policy.invite_ready&&<p className="recruitmentNote">Invitation readiness does not create membership. The invitee must still sign in or sign up, meet profile and project eligibility, and pass current capacity/cutoff checks before joining this same run.</p>}<div className="formStatus" role="status" aria-live="polite">{message}</div><style jsx>{`.recruitmentActions{display:grid;gap:12px;padding:18px;border:1px solid #d9dde2;border-radius:14px;background:#fff}.recruitmentActions h3{margin:7px 0 5px}.recruitmentActions p{margin:0;color:#5b6470;font-size:.75rem;line-height:1.55}.recruitmentButtons{display:flex;gap:8px;flex-wrap:wrap}.recruitmentButtons .button{min-height:44px}.recruitmentNote{padding:10px;border-radius:9px;background:#fbf7ee}.formStatus{min-height:20px;font-size:.72rem;color:#5b6470}@media(max-width:560px){.recruitmentButtons{display:grid}.recruitmentButtons .button{width:100%}}`}</style></section>;
}
