'use client';

import {FormEvent,useState} from 'react';

type Props={projectId:string;projectRunId:string;activeNeedId:string|null;activeNeedLabel:string|null;weeklyCommitment:string|null;canRecruit:boolean;canManage:boolean;canFind:boolean;canPost:boolean;canShare:boolean;stateLabel:string;stateMessage:string};

export default function ProjectGrowTeamActions({projectId,projectRunId,activeNeedId,activeNeedLabel,weeklyCommitment,canRecruit,canManage,canFind,canPost,canShare,stateLabel,stateMessage}:Props){
 const[needId,setNeedId]=useState(activeNeedId);const[needLabel,setNeedLabel]=useState(activeNeedLabel);const[status,setStatus]=useState('');const[working,setWorking]=useState(false);const[showForm,setShowForm]=useState(false);
 const discoveryHref=needId?`/member/find-collaborators?project_id=${encodeURIComponent(projectId)}&collaboration_need=${encodeURIComponent(needId)}`:`/member/find-collaborators?project_id=${encodeURIComponent(projectId)}`;
 const publicPath=needId?`/collaborate/${encodeURIComponent(needId)}`:null;
 async function createNeed(event:FormEvent<HTMLFormElement>){event.preventDefault();if(working||!canPost)return;const form=new FormData(event.currentTarget);const responsibility=String(form.get('responsibility')||'').trim(),memberMessage=String(form.get('member_message')||'').trim();if(!responsibility){setStatus('Add the responsibility or help the team needs.');return}setWorking(true);setStatus('');try{const response=await fetch('/api/collaboration-needs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({project_id:projectId,project_run_id:projectRunId,responsibility,member_message:memberMessage||null,weekly_commitment:weeklyCommitment||null,source:'member'})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Unable to open the collaboration need.');setNeedId(body.item.id);setNeedLabel(responsibility);setShowForm(false);setStatus('Collaboration need is live. Find and share routes are now tied to this exact project run.');}catch(error){setStatus(error instanceof Error?error.message:'Unable to open the collaboration need.')}finally{setWorking(false)}}
 async function closeNeed(){if(!needId||working)return;setWorking(true);setStatus('');try{const response=await fetch('/api/collaboration-needs',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:needId,project_id:projectId,project_run_id:projectRunId,reason:'closed_from_mettelo_lab_team'})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Unable to close the collaboration need.');setNeedId(null);setNeedLabel(null);setStatus('Collaboration need closed. Mettelo will no longer show or accept interest through that opportunity.');}catch(error){setStatus(error instanceof Error?error.message:'Unable to close the collaboration need.')}finally{setWorking(false)}}
 async function shareNeed(){if(!publicPath||!canShare)return;const url=`${window.location.origin}${publicPath}`;const text=`We are looking for ${needLabel||'a collaborator'} to join our Mettelo project.${weeklyCommitment?` Commitment: ${weeklyCommitment}.`:''}`;try{if(navigator.share){await navigator.share({title:'Mettelo collaboration opportunity',text,url});setStatus('Share sheet opened.');return}await navigator.clipboard.writeText(url);setStatus('Public collaboration link copied.');}catch(error){if(error instanceof DOMException&&error.name==='AbortError')return;setStatus('Could not open sharing. Use View collaboration post and copy its public link.')}}
 const routeDisabled=!canRecruit||!canManage;
 return <div className="growTeamRoot">
  <div className="growTeamState" role="status"><strong>{stateLabel}</strong><span>{stateMessage}</span>{needId&&<small>Current need · {needLabel||'Collaborator needed'}</small>}</div>
  <div className="growTeamActions" aria-label="Grow the team routes">
   {needId&&canFind&&!routeDisabled?<a className="growTeamButton growTeamPrimary" href={discoveryHref}>Find people on Mettelo</a>:<span className="growTeamButton growTeamPrimary growTeamDisabled" aria-disabled="true" title={!needId?'Post a collaborator need first.':!canFind?'Member invitations are disabled for this project.':undefined}>Find people on Mettelo</span>}
   <button className="growTeamButton" type="button" onClick={()=>setShowForm(value=>!value)} disabled={routeDisabled||!canPost||Boolean(needId)||working} title={needId?'A collaboration need is already active.':!canPost?'Collaboration posting is disabled for this project.':undefined}>Post collaborator needed</button>
   <button className="growTeamButton" type="button" onClick={()=>void shareNeed()} disabled={routeDisabled||!canShare||!needId||working} title={!needId?'Post a collaborator need first.':!canShare?'Public sharing is disabled or unavailable for this project.':undefined}>Share to find collaborators</button>
  </div>
  {!needId&&canRecruit&&canManage&&<p className="growTeamHint">Post the structured need first. Mettelo then binds member discovery, direct invitations, public sharing and incoming interest to this exact run. No route creates membership directly.</p>}
  {needId&&canRecruit&&canManage&&<div className="growTeamSecondary"><a className="growTeamButton" href={publicPath||'#'}>View collaboration post</a><button className="growTeamButton growTeamDanger" type="button" onClick={()=>void closeNeed()} disabled={working}>{working?'Updating…':'Close collaboration need'}</button></div>}
  {canRecruit&&!canManage?<p className="growTeamNotice">Recruitment is open, but only the Project Lead, Admin, or sole active member of an independent run can manage collaboration needs.</p>:null}
  {!canRecruit?<p className="growTeamNotice">Recruitment actions are unavailable in the current project state.</p>:null}
  {!needId&&showForm&&canRecruit&&canManage&&canPost&&<form className="growTeamForm" onSubmit={createNeed}><label><span>Responsibility needed</span><input name="responsibility" required maxLength={160} placeholder="e.g. Dashboard & insights"/></label>{weeklyCommitment&&<label><span>Commitment</span><input value={weeklyCommitment} readOnly aria-readonly="true"/></label>}<label className="growTeamWide"><span>Optional message</span><textarea name="member_message" maxLength={800} rows={3} placeholder="Add short context about the stage of work and the help needed."/></label><div className="growTeamFormActions"><button className="growTeamButton growTeamPrimary" type="submit" disabled={working}>{working?'Publishing…':'Publish collaboration need'}</button><button className="growTeamButton" type="button" onClick={()=>setShowForm(false)} disabled={working}>Cancel</button></div></form>}
  <div className="growTeamStatus" aria-live="polite">{status}</div>
  <style jsx>{`.growTeamRoot{display:grid;gap:14px}.growTeamState{display:grid;gap:4px;padding:13px 14px;border:1px solid var(--line);border-radius:12px;background:var(--paper)}.growTeamState strong{font-size:.78rem;letter-spacing:.04em;text-transform:uppercase}.growTeamState span,.growTeamState small,.growTeamHint,.growTeamNotice,.growTeamStatus{color:var(--slate);line-height:1.45}.growTeamState small{font-weight:700}.growTeamActions,.growTeamSecondary{display:flex;gap:9px;flex-wrap:wrap;align-items:center}.growTeamButton{min-height:44px;display:inline-flex;align-items:center;justify-content:center;padding:10px 13px;border:1px solid var(--ink);border-radius:10px;background:var(--white);color:var(--ink);font:inherit;font-size:.78rem;font-weight:800;cursor:pointer;text-decoration:none}.growTeamButton:focus-visible{outline:3px solid #173f8f;outline-offset:3px}.growTeamButton:disabled,.growTeamDisabled{opacity:.5;cursor:not-allowed}.growTeamPrimary{background:var(--ink);color:var(--white)}.growTeamDanger{border-color:#7d2929;color:#7d2929}.growTeamHint,.growTeamNotice{margin:0;font-size:.75rem;max-width:760px}.growTeamForm{display:grid;grid-template-columns:1fr 1fr;gap:12px;padding:14px;border:1px solid var(--line);border-radius:12px;background:var(--white)}.growTeamForm label{display:grid;gap:6px;font-size:.74rem;font-weight:800}.growTeamForm input,.growTeamForm textarea{width:100%;min-width:0;border:1px solid #cfc7ba;border-radius:9px;padding:10px 11px;background:var(--paper);color:var(--ink);font:inherit}.growTeamWide,.growTeamFormActions{grid-column:1/-1}.growTeamFormActions{display:flex;gap:8px;flex-wrap:wrap}.growTeamStatus{min-height:20px;font-size:.78rem}@media(max-width:640px){.growTeamActions,.growTeamSecondary,.growTeamForm{display:grid;grid-template-columns:1fr}.growTeamButton{width:100%}.growTeamWide,.growTeamFormActions{grid-column:1}.growTeamFormActions{display:grid}.growTeamHint{max-width:none}}`}</style>
 </div>;
}
