'use client';

import {useState} from 'react';

type Props={opportunityId:string;initialEnabled:boolean};
export default function SavedOpportunityReminderToggle({opportunityId,initialEnabled}:Props){
 const [enabled,setEnabled]=useState(initialEnabled);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 async function change(next:boolean){const previous=enabled;setEnabled(next);setBusy(true);setMessage('');try{const response=await fetch('/api/opportunities/saved',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({opportunity_id:opportunityId,reminders_enabled:next})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Unable to update reminder preference.');setEnabled(Boolean(body.reminders_enabled));setMessage(body.message||'Reminder preference updated.')}catch(error){setEnabled(previous);setMessage(error instanceof Error?error.message:'Unable to update reminder preference.')}finally{setBusy(false)}}
 return <div className="savedReminder"><label><input type="checkbox" checked={enabled} disabled={busy} onChange={event=>void change(event.target.checked)}/><span><strong>Deadline reminder</strong><small>{enabled?'On · notify me when this saved role is nearing its closing date':'Off · do not send deadline reminders for this role'}</small></span></label>{message&&<small className="savedReminderStatus" role="status" aria-live="polite">{message}</small>}<style jsx>{`.savedReminder{display:grid;gap:5px}.savedReminder label{display:flex;align-items:flex-start;gap:10px;min-height:44px;padding:9px 10px;border:1px solid var(--ui-line,#e5e8ed);border-radius:10px;background:#fff;cursor:pointer}.savedReminder input{width:20px;height:20px;flex:none;margin-top:1px}.savedReminder span{display:grid;gap:2px}.savedReminder strong{font-size:.76rem}.savedReminder small{color:#626c78;font-size:.69rem;line-height:1.4}.savedReminderStatus{color:#4d5866;font-size:.7rem}@media (min-width:481px) and (max-width:1024px){.savedReminder label{padding:10px 12px}}@media(max-width:480px){.savedReminder label{width:100%;box-sizing:border-box;min-height:46px}}`}</style></div>
}
