'use client';

import {useState} from 'react';

const labels:Record<string,string>={todo:'To do',in_progress:'In progress',blocked:'Blocked',ready_for_review:'Ready for review',done:'Done'};
const optionsByStatus:Record<string,string[]>={todo:['todo','in_progress','blocked'],in_progress:['in_progress','blocked','ready_for_review'],blocked:['blocked','in_progress'],ready_for_review:['ready_for_review','in_progress','done'],done:['done']};
type Activity={id:string;event_type:string;from_status:string|null;to_status:string|null;comment:string|null;evidence_url:string|null;created_at:string;actor_name:string};

export default function TaskStatusControl({taskId,initialStatus}:{taskId:string;initialStatus:string}){
 const normalised=initialStatus==='review'?'ready_for_review':initialStatus;const [status,setStatus]=useState(normalised);const [selected,setSelected]=useState(normalised);const [blockerReason,setBlockerReason]=useState('');const [reviewComment,setReviewComment]=useState('');const [working,setWorking]=useState(false);const [message,setMessage]=useState('');const [activity,setActivity]=useState<Activity[]|null>(null);const [activityOpen,setActivityOpen]=useState(false);const needsBlocker=selected==='blocked'&&status!=='blocked';const needsReviewComment=status==='ready_for_review'&&selected==='in_progress';const controlId=`task-status-${taskId}`,blockerId=`task-blocker-${taskId}`,reviewId=`task-review-${taskId}`;
 async function update(next:string){setWorking(true);setMessage('');try{const response=await fetch('/api/project-delivery',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({task_id:taskId,status:next,blocker_reason:next==='blocked'?blockerReason:undefined,review_comment:status==='ready_for_review'&&next==='in_progress'?reviewComment:undefined})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Unable to update task.');setStatus(next);setSelected(next);setBlockerReason('');setReviewComment('');setMessage(`Task status changed to ${labels[next]||next}.`);setActivity(null)}catch(error){setSelected(status);setMessage(error instanceof Error?error.message:'Unable to update task.')}finally{setWorking(false)}}
 function choose(next:string){setSelected(next);setMessage('');const requiresInput=(next==='blocked'&&status!=='blocked')||(status==='ready_for_review'&&next==='in_progress');if(next!==status&&!requiresInput)void update(next)}
 async function toggleActivity(){const next=!activityOpen;setActivityOpen(next);if(!next||activity)return;setMessage('Loading task activity…');try{const response=await fetch(`/api/project-task-history?task_id=${encodeURIComponent(taskId)}`,{cache:'no-store'});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Unable to load task activity.');setActivity(body.items||[]);setMessage('')}catch(error){setMessage(error instanceof Error?error.message:'Unable to load task activity.')}}
 return <div className="taskStatusControl">
  <label htmlFor={controlId}><strong>Status</strong></label><select id={controlId} value={selected} disabled={working||status==='done'} onChange={event=>choose(event.target.value)}>{(optionsByStatus[status]||[status]).map(value=><option key={value} value={value}>{labels[value]||value}</option>)}</select>
  {needsBlocker&&<div className="taskStatusFollowup"><label htmlFor={blockerId}><strong>Why is this task blocked?</strong></label><textarea id={blockerId} value={blockerReason} onChange={event=>setBlockerReason(event.target.value)} rows={3} required maxLength={1500} aria-describedby={`${blockerId}-help`}/><small id={`${blockerId}-help`}>Explain what is preventing progress so the Project Lead can intervene.</small><button type="button" disabled={working||!blockerReason.trim()} onClick={()=>update('blocked')}>Mark task blocked</button></div>}
  {needsReviewComment&&<div className="taskStatusFollowup"><label htmlFor={reviewId}><strong>What needs to change?</strong></label><textarea id={reviewId} value={reviewComment} onChange={event=>setReviewComment(event.target.value)} rows={3} required maxLength={1500}/><button type="button" disabled={working||!reviewComment.trim()} onClick={()=>update('in_progress')}>Request changes</button></div>}
  {status==='ready_for_review'&&selected==='ready_for_review'&&<small>Project Leads can approve this task or request changes.</small>}
  <button type="button" className="linkButton" aria-expanded={activityOpen} onClick={()=>void toggleActivity()}>{activityOpen?'Hide activity':'View activity'}</button>
  {activityOpen&&<div className="taskActivity" aria-label="Task activity timeline">{activity===null?<small>Loading activity…</small>:activity.length?activity.map(item=><div className="taskActivityItem" key={item.id}><strong>{item.event_type.replaceAll('_',' ')}</strong><small>{item.actor_name} · {new Date(item.created_at).toLocaleString('en-GB')}</small>{item.from_status&&item.to_status&&<small>{labels[item.from_status]||item.from_status} → {labels[item.to_status]||item.to_status}</small>}{item.comment&&<p>{item.comment}</p>}{item.evidence_url&&<a href={item.evidence_url} target="_blank" rel="noopener noreferrer">Open evidence</a>}</div>):<small>No recorded task activity yet.</small>}</div>}
  {message&&<p role="status" aria-live="polite">{message}</p>}
 </div>;
}
