import type { Metadata } from 'next';
export const metadata: Metadata = { title:'Contribution Activity', description:'How Mettelo surfaces meaningful contribution without a vanity leaderboard.' };

export default function ActivityPage(){
 const signals=[['Verified project delivery','Completed work accepted through project QA and linked to a clear role.'],['Leadership contribution','Project leadership, mentoring, review, facilitation and useful coordination.'],['Open-source value','Reusable code, documentation, datasets, issue resolution and technical review.'],['Community contribution','Helpful support, knowledge sharing and actions that create measurable value for others.']];
 return <>
 <section className="hero"><div className="shell heroGrid"><div><div className="eyebrow">Contribution Activity</div><h1>Recognise useful work without turning Mettelo into a popularity contest.</h1><p className="heroLead">Activity should help members discover what is being built and recognise consistent contribution. It should not rank people by message volume, likes or superficial engagement.</p></div><aside className="heroPanel"><span className="chip">DESIGN RULE</span><h3 style={{marginTop:18}}>Evidence before points.</h3><p>Any future reputation score should be explainable through verified activity, quality and role-specific contribution — not opaque gamification.</p></aside></div></section>
 <section className="section"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">Signals that matter</div><h2>Contribution can be visible without becoming competitive noise.</h2></div></div><div className="grid4">{signals.map(([t,c])=><article className="card" key={t}><h3>{t}</h3><p>{c}</p></article>)}</div></div></section>
 <section className="section softSection"><div className="shell"><div className="panel"><div className="panelHead"><h3>Example ecosystem activity</h3><span className="chip green">VERIFIED ACTIVITY</span></div><div className="listRow"><div><strong>Project milestone completed</strong><br/><small>Open Data Quality Monitor · QA approved</small></div><span>Project team</span></div><div className="listRow"><div><strong>Mentor office hours delivered</strong><br/><small>Technical Review · 12 members supported</small></div><span>Mentoring</span></div><div className="listRow"><div><strong>Reusable documentation merged</strong><br/><small>Contributor guide · Mettelo GitHub</small></div><span>Open source</span></div></div></div></section>
 </>;
}
