import {createServerSupabaseClient} from '@/lib/supabase/server';
import {normalizeCareerRole,normalizeCapability} from '@/lib/project-catalogue-taxonomy';

const PROJECT_STATUSES=['pilot','recruiting','open','forming','active','review','completed'];
const SCALARS='id,slug,title,summary,status,project_type,location,location_type,difficulty_level,team_size_threshold,duration_weeks,weekly_commitment,application_deadline,applications_open,created_at';
const PRIMARY_SELECT=`${SCALARS},project_roles(id,title,canonical_role_key,skills,openings),project_role_families(project_role_catalogue(slug,title)),project_capabilities(capabilities(id,slug,name)),project_domains(domains(slug,name)),project_tools(tools(slug,name)),project_methods(methods(slug,name))`;
const CORE_FACET_SELECT=`${SCALARS},project_roles(id,title,canonical_role_key,skills,openings),project_capabilities(capabilities(id,slug,name)),project_domains(domains(slug,name)),project_tools(tools(slug,name)),project_methods(methods(slug,name))`;
const MINIMAL_SELECT=`${SCALARS},project_roles(id,title,canonical_role_key,skills,openings)`;
const DISCOVER_BATCH_SIZE=200;

type MemberServerDb=Awaited<ReturnType<typeof createServerSupabaseClient>>;
type RoleRow={title?:string|null;canonical_role_key?:string|null;skills?:string[]|null};
type ProjectRow=Record<string,unknown>&{project_roles?:RoleRow[]|null;project_role_families?:unknown[]|null;project_capabilities?:unknown[]|null};
function projectQuery(db:MemberServerDb,select:string,from:number,to:number){return db.from('projects').select(select).in('visibility',['public','members']).in('status',PROJECT_STATUSES).order('created_at',{ascending:false}).order('id',{ascending:false}).range(from,to)}
async function loadAllProjectBatches(db:MemberServerDb,select:string){let from=0;const rows:unknown[]=[];let lastResult:Awaited<ReturnType<typeof projectQuery>>|null=null;while(true){const to=from+DISCOVER_BATCH_SIZE-1;const result=await projectQuery(db,select,from,to);lastResult=result;if(result.error)return result;const batch=(result.data||[]) as unknown[];rows.push(...batch);if(batch.length<DISCOVER_BATCH_SIZE)break;from+=DISCOVER_BATCH_SIZE}if(!lastResult)return projectQuery(db,select,0,DISCOVER_BATCH_SIZE-1);return{...lastResult,data:rows}}
function enrichProject(row:ProjectRow){const roles=Array.isArray(row.project_roles)?row.project_roles:[];const roleMap=new Map<string,{project_role_catalogue:{slug:string;title:string}}>();const skillMap=new Map<string,{capabilities:{id:string;slug:string;name:string}}>();for(const relation of Array.isArray(row.project_role_families)?row.project_role_families:[]){const value=(relation as {project_role_catalogue?:{slug?:string;title?:string}|null}).project_role_catalogue;const canonical=value?(normalizeCareerRole(value.slug)||normalizeCareerRole(value.title)):null;if(canonical&&!roleMap.has(canonical.slug))roleMap.set(canonical.slug,{project_role_catalogue:{slug:canonical.slug,title:canonical.label}})}for(const role of roles){const canonical=normalizeCareerRole(role.title)||normalizeCareerRole(role.canonical_role_key);if(canonical&&!roleMap.has(canonical.slug))roleMap.set(canonical.slug,{project_role_catalogue:{slug:canonical.slug,title:canonical.label}});for(const raw of Array.isArray(role.skills)?role.skills:[]){const capability=normalizeCapability(String(raw));if(capability&&!skillMap.has(capability.slug))skillMap.set(capability.slug,{capabilities:{id:`role-skill:${capability.slug}`,slug:capability.slug,name:capability.label}})}}const capabilities=Array.isArray(row.project_capabilities)?row.project_capabilities:[];return{...row,project_role_families:[...roleMap.values()],project_capabilities:capabilities.length?capabilities:[...skillMap.values()]}}
function enriched<T extends {data:unknown[]|null}>(result:T):T{return{...result,data:(result.data||[]).map(row=>enrichProject(row as ProjectRow))} as T}
export async function loadMemberDiscoverProjects(db:MemberServerDb){const primary=await loadAllProjectBatches(db,PRIMARY_SELECT);if(!primary.error)return enriched(primary);console.warn('member Discover enriched project query failed; retrying without optional role-family catalogue relation',primary.error.message);const core=await loadAllProjectBatches(db,CORE_FACET_SELECT);if(!core.error)return enriched(core);console.warn('member Discover core-facet project query failed; retrying canonical project and role fields only',core.error.message);const minimal=await loadAllProjectBatches(db,MINIMAL_SELECT);return minimal.error?minimal:enriched(minimal)}
