'use client';

import Link from 'next/link';
import SaveProjectButton from '@/components/SaveProjectButton';
import ProjectMemberCanonicalSections from '@/components/project-experience/ProjectMemberCanonicalSections';
import type {MemberProjectState} from '@/lib/member-project-journey';
import type {ProjectExperienceModel} from '@/lib/project-experience-model';
import styles from './MemberProjectDetailV2.module.css';

type Role={id:string;title:string;description:string|null;skills:string[];openings:number;remaining:number|null;available:boolean;responsibilities:string[];recommendedSkills:string[];experienceExpectation:string|null;weeklyCommitment:string|null;applicationRequirements:string|null};
type ContributionArea={slug:string;title:string;description:string|null};
type Props={model:ProjectExperienceModel;state:MemberProjectState;stateLabel:string;stateCopy:string;primaryAction:{label:string;href:string}|null;applicationReady:boolean;profileCompletion:number;applicationMissing:string[];roleAvailabilityKnown:boolean;saved:boolean;roles:Role[];contributionAreas:ContributionArea[]};

function date(value:string|null){if(!value)return'Not published';const parsed=new Date(value);if(Number.isNaN(parsed.getTime()))return'Not published';return new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric'}).format(parsed)}
function openStatus(state:MemberProjectState,deadline:string|null){if(state!=='open_eligible')return null;if(!deadline)return'Open for applications';const days=Math.ceil((new Date(deadline).getTime()-Date.now())/86400000);return days>0&&days<=7?`Closing soon · ${days} ${days===1?'day':'days'}`:'Open for applications'}
function compact(value:string,max=190){const text=value.trim();if(text.length<=max)return text;const cut=text.slice(0,max);const end=Math.max(cut.lastIndexOf('. '),cut.lastIndexOf('; '),cut.lastIndexOf(', '),cut.lastIndexOf(' '));return`${cut.slice(0,end>80?end:max).trim()}…`}

export default function MemberProjectDetailV2({model,state,stateLabel,stateCopy,primaryAction,applicationReady,profileCompletion,applicationMissing,roleAvailabilityKnown,saved,roles,contributionAreas}:Props){
 const project=model.project;
 const status=openStatus(state,project.applicationDeadline)||stateLabel;
 const action=state==='open_eligible'?{label:'Apply now',href:`/member/discover/${project.id}/apply`}:primaryAction;
 const workingModel=project.locationType?.replaceAll('_',' ')||project.location||'Project-specific';
 const availablePlaces=roleAvailabilityKnown?roles.reduce((sum,role)=>sum+(role.available?Math.max(0,role.remaining??0):0),0):null;
 const learningSignals=[...model.capabilities.technical,...model.capabilities.professional].filter((value,index,values)=>values.indexOf(value)===index).slice(0,10);
 return <div className={styles.page}>
  <a className={styles.skip} href="#member-project-main">Skip to project details</a>
  <nav className={styles.breadcrumb} aria-label="Project breadcrumb"><Link href="/member">My Mettelo</Link><span aria-hidden="true">/</span><Link href="/member/discover">Discover</Link><span aria-hidden="true">/</span><strong>{project.title}</strong></nav>
  <header className={styles.hero} aria-labelledby="member-project-title"><div className={styles.heroMain}><div className={styles.eyebrow}>MEMBER PROJECT DETAIL</div><h1 id="member-project-title">{project.title}</h1><p>{project.summary}</p><div className={styles.pills} aria-label="Project characteristics"><span className={`${styles.pill} ${state==='open_eligible'?styles.open:''}`}>{status}</span>{project.durationWeeks&&<span className={styles.pill}>{project.durationWeeks} {project.durationWeeks===1?'week':'weeks'}</span>}{project.weeklyCommitment&&<span className={styles.pill}>{project.weeklyCommitment}</span>}<span className={styles.pill}>{workingModel}</span></div></div>
   <aside className={styles.decision} aria-labelledby="member-decision-title"><div className={styles.eyebrow}>YOUR DECISION</div><h2 id="member-decision-title">{state==='open_eligible'?'Ready to contribute?':stateLabel}</h2><p>{state==='open_eligible'?'Review the project, contribution areas and commitment. Open the full specification only when you need deeper detail.':stateCopy}</p><dl className={styles.meta}><div><dt>Duration</dt><dd>{project.durationWeeks?`${project.durationWeeks} ${project.durationWeeks===1?'week':'weeks'}`:'Not published'}</dd></div><div><dt>Commitment</dt><dd>{project.weeklyCommitment||'Not published'}</dd></div><div><dt>Team openings</dt><dd>{availablePlaces===null?'Checking availability':`${availablePlaces} ${availablePlaces===1?'place':'places'}`}</dd></div><div><dt>Applications close</dt><dd>{date(project.applicationDeadline)}</dd></div></dl>{state==='ineligible'&&!applicationReady&&<div className={styles.readiness} role="status"><strong>{applicationMissing.length} profile requirement{applicationMissing.length===1?'':'s'} remaining</strong><span>Profile completion: {profileCompletion}%</span></div>}{action&&<Link className={styles.primaryButton} href={action.href}>{action.label}</Link>}<div className="pdv2SaveUtility"><SaveProjectButton projectId={project.id} initialSaved={saved}/></div>{state==='ineligible'&&!applicationReady&&<Link className={styles.secondaryButton} href={`/member/profile?next=${encodeURIComponent(`/member/discover/${project.id}`)}`}>Complete profile requirements</Link>}</aside>
  </header>
  <div id="member-project-main" className={`${styles.layout} pdv2Layout`}><div className={styles.content}><ProjectMemberCanonicalSections model={model}/>
   <section className="pdv2Section" id="roles" aria-labelledby="member-roles-heading"><div className="pdv2Eyebrow">08 · CONTRIBUTION AREAS</div><h2 id="member-roles-heading">Where you can contribute</h2><p>Each role owns a distinct part of the project. Use the short ownership statement to compare fit; expand a role only when you want the full responsibility detail.</p>
    {contributionAreas.length?<div className="pdv2RoleGrid pdv2RoleGridInformational">{contributionAreas.map(area=><article className="pdv2Role pdv2RoleInformational" key={area.slug}><div className="pdv2RoleTop"><div><h3>{area.title}</h3><p>{area.description||'A project-specific contribution area used to organise ownership, collaboration and delivery across the team.'}</p></div><span className="pdv2RoleStatus">Contribution area</span></div></article>)}</div>:roles.length?<div className="pdv2RoleGrid pdv2RoleGridInformational">{roles.map(role=>{const ownership=role.responsibilities[0]||role.description||`${role.title} owns a defined project workstream and the evidence produced from it.`;return <article className="pdv2Role pdv2RoleInformational" key={role.id}><div className="pdv2RoleTop"><div><h3>{role.title}</h3><p>{compact(ownership)}</p></div><span className="pdv2RoleStatus">{role.available?'Open':'At capacity'}</span></div>{role.skills.length>0&&<div className="pdv2Pills">{role.skills.slice(0,4).map(skill=><span className="pdv2Pill" key={skill}>{skill}</span>)}</div>}{role.remaining!==null&&<div className="pdv2RoleMeta"><span>{role.remaining} of {role.openings} place{role.openings===1?'':'s'} remaining</span></div>}{(role.responsibilities.length>1||role.recommendedSkills.length>0||role.experienceExpectation||role.weeklyCommitment||role.applicationRequirements)&&<details className="pdv2Disclosure"><summary>View role responsibilities</summary><div className="pdv2DisclosureBody">{role.responsibilities.length>0&&<><h3>Responsibilities</h3><ul>{role.responsibilities.map(item=><li key={item}>{item}</li>)}</ul></>}{role.experienceExpectation&&<><h3>Experience expectation</h3><p>{role.experienceExpectation}</p></>}{role.weeklyCommitment&&<p><strong>Role commitment:</strong> {role.weeklyCommitment}</p>}{role.recommendedSkills.length>0&&<><h3>Recommended skills</h3><div className="pdv2Pills">{role.recommendedSkills.slice(0,8).map(skill=><span className="pdv2Pill" key={skill}>{skill}</span>)}</div></>}{role.applicationRequirements&&<><h3>Application requirement</h3><p>{role.applicationRequirements}</p></>}</div></details>}</article>})}</div>:<div className="pdv2Empty" role="status"><strong>Contribution areas are still being prepared.</strong><span>You can review the project brief now. Mettelo will not invent roles that have not been published for this project.</span></div>}
    {learningSignals.length>0&&<div className="pdv2LearningBand"><div><span className="pdv2Eyebrow">CAPABILITIES IN PRACTICE</span><strong>Areas this project can help you practise and demonstrate</strong></div><div className="pdv2LearningChips">{learningSignals.map(signal=><span key={signal}>{signal}</span>)}</div></div>}
   </section>
   <section className="pdv2Section" aria-labelledby="member-next-heading"><div className="pdv2Eyebrow">09 · WHAT HAPPENS NEXT</div><h2 id="member-next-heading">Your project journey</h2><div className="pdv2Timeline"><div><span>1</span><p><strong>Review the project</strong>Understand the challenge, outcome, commitment and quality bar.</p></div><div><span>2</span><p><strong>Compare contribution areas</strong>Choose where your current capability can add the most value.</p></div><div><span>3</span><p><strong>Apply from one form</strong>Confirm your preferred contribution area and what you could bring.</p></div><div><span>4</span><p><strong>Track the decision</strong>Your status and next action remain visible in My Mettelo.</p></div><div><span>5</span><p><strong>Deliver in Mettelo Lab</strong>Accepted members move into the authorised workspace with the same canonical project definition.</p></div></div></section>
  </div></div>
  {state==='open_eligible'&&<div className={styles.mobileCta}><div><strong>Ready to contribute?</strong><span>{project.weeklyCommitment||'Review the commitment before applying'}</span></div><Link className={styles.primaryButton} href={`/member/discover/${project.id}/apply`}>Apply now</Link></div>}
 </div>
}
