import type { Metadata } from 'next';

export const metadata:Metadata={title:'Events',description:'Mettelo events bring Data & AI professionals together for practical conversations, project showcases, workshops and build sessions.'};

export default function EventsPage(){return <>
<section className="hero"><div className="shell heroGrid"><div><div className="eyebrow">Mettelo Events</div><h1>Meet the people. Learn the context. Show the work.</h1><p className="heroLead">Mettelo events are built around practitioner reality: AMAs, workshops, project showcases, build sessions and focused professional conversations.</p><div className="actions"><a className="button dark" href="/newsletter">Get event alerts →</a></div></div><aside className="heroPanel"><span className="chip">LAUNCH STATE</span><h3 style={{marginTop:18}}>Next public dates are being confirmed.</h3><p>We are not showing placeholder registration buttons as live events. Confirmed sessions will publish with a real registration destination and clear timezone.</p><div className="path"><span>Publish</span><span>Register</span><span>Attend</span><span>Replay</span><span>Resources</span></div></aside></div></section>
<section className="section"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">Event formats</div><h2>Every format has a job.</h2></div><p>Events should create connection, context or proof — not fill a calendar for the sake of activity.</p></div><div className="grid4"><article className="card"><span className="chip">AMA</span><h3 style={{marginTop:18}}>Career reality</h3><p>Applications, interviews, progression, role expectations and honest practitioner Q&A.</p></article><article className="card"><span className="chip">WORKSHOP</span><h3 style={{marginTop:18}}>Practical capability</h3><p>Focused sessions on real workflows, communication, delivery and technical practice.</p></article><article className="card"><span className="chip">SHOWCASE</span><h3 style={{marginTop:18}}>Project proof</h3><p>Teams explain what they built, the decisions they made and what each contributor owned.</p></article><article className="card"><span className="chip">BUILD</span><h3 style={{marginTop:18}}>Working sessions</h3><p>Short build sprints, open-source orientations and collaborative problem-solving.</p></article></div></div></section>
<section className="section softSection"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">After the event</div><h2>A useful session should keep creating value.</h2></div><p>Where permission allows, event pages can retain replay, resources, speaker context and related project or member links.</p></div><div className="grid3"><article className="card"><h3>Replay</h3><p>Attach the recording only when a real video exists and publication permission is clear.</p></article><article className="card"><h3>Resources</h3><p>Keep slides, references, templates and follow-up material near the event context.</p></article><article className="card"><h3>Next action</h3><p>Connect a session to the relevant community route, Labs brief, article or contribution pathway.</p></article></div></div></section>
<section className="section compact"><div className="shell"><div className="ctaBand"><div><div className="cardNumber">SPEAK · HOST · PARTNER</div><h2>Have a session that would be useful to serious Data & AI professionals?</h2><p>Bring a practitioner topic, project showcase or partnership idea with a clear audience and outcome.</p></div><div className="actions"><a className="button dark" href="/contact">Propose an event →</a></div></div></div></section>
</>}
