import {redirect} from 'next/navigation';
import Link from 'next/link';
import {createServerSupabaseClient} from '@/lib/supabase/server';
import ContributionForm from '@/components/ContributionForm';
import SocialShare from '@/components/SocialShare';
import ProofVisibilityControl from '@/components/ProofVisibilityControl';

export const dynamic='force-dynamic';
type Contribution={id:string;title:string;contribution_type:string;verification_status:string;created_at:string;verified_at:string|null;evidence_url:string|null;review_notes:string|null;visibility:string;visibility_reviewed_at:string|null;projects:{title:string}|null};
type Membership={project_id:string;membership_status:string;projects:{title:string;status:string}|null};
type Credential={credential_id:string;status:string;issued_at:string};
const statusCopy:Record<string,string>={pending:'Under review',needs_changes:'Changes requested',verified:'Verified',rejected:'Not verified'};
const visibilityCopy:Record<string,string>={public:'Public',mettelo_only:'Mettelo only',private:'Private'};

export default async function ProofPage(){
  const supabase=await createServerSupabaseClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/signin');
  const [contributionResult,membershipResult,credentialResult]=await Promise.all([
    supabase.from('contributions').select('id,title,contribution_type,verification_status,created_at,verified_at,evidence_url,review_notes,visibility,visibility_reviewed_at,projects(title)').eq('user_id',user.id).order('created_at',{ascending:false}),
    supabase.from('project_members').select('project_id,membership_status,projects(title,status)').eq('user_id',user.id).in('membership_status',['active','completed']),
    supabase.from('project_architect_credentials').select('credential_id,status,issued_at').eq('user_id',user.id).order('issued_at',{ascending:false}).limit(1).maybeSingle()
  ]);
  const contributions=(contributionResult.data||[]) as unknown as Contribution[];const memberships=(membershipResult.data||[]) as unknown as Membership[];const credential=(credentialResult.data||null) as Credential|null;const projects=memberships.map(x=>({id:x.project_id,title:x.projects?.title||'Mettelo project'}));const verified=contributions.filter(x=>x.verification_status==='verified').length;const pending=contributions.filter(x=>['pending','needs_changes'].includes(x.verification_status)).length;
  return <section className="section softSection memberWorkspace"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">My work · Proof & credentials</div><h1>Evidence you control.</h1></div><p>Verification confirms what Mettelo reviewed. Visibility is a separate choice: keep Proof private, show it inside Mettelo, or make it public and shareable.</p></div>
  <div className="metricGrid"><div className="metric"><strong>{verified}</strong><span>Verified</span></div><div className="metric"><strong>{pending}</strong><span>In review</span></div><div className="metric"><strong>{contributions.length}</strong><span>Total contributions</span></div></div>
  {credential&&<section className="panel" style={{marginTop:18}} aria-labelledby="credential-title"><div className="panelHead"><div><span className="cardNumber">CREDENTIAL</span><h2 id="credential-title" style={{marginTop:8}}>Mettelo Data &amp; AI Project Architect</h2></div><span className={`chip ${credential.status==='active'?'green':''}`}>{credential.status.toUpperCase()}</span></div><p>Your credential has its own verification page and status. It does not depend on making every individual Proof item public.</p><div className="metaRow"><span className="metaPill">Issued {new Date(credential.issued_at).toLocaleDateString('en-GB',{dateStyle:'long'})}</span><span className="metaPill">ID {credential.credential_id}</span></div><div className="actions" style={{marginTop:14}}><Link className="button dark" href={`/credentials/${credential.credential_id}`}>Open credential verification →</Link></div></section>}
  <section className="panel" style={{marginTop:18}}><div className="panelHead"><div><span className="cardNumber">PROOF RECORD</span><h2 style={{marginTop:8}}>Your contributions</h2></div><a className="linkArrow" href="/showcase">Explore public Proof →</a></div>{contributions.length?<div className="grid3">{contributions.map(item=>{const publicProof=item.verification_status==='verified'&&item.visibility==='public';const shareText=`I have verified contribution proof on Mettelo: ${item.title}${item.projects?.title?` · ${item.projects.title}`:''}.`;const shareUrl=`https://mettelo.com/proof/${item.id}`;return <article className="card proofCard" key={item.id}><div className="proofCardTop"><span className={`chip ${item.verification_status==='verified'?'green':''}`}>{statusCopy[item.verification_status]||item.verification_status.replaceAll('_',' ')}</span>{publicProof&&<SocialShare url={shareUrl} text={shareText} label="Share this Proof"/>}</div><h3>{item.title}</h3><p>{item.projects?.title||'Mettelo contribution'} · {item.contribution_type.replaceAll('_',' ')}</p>{item.verified_at&&<p><strong>Verified:</strong> {new Date(item.verified_at).toLocaleDateString('en-GB',{dateStyle:'long'})}</p>}{item.review_notes&&<p><strong>Reviewer comments:</strong> {item.review_notes}</p>}{item.verification_status==='verified'?<><p><strong>Visibility:</strong> {visibilityCopy[item.visibility]||'Private'}</p><ProofVisibilityControl id={item.id} initialVisibility={item.visibility}/>{publicProof?<a className="linkArrow" href={`/proof/${item.id}`}>Open public Proof →</a>:<p className="panelNote">{item.visibility==='mettelo_only'?'This record is not available to anonymous visitors.':'No public Proof link is available while this record is private.'}</p>}</>:item.verification_status==='needs_changes'?<p className="panelNote"><strong>Action required.</strong> Update the requested evidence from the project workspace and resubmit.</p>:item.verification_status==='pending'?<p className="panelNote"><strong>No action required.</strong> This contribution is waiting for review.</p>:null}{item.evidence_url&&<a className="linkArrow" href={item.evidence_url} target="_blank" rel="noopener noreferrer">Evidence →</a>}</article>})}</div>:<div className="emptyState"><h3>No Proof yet.</h3><p>Complete project delivery or submit evidence from work you actually owned.</p></div>}</section>
  <section style={{marginTop:18}} id="submit"><ContributionForm projects={projects}/></section></div></section>;
}
