import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {serviceDb} from '@/lib/project-flow';

type Props={params:Promise<{credentialId:string}>};
async function record(credentialId:string){
  const db=serviceDb();if(!db)return null;
  const {data:credential}=await db.from('project_architect_credentials').select('credential_id,user_id,status,issued_at').eq('credential_id',credentialId).maybeSingle();if(!credential)return null;
  const [{data:identity},{data:profile}]=await Promise.all([db.from('account_identities').select('account_type,show_project_architect_designation').eq('user_id',credential.user_id).maybeSingle(),db.from('profiles').select('full_name,headline,avatar_url,is_public').eq('id',credential.user_id).maybeSingle()]);
  if(credential.status!=='active'||identity?.account_type!=='project_architect'||!identity.show_project_architect_designation||!profile?.is_public)return null;
  const {data:proof}=await db.from('contributions').select('id,title,contribution_type,verified_at,projects(title)').eq('user_id',credential.user_id).eq('verification_status','verified').eq('is_public',true).order('verified_at',{ascending:false}).limit(12);
  return{credential,profile,proof:proof||[]};
}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {credentialId}=await params;const data=await record(credentialId);return data?{title:`${data.profile.full_name||'Mettelo professional'} · Project Architect`,description:'Verify an evidence-backed Mettelo Data & AI Project Architect designation.'}:{title:'Credential not available'};}
export default async function CredentialPage({params}:Props){const {credentialId}=await params;const data=await record(credentialId);if(!data)notFound();const name=data.profile.full_name||'Mettelo professional';return <><section className="hero"><div className="shell heroGrid"><div><div className="eyebrow">Verified Mettelo designation</div><h1>Mettelo Data &amp; AI Project Architect.</h1><p className="heroLead">This active designation is backed by an approved evidence review and a traceable Mettelo project record.</p></div><aside className="heroPanel"><span className="chip green">ACTIVE</span><h3 style={{marginTop:18}}>{name}</h3><p>{data.profile.headline||'Data & AI professional'}</p><div className="publicProfileFact"><small>CREDENTIAL ID</small><strong>{data.credential.credential_id}</strong></div><div className="publicProfileFact"><small>ISSUED</small><strong>{new Date(data.credential.issued_at).toLocaleDateString('en-GB',{dateStyle:'long'})}</strong></div></aside></div></section><section className="section"><div className="shell"><div className="sectionHead"><div><div className="cardNumber">EVIDENCE-BACKED RECORD</div><h2>Verified work connected to the designation.</h2></div><p>This page verifies a Mettelo identity. It does not claim employment or formal professional certification.</p></div>{data.proof.length?<div className="grid3">{data.proof.map(item=>{const project=Array.isArray(item.projects)?item.projects[0]:item.projects;return <article className="card" key={item.id}><span className="chip green">VERIFIED PROOF</span><h3>{item.title}</h3><p>{project?.title||'Mettelo project'} · {item.contribution_type.replaceAll('_',' ')}</p><Link className="linkArrow" href={`/proof/${item.id}`}>Open Proof →</Link></article>})}</div>:<div className="emptyState"><h3>No public Proof selected.</h3><p>The designation remains verified through the approved application record; the member has not made individual Proof items public.</p></div>}<div className="ctaBand" style={{marginTop:28}}><div><div className="cardNumber">PUBLIC PROFILE</div><h2>See the professional context.</h2></div><Link className="button dark" href={`/people/${data.credential.user_id}`}>View {name}&apos;s profile →</Link></div></div></section></>}
