import {redirect} from 'next/navigation';
import {createClient} from '@supabase/supabase-js';
import {createServerSupabaseClient} from '@/lib/supabase/server';
import MemberApplicationTracker from '@/components/MemberApplicationTracker';

type AppEvent={id:string;application_id:string;from_status:string|null;to_status:string;created_at:string};
type Application={id:string;status:string;submitted_at:string;updated_at:string;project_id:string;project_run_id:string|null;application_kind?:string;requested_role?:string|null;projects:{title:string;status:string;project_type?:string;team_size_threshold?:number|null;forming_deadline?:string|null;kickoff_at?:string|null}|null;project_roles:{title:string}|null;formation?:{filled:number;threshold:number;status:string;is_full:boolean;kickoff_at:string|null;forming_deadline:string|null;run_number:number|null}|null;events?:AppEvent[]};
type OfferDoc={id:string;application_id:string;file_name:string;size_bytes:number;created_at:string};
type CareerApp={id:string;status:string;submitted_at:string;updated_at:string;interview_at:string|null;interview_details:string|null;offer_details:string|null;career_roles:{title:string}|null;offer_documents?:OfferDoc[]};

export const dynamic='force-dynamic';
export default async function ApplicationsPage(){
  const auth=await createServerSupabaseClient();const {data:{user}}=await auth.auth.getUser();if(!user)redirect('/signin');
  const [{data:projectData},{data:careerData}]=await Promise.all([
    auth.from('project_applications').select('id,status,submitted_at,updated_at,project_id,project_run_id,application_kind,requested_role,projects(title,status,project_type,team_size_threshold,forming_deadline,kickoff_at),project_roles(title)').eq('user_id',user.id).order('submitted_at',{ascending:false}),
    auth.from('career_applications').select('id,status,submitted_at,updated_at,interview_at,interview_details,offer_details,career_roles(title)').eq('user_id',user.id).order('submitted_at',{ascending:false})
  ]);
  const applications=(projectData||[]) as unknown as Application[];let careers=(careerData||[]) as unknown as CareerApp[];const applicationIds=applications.map(x=>x.id);const runIds=[...new Set(applications.map(x=>x.project_run_id).filter((id):id is string=>Boolean(id)))];
  const {data:eventRows}=applicationIds.length?await auth.from('project_application_events').select('id,application_id,from_status,to_status,created_at').in('application_id',applicationIds).order('created_at',{ascending:true}):{data:[] as AppEvent[]};
  const events=(eventRows||[]) as AppEvent[];
  const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;const service=url&&key?createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}):null;const formation=new Map<string,{filled:number;threshold:number;status:string;is_full:boolean;kickoff_at:string|null;forming_deadline:string|null;run_number:number|null}>();
  if(service&&runIds.length){const [{data:runs},{data:members}]=await Promise.all([service.from('project_runs').select('id,project_id,run_number,status,team_size_threshold,kickoff_at').in('id',runIds),service.from('project_members').select('project_run_id,membership_status').in('project_run_id',runIds).in('membership_status',['waiting','active'])]);for(const run of runs||[]){const app=applications.find(item=>item.project_run_id===run.id);const filled=(members||[]).filter(member=>member.project_run_id===run.id).length;const threshold=Number(run.team_size_threshold||app?.projects?.team_size_threshold||1);formation.set(run.id,{filled,threshold,status:run.status,is_full:filled>=threshold,kickoff_at:run.kickoff_at||app?.projects?.kickoff_at||null,forming_deadline:app?.projects?.forming_deadline||null,run_number:run.run_number||null})}}
  if(service&&careers.length){const careerIds=careers.map(c=>c.id);const {data:docs}=await service.from('career_offer_documents').select('id,application_id,file_name,size_bytes,created_at').in('application_id',careerIds).eq('active',true).order('created_at',{ascending:false});careers=careers.map(c=>({...c,offer_documents:(docs||[]).filter(d=>d.application_id===c.id) as OfferDoc[]}));}
  const enriched=applications.map(a=>({...a,formation:a.project_run_id?formation.get(a.project_run_id)||null:null,events:events.filter(event=>event.application_id===a.id)}));
  return <section className="section softSection memberWorkspace"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">My Mettelo · Applications</div><h1>See where your applications stand.</h1></div><p>Every project application shows what happened, when it happened, what it means, whether you need to act and what comes next.</p></div>
    <section className="panel"><div className="panelHead"><div><span className="cardNumber">PROJECTS</span><h3 style={{marginTop:8}}>Project applications</h3></div><span className="chip">{enriched.length}</span></div><MemberApplicationTracker applications={enriched}/></section>
    <section className="panel" id="careers" style={{marginTop:20}}><div className="panelHead"><div><span className="cardNumber">CAREERS</span><h3 style={{marginTop:8}}>Mettelo role applications</h3></div><span className="chip">{careers.length}</span></div>{careers.length?careers.map(item=><article className="applicationReview" key={item.id}><div className="panelHead"><div><span className="chip">{item.status.replaceAll('_',' ').toUpperCase()}</span><h3 style={{margin:'9px 0 3px'}}>{item.career_roles?.title||'Mettelo role'}</h3><small>Applied {new Date(item.submitted_at).toLocaleDateString('en-GB')}</small></div></div>{item.status==='interview'&&<p><strong>Interview:</strong> {item.interview_at?new Date(item.interview_at).toLocaleString('en-GB'):'Details coming soon.'}{item.interview_details?` ${item.interview_details}`:''}</p>}{item.status==='offer'&&item.offer_details&&<p><strong>Offer update:</strong> {item.offer_details}</p>}{item.status==='offer'&&item.offer_documents?.length?<div style={{padding:'12px 14px',border:'1px solid #e2dccf',borderRadius:10,margin:'12px 0'}}><strong>Offer documents</strong>{item.offer_documents.map(doc=><p key={doc.id} style={{margin:'8px 0 0'}}><a className="linkArrow" href={`/api/careers/offer-documents/${doc.id}`}>{doc.file_name} →</a> <small>({Math.ceil(doc.size_bytes/1024)} KB)</small></p>)}</div>:null}<p>{item.status==='submitted'?'Your application has been received.':item.status==='in_review'?'Your application is being reviewed.':item.status==='shortlisted'?'You have been shortlisted.':item.status==='interview'?'You have reached the interview stage.':item.status==='offer'?'Your offer is ready. Review the details and any secure documents above.':item.status==='hired'?'Your application is complete. Welcome to Mettelo.':item.status==='rejected'?'This application is now closed.':'We will show the next update here.'}</p></article>):<div className="emptyState"><h3>No Mettelo role applications yet.</h3><p>If you apply while signed in, your application will appear here.</p><a className="linkArrow" href="/careers">View open roles →</a></div>}</section>
  </div></section>;
}
