import {redirect} from 'next/navigation';
import {createServerSupabaseClient} from '@/lib/supabase/server';
import {serviceDb} from '@/lib/project-flow';
import MemberApplicationTracker from '@/components/MemberApplicationTracker';
import MemberPhase6AdmissionSummary from '@/components/MemberPhase6AdmissionSummary';
import MemberClarificationRequests from '@/components/MemberClarificationRequests';
import MemberPageHeader from '@/components/MemberPageHeader';

type AppEvent={id:string;application_id:string;from_status:string|null;to_status:string;created_at:string};
type Formation={filled:number;threshold:number;status:string;is_full:boolean;kickoff_at:string|null;scheduled_start_at:string|null;forming_deadline:string|null;run_number:number|null;auto_start_paused_at:string|null;auto_start_blocked_at:string|null;auto_start_failure:string|null};
type Application={id:string;status:string;submitted_at:string;updated_at:string;project_id:string;project_run_id?:string|null;application_kind?:string;requested_role?:string|null;admission_decision?:string|null;participation_preference?:string|null;reviewer_notes?:string|null;clarification_requested_at?:string|null;projects:{title:string;status:string;project_type?:string;partner_name?:string|null;team_size_threshold?:number|null;forming_deadline?:string|null;kickoff_at?:string|null}|null;project_roles:{title:string}|null;formation?:Formation|null;events?:AppEvent[]};

type ProjectQueryError={code?:string;message?:string}|null;

export const dynamic='force-dynamic';

function isHistoricalProjectApplicationColumnError(error:ProjectQueryError){if(!error||error.code!=='42703')return false;return /project_applications\.(application_kind|requested_role|project_run_id|admission_decision|participation_preference|reviewer_notes|clarification_requested_at)|column ["']?(application_kind|requested_role|project_run_id|admission_decision|participation_preference|reviewer_notes|clarification_requested_at)["']?/i.test(error.message||'')}

export default async function ApplicationsPage(){
  const auth=await createServerSupabaseClient();const {data:{user}}=await auth.auth.getUser();if(!user)redirect('/signin?next=/member/applications');
  const primary=await auth.from('project_applications').select('id,status,submitted_at,updated_at,project_id,project_run_id,application_kind,requested_role,admission_decision,participation_preference,reviewer_notes,clarification_requested_at,projects(title,status,project_type,partner_name,team_size_threshold,forming_deadline,kickoff_at)').eq('user_id',user.id).order('submitted_at',{ascending:false});
  let projectData:unknown=primary.data;let error:ProjectQueryError=primary.error;
  if(isHistoricalProjectApplicationColumnError(error)){
    const fallback=await auth.from('project_applications').select('id,status,submitted_at,updated_at,project_id,project_run_id,application_kind,requested_role,projects(title,status,project_type,team_size_threshold,forming_deadline,kickoff_at)').eq('user_id',user.id).order('submitted_at',{ascending:false});projectData=fallback.data;error=fallback.error
  }
  if(error)console.error('member project requests query failed',error);
  const applications=(projectData||[]) as unknown as Application[];const applicationIds=applications.map(item=>item.id);const runIds=[...new Set(applications.map(item=>item.project_run_id).filter((id):id is string=>Boolean(id)))];
  const {data:eventRows}=applicationIds.length?await auth.from('project_application_events').select('id,application_id,from_status,to_status,created_at').in('application_id',applicationIds).order('created_at',{ascending:true}):{data:[] as AppEvent[]};const events=(eventRows||[]) as AppEvent[];
  const formation=new Map<string,Formation>();const service=serviceDb();if(service&&runIds.length){const [{data:runs},{data:members}]=await Promise.all([service.from('project_runs').select('id,project_id,run_number,status,team_size_threshold,required_team_size,kickoff_at,scheduled_start_at,auto_start_paused_at,auto_start_blocked_at,auto_start_failure').in('id',runIds),service.from('project_members').select('project_run_id,membership_status').in('project_run_id',runIds).in('membership_status',['waiting','active'])]);for(const run of runs||[]){const app=applications.find(item=>item.project_run_id===run.id);const filled=(members||[]).filter(member=>member.project_run_id===run.id).length;const threshold=Number(run.required_team_size||run.team_size_threshold||app?.projects?.team_size_threshold||1);formation.set(run.id,{filled,threshold,status:run.status,is_full:filled>=threshold,kickoff_at:run.kickoff_at||app?.projects?.kickoff_at||null,scheduled_start_at:run.scheduled_start_at||null,forming_deadline:app?.projects?.forming_deadline||null,run_number:run.run_number||null,auto_start_paused_at:run.auto_start_paused_at||null,auto_start_blocked_at:run.auto_start_blocked_at||null,auto_start_failure:run.auto_start_failure||null})}}
  const enriched=applications.map(item=>({...item,formation:item.project_run_id?formation.get(item.project_run_id)||null:null,events:events.filter(event=>event.application_id===item.id)}));
  const clarifications=enriched.filter(item=>item.status==='clarification_requested').map(item=>({id:item.id,projectTitle:item.projects?.title||'Mettelo project',projectType:item.projects?.project_type||null,partnerName:item.projects?.partner_name||null,reviewerNotes:item.reviewer_notes||null,requestedAt:item.clarification_requested_at||item.updated_at}));
  return <div className="applicationsPage"><MemberPageHeader eyebrow="MY WORK · PROJECT REQUESTS" title="Applications" titleId="applications-title" description="Track project interests, automatic project entry, governed review, clarification requests, team formation and confirmed project work from one canonical request history." actions={<><a className="applicationsButton applicationsButtonDark" href="/member/discover">Discover projects</a><a className="applicationsButton" href="/member/recommended">Recommended</a></>}/>{error?<section className="applicationsError" role="alert"><h2>We couldn’t load your project requests</h2><p>Refresh the page to try again. Your project data has not been changed.</p></section>:<><MemberClarificationRequests items={clarifications}/><MemberPhase6AdmissionSummary items={enriched}/><MemberApplicationTracker applications={enriched}/></>}<style>{`.applicationsPage{width:min(100%,1240px);margin:0;min-width:0;color:#111318}.applicationsButton{min-height:44px;padding:0 15px;border:1px solid #b8c0c9;border-radius:10px;background:#fff;color:#111318;display:inline-flex;align-items:center;justify-content:center;text-decoration:none;font-size:13px;font-weight:800}.applicationsButtonDark{background:#111318;border-color:#111318;color:#fff}.applicationsButton:focus-visible{outline:3px solid #173f8f;outline-offset:3px}.applicationsError{margin-top:20px;padding:20px;border:1px solid #d0a0a0;border-radius:14px;background:#fff}.applicationsError h2{margin:0 0 6px;font-size:1.1rem}.applicationsError p{margin:0;color:#59636f}@media(max-width:480px){.applicationsButton{font-size:13px}}`}</style></div>;
}
