import {redirect} from 'next/navigation';
import {createServerSupabaseClient} from '@/lib/supabase/server';
import MemberProfileSection from '@/components/MemberProfileSection';
import ProfileReturnAfterSave from '@/components/ProfileReturnAfterSave';

export const dynamic='force-dynamic';
type TaxonomyItem={slug:string;name:string};
type PrefRow<T>={domains?:T|null;tools?:T|null};
export default async function ProfilePage(){
  const supabase=await createServerSupabaseClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/signin');
  const [profileResult,domainsResult,toolsResult,domainPrefsResult,toolPrefsResult]=await Promise.all([
    supabase.from('profiles').select('*').eq('id',user.id).single(),supabase.from('domains').select('slug,name').eq('is_active',true).order('sort_order'),supabase.from('tools').select('slug,name').eq('is_active',true).order('sort_order'),supabase.from('profile_domain_preferences').select('domains(slug,name)').eq('user_id',user.id),supabase.from('profile_tool_preferences').select('tools(slug,name)').eq('user_id',user.id)
  ]);
  const profile=profileResult.data||{full_name:user.user_metadata?.full_name||'',headline:'',bio:'',location:'',professional_area:'',primary_goal:'',linkedin_url:'',github_url:'',portfolio_url:'',avatar_url:null,skills:[],preferred_roles:[],languages:[],is_public:false,current_job_title:'',organisation:'',experience_level:'',employment_status:'',project_availability:'',weekly_capacity:''};
  const domains=(domainsResult.data||[]) as TaxonomyItem[];const tools=(toolsResult.data||[]) as TaxonomyItem[];
  const domainPreferences=((domainPrefsResult.data||[]) as unknown as PrefRow<TaxonomyItem>[]).map(row=>row.domains?.slug).filter((v):v is string=>Boolean(v));const toolPreferences=((toolPrefsResult.data||[]) as unknown as PrefRow<TaxonomyItem>[]).map(row=>row.tools?.slug).filter((v):v is string=>Boolean(v));
  return <section className="section softSection memberWorkspace"><ProfileReturnAfterSave/><div className="shell"><div className="sectionHead"><div><div className="eyebrow">My profile</div><h1>Build your professional profile.</h1></div><p>Add your experience, skills, interests and availability so Mettelo can understand your professional context and help connect you with relevant project work. Your profile describes your background; Mettelo Proof separately shows evidence from project contributions that have completed review.</p></div><div className="profilePurpose" role="note" aria-label="How your profile is used"><div><strong>Better project matches</strong><span>Skills and interests help us show more relevant work.</span></div><div><strong>Faster applications</strong><span>A complete profile means less information to repeat when you apply.</span></div><div><strong>Build on demonstrated work</strong><span>Use your Profile and Mettelo Proof together as you take on new project work, broader responsibility or leadership opportunities where available.</span></div></div><MemberProfileSection userId={user.id} profile={profile} domains={domains} tools={tools} domainPreferences={domainPreferences} toolPreferences={toolPreferences}/></div><style>{`.profilePurpose{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin:0 0 20px}.profilePurpose>div{display:grid;gap:5px;padding:15px 16px;border:1px solid rgba(16,19,29,.08);border-radius:14px;background:#fff}.profilePurpose strong{font-size:.8rem}.profilePurpose span{color:#68717e;font-size:.72rem;line-height:1.5}@media(max-width:760px){.profilePurpose{grid-template-columns:1fr}.profilePurpose>div{padding:14px}}`}</style></section>;
}
