import {notFound} from 'next/navigation';
import {createPublicSupabaseClient} from '@/lib/supabase/public';
import {createServerSupabaseClient} from '@/lib/supabase/server';
import ProjectApplicationForm from '@/components/ProjectApplicationForm';
import SubmissionForm from '@/components/SubmissionForm';

export const dynamic='force-dynamic';
type Role={id:string;title:string;description:string|null;skills:string[];openings:number;discipline:string|null};
type TaxonomyRef={slug:string;name:string};
type Project={id:string;title:string;summary:string;problem_statement:string|null;status:string;project_type:string;partner_name:string|null;location:string|null;location_type:string|null;difficulty_level:string|null;duration_weeks:number|null;weekly_commitment:string|null;application_deadline:string|null;team_size_threshold:number|null;forming_deadline:string|null;kickoff_at:string|null;project_roles?:Role[];project_domains?:{is_primary:boolean;domains:TaxonomyRef|null}[];project_tools?:{tools:TaxonomyRef|null}[];project_methods?:{methods:TaxonomyRef|null}[]};
function titleCase(value:string){return value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function statusLabel(status:string){return status==='recruiting'||status==='open'?'Open':status==='forming'?'Team forming':status==='active'?'Active':status==='review'?'In review':status==='completed'?'Completed':titleCase(status)}

export default async function ProjectDetailPage({params}:{params:Promise<{id:string}>}){
  const {id}=await params;const publicDb=createPublicSupabaseClient();if(!publicDb)notFound();
  const {data,error}=await publicDb.from('projects').select('id,title,summary,problem_statement,status,project_type,partner_name,location,location_type,difficulty_level,duration_weeks,weekly_commitment,application_deadline,team_size_threshold,forming_deadline,kickoff_at,project_roles(id,title,description,skills,openings,discipline),project_domains(is_primary,domains(slug,name)),project_tools(tools(slug,name)),project_methods(methods(slug,name))').eq('id',id).eq('visibility','public').single();
  if(error||!data)notFound();const project=data as unknown as Project;
  const auth=await createServerSupabaseClient();const {data:{user}}=await auth.auth.getUser();
  const profileMissing:string[]=[];
  if(user){const {data:profile}=await auth.from('profiles').select('skills,project_availability,weekly_capacity,preferred_roles,headline,current_job_title,professional_area').eq('id',user.id).maybeSingle();if(!profile?.skills?.length||profile.skills.length<3)profileMissing.push('At least 3 core skills');if(!profile?.project_availability)profileMissing.push('Project availability');if(!profile?.weekly_capacity?.trim())profileMissing.push('Weekly collaboration capacity');if(!profile?.preferred_roles?.length&&!profile?.headline&&!profile?.current_job_title&&!profile?.professional_area)profileMissing.push('Professional role or headline');}
  const roles=project.project_roles||[];const isPilot=project.status==='pilot';const statusAccepting=project.project_type==='open'?!['pilot','completed','archived','cancelled'].includes(project.status):['recruiting','open','forming'].includes(project.status);const deadline=project.application_deadline?new Date(project.application_deadline):null;const deadlinePassed=deadline?deadline.getTime()<Date.now():false;const canApply=statusAccepting&&!deadlinePassed&&roles.length>0;const displayStatus=canApply?'Applications open':statusAccepting&&roles.length===0?'Roles pending':deadlinePassed&&statusAccepting?'Applications closed':statusLabel(project.status);
  const domains=(project.project_domains||[]).map(x=>x.domains).filter(Boolean) as TaxonomyRef[];const tools=(project.project_tools||[]).map(x=>x.tools).filter(Boolean) as TaxonomyRef[];const methods=(project.project_methods||[]).map(x=>x.methods).filter(Boolean) as TaxonomyRef[];
  const applicationProjects=[{id:project.id,title:project.title,roles:roles.map(role=>({id:role.id,title:role.title}))}];
  const signinNext=`/projects/${project.id}#apply`;
  const interestReturn=`/projects/${project.id}#interest`;
  const interestHref=user?'#interest':`/signin?next=${encodeURIComponent(interestReturn)}`;
  const facts=[
    ['Stage',displayStatus],
    ['Commitment',project.duration_weeks?`${project.duration_weeks} weeks`:'To be confirmed'],
    ['Weekly time',project.weekly_commitment||'Confirm in application'],
    ['Working model',project.location_type?titleCase(project.location_type):project.location||'Project-specific']
  ];

  return <>
    <section className="projectDetailHeroV2" aria-labelledby="project-detail-title">
      <div className="shell">
        <a className="projectBackLink" href="/projects">← Back to projects</a>
        <div className="projectDetailHeroGrid">
          <div className="projectDetailLead">
            <div className="eyebrow">{project.project_type==='partner'?'PARTNER PROJECT':'OPEN PROJECT'}</div>
            <h1 id="project-detail-title">{project.title}</h1>
            <p className="projectDetailSummary">{project.summary}</p>
            {project.partner_name&&<p className="projectDetailPartner">In partnership with <strong>{project.partner_name}</strong></p>}
          </div>
          <aside className="projectDetailDecision" aria-label="Project application status">
            <span className="projectStatusBadge">{displayStatus}</span>
            <div><small>Application deadline</small><strong>{deadline?deadline.toLocaleDateString('en-GB'):'No fixed deadline published'}</strong></div>
            <div><small>Team size</small><strong>{project.team_size_threshold?`${project.team_size_threshold} members`:'Defined by project operations'}</strong></div>
            <div className="projectDetailActions">{canApply&&<a className="button dark" href="#apply">Apply to project →</a>}{!canApply&&!isPilot&&<a className="button ghost" href="/projects">Browse projects →</a>}<a className={`button ${isPilot||!canApply?'dark':'ghost'}`} href={interestHref}>Submit interest →</a></div>
          </aside>
        </div>
        <div className="projectFactStrip" aria-label="Project facts">{facts.map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div>
      </div>
    </section>

    <section className="projectDetailContent"><div className="shell projectDetailGridV2"><main className="projectDetailMainV2">
      <section className="projectDetailSectionV2"><span className="cardNumber">THE PROBLEM</span><h2>What this project is solving</h2><p>{project.problem_statement||project.summary}</p></section>

      <section className="projectDetailSectionV2"><span className="cardNumber">YOUR COMMITMENT</span><h2>Know what you are committing to</h2><div className="commitmentGridV2"><div><small>DURATION</small><strong>{project.duration_weeks?`${project.duration_weeks} weeks`:'To be confirmed'}</strong></div><div><small>WEEKLY COMMITMENT</small><strong>{project.weekly_commitment||'Confirm in your application'}</strong></div><div><small>WORKING MODEL</small><strong>{project.location_type?titleCase(project.location_type):project.location||'Project-specific'}</strong></div><div><small>LEVEL</small><strong>{project.difficulty_level?titleCase(project.difficulty_level):'Open level'}</strong></div></div></section>

      <section className="projectDetailSectionV2"><span className="cardNumber">AVAILABLE ROLES</span><h2>Choose the responsibility you can own</h2>{roles.length?<div className="roleListV2">{roles.map(role=><article key={role.id}><div><h3>{role.title}</h3>{role.discipline&&<small>{role.discipline}</small>}</div><span className="projectRoleOpenings">{role.openings} OPEN</span>{role.description&&<p>{role.description}</p>}{role.skills?.length?<div className="projectRoleSkills">{role.skills.slice(0,6).map(skill=><span key={skill}>{skill}</span>)}</div>:null}</article>)}</div>:<div className="emptyState compactRoleState"><h3>Roles are still being prepared.</h3><p>The project brief is visible, but there is not yet a published role to apply for. Check back when project operations publishes the team roles.</p></div>}</section>

      <section className="projectDetailSectionV2"><span className="cardNumber">PROJECT FIT</span><h2>Skills, methods and context</h2><div className="projectFitGrid"><div><strong>Domains</strong><div className="projectFitTags">{domains.length?domains.map(item=><span key={item.slug}>{item.name}</span>):<span>No domain tags published.</span>}</div></div><div><strong>Tools</strong><div className="projectFitTags">{tools.length?tools.map(item=><span key={item.slug}>{item.name}</span>):<span>Tool choices depend on the team approach.</span>}</div></div><div><strong>Methods</strong><div className="projectFitTags">{methods.length?methods.map(item=><span key={item.slug}>{item.name}</span>):<span>Methods will be agreed during kickoff.</span>}</div></div></div></section>

      <section className="projectDetailSectionV2 proofSectionV2"><span className="cardNumber">EXPECTED PROOF</span><h2>What you should be able to evidence afterwards</h2><p>Mettelo Proof is based on the work you actually complete and the evidence accepted during project delivery. Your final Proof can connect your role, verified contribution, project context and review outcome rather than simply recording attendance.</p></section>
    </main>

    <aside className="projectDetailSideV2"><section className="projectApplyPanelV2"><span className="cardNumber">BEFORE YOU APPLY</span><h3>Application readiness</h3><p>{isPilot?'This project is registering interest while the brief and contribution roles are being prepared.':canApply?'This project is accepting applications. Review the commitment and choose a role you can realistically own.':deadlinePassed?'The published application deadline has passed.':statusAccepting&&roles.length===0?'The project is open, but the application roles have not been published yet.':'This project is not currently accepting applications.'}</p>{project.status==='forming'&&<div className="formationNoticeV2"><strong>Team forming</strong><span>Applications may still be reviewed while the delivery team is being completed.</span></div>}{project.forming_deadline&&<p><strong>Formation target:</strong> {new Date(project.forming_deadline).toLocaleDateString('en-GB')}</p>}{project.kickoff_at&&<p><strong>Kickoff:</strong> {new Date(project.kickoff_at).toLocaleString('en-GB')}</p>}<div className="projectDetailActions">{canApply&&<a className="button dark" href="#apply">Apply to project →</a>}{!canApply&&!isPilot&&<a className="button ghost" href="/projects">Browse projects →</a>}<a className={`button ${isPilot||!canApply?'dark':'ghost'}`} href={interestHref}>Submit interest →</a></div></section></aside>
    </div></section>

    {canApply&&<section className="section softSection" id="apply"><div className="shell formShell"><div><div className="eyebrow">Apply</div><h2>Apply with the full project context in view.</h2><p className="lead">Your draft saves automatically. We check profile readiness first, then you review the application before final submission.</p></div>{user?<ProjectApplicationForm projects={applicationProjects} selectedProjectId={project.id} profileMissing={profileMissing}/>:<div className="formCard"><span className="chip">SIGN IN REQUIRED</span><h3>Sign in without losing this task.</h3><p>After sign in, Mettelo returns you to this project application.</p><a className="button dark" href={`/signin?next=${encodeURIComponent(signinNext)}`}>Sign in to apply →</a></div>}</div></section>}

    <section className="section softSection" id="interest">
      <div className="shell formShell">
        <div><div className="eyebrow">SUBMIT INTEREST</div><h2>Tell us how you could contribute.</h2><p className="lead">Your interest stays connected to this project so the team can contact you about a suitable next step.</p></div>
        {user?<SubmissionForm formType="project_application" submitLabel="Submit my interest →">
          <input type="hidden" name="project_id" value={project.id}/><input type="hidden" name="project" value={project.title}/>
          <label htmlFor="interest-name">Full name *</label><input id="interest-name" required name="name" autoComplete="name"/>
          <label htmlFor="interest-email">Email address *</label><input id="interest-email" required name="email" type="email" autoComplete="email"/>
          <label htmlFor="interest-role">Where could you contribute? *</label><select id="interest-role" name="role" required defaultValue=""><option value="" disabled>Select an area</option><option>Data Analysis / BI</option><option>Data Engineering</option><option>AI / ML</option><option>Research / UX</option><option>Project Lead</option><option>QA / Technical Review</option><option>Documentation / Storytelling</option></select>
          <label htmlFor="interest-profile">LinkedIn, GitHub or portfolio</label><input id="interest-profile" name="profile" type="url" placeholder="https://"/>
          <label htmlFor="interest-contribution">Tell us what you could bring to this project *</label><textarea id="interest-contribution" name="contribution" required/>
          <label className="consent"><input required type="checkbox" name="consent" value="yes"/><span>I agree that Mettelo can use this information to review my interest in this project.</span></label>
        </SubmissionForm>:<div className="formCard"><span className="chip">SIGN IN REQUIRED</span><h3>Sign in to submit your interest.</h3><p>After sign in, Mettelo returns you to this project and opens the interest form.</p><a className="button dark" href={`/signin?next=${encodeURIComponent(interestReturn)}`}>Sign in to continue →</a></div>}
      </div>
    </section>

    <style>{`
      .projectDetailHeroV2{padding:34px 0 26px;background:linear-gradient(180deg,#fbf7ee 0%,#fcfbf7 100%);border-bottom:1px solid #e7e1d6}
      .projectBackLink{display:inline-flex;min-height:44px;align-items:center;color:#303845;font-weight:750;text-decoration:none}.projectBackLink:hover{text-decoration:underline;text-underline-offset:4px}.projectBackLink:focus-visible{outline:3px solid rgba(198,137,42,.34);outline-offset:3px;border-radius:4px}
      .projectDetailHeroGrid{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(280px,.65fr);gap:46px;align-items:start;margin-top:18px}
      .projectDetailLead{min-width:0}.projectDetailLead h1{max-width:820px;margin:10px 0 14px;font-size:clamp(2.7rem,4.6vw,4.6rem);line-height:.98;letter-spacing:-.045em;overflow-wrap:anywhere}.projectDetailSummary{max-width:800px;margin:0;color:#55606f;font-size:1rem;line-height:1.62;overflow-wrap:anywhere;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden}.projectDetailPartner{margin:14px 0 0;color:#5b6472}.projectDetailPartner strong{color:#2a2f52}
      .projectDetailDecision{display:grid;gap:16px;padding:20px;border:1px solid #ddd6ca;border-radius:18px;background:#fff;box-shadow:0 12px 30px rgba(16,19,29,.04)}.projectStatusBadge{width:max-content;max-width:100%;padding:6px 9px;border:1px solid #c89a50;background:#fbf7ee;color:#70470f;font-size:.68rem;font-weight:820;text-transform:uppercase;letter-spacing:.05em}.projectDetailDecision div{display:grid;gap:4px}.projectDetailDecision small{color:#707987;font-size:.68rem;font-weight:760;text-transform:uppercase;letter-spacing:.05em}.projectDetailDecision strong{color:#10131d;line-height:1.4}.projectDetailDecision .button{width:100%;min-height:46px}.projectDetailActions{display:grid!important;gap:8px!important}.projectDetailActions .button{width:100%;min-height:46px}
      .projectFactStrip{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));margin-top:24px;border-top:1px solid #d8d0c2;border-bottom:1px solid #d8d0c2}.projectFactStrip div{padding:14px 16px 14px 0}.projectFactStrip div+div{padding-left:16px;border-left:1px solid #e5dfd5}.projectFactStrip small{display:block;margin-bottom:4px;color:#707987;font-size:.63rem;font-weight:780;text-transform:uppercase;letter-spacing:.07em}.projectFactStrip strong{display:block;color:#242b35;font-size:.84rem;line-height:1.4}
      .projectDetailContent{padding:48px 0 70px;background:#f7f8fa}.projectDetailGridV2{display:grid;grid-template-columns:minmax(0,1fr) 320px;gap:24px;align-items:start}.projectDetailMainV2{display:grid;gap:18px}.projectDetailSectionV2{padding:26px;border:1px solid #e1ddd5;border-radius:16px;background:#fff}.projectDetailSectionV2 h2{margin:8px 0 14px;font-size:clamp(1.7rem,2.8vw,2.5rem);line-height:1.08;letter-spacing:-.03em}.projectDetailSectionV2>p{max-width:800px;margin:0;color:#55606f;line-height:1.72;overflow-wrap:anywhere}.commitmentGridV2{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.commitmentGridV2>div{padding:14px;border:1px solid #ece7de;background:#fcfbf7}.commitmentGridV2 small{display:block;margin-bottom:5px;color:#8b5a17;font-size:.62rem;font-weight:850;letter-spacing:.07em}.commitmentGridV2 strong{display:block;color:#232a34;line-height:1.4}
      .roleListV2{display:grid;gap:10px}.roleListV2 article{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px 14px;padding:15px;border:1px solid #e2ddd4;background:#fcfbf7}.roleListV2 h3{margin:0;font-size:1.05rem}.roleListV2 small{color:#68727f}.roleListV2 article p,.projectRoleSkills{grid-column:1/-1}.roleListV2 article p{margin:0;color:#5b6472;line-height:1.6}.projectRoleOpenings{align-self:start;padding:5px 8px;border:1px solid #c9a15f;color:#70470f;font-size:.62rem;font-weight:820}.projectRoleSkills,.projectFitTags{display:flex;flex-wrap:wrap;gap:6px}.projectRoleSkills span,.projectFitTags span{display:inline-flex;align-items:center;min-height:30px;padding:5px 8px;border:1px solid #ddd7cd;background:#fff;color:#404853;font-size:.68rem;font-weight:670}.projectFitGrid{display:grid;gap:0}.projectFitGrid>div{display:grid;grid-template-columns:110px minmax(0,1fr);gap:16px;padding:14px 0;border-bottom:1px solid #ece7de}.projectFitGrid>div:last-child{border-bottom:0}.projectFitGrid strong{color:#303845;font-size:.8rem}.proofSectionV2{background:#10131d;color:#fff;border-color:#10131d}.proofSectionV2 h2{color:#fff}.proofSectionV2>p{color:#c9ced6}
      .projectDetailSideV2{min-width:0}.projectApplyPanelV2{position:sticky;top:96px;padding:22px;border:1px solid #ddd6ca;border-radius:16px;background:#fff;box-shadow:0 10px 26px rgba(16,19,29,.035)}.projectApplyPanelV2 h3{margin:8px 0 10px}.projectApplyPanelV2 p{margin:0 0 14px;color:#5b6472;line-height:1.58}.projectApplyPanelV2 .button{width:100%;min-height:46px}.formationNoticeV2{display:grid;gap:4px;margin:14px 0;padding:12px;border-left:3px solid #c6892a;background:#fbf7ee}.formationNoticeV2 span{color:#5b6472;font-size:.8rem;line-height:1.45}
      @media(min-width:481px) and (max-width:1024px){.projectDetailHeroV2{padding:30px 0 24px}.projectDetailHeroGrid{grid-template-columns:1fr;gap:22px}.projectDetailDecision{grid-template-columns:repeat(2,minmax(0,1fr));align-items:end}.projectDetailDecision .projectStatusBadge,.projectDetailDecision .button{grid-column:1/-1}.projectFactStrip{grid-template-columns:repeat(2,minmax(0,1fr))}.projectFactStrip div:nth-child(3){border-left:0;padding-left:0;border-top:1px solid #e5dfd5}.projectFactStrip div:nth-child(4){border-top:1px solid #e5dfd5}.projectDetailGridV2{grid-template-columns:1fr}.projectApplyPanelV2{position:static}}
      @media(max-width:480px){.projectDetailHeroV2{padding:22px 0 18px}.projectDetailHeroGrid{grid-template-columns:1fr;gap:18px;margin-top:12px}.projectDetailLead h1{font-size:clamp(2.15rem,10vw,2.7rem);line-height:1}.projectDetailSummary{font-size:.92rem;-webkit-line-clamp:4}.projectDetailDecision{padding:16px;border-radius:14px}.projectFactStrip{grid-template-columns:1fr;margin-top:18px}.projectFactStrip div,.projectFactStrip div+div{padding:11px 0;border-left:0;border-top:1px solid #e5dfd5}.projectFactStrip div:first-child{border-top:0}.projectDetailContent{padding:30px 0 48px}.projectDetailSectionV2{padding:18px;border-radius:14px}.projectDetailSectionV2 h2{font-size:1.65rem}.commitmentGridV2{grid-template-columns:1fr}.roleListV2 article{grid-template-columns:1fr}.projectRoleOpenings{width:max-content}.projectFitGrid>div{grid-template-columns:1fr;gap:8px}.projectApplyPanelV2{position:static;padding:18px}.projectRoleSkills span,.projectFitTags span{max-width:100%;overflow-wrap:anywhere}}
    `}</style>
  </>;
}
