import {NextResponse} from 'next/server';
import {createServerSupabaseClient} from '@/lib/supabase/server';
import {serviceDb} from '@/lib/project-flow';
import {canonicalAdmissionMode,safeAutoStartDelayMinutes} from '@/lib/project-admission';
import {startProjectRun} from '@/lib/project-start-service';

async function adminContext(){const auth=await createServerSupabaseClient();const {data:{user}}=await auth.auth.getUser();if(!user)return{error:NextResponse.json({error:'Authentication required.'},{status:401})};if(user.app_metadata?.role!=='admin')return{error:NextResponse.json({error:'Admin access required.'},{status:403})};const db=serviceDb();if(!db)return{error:NextResponse.json({error:'Admin data service is not configured.'},{status:503})};return{db,user}}
function cutoff(value:unknown){if(value===null||value===''||value===undefined)return null;const parsed=new Date(String(value));return Number.isNaN(parsed.getTime())?undefined:parsed.toISOString()}
const policyFields='id,admission_mode,auto_start_delay_minutes,auto_start_paused_at,late_joining_enabled,late_joining_cutoff_at,project_sharing_enabled,member_invites_enabled';

export async function GET(request:Request){
 try{const ctx=await adminContext();if('error'in ctx)return ctx.error;const projectId=new URL(request.url).searchParams.get('project_id')?.trim()||'';if(!projectId)return NextResponse.json({error:'Project is required.'},{status:400});const [{data,error},{data:runs,error:runError}]=await Promise.all([ctx.db.from('projects').select(policyFields).eq('id',projectId).maybeSingle(),ctx.db.from('project_runs').select('id,run_number,status,has_started,required_team_size,scheduled_start_at,start_scheduled_at,auto_start_paused_at,auto_start_failure,recruitment_open').eq('project_id',projectId).not('status','in','("completed","cancelled")').order('run_number',{ascending:false})]);if(error||!data)return NextResponse.json({error:'Project not found.'},{status:404});if(runError)throw runError;return NextResponse.json({item:data,runs:runs||[]})}catch(error){console.error('project admission policy read error',error);return NextResponse.json({error:'Unable to load project admission policy.'},{status:500})}
}

export async function PATCH(request:Request){
 try{
  const ctx=await adminContext();if('error'in ctx)return ctx.error;const {db,user}=ctx;const body=await request.json();const projectId=String(body.project_id||'').trim();if(!projectId)return NextResponse.json({error:'Project is required.'},{status:400});const action=String(body.action||'').trim();const now=new Date().toISOString();
  if(['pause_run','resume_run','retry_run','start_run'].includes(action)){
   const runId=String(body.project_run_id||'').trim();if(!runId)return NextResponse.json({error:'Project run is required.'},{status:400});const {data:run,error:runError}=await db.from('project_runs').select('id,run_number,status,has_started,scheduled_start_at,start_scheduled_at,auto_start_paused_at,auto_start_failure').eq('id',runId).eq('project_id',projectId).maybeSingle();if(runError||!run)return NextResponse.json({error:'Project run not found.'},{status:404});if(run.has_started||run.status==='active')return NextResponse.json({error:'This project run has already started.'},{status:409});
   if(action==='pause_run'){await db.from('project_runs').update({auto_start_paused_at:run.auto_start_paused_at||now,updated_at:now}).eq('id',runId).eq('has_started',false);await db.from('project_activity_log').insert({project_id:projectId,project_run_id:runId,event_type:'project_auto_start_paused',actor_type:'user',actor_user_id:user.id,from_status:'forming',to_status:'forming',metadata:{scheduled_start_at:run.scheduled_start_at}});return NextResponse.json({ok:true,action,status:'paused'})}
   if(action==='resume_run'){await db.from('project_runs').update({auto_start_paused_at:null,auto_start_failure:null,scheduled_start_at:run.scheduled_start_at||now,start_scheduled_at:run.start_scheduled_at||now,updated_at:now}).eq('id',runId).eq('has_started',false);await db.from('project_activity_log').insert({project_id:projectId,project_run_id:runId,event_type:'project_auto_start_resumed',actor_type:'user',actor_user_id:user.id,from_status:'forming',to_status:'forming',metadata:{scheduled_start_at:run.scheduled_start_at||now}});return NextResponse.json({ok:true,action,status:'scheduled'})}
   await db.from('project_runs').update({auto_start_paused_at:null,auto_start_failure:null,updated_at:now}).eq('id',runId).eq('has_started',false);const result=await startProjectRun({db,projectId,runId,source:action==='start_run'?'manual':'admin_retry',actorUserId:user.id});if(result.notReady){await db.from('project_runs').update({auto_start_failure:`readiness:${(result.blockers||[]).join(',')}`,updated_at:now}).eq('id',runId).eq('has_started',false);return NextResponse.json({ok:false,status:'needs_attention',blockers:result.blockers||[]},{status:409})}return NextResponse.json({ok:true,action,status:result.started||result.alreadyStarted?'active':'scheduled',result});
  }
  const admissionMode=canonicalAdmissionMode(body.admission_mode);const delay=safeAutoStartDelayMinutes(body.auto_start_delay_minutes);const pause=body.auto_start_paused===true;const lateJoining=body.late_joining_enabled!==false;const sharing=body.project_sharing_enabled!==false;const invites=body.member_invites_enabled===true;const lateJoiningCutoff=cutoff(body.late_joining_cutoff_at);if(lateJoiningCutoff===undefined)return NextResponse.json({error:'Choose a valid late-joining cutoff date and time.'},{status:400});
  const {data:current,error:loadError}=await db.from('projects').select(policyFields).eq('id',projectId).maybeSingle();if(loadError||!current)return NextResponse.json({error:'Project not found.'},{status:404});
  const patch={admission_mode:admissionMode,auto_start_delay_minutes:delay,auto_start_paused_at:pause?(current.auto_start_paused_at||now):null,late_joining_enabled:lateJoining,late_joining_cutoff_at:lateJoiningCutoff,project_sharing_enabled:sharing,member_invites_enabled:invites,updated_at:now,updated_by_user_id:user.id};
  const {data,error}=await db.from('projects').update(patch).eq('id',projectId).select(policyFields).single();if(error)throw error;
  await db.from('project_activity_log').insert({project_id:projectId,event_type:'project_admission_policy_updated',actor_type:'user',actor_user_id:user.id,from_status:current.admission_mode||'review_required',to_status:admissionMode,metadata:{previous_delay_minutes:current.auto_start_delay_minutes,new_delay_minutes:delay,auto_start_paused:pause,late_joining_enabled:lateJoining,late_joining_cutoff_at:lateJoiningCutoff,project_sharing_enabled:sharing,member_invites_enabled:invites}});
  return NextResponse.json({ok:true,item:data});
 }catch(error){console.error('project admission configuration error',error);return NextResponse.json({error:'Unable to update project admission policy.'},{status:500})}
}