import {NextResponse} from 'next/server';
import {architectContext,archetypes,assignedRole,classifyRisk,clean,recordGovernance} from '@/lib/project-governance';

const sourceTypes=new Set(['google_sheets','excel','google_drive','github','kaggle','hugging_face','api','public_portal','cloud_location','external_website','other']);
const sensitivities=new Set(['public','internal','restricted']);
const capabilityImportance=new Set(['core','supporting','exposure']);
type Item=Record<string,unknown>;
type RouteContext={params:Promise<{id:string}>};

function items(value:unknown,max=40){return(Array.isArray(value)?value:[]).filter((item):item is Item=>Boolean(item)&&typeof item==='object').slice(0,max)}
function list(value:unknown,maxItems=20,maxLength=1200){return(Array.isArray(value)?value:[]).map(item=>clean(item,maxLength)).filter(Boolean).slice(0,maxItems)}
function httpsUrl(value:unknown,max=2000){const url=clean(value,max);return /^https:\/\//i.test(url)?url:''}
function boundedInt(value:unknown,min:number,max:number,fallback:number|null=null){const parsed=Number(value);return Number.isFinite(parsed)?Math.max(min,Math.min(max,Math.floor(parsed))):fallback}
function uuid(value:unknown){const id=clean(value,80);return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(id)?id:''}
function same(a:unknown,b:unknown){return String(a??'')===String(b??'')}

async function editableProject(id:string){
  const ctx=await architectContext();if('error'in ctx)return{error:ctx.error} as const;
  const {db,user,isAdmin}=ctx;
  const {data:project,error}=await db.from('projects').select('id,slug,title,summary,project_archetype,governance_status,status,visibility,project_type,partner_name,location,difficulty_level,duration_weeks,weekly_commitment,team_size_threshold,presentation_required,risk_level,admin_review_required,created_by_user_id').eq('id',id).maybeSingle();
  if(error)throw error;if(!project)return{error:NextResponse.json({error:'Project proposal not found.'},{status:404})} as const;
  const roles=await assignedRole(db,id,user.id);const creator=roles.includes('creating_architect');
  if(!isAdmin&&!creator)return{error:NextResponse.json({error:'Creating Project Architect access is required.'},{status:403})} as const;
  if(!['draft','changes_requested'].includes(project.governance_status))return{error:NextResponse.json({error:'Only draft or changes-requested proposals can be edited. Return the project through governance before changing its canonical definition.'},{status:409})} as const;
  return{db,user,isAdmin,project} as const;
}

export async function GET(_:Request,{params}:RouteContext){
  try{
    const {id}=await params;const access=await editableProject(clean(id,80));if('error'in access)return access.error;const {db,project}=access;
    const [brief,resources,deliverables,criteria,milestones,capabilities,roles]=await Promise.all([
      db.from('project_problem_briefs').select('context,stakeholder,primary_question,expected_outcome,success_metrics,constraints,ethics_considerations,primary_use_case,primary_objective,supporting_objectives,key_questions,in_scope,out_of_scope').eq('project_id',project.id).maybeSingle(),
      db.from('project_data_sources').select('id,name,description,source_type,external_url,provider_id,provider_name,provider_url,licence_name,licence_url,required_subset,approximate_size,data_period,data_format,unit_of_observation,known_limitations,provenance,sensitivity,governance_status,retention_policy,internal_storage_policy').eq('project_id',project.id).is('project_run_id',null).order('created_at'),
      db.from('project_deliverables').select('id,title,deliverable_type,acceptance_criteria,public_summary,expected_format,is_required,sort_order').eq('project_id',project.id).is('project_run_id',null).order('sort_order').order('created_at'),
      db.from('project_success_criteria').select('id,title,description,measurement,is_required,visibility,sort_order').eq('project_id',project.id).order('sort_order').order('created_at'),
      db.from('project_milestones').select('id,title,description,week_start,week_end,expected_output,sort_order').eq('project_id',project.id).is('project_run_id',null).order('sort_order').order('created_at'),
      db.from('project_capabilities').select('capability_id,importance,evidence_expected').eq('project_id',project.id),
      db.from('project_roles').select('id,title,discipline,description,openings,skills,responsibilities,recommended_skills,experience_expectation,weekly_commitment,application_requirements,role_status').eq('project_id',project.id).order('created_at')
    ]);
    for(const result of [brief,resources,deliverables,criteria,milestones,capabilities,roles])if(result.error)throw result.error;
    return NextResponse.json({project,brief:brief.data,resources:resources.data||[],deliverables:deliverables.data||[],success_criteria:criteria.data||[],milestones:milestones.data||[],capabilities:capabilities.data||[],roles:roles.data||[]});
  }catch(error){console.error('architect project draft load error',error);return NextResponse.json({error:'Unable to load this canonical project draft.'},{status:500})}
}

export async function PATCH(request:Request,{params}:RouteContext){
  try{
    const {id}=await params;const access=await editableProject(clean(id,80));if('error'in access)return access.error;const {db,user,project}=access;const body=await request.json();
    const title=clean(body.title,180),summary=clean(body.summary,900),archetype=clean(body.project_archetype,40),context=clean(body.problem_context,4000),stakeholder=clean(body.problem_stakeholder,2400),question=clean(body.problem_primary_question,2400),outcome=clean(body.problem_expected_outcome,2400),metrics=clean(body.problem_success_metrics,2400);
    if(!title||!summary||!archetypes.includes(archetype as typeof archetypes[number]))return NextResponse.json({error:'Add a title, summary and valid Data & AI archetype.'},{status:400});
    if(!context||!stakeholder||!question||!outcome||!metrics)return NextResponse.json({error:'Complete the problem context, stakeholder, primary question, expected outcome and success measures.'},{status:400});

    const resourceInputs=items(body.resources,20).map((item,index)=>{const rawUrl=clean(item.external_url,2000),externalUrl=httpsUrl(item.external_url),sourceType=clean(item.source_type,40),rawProviderId=clean(item.provider_id,80),providerId=rawProviderId?uuid(rawProviderId):'';return{index,id:uuid(item.id)||null,name:clean(item.name,180),description:clean(item.description,1600)||null,source_type:sourceType,external_url:externalUrl,invalid_url:Boolean(rawUrl&&!externalUrl),provider_id:providerId||null,invalid_provider_id:Boolean(rawProviderId&&!providerId),provider_name:clean(item.provider_name,180)||null,provider_url:httpsUrl(item.provider_url)||null,licence_name:clean(item.licence_name,180)||null,licence_url:httpsUrl(item.licence_url)||null,required_subset:clean(item.required_subset,1200)||null,approximate_size:clean(item.approximate_size,120)||null,data_period:clean(item.data_period,180)||null,data_format:clean(item.data_format,120)||null,unit_of_observation:clean(item.unit_of_observation,240)||null,known_limitations:clean(item.known_limitations,1600)||null,provenance:clean(item.provenance,1600)||null,sensitivity:sensitivities.has(clean(item.sensitivity,30))?clean(item.sensitivity,30):'internal'};});
    const invalidResource=resourceInputs.find(item=>!item.name||!sourceTypes.has(item.source_type)||!item.external_url||item.invalid_url||item.invalid_provider_id);if(invalidResource)return NextResponse.json({error:`Resource ${invalidResource.index+1} needs a name, supported source type, HTTPS source URL and valid provider reference when supplied.`},{status:400});
    const providerIds=[...new Set(resourceInputs.map(item=>item.provider_id).filter((value):value is string=>Boolean(value)))];if(providerIds.length){const {data,error}=await db.from('project_resource_providers').select('id').in('id',providerIds).eq('is_active',true);if(error)throw error;if((data||[]).length!==providerIds.length)return NextResponse.json({error:'Choose only active governed source providers.'},{status:400})}

    const deliverableInputs=items(body.deliverables,20).map((item,index)=>({id:uuid(item.id)||null,title:clean(item.title,180),deliverable_type:clean(item.deliverable_type,80)||'project_output',acceptance_criteria:clean(item.acceptance_criteria,2400),public_summary:clean(item.public_summary,1000)||null,expected_format:clean(item.expected_format,180)||null,is_required:item.is_required!==false,sort_order:boundedInt(item.sort_order,0,1000,index)??index}));if(deliverableInputs.some(item=>!item.title||!item.acceptance_criteria))return NextResponse.json({error:'Every deliverable needs a title and acceptance criteria.'},{status:400});
    const successInputs=items(body.success_criteria,20).map((item,index)=>({id:uuid(item.id)||null,title:clean(item.title,240),description:clean(item.description,1200)||null,measurement:clean(item.measurement,1200)||null,is_required:item.is_required!==false,visibility:['public','member','team','admin'].includes(clean(item.visibility,20))?clean(item.visibility,20):'public',sort_order:boundedInt(item.sort_order,0,1000,index)??index}));if(successInputs.some(item=>!item.title))return NextResponse.json({error:'Every success criterion needs a title.'},{status:400});
    const milestoneInputs=items(body.milestones,20).map((item,index)=>{const weekStart=boundedInt(item.week_start,1,520),weekEnd=boundedInt(item.week_end,1,520);return{id:uuid(item.id)||null,title:clean(item.title,180),description:clean(item.description,1200)||null,week_start:weekStart,week_end:weekEnd??weekStart,expected_output:clean(item.expected_output,1000)||null,sort_order:boundedInt(item.sort_order,0,1000,index)??index}});if(milestoneInputs.some(item=>!item.title||(item.week_start&&item.week_end&&item.week_end<item.week_start)))return NextResponse.json({error:'Every milestone needs a title and valid week range.'},{status:400});
    const roleInputs=items(body.roles,20).map(item=>({id:uuid(item.id)||null,title:clean(item.title,120),discipline:clean(item.discipline,120)||null,description:clean(item.description,1000)||null,openings:boundedInt(item.openings,1,20,1)??1,skills:list(item.skills,20,100),responsibilities:list(item.responsibilities,20,800),recommended_skills:list(item.recommended_skills,20,180),experience_expectation:clean(item.experience_expectation,1000)||null,weekly_commitment:clean(item.weekly_commitment,180)||null,application_requirements:clean(item.application_requirements,1600)||null})).filter(item=>item.title);
    const rawCapabilities=items(body.capabilities,40).map(item=>{const capabilityId=uuid(item.capability_id),importance=clean(item.importance,20);return{capability_id:capabilityId,importance:capabilityImportance.has(importance)?importance:'core',evidence_expected:item.evidence_expected===true}});if(rawCapabilities.some(item=>!item.capability_id))return NextResponse.json({error:'Every selected capability must reference a governed capability.'},{status:400});const capabilityInputs=[...new Map(rawCapabilities.map(item=>[item.capability_id,item])).values()];if(capabilityInputs.length){const {data,error}=await db.from('capabilities').select('id').in('id',capabilityInputs.map(item=>item.capability_id)).eq('is_active',true);if(error)throw error;if((data||[]).length!==capabilityInputs.length)return NextResponse.json({error:'Choose only active governed capabilities.'},{status:400})}

    const [{data:existingResources,error:resourceError},{data:reviews,error:reviewError}]=await Promise.all([
      db.from('project_data_sources').select('id,name,description,source_type,external_url,provider_id,provider_name,provider_url,licence_name,licence_url,required_subset,approximate_size,data_period,data_format,unit_of_observation,known_limitations,provenance,sensitivity,governance_status').eq('project_id',project.id).is('project_run_id',null),
      db.from('project_data_source_governance_reviews').select('data_source_id').in('data_source_id',(resourceInputs.map(item=>item.id).filter((value):value is string=>Boolean(value))))
    ]);if(resourceError)throw resourceError;if(reviewError)throw reviewError;
    const existingResourceMap=new Map((existingResources||[]).map(row=>[row.id,row]));const submittedResourceIds=new Set(resourceInputs.map(item=>item.id).filter((value):value is string=>Boolean(value)));const reviewedIds=new Set((reviews||[]).map(row=>row.data_source_id));
    for(const input of resourceInputs){if(!input.id)continue;const existing=existingResourceMap.get(input.id);if(!existing)return NextResponse.json({error:'A resource ID does not belong to this project.'},{status:400});const changed=!same(existing.name,input.name)||!same(existing.description,input.description)||!same(existing.source_type,input.source_type)||!same(existing.external_url,input.external_url)||!same(existing.provider_id,input.provider_id)||!same(existing.provider_name,input.provider_name)||!same(existing.provider_url,input.provider_url)||!same(existing.licence_name,input.licence_name)||!same(existing.licence_url,input.licence_url)||!same(existing.required_subset,input.required_subset)||!same(existing.approximate_size,input.approximate_size)||!same(existing.data_period,input.data_period)||!same(existing.data_format,input.data_format)||!same(existing.unit_of_observation,input.unit_of_observation)||!same(existing.known_limitations,input.known_limitations)||!same(existing.provenance,input.provenance)||!same(existing.sensitivity,input.sensitivity);if(changed&&existing.governance_status==='green')return NextResponse.json({error:`${existing.name} is GREEN and cannot be changed by a Project Architect. Admin must reopen its governance decision first.`},{status:409})}
    for(const existing of existingResources||[]){if(submittedResourceIds.has(existing.id))continue;if(existing.governance_status!=='unreviewed'||reviewedIds.has(existing.id))return NextResponse.json({error:`${existing.name} has governance history and cannot be removed from the canonical project definition. Admin must resolve it explicitly.`},{status:409})}

    const risk=classifyRisk({declared:body.declared_risk,partner:body.partner_project,sensitivity:body.data_sensitivity,impact:body.impact_area,rightsConfirmed:body.data_rights_confirmed,prohibited:body.prohibited_activity});if(risk.level==='prohibited')return NextResponse.json({error:'This proposal cannot proceed. Remove prohibited activity and confirm legitimate data rights.',risk_reasons:risk.reasons},{status:422});
    const now=new Date().toISOString();
    const {error:projectError}=await db.from('projects').update({title,summary,problem_statement:question,project_archetype:archetype,project_type:body.partner_project?'partner':'open',partner_name:clean(body.partner_name,180)||null,location:clean(body.location,160)||'Remote',difficulty_level:clean(body.difficulty_level,30)||null,duration_weeks:boundedInt(body.duration_weeks,1,52),weekly_commitment:clean(body.weekly_commitment,120)||null,team_size_threshold:boundedInt(body.team_size_threshold,1,50,5)??5,presentation_required:Boolean(body.presentation_required),risk_level:risk.level,risk_reasons:risk.reasons,admin_review_required:risk.adminReviewRequired,updated_at:now}).eq('id',project.id);if(projectError)throw projectError;
    const {error:briefError}=await db.from('project_problem_briefs').upsert({project_id:project.id,context,stakeholder,primary_question:question,expected_outcome:outcome,success_metrics:metrics,constraints:clean(body.problem_constraints,3000),ethics_considerations:clean(body.problem_ethics,3000),primary_use_case:clean(body.problem_primary_use_case,2400)||null,primary_objective:clean(body.problem_primary_objective,2400)||null,supporting_objectives:list(body.problem_supporting_objectives,12,1200),key_questions:list(body.problem_key_questions,12,1200),in_scope:list(body.problem_in_scope,20,800),out_of_scope:list(body.problem_out_of_scope,20,800),updated_by:user.id,updated_at:now},{onConflict:'project_id'});if(briefError)throw briefError;

    for(const input of resourceInputs){const row={name:input.name,description:input.description,source_type:input.source_type,external_url:input.external_url,provider_id:input.provider_id,provider_name:input.provider_id?null:input.provider_name,provider_url:input.provider_id?null:input.provider_url,licence_name:input.licence_name,licence_url:input.licence_url,required_subset:input.required_subset,approximate_size:input.approximate_size,data_period:input.data_period,data_format:input.data_format,unit_of_observation:input.unit_of_observation,known_limitations:input.known_limitations,provenance:input.provenance,sensitivity:input.sensitivity};if(input.id){const existing=existingResourceMap.get(input.id)!;const reset=existing.governance_status!=='unreviewed'||reviewedIds.has(input.id);const {error}=await db.from('project_data_sources').update({...row,...(reset?{governance_status:'unreviewed',governance_verified_at:null,governance_verified_by:null,publish_policy:'not_permitted',quality_status:'unreviewed'}:{})}).eq('id',input.id).eq('project_id',project.id).is('project_run_id',null);if(error)throw error}else{const {error}=await db.from('project_data_sources').insert({project_id:project.id,project_run_id:null,...row,owner_user_id:null,access_status:'needs_access',quality_status:'unreviewed',download_policy:'team_only',publish_policy:'not_permitted',retention_policy:'unknown',internal_storage_policy:'unknown',governance_status:'unreviewed',added_by:user.id});if(error)throw error}}
    const removableResources=(existingResources||[]).filter(row=>!submittedResourceIds.has(row.id)&&row.governance_status==='unreviewed'&&!reviewedIds.has(row.id)).map(row=>row.id);if(removableResources.length){const {error}=await db.from('project_data_sources').delete().in('id',removableResources).eq('project_id',project.id).is('project_run_id',null);if(error)throw error}

    const {data:existingDeliverables,error:existingDeliverableError}=await db.from('project_deliverables').select('id').eq('project_id',project.id).is('project_run_id',null);if(existingDeliverableError)throw existingDeliverableError;const deliverableIds=new Set(deliverableInputs.map(item=>item.id).filter((value):value is string=>Boolean(value)));for(const input of deliverableInputs){const row={project_id:project.id,project_run_id:null,workstream_id:null,title:input.title,deliverable_type:input.deliverable_type,acceptance_criteria:input.acceptance_criteria,public_summary:input.public_summary,expected_format:input.expected_format,is_required:input.is_required,sort_order:input.sort_order};if(input.id){const {error}=await db.from('project_deliverables').update(row).eq('id',input.id).eq('project_id',project.id).is('project_run_id',null);if(error)throw error}else{const {error}=await db.from('project_deliverables').insert({...row,status:'planned',created_by:user.id});if(error)throw error}}const removedDeliverables=(existingDeliverables||[]).map(row=>row.id).filter(id=>!deliverableIds.has(id));if(removedDeliverables.length){const {error}=await db.from('project_deliverables').delete().in('id',removedDeliverables).eq('project_id',project.id).is('project_run_id',null);if(error)throw error}

    const {data:existingCriteria,error:existingCriteriaError}=await db.from('project_success_criteria').select('id').eq('project_id',project.id);if(existingCriteriaError)throw existingCriteriaError;const criterionIds=new Set(successInputs.map(item=>item.id).filter((value):value is string=>Boolean(value)));for(const input of successInputs){const row={project_id:project.id,title:input.title,description:input.description,measurement:input.measurement,is_required:input.is_required,visibility:input.visibility,sort_order:input.sort_order,updated_at:now};if(input.id){const {error}=await db.from('project_success_criteria').update(row).eq('id',input.id).eq('project_id',project.id);if(error)throw error}else{const {error}=await db.from('project_success_criteria').insert({...row,created_by_user_id:user.id});if(error)throw error}}const removedCriteria=(existingCriteria||[]).map(row=>row.id).filter(id=>!criterionIds.has(id));if(removedCriteria.length){const {error}=await db.from('project_success_criteria').delete().in('id',removedCriteria).eq('project_id',project.id);if(error)throw error}

    const {data:existingMilestones,error:existingMilestoneError}=await db.from('project_milestones').select('id').eq('project_id',project.id).is('project_run_id',null);if(existingMilestoneError)throw existingMilestoneError;const milestoneIds=new Set(milestoneInputs.map(item=>item.id).filter((value):value is string=>Boolean(value)));for(const input of milestoneInputs){const row={project_id:project.id,title:input.title,description:input.description,week_start:input.week_start,week_end:input.week_end,expected_output:input.expected_output,sort_order:input.sort_order};if(input.id){const {error}=await db.from('project_milestones').update(row).eq('id',input.id).eq('project_id',project.id).is('project_run_id',null);if(error)throw error}else{const {error}=await db.from('project_milestones').insert({...row,status:'planned'});if(error)throw error}}const removedMilestones=(existingMilestones||[]).map(row=>row.id).filter(id=>!milestoneIds.has(id));if(removedMilestones.length){const {error}=await db.from('project_milestones').delete().in('id',removedMilestones).eq('project_id',project.id).is('project_run_id',null);if(error)throw error}

    const {data:existingRoles,error:existingRoleError}=await db.from('project_roles').select('id').eq('project_id',project.id);if(existingRoleError)throw existingRoleError;const roleIds=new Set(roleInputs.map(item=>item.id).filter((value):value is string=>Boolean(value)));for(const input of roleInputs){const row={project_id:project.id,title:input.title,discipline:input.discipline,description:input.description,openings:input.openings,skills:input.skills,responsibilities:input.responsibilities,recommended_skills:input.recommended_skills,experience_expectation:input.experience_expectation,weekly_commitment:input.weekly_commitment,application_requirements:input.application_requirements,role_status:'open'};if(input.id){const {error}=await db.from('project_roles').update(row).eq('id',input.id).eq('project_id',project.id);if(error)throw error}else{const {error}=await db.from('project_roles').insert(row);if(error)throw error}}const removedRoles=(existingRoles||[]).map(row=>row.id).filter(id=>!roleIds.has(id));if(removedRoles.length){const {error}=await db.from('project_roles').update({role_status:'closed'}).in('id',removedRoles).eq('project_id',project.id);if(error)throw error}

    const capabilityIds=new Set(capabilityInputs.map(item=>item.capability_id));const {data:existingCapabilities,error:existingCapabilityError}=await db.from('project_capabilities').select('capability_id').eq('project_id',project.id);if(existingCapabilityError)throw existingCapabilityError;for(const input of capabilityInputs){const {error}=await db.from('project_capabilities').upsert({project_id:project.id,capability_id:input.capability_id,importance:input.importance,evidence_expected:input.evidence_expected},{onConflict:'project_id,capability_id'});if(error)throw error}const removedCapabilities=(existingCapabilities||[]).map(row=>row.capability_id).filter(id=>!capabilityIds.has(id));if(removedCapabilities.length){const {error}=await db.from('project_capabilities').delete().eq('project_id',project.id).in('capability_id',removedCapabilities);if(error)throw error}

    await recordGovernance(db,{projectId:project.id,actorId:user.id,actorScope:access.isAdmin?'admin':'project_architect',eventType:'project_definition_updated',from:project.governance_status,to:project.governance_status,reason:'Canonical project draft updated in place.',metadata:{resources:resourceInputs.length,deliverables:deliverableInputs.length,success_criteria:successInputs.length,milestones:milestoneInputs.length,roles:roleInputs.length,capabilities:capabilityInputs.length,risk_level:risk.level}});
    return NextResponse.json({ok:true,id:project.id,slug:project.slug,governance_status:project.governance_status});
  }catch(error){console.error('architect project draft update error',error);return NextResponse.json({error:'Unable to update this canonical project draft.'},{status:500})}
}
