export default function OpportunitiesPage(){
  const opportunities=[
    ['JOB','Senior Data Analyst','United Kingdom · Hybrid','Permanent','Verified source','View role'],
    ['REFERRAL','Data Engineer referral route','United Kingdom · Member only','Full-time','Community referral','Sign in to view'],
    ['VOLUNTEER','Data for Social Impact Project','Nigeria / Remote','6 weeks','Experience-building','View opportunity'],
    ['FELLOWSHIP','AI & Public Interest Fellowship','Africa / Remote','Cohort','External programme','View details'],
    ['JOB','Analytics Engineer','Remote · EMEA','Permanent','Verified source','View role'],
    ['CONTRIBUTION','Open Data QA Reviewer','Remote','4–6 weeks','Mettelo Labs','Join project']
  ];
  return <>
    <section className="hero"><div className="shell heroGrid"><div><div className="eyebrow">Mettelo Opportunities</div><h1>Better access starts with better signal.</h1><p>Search jobs, referrals, volunteer work, fellowships and project-based opportunities — with clear location, eligibility, source and member access information.</p><div className="actions"><a className="button dark" href="#opportunity-feed">Browse opportunities →</a><a className="button ghost" href="/membership">Join for member-only routes</a></div></div><aside className="heroPanel"><span className="chip">DISCOVERY</span><h3 style={{marginTop:18}}>Opportunity should connect back to proof.</h3><p>As Mettelo matures, member projects and verified contributions can help employers and partners discover capability through demonstrated work.</p><div className="path"><span>Jobs</span><span>Referrals</span><span>Volunteer</span><span>Fellowships</span><span>Project work</span></div></aside></div></section>
    <section className="section" id="opportunity-feed"><div className="shell"><div className="searchPanel"><div><div className="eyebrow">Opportunity search</div><input className="searchInput" placeholder="Search role, skill, organisation or keyword…"/></div><div><div className="eyebrow">Quick filters</div><div className="filterBar" style={{marginBottom:0}}><span className="filter active">All</span><span className="filter">UK</span><span className="filter">Nigeria</span><span className="filter">Remote</span><span className="filter">Member only</span></div></div></div><div className="sectionHead" style={{marginTop:44}}><div><h2>Latest opportunities.</h2></div><p>Production data can be curated manually, imported from trusted sources or automated — but each item should retain source and eligibility metadata.</p></div><div className="grid3">{opportunities.map(([type,title,location,term,source,cta])=><article className="card featureCard" key={title}><div><span className="chip">{type}</span><h3 style={{marginTop:18}}>{title}</h3><p>{location}</p><div className="metaRow"><span className="metaPill">{term}</span><span className="metaPill">{source}</span></div></div><a className="linkArrow" href={type==='CONTRIBUTION'?'/projects':'/member'}>{cta} →</a></article>)}</div></div></section>
    <section className="section softSection"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">For members</div><h2>Save, track and act — without losing opportunities in chat.</h2></div><p>My Mettelo should eventually make opportunity discovery personal rather than turning WhatsApp and Discord into unsearchable job boards.</p></div><div className="grid4"><article className="card"><h3>Saved roles</h3><p>Bookmark opportunities to review later.</p></article><article className="card"><h3>Eligibility</h3><p>Surface location, work rights, seniority and access rules clearly.</p></article><article className="card"><h3>Referral routes</h3><p>Protect member-only referrals behind authenticated access.</p></article><article className="card"><h3>Relevant proof</h3><p>Eventually link roles to projects and skills already demonstrated on Mettelo.</p></article></div></div></section>
  </>;
}
