import {redirect} from 'next/navigation';
import {createServerSupabaseClient} from '@/lib/supabase/server';
import {serviceDb} from '@/lib/project-flow';
import AdminCareerRoleManager from '@/components/AdminCareerRoleManager';
import AdminCareerApplicationQueue from '@/components/AdminCareerApplicationQueue';

export const dynamic='force-dynamic';
type Question={id?:string;label?:string;required?:boolean}|string;
type Role={id:string;title:string;slug:string;team:string|null;employment_type:string;status:string;closes_at:string|null;location:string|null;work_arrangement:string|null;salary_text:string|null;summary:string;responsibilities:string;requirements:string;nice_to_have:string|null;eligibility:string|null;expected_response_days:number|null;application_process:string|null;application_questions:Question[]};
type Application={id:string;user_id:string|null;full_name:string;email:string;status:string;submitted_at:string;location:string|null;linkedin_url:string|null;portfolio_url:string|null;work_authorisation:string|null;motivation:string;relevant_experience:string;answers:Record<string,string>;admin_notes:string|null;interview_at:string|null;interview_timezone:string|null;interview_format:string|null;interview_url:string|null;interviewer:string|null;interview_instructions:string|null;offer_salary_rate:string|null;offer_start_date:string|null;offer_employment_type:string|null;offer_manager:string|null;offer_working_arrangement:string|null;offer_conditions:string|null;offer_acceptance_deadline:string|null;offer_personal_message:string|null;cv_path:string|null;career_roles:{title:string;application_questions:Question[]}|null};
type Profile={id:string;full_name:string|null;headline:string|null;current_job_title:string|null;professional_area:string|null;skills:string[]|null;project_availability:string|null};
type Communication={id:string;related_id:string|null;template_key:string;subject:string;status:string;created_at:string;sent_at:string|null};
type Onboarding={id:string;application_id:string;item_key:string;title:string;description:string|null;status:string;due_at:string|null;completed_at:string|null};

export default async function AdminCareersPage(){
  const auth=await createServerSupabaseClient();const {data:{user}}=await auth.auth.getUser();if(!user)redirect('/signin');if(user.app_metadata?.role!=='admin')redirect('/member');
  const db=serviceDb();let roles:Role[]=[];const applications:(Application&{cv_url:string|null;profile:Profile|null;communications:Communication[];onboarding_items:Onboarding[]})[]=[];
  if(db){
    const [r,a]=await Promise.all([
      db.from('career_roles').select('id,title,slug,team,employment_type,status,closes_at,location,work_arrangement,salary_text,summary,responsibilities,requirements,nice_to_have,eligibility,expected_response_days,application_process,application_questions').order('created_at',{ascending:false}),
      db.from('career_applications').select('id,user_id,full_name,email,status,submitted_at,location,linkedin_url,portfolio_url,work_authorisation,motivation,relevant_experience,answers,admin_notes,interview_at,interview_timezone,interview_format,interview_url,interviewer,interview_instructions,offer_salary_rate,offer_start_date,offer_employment_type,offer_manager,offer_working_arrangement,offer_conditions,offer_acceptance_deadline,offer_personal_message,cv_path,career_roles(title,application_questions)').order('submitted_at',{ascending:false}).limit(100)
    ]);roles=(r.data||[]) as unknown as Role[];const rows=(a.data||[]) as unknown as Application[];const userIds=[...new Set(rows.map(x=>x.user_id).filter((id):id is string=>Boolean(id)))];const ids=rows.map(x=>x.id);
    const [profilesResult,communicationsResult,onboardingResult]=await Promise.all([
      userIds.length?db.from('profiles').select('id,full_name,headline,current_job_title,professional_area,skills,project_availability').in('id',userIds):Promise.resolve({data:[]}),
      ids.length?db.from('communication_records').select('id,related_id,template_key,subject,status,created_at,sent_at').eq('related_type','career_application').in('related_id',ids).order('created_at',{ascending:false}):Promise.resolve({data:[]}),
      ids.length?db.from('career_onboarding_items').select('id,application_id,item_key,title,description,status,due_at,completed_at').in('application_id',ids).order('created_at',{ascending:true}):Promise.resolve({data:[]})
    ]);
    const profiles=(profilesResult.data||[]) as Profile[];const communications=(communicationsResult.data||[]) as Communication[];const onboarding=(onboardingResult.data||[]) as Onboarding[];
    for(const item of rows){let cv_url:string|null=null;if(item.cv_path){const signed=await db.storage.from('career-cvs').createSignedUrl(item.cv_path,3600);cv_url=signed.data?.signedUrl||null;}applications.push({...item,cv_url,profile:item.user_id?profiles.find(p=>p.id===item.user_id)||null:null,communications:communications.filter(c=>c.related_id===item.id).slice(0,8),onboarding_items:onboarding.filter(o=>o.application_id===item.id)});}
  }
  const active=applications.filter(a=>!['hired','rejected','withdrawn'].includes(a.status));
  return <section className="section softSection"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">Mettelo Admin · Careers</div><h1>Run recruitment as one traceable journey.</h1></div><p>Publish clear roles, review complete candidate context, send stage communications and continue from hiring into onboarding without leaving Mettelo.</p></div><div className="metricGrid"><div className="metric"><strong>{roles.filter(r=>r.status==='published').length}</strong><span>Open roles</span></div><div className="metric"><strong>{active.length}</strong><span>Active candidates</span></div><div className="metric"><strong>{applications.filter(a=>a.status==='interview').length}</strong><span>Interviews</span></div><div className="metric"><strong>{applications.filter(a=>a.status==='hired').length}</strong><span>Hired</span></div></div><AdminCareerRoleManager initialRoles={roles}/><section className="panel" style={{marginTop:18}}><div className="panelHead"><div><span className="cardNumber">CANDIDATE PIPELINE</span><h3 style={{marginTop:8}}>Applications, decisions and communication</h3></div><span className="chip">{applications.length}</span></div><p style={{color:'#5b6470',fontSize:'.78rem',lineHeight:1.55}}>Each transition should leave the candidate, Admin timeline, notification and email describing the same recruitment state.</p><AdminCareerApplicationQueue initialItems={applications}/></section></div></section>;
}
