import type {Metadata} from 'next';
import {redirect} from 'next/navigation';
import {createClient} from '@supabase/supabase-js';
import {createServerSupabaseClient} from '@/lib/supabase/server';
import AdminApplicationQueue from '@/components/AdminApplicationQueue';
import AdminTeamFormation from '@/components/AdminTeamFormation';
import AdminProjectManager from '@/components/AdminProjectManager';

export const metadata:Metadata={title:'Project Operations | Mettelo Admin',description:'Review project applications, manage projects, form teams and monitor delivery.'};export const dynamic='force-dynamic';
type Row={id:string;user_id:string;status:string;submitted_at:string;contribution_statement:string;portfolio_url:string|null;availability:string|null;application_kind:string|null;requested_role:string|null;reviewer_notes:string|null;projects:{title:string;project_type:string}|null;project_roles:{title:string}|null};

export default async function ProjectOperationsPage({searchParams}:{searchParams?:Promise<{project?:string|string[]}>}){
  const params=await searchParams||{};const focusProjectId=Array.isArray(params.project)?params.project[0]:params.project;
  const auth=await createServerSupabaseClient();const {data:{user}}=await auth.auth.getUser();if(!user)redirect('/signin');if(user.app_metadata?.role!=='admin')redirect('/member');
  const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;const db=url&&key?createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}):null;
  let items:{id:string;name:string;email:string;project:string;role:string;status:string;submitted_at:string;statement:string;portfolio_url:string|null;availability:string|null;reviewer_notes:string|null;profile:{headline:string|null;skills:string[];experience_level:string|null;project_availability:string|null;weekly_capacity:string|null};communications:{title:string;body:string;created_at:string}[]}[]=[];
  if(db){const {data}=await db.from('project_applications').select('id,user_id,status,submitted_at,contribution_statement,portfolio_url,availability,application_kind,requested_role,reviewer_notes,projects(title,project_type),project_roles(title)').in('status',['submitted','in_review','shortlisted']).order('submitted_at',{ascending:true});const rows=(data||[]) as unknown as Row[];const ids=[...new Set(rows.map(r=>r.user_id))];const appIds=rows.map(r=>r.id);const profiles=new Map<string,{full_name:string;headline:string|null;skills:string[];experience_level:string|null;project_availability:string|null;weekly_capacity:string|null}>();const emails=new Map<string,string>();const communications=new Map<string,{title:string;body:string;created_at:string}[]>();if(ids.length){const {data:profileRows}=await db.from('profiles').select('id,full_name,headline,skills,experience_level,project_availability,weekly_capacity').in('id',ids);(profileRows||[]).forEach(p=>profiles.set(p.id,{full_name:p.full_name||'Mettelo member',headline:p.headline||null,skills:p.skills||[],experience_level:p.experience_level||null,project_availability:p.project_availability||null,weekly_capacity:p.weekly_capacity||null}));const users=await db.auth.admin.listUsers({page:1,perPage:1000});users.data.users.forEach(u=>{if(ids.includes(u.id))emails.set(u.id,u.email||'')})}if(appIds.length){const {data:notes}=await db.from('notifications').select('application_id,title,body,created_at').in('application_id',appIds).order('created_at',{ascending:false});for(const note of notes||[]){if(!note.application_id)continue;const current=communications.get(note.application_id)||[];if(current.length<5){current.push({title:note.title,body:note.body,created_at:note.created_at});communications.set(note.application_id,current)}}}items=rows.map(row=>{const profile=profiles.get(row.user_id);return{id:row.id,name:profile?.full_name||'Mettelo member',email:emails.get(row.user_id)||'',project:row.projects?.title||'Project',role:row.project_roles?.title||row.requested_role||(row.application_kind==='interest'?'Project interest':'Role not set'),status:row.status,submitted_at:row.submitted_at,statement:row.contribution_statement,portfolio_url:row.portfolio_url,availability:row.availability,reviewer_notes:row.reviewer_notes,profile:{headline:profile?.headline||null,skills:profile?.skills||[],experience_level:profile?.experience_level||null,project_availability:profile?.project_availability||null,weekly_capacity:profile?.weekly_capacity||null},communications:communications.get(row.id)||[]}})}
  return <section className="section softSection"><div className="shell"><div className="sectionHead"><div><div className="eyebrow">Mettelo Admin · Projects</div><h1>Review applications and keep teams moving.</h1></div><p>Manage existing projects, review new applications, then check forming, active, paused and review-stage teams.</p></div><div className="actions adminQuickActions"><a className="button dark" href="/admin/content#publisher">Create project →</a><a className="button ghost" href="#manage-projects">Manage projects</a><a className="button ghost" href="#request-review">Review {items.length} application{items.length===1?'':'s'}</a><a className="button ghost" href="#team-formation">Project teams</a><a className="button ghost" href="/admin/access">Admin access</a></div><div className="adminProjectPublishHint"><div><span className="cardNumber">PROJECT OPERATIONS</span><strong>Create new work or manage what already exists</strong><p>Use Create Project for a new brief. Use Manage Projects to edit, change status, archive, delete safe drafts, or jump into a project’s team operations.</p></div><a className="linkArrow" href="#manage-projects">Open project list →</a></div><AdminProjectManager/><section className="panel" id="request-review" style={{marginTop:22,marginBottom:22}}><div className="panelHead"><div><span className="cardNumber">APPLICATIONS</span><h3 style={{marginTop:8}}>Waiting for review</h3></div><span className="chip">{items.length} OPEN</span></div><AdminApplicationQueue initialItems={items}/></section><section className="panel" id="team-formation"><div className="panelHead"><div><span className="cardNumber">PROJECT TEAMS</span><h3 style={{marginTop:8}}>Formation, delivery, pauses and completion</h3></div></div><AdminTeamFormation focusProjectId={focusProjectId}/></section></div><style>{`.adminProjectPublishHint{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:22px;align-items:center;margin:18px 0 0;padding:18px 20px;border:1px solid var(--line);border-radius:16px;background:#fff}.adminProjectPublishHint strong{display:block;margin:4px 0}.adminProjectPublishHint p{margin:0;color:var(--slate);max-width:760px}.adminProjectPublishHint .linkArrow{white-space:nowrap}@media(max-width:700px){.adminQuickActions{display:grid}.adminQuickActions .button{width:100%;min-height:46px}.adminProjectPublishHint{grid-template-columns:1fr}.adminProjectPublishHint .linkArrow{white-space:normal}}`}</style></section>;
}
