import {NextResponse} from 'next/server';
import {createServerSupabaseClient} from '@/lib/supabase/server';
import {serviceDb} from '@/lib/project-flow';

const MAX_FILES=4,MAX_BYTES=10*1024*1024;const allowed=new Set(['application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document']);
async function context(){const auth=await createServerSupabaseClient();const {data:{user}}=await auth.auth.getUser();if(!user||user.app_metadata?.role!=='admin')return null;const db=serviceDb();return db?{db,user}:null}
function safeName(name:string){return name.replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/-+/g,'-').slice(-180)||'document'}

export async function GET(request:Request){const ctx=await context();if(!ctx)return NextResponse.json({error:'Admin access required.'},{status:403});const key=new URL(request.url).searchParams.get('template_key')||'';const {data:template}=await ctx.db.from('communication_templates').select('id,allow_attachments').eq('template_key',key).maybeSingle();if(!template)return NextResponse.json({attachments:[],allow_attachments:false});const {data,error}=await ctx.db.from('communication_template_attachments').select('id,file_name,content_type,size_bytes,sort_order,active,created_at').eq('template_id',template.id).eq('active',true).order('sort_order').order('created_at');if(error)return NextResponse.json({error:'Unable to load attachments.'},{status:500});return NextResponse.json({attachments:data||[],allow_attachments:template.allow_attachments})}

export async function POST(request:Request){try{const ctx=await context();if(!ctx)return NextResponse.json({error:'Admin access required.'},{status:403});const form=await request.formData();const key=String(form.get('template_key')||'');const file=form.get('file');if(!(file instanceof File)||!key)return NextResponse.json({error:'Template and document are required.'},{status:400});if(!allowed.has(file.type)||file.size<=0||file.size>MAX_BYTES)return NextResponse.json({error:'Use a PDF or DOCX file up to 10MB.'},{status:400});const {data:template}=await ctx.db.from('communication_templates').select('id,allow_attachments').eq('template_key',key).maybeSingle();if(!template||!template.allow_attachments)return NextResponse.json({error:'Attachments are not enabled for this template.'},{status:409});const {count}=await ctx.db.from('communication_template_attachments').select('id',{count:'exact',head:true}).eq('template_id',template.id).eq('active',true);if((count||0)>=MAX_FILES)return NextResponse.json({error:`A template can have at most ${MAX_FILES} active attachments.`},{status:409});const path=`${template.id}/${crypto.randomUUID()}-${safeName(file.name)}`;const bytes=new Uint8Array(await file.arrayBuffer());const upload=await ctx.db.storage.from('communication-template-documents').upload(path,bytes,{contentType:file.type,upsert:false});if(upload.error)throw upload.error;const {data,error}=await ctx.db.from('communication_template_attachments').insert({template_id:template.id,file_name:safeName(file.name),storage_path:path,content_type:file.type,size_bytes:file.size,sort_order:count||0,created_by:ctx.user.id}).select('id,file_name,content_type,size_bytes,sort_order,active,created_at').single();if(error){await ctx.db.storage.from('communication-template-documents').remove([path]);throw error}await ctx.db.from('communication_audit_log').insert({actor_user_id:ctx.user.id,action:'template_attachment_added',entity_type:'communication_template',entity_id:template.id,metadata:{template_key:key,file_name:file.name,size_bytes:file.size}});return NextResponse.json({ok:true,attachment:data});}catch(error){console.error('template attachment upload error',error);return NextResponse.json({error:'Unable to upload template attachment.'},{status:500})}}

export async function PATCH(request:Request){try{const ctx=await context();if(!ctx)return NextResponse.json({error:'Admin access required.'},{status:403});const body=await request.json();const ids=Array.isArray(body.ordered_ids)?body.ordered_ids.map(String).slice(0,MAX_FILES):[];if(!ids.length)return NextResponse.json({error:'Attachment order is required.'},{status:400});for(let i=0;i<ids.length;i++)await ctx.db.from('communication_template_attachments').update({sort_order:i,updated_at:new Date().toISOString()}).eq('id',ids[i]);return NextResponse.json({ok:true});}catch(error){console.error('template attachment reorder error',error);return NextResponse.json({error:'Unable to reorder attachments.'},{status:500})}}

export async function DELETE(request:Request){try{const ctx=await context();if(!ctx)return NextResponse.json({error:'Admin access required.'},{status:403});const {id}=await request.json();const {data:item}=await ctx.db.from('communication_template_attachments').select('id,template_id,storage_path,file_name').eq('id',String(id||'')).maybeSingle();if(!item)return NextResponse.json({error:'Attachment not found.'},{status:404});await ctx.db.from('communication_template_attachments').update({active:false,updated_at:new Date().toISOString()}).eq('id',item.id);await ctx.db.storage.from('communication-template-documents').remove([item.storage_path]);await ctx.db.from('communication_audit_log').insert({actor_user_id:ctx.user.id,action:'template_attachment_removed',entity_type:'communication_template',entity_id:item.template_id,metadata:{file_name:item.file_name}});return NextResponse.json({ok:true});}catch(error){console.error('template attachment remove error',error);return NextResponse.json({error:'Unable to remove template attachment.'},{status:500})}}
