import type {Metadata} from 'next';
import Image from 'next/image';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {getInsightArticle,insightArticles} from '@/lib/insights-seed';
import '../insights.css';

export function generateStaticParams(){return insightArticles.map(article=>({slug:article.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const article=getInsightArticle(slug);if(!article)return {title:'Insights & News'};return {title:article.title,description:article.summary,openGraph:{title:article.title,description:article.summary,type:'article',url:`/blog/${article.slug}`,images:[{url:article.image,width:1200,height:675,alt:article.imageAlt}]},twitter:{card:'summary_large_image',title:article.title,description:article.summary,images:[article.image]}};}

export default async function InsightArticlePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const article=getInsightArticle(slug);if(!article)notFound();const related=insightArticles.filter(item=>item.slug!==article.slug).slice(0,2);return <>
<section className="section articleHero"><div className="shell"><Link className="articleBack" href="/blog">← Insights & News</Link><div className="eyebrow">{article.category}</div><h1>{article.title}</h1><p className="articleDeck">{article.summary}</p><div className="articleMetaRow"><span className="metaPill">{new Date(article.publishedAt+'T12:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}</span><span className="metaPill">{article.readTime}</span><span className="metaPill">Mettelo Editorial</span></div><div className="articleCoverWrap"><Image src={article.image} alt={article.imageAlt} width={1200} height={675} className="articleCover" priority/></div></div></section>
<section className="section softSection"><div className="shell articleLayout"><article className="articleBody">{article.sections.map((section,index)=><section key={`${article.slug}-${index}`}>{section.heading&&<h2>{section.heading}</h2>}{section.paragraphs.map((paragraph,pIndex)=><p key={`${index}-${pIndex}`}>{paragraph}</p>)}</section>)}<div className="articleRelated"><div className="eyebrow">Keep reading</div><h2>More from Mettelo</h2><div className="articleRelatedGrid">{related.map(item=><div className="articleRelatedCard" key={item.slug}><small>{item.category}</small><strong>{item.title}</strong><Link href={`/blog/${item.slug}`}>Read article →</Link></div>)}</div></div></article><aside className="articleAside"><small>ABOUT THIS SERIES</small><strong>Practical thinking on capability, Data & AI and what Mettelo is building.</strong><p>These test articles use Mettelo-owned editorial content so we can evaluate the public content experience before the full CMS workflow is introduced.</p><Link className="button dark" href="/newsletter">Get new insights →</Link></aside></div></section>
</>}
