begin;
alter function public.enforce_auto_opportunity_publication() set search_path = public, pg_temp;
create index if not exists account_identities_approved_application_id_idx on public.account_identities(approved_application_id);
create index if not exists career_offer_documents_uploaded_by_idx on public.career_offer_documents(uploaded_by);
create index if not exists career_roles_created_by_idx on public.career_roles(created_by);
create index if not exists communication_audit_log_actor_user_id_idx on public.communication_audit_log(actor_user_id);
create index if not exists communication_records_actor_user_id_idx on public.communication_records(actor_user_id);
create index if not exists communication_records_recipient_user_id_idx on public.communication_records(recipient_user_id);
create index if not exists communication_template_versions_changed_by_idx on public.communication_template_versions(changed_by);
create index if not exists communication_templates_updated_by_idx on public.communication_templates(updated_by);
create index if not exists contribution_evidence_links_project_run_id_idx on public.contribution_evidence_links(project_run_id);
create index if not exists contributions_project_run_id_idx on public.contributions(project_run_id);
create index if not exists opportunity_ingestion_sources_created_by_idx on public.opportunity_ingestion_sources(created_by);
create index if not exists project_architect_application_evidence_contribution_id_idx on public.project_architect_application_evidence(contribution_id);
create index if not exists project_architect_application_history_changed_by_idx on public.project_architect_application_history(changed_by);
create index if not exists project_architect_applications_reviewed_by_idx on public.project_architect_applications(reviewed_by);
create index if not exists project_architect_assignments_assigned_by_user_id_idx on public.project_architect_assignments(assigned_by_user_id);
create index if not exists project_architect_credentials_application_id_idx on public.project_architect_credentials(application_id);
create index if not exists project_data_sources_added_by_idx on public.project_data_sources(added_by);
create index if not exists project_data_sources_owner_user_id_idx on public.project_data_sources(owner_user_id);
create index if not exists project_data_sources_project_id_idx on public.project_data_sources(project_id);
create index if not exists project_deliverable_data_sources_data_source_id_idx on public.project_deliverable_data_sources(data_source_id);
create index if not exists project_deliverable_data_sources_project_run_id_idx on public.project_deliverable_data_sources(project_run_id);
create index if not exists project_deliverable_tasks_project_run_id_idx on public.project_deliverable_tasks(project_run_id);
drop index if exists public.opportunities_reverification_idx;
commit;
