import type {Metadata} from 'next';
import FAQAccordion from '@/components/FAQAccordion';
import {getPublicWebsiteCmsPage} from '@/lib/website-pages-cms';

export const metadata:Metadata={title:'FAQ',description:'Answers to common questions about Mettelo projects, Proof, careers, commitment and support.'};
const items=[
 {question:'What is Mettelo, and who is it for?',answer:'Mettelo is technology-led infrastructure for professionals to build real capability, prove it with verified evidence and get discovered. It is designed for people who want credible experience, structured project work and stronger professional signals — especially across Data, AI and adjacent digital disciplines.'},
 {question:'How do project applications work?',answer:'Browse a project, review the problem, role, commitment, timing and expected Proof, then apply for the role that fits you. Your application is tracked in My Mettelo so you can see its status, what happens next and whether you need to take action.'},
 {question:'What does “Proof” mean on Mettelo?',answer:'Proof is evidence-backed recognition of work you actually contributed to. Where Mettelo verifies a contribution, the record connects the project, your role, submitted evidence and the verification state so other people can understand what you did and how it was reviewed.'},
 {question:'Are Mettelo projects paid or voluntary?',answer:'It depends on the opportunity. Each project or role should state its commitment and any compensation clearly before you apply; some experiences may be paid, some may be voluntary, and some may focus on professional evidence or collaboration rather than payment.'},
 {question:'What happens after I apply to a project?',answer:'You receive confirmation, then the application moves through a visible review and team-formation journey. If selected, you will see the next expected event, role confirmation, project start information and any action required from you.'},
 {question:'What are Project Architect and Project Lead?',answer:'They are structured project leadership roles inside Mettelo. Project Architects help shape strong project briefs and governance, while Project Leads coordinate delivery once a team is active; progression into these roles is managed from the member workspace rather than the public marketing site.'},
 {question:'How do careers and recruitment work?',answer:'Mettelo can manage a full recruitment journey from role discovery and application through review, interview, offer and onboarding. Candidates should be able to track meaningful status changes and receive the same story across the candidate experience and communications.'},
 {question:'How much time do projects usually require?',answer:'Time expectations vary by project and role. Before applying, check the listed duration, weekly commitment, milestones and application deadline so you know what you are agreeing to.'},
 {question:'Is Mettelo only for people in Africa?',answer:'Mettelo is building professional capability infrastructure with a clear commitment to professionals across Africa and beyond. The platform is designed to connect credible work, verified evidence and opportunity across borders while keeping that Africa-and-beyond mission explicit.'},
 {question:'How do I get support or contact the team?',answer:'Use the Contact page for support, partnership or general questions, and the Feedback page for product feedback. If your request creates an intake record, Mettelo routes it internally so it has an owner and a follow-up path rather than disappearing into an untracked inbox.'}
];
export default async function FAQPage(){const copy=(await getPublicWebsiteCmsPage('faq')).values;return <><section className="hero faqHero" aria-labelledby="faq-page-title"><div className="shell"><div className="eyebrow">{copy.hero_eyebrow}</div><h1 id="faq-page-title">{copy.hero_title}</h1><p className="heroLead">{copy.hero_lead}</p></div></section><section className="section"><div className="shell faqShell"><div className="sectionHead"><div><h2>{copy.section_title}</h2></div><p>{copy.section_body}</p></div><FAQAccordion items={items}/><div className="ctaBand faqCta"><div><div className="cardNumber">STILL HAVE QUESTIONS?</div><h2>{copy.empty_title}</h2><p>{copy.empty_body}</p></div><div className="actions"><a className="button dark" href={copy.final_cta_href}>{copy.final_cta_label}</a></div></div></div></section><style>{`.faqHero{padding-bottom:54px}.faqHero #faq-page-title{max-width:900px;font-size:var(--type-page-title);line-height:1.04;letter-spacing:-.045em}.faqShell{max-width:900px}.faqAccordion{display:grid;gap:12px}.faqItem{min-width:0;border:1px solid var(--line);border-radius:18px;background:#fff;overflow:hidden}.faqItem h2{margin:0;font-family:var(--font-space),sans-serif;font-size:var(--type-accordion-question)!important;line-height:1.28;letter-spacing:-.025em}.faqItem button{width:100%;min-height:60px;display:flex;align-items:center;justify-content:space-between;gap:18px;padding:14px 18px;border:0;background:#fff;color:var(--ink);text-align:left;font-weight:800;cursor:pointer}.faqItem button:hover{background:var(--sand-2)}.faqItem button:focus-visible{outline:3px solid rgba(198,137,42,.44);outline-offset:-3px}.faqIcon{width:32px;height:32px;display:grid;place-items:center;flex:none;align-self:center;border:1px solid var(--line);border-radius:50%;font-size:1.25rem;line-height:1}.faqAnswer{padding:0 18px 18px}.faqAnswer p{margin:0;color:var(--slate);overflow-wrap:anywhere}.faqCta{margin-top:42px}@media(min-width:481px) and (max-width:1024px){.faqHero{padding-bottom:44px}.faqHero #faq-page-title{max-width:760px}.faqShell{max-width:820px}.faqItem button{min-height:58px;gap:16px}.faqCta{margin-top:34px}}@media(max-width:480px){.faqHero{padding-bottom:34px}.faqItem button{min-height:56px;gap:14px;padding:14px 16px}.faqCta{margin-top:28px}}`}</style></>}
